import type { IslamicHistoryEvent } from "../../types/islamic-history";
import type { DeepPartial } from "./localize";

// French translation overlay for the Islamic History timeline. Mirrors the
// order of ISLAMIC_HISTORY_EVENTS in ../islamic-history.ts (index-aligned);
// untranslated entries fall back to English. Only human-readable text is
// translated — ids, years and hadith citations stay in the English source.
export const ISLAMIC_HISTORY_EVENTS_FR: DeepPartial<IslamicHistoryEvent>[] = [
  {
    title: "La mort du Prophète ﷺ et la succession",
    location: "Médine",
    body: "Lorsque le Prophète ﷺ mourut en 11 AH, la jeune communauté musulmane fit face à sa première épreuve majeure sans lui : qui la dirigerait ? Un groupe d'Ansar se réunit à Saqifa Bani Sa'ida à Médine pour discuter de la question entre eux. Apprenant cela, Abou Bakr et Omar se hâtèrent de les rejoindre, et après discussion, l'assemblée prêta allégeance à Abou Bakr — la communauté plus large suivant le lendemain. Ali et d'autres prêtèrent allégeance un peu plus tard, après avoir enterré le Prophète ﷺ, mais la transition elle-même se déroula sans violence.\n\nLes paroles inaugurales d'Abou Bakr au peuple, préservées dans les histoires classiques, donnèrent le ton de cette fonction : « J'ai reçu autorité sur vous, bien que je ne sois pas le meilleur d'entre vous… si je fais bien, aidez-moi ; si je fais mal, corrigez-moi. » C'est le point d'origine du Califat — khilafa, signifiant « succession » — un leadership choisi par la communauté et responsable devant elle plutôt qu'hérité automatiquement par filiation.\n\nLa leçon : même à son moment le plus fragile, la communauté résolut une question de leadership par la consultation (choura) plutôt que par la force, un précédent auquel chaque récit du premier Califat revient.",
  },
  {
    title: "Les guerres de Ridda",
    location: "Arabie",
    body: "Presque immédiatement après la mort du Prophète ﷺ, plusieurs tribus arabes qui lui avaient prêté allégeance traitèrent ce serment comme personnel à lui seul et renoncèrent à l'islam ou refusèrent de payer la zakat au nouveau calife, tandis qu'une poignée d'individus revendiquaient également la prophétie pour eux-mêmes. Abou Bakr jugea cela une menace existentielle pour l'unité que l'islam avait construite et insista, célèbrement, qu'il combattrait quiconque retiendrait même la valeur d'une jeune chèvre due comme zakat, s'ils l'avaient donnée au Prophète ﷺ.\n\nDurant environ une année de dure campagne — les guerres de Ridda (« apostasie ») — les forces musulmanes sous des commandants dont Khalid ibn al-Walid restaurèrent l'autorité de Médine à travers la péninsule arabique, défaisant les tribus rebelles et les faux prétendants à la prophétie, le plus significativement à la bataille d'al-Yamama contre les forces de Mousaylima.\n\nLa leçon : la fermeté d'Abou Bakr maintint unie une communauté qui aurait pu facilement se fracturer tribu par tribu dès sa toute première année — la zakat et le leadership unifié furent traités comme inséparables de la foi elle-même.",
  },
  {
    title: "La première compilation écrite du Coran",
    location: "Médine",
    body: "La bataille de Yamama durant les guerres de Ridda tua un grand nombre de compagnons qui avaient mémorisé le Coran en entier. Alarmé qu'une bataille supplémentaire puisse mettre des parties du Coran en risque de disparaître totalement de la mémoire, Omar exhorta Abou Bakr à le faire rassembler en une collection écrite unique — chose que le Prophète ﷺ lui-même n'avait jamais ordonnée, puisque le Coran avait été préservé à la fois par écrit sur des matériaux dispersés et dans les mémoires des huffaz durant sa vie.\n\nAbou Bakr chargea Zayd ibn Thabit, un des anciens scribes du Prophète ﷺ, de cette tâche. Zayd décrivit plus tard cela comme la chose la plus difficile qu'on lui ait jamais demandée, rassemblant des versets à partir de tiges de feuilles de palmier, de pierres plates, de morceaux de cuir, et des mémoires de ceux qui les avaient appris directement du Prophète ﷺ, vérifiant soigneusement chaque portion (Sahih al-Boukhari 4986). Le manuscrit résultant passa ensuite à Omar, puis à sa fille Hafsa pour être conservé.\n\nLa leçon : la préservation du Coran combina dès le début à la fois la mémorisation orale et l'écriture soigneusement vérifiée — un processus délibéré et vérifié plutôt que l'effort privé d'une seule personne.",
  },
  {
    title: "La bataille de Yarmouk",
    location: "Rivière Yarmouk, près de la frontière syro-jordanienne",
    body: "Tandis que les armées musulmanes progressaient dans le Levant sous le calife Omar, l'Empire byzantin assembla une très grande force pour renverser leurs gains. Les deux camps se rencontrèrent près de la rivière Yarmouk en 15 AH. Tôt dans la campagne, Khalid ibn al-Walid, amené pour unifier le commandement de plusieurs détachements musulmans, restructura la force musulmane plus petite en un arrangement plus mobile et discipliné, et après des jours de combats acharnés, l'armée byzantine se rompit et fut décisivement défaite.\n\nYarmouk mit effectivement fin à la domination byzantine sur la Syrie et ouvrit la voie à la conquête musulmane du Levant plus large, incluant Damas et, peu après, Jérusalem. Elle est rappelée dans les histoires classiques (al-Tabari) comme une des batailles les plus déterminantes des premières conquêtes, obtenue malgré des forces musulmanes considérablement inférieures en nombre.\n\nLa leçon : une organisation disciplinée et un commandement unifié, plus que le simple nombre, décidèrent du résultat — un schéma sur lequel les premiers généraux musulmans s'appuyèrent à répétition durant cette période d'expansion rapide.",
  },
  {
    title: "La bataille d'al-Qadisiyya",
    location: "près d'al-Qadisiyya, Irak",
    body: "À peu près à la même période que Yarmouk, les forces musulmanes sous le calife Omar affrontèrent aussi l'Empire sassanide perse, dont l'armée était renforcée d'éléphants de guerre et d'un équipement de loin supérieur. À al-Qadisiyya, l'armée musulmane — commandée par Sa'd ibn Abi Waqqas, un des Dix Promis au Paradis — mena une bataille de plusieurs jours qui se termina par une victoire musulmane décisive.\n\nLa défaite brisa la capacité de l'Empire sassanide à tenir l'Irak, et Sa'd fonda ensuite la ville-garnison de Koufa comme nouveau centre administratif et militaire de la région. Al-Qadisiyya est traitée dans les histoires classiques comme le chapitre d'ouverture de la conquête de la Perse, qui continua à travers d'autres campagnes dans les années qui suivirent.\n\nLa leçon : comme à Yarmouk, une discipline soutenue sous un leadership capable et guidé par la foi — non un armement supérieur — est créditée du résultat dans ces récits.",
  },
  {
    title: "La conquête de Jérusalem et le Pacte d'Omar",
    location: "Jérusalem",
    body: "Après la chute de Damas et du Levant plus large, le patriarche chrétien de Jérusalem, Sophrone, accepta de rendre la ville — mais aurait demandé que le calife lui-même vienne accepter la reddition en personne plutôt qu'un général. Omar voyagea depuis Médine pour l'occasion, et les termes qu'il négocia avec le Patriarche, connus comme le Pacte d'Omar (al-'Ahd al-'Oumari), garantirent aux habitants chrétiens de la ville la sécurité de leurs vies, biens et églises, en échange de la jizya payée par les sujets non-musulmans sous domination musulmane.\n\nUn détail bien connu préservé dans les récits historiques (al-Tabari, Ibn Kathir) est que lorsque l'heure de la prière arriva alors qu'Omar se trouvait à l'intérieur de l'église du Saint-Sépulcre, il refusa d'y prier lui-même, par crainte que les générations futures n'utilisent son précédent pour convertir l'église en mosquée — choisissant plutôt de prier à l'extérieur.\n\nLa leçon : la conquête fut associée, dans le même épisode, à un acte délibéré de retenue pour protéger les droits religieux d'une population vaincue — un modèle de conduite que le calife établit personnellement plutôt que de le déléguer.",
  },
  {
    title: "Omar établit le calendrier hégirien",
    location: "Médine",
    body: "Comme l'administration du jeune État musulman grandissait — traités, lettres et registres financiers nécessitant tous une datation cohérente — Omar convoqua ses compagnons seniors pour convenir d'un point de départ pour un calendrier islamique unifié. Diverses options furent discutées, incluant la naissance du Prophète ﷺ, mais le groupe s'accorda sur la Hijra, l'émigration de la Mecque à Médine, comme époque : l'année de la Hijra (622) devint l'an 1 AH (Anno Hegirae).\n\nLe calendrier suit douze mois lunaires, comme le décrit le Coran (Coran 9:36), et reste le calcul standard utilisé aujourd'hui dans toute la vie religieuse islamique, y compris pour le Ramadan, le Hajj, et les calculs de zakat.\n\nLa leçon : le choix d'Omar de dater l'histoire de la communauté à partir d'un acte de sacrifice et de foi — laissant tout derrière pour l'amour d'Allah — plutôt que d'une naissance ou d'une bataille, reflète ce que la première communauté considérait comme son véritable moment fondateur.",
  },
  {
    title: "L'assassinat d'Omar et le conseil de choura",
    location: "Médine",
    body: "En 23 AH, alors qu'il dirigeait la prière du Fajr dans la mosquée de Médine, Omar fut mortellement poignardé par Abou Loulou'a, un esclave persan avec un grief personnel contre lui. Il vécut encore quelques jours, durant lesquels — plutôt que de nommer un seul successeur lui-même, comme Abou Bakr l'avait nommé — il désigna un conseil (choura) de six compagnons seniors, dont Othman, Ali, Talha, al-Zubayr, Abd al-Rahman ibn Awf, et Sa'd ibn Abi Waqqas, et leur ordonna de choisir le prochain calife parmi eux dans les trois jours.\n\nAbd al-Rahman ibn Awf dirigea les consultations, sondant personnellement l'opinion à travers Médine, et la décision du conseil s'arrêta sur Othman ibn Affan, à qui l'allégeance fut prêtée peu après.\n\nLa leçon : le choix d'Omar d'institutionnaliser la consultation plutôt que de simplement nommer son héritier préféré montre un dirigeant limitant délibérément sa propre influence sur ce qui viendrait après lui, confiant la décision à un processus plus large et délibéré.",
  },
  {
    title: "Le Califat d'Othman : expansion et le Coran standard",
    location: "Médine et l'empire élargi",
    body: "Sous Othman, les frontières de l'État musulman continuèrent à s'étendre significativement, atteignant plus loin en Afrique du Nord, en Perse et en Asie centrale, et une marine musulmane fut organisée pour la première fois pour des campagnes en Méditerranée. Comme l'empire devenait plus diversifié, un compagnon nommé Houdhayfa ibn al-Yaman, revenant de campagnes à l'est, rapporta à Othman son inquiétude que les musulmans de différentes provinces commençaient à réciter le Coran avec des lectures régionales notablement différentes, et avertit que la communauté risquait le genre de division scripturaire qu'il avait vue chez les juifs et les chrétiens.\n\nOthman répondit en demandant le manuscrit original du Coran conservé par Hafsa et chargea un petit comité, à nouveau dirigé par Zayd ibn Thabit, de produire un petit nombre d'exemplaires standardisés dans le dialecte des Quraych, qu'il envoya ensuite aux principaux centres provinciaux, ordonnant que les copies partielles ou variantes antérieures soient mises de côté en faveur du nouveau texte standard (Sahih al-Boukhari 4987).\n\nLa leçon : comme la communauté devenait plus grande et plus dispersée géographiquement, Othman agit tôt et avec décision pour protéger l'unité de son texte central — le même instinct qui avait guidé la compilation antérieure d'Abou Bakr, maintenant appliqué à l'échelle de tout l'empire.",
  },
  {
    title: "Troubles et assassinat d'Othman",
    location: "Médine",
    body: "Dans les dernières années de son règne, Othman fit face à un mécontentement politique croissant de plusieurs provinces, alimenté par un mélange de griefs — des différends sur la conduite de certains de ses gouverneurs nommés, et des désaccords sur la répartition de la nouvelle richesse afflux des conquêtes. Des groupes d'hommes mécontents voyagèrent à Médine pour présenter leurs plaintes directement, et la situation dégénéra en un siège prolongé de la propre maison d'Othman.\n\nOthman, selon la plupart des récits historiques, choisit de ne pas permettre de combats à grande échelle pour sa défense à l'intérieur même de Médine, préférant éviter l'effusion de sang parmi les musulmans même au prix de sa propre vie ; il fut tué à l'intérieur de sa maison en 35 AH alors que, comme les histoires le rapportent, il lisait le Coran. Sa mort choqua la communauté plus large et laissa des blessures politiques profondes et durables auxquelles les années suivantes devraient faire face.\n\nLa leçon : cet épisode, souvent appelé la Fitna (la grande épreuve), marque un véritable tournant dans l'histoire islamique précoce — un rappel que même une communauté bâtie sur la foi n'est pas à l'abri de tensions politiques internes, et que la réponse à une telle tension façonne tout ce qui suit.",
  },
  {
    title: "Le Califat d'Ali et la bataille du Chameau",
    location: "près de Bassora, Irak",
    body: "Après la mort d'Othman, le peuple de Médine prêta allégeance à Ali ibn Abi Talib comme quatrième calife. Il hérita d'une communauté déjà ébranlée par l'assassinat et par le désaccord sur la manière de poursuivre la justice à ce sujet, et sur la rapidité avec laquelle les responsables devaient être identifiés et tenus pour responsables.\n\nAïcha, avec les compagnons Talha ibn Oubaydallah et al-Zubayr ibn al-Awwam, se dirigea vers Bassora en quête de responsabilité pour le meurtre d'Othman ; Ali, cherchant à résoudre l'affaire par le dialogue, se déplaça pour les rencontrer, et les négociations firent apparemment de réels progrès. Cependant, des combats éclatèrent — les récits diffèrent sur la manière exacte dont cela commença — dans ce qui devint connu comme la bataille du Chameau, nommée pour l'animal qu'Aïcha montait durant la rencontre. Talha et al-Zubayr furent tous deux tués, et Ali traita ensuite Aïcha avec respect et organisa son retour en sécurité à Médine.\n\nLa leçon : même des compagnons du plus haut rang pouvaient se retrouver dans des camps opposés d'une crise politique sans qu'aucun d'eux ne soit simplement « dans l'erreur » — les récits classiques enregistrent soigneusement leur respect mutuel avant et après le combat, plutôt que de le présenter comme un affrontement entre méchants et héros.",
  },
  {
    title: "La bataille de Siffin et son arbitrage",
    location: "Siffin, sur le fleuve Euphrate",
    body: "Séparément du conflit sur la mort d'Othman, le Califat d'Ali fit face à un défi de Mou'awiya ibn Abi Sufyan, gouverneur de Syrie et proche d'Othman, qui refusait de se soumettre à l'autorité d'Ali jusqu'à ce que les assassins d'Othman soient traduits en justice. Les armées des deux camps se rencontrèrent à Siffin en 37 AH, et après des combats prolongés et largement indécis, les deux camps convinrent de régler le différend par arbitrage plutôt que par la poursuite de la bataille.\n\nLe processus d'arbitrage lui-même s'éternisa sans produire une solution que l'un ou l'autre camp accepterait pleinement, et la division politique sous-jacente entre les camps d'Ali et de Mou'awiya persista bien au-delà de la bataille elle-même.\n\nLa leçon : la volonté des deux camps d'arrêter la guerre ouverte en faveur de l'arbitrage reflète une valeur durable même au milieu d'une crise profonde — qu'un processus négocié, même imparfait, était préférable à un conflit sans limite entre musulmans.",
  },
  {
    title: "L'émergence des Kharijites",
    location: "Irak",
    body: "Une partie des propres partisans d'Ali étaient mécontents de sa décision d'accepter l'arbitrage à Siffin, arguant que l'affaire aurait dû être laissée au jugement d'Allah par la poursuite du combat plutôt que par une négociation humaine. Ce groupe se sépara du camp d'Ali, devenant connu comme les Kharijites (« ceux qui sont sortis »), et développa des positions de plus en plus extrêmes, incluant la déclaration de mécréance envers les musulmans qui n'étaient pas d'accord avec eux.\n\nAli affronta ce groupe dissident lors de la bataille de Nahrawan en 38 AH, où la plupart de leurs combattants furent tués, mais les idées du mouvement persistèrent ensuite en groupes plus petits à travers la région plus large.\n\nLa leçon : cet épisode est rappelé dans l'enseignement sunnite dominant comme un avertissement précoce sur le danger de l'extrémisme — traiter le désaccord sur des jugements politiques difficiles comme un motif de déclarer des musulmans en dehors de la foi.",
  },
  {
    title: "L'assassinat d'Ali",
    location: "Koufa, Irak",
    body: "En 40 AH, un ancien Kharijite nommé Ibn Muldjam frappa Ali d'une épée empoisonnée alors qu'il se rendait diriger la prière du Fajr dans la mosquée principale de Koufa, en vengeance de la défaite des Kharijites à Nahrawan. Ali mourut de sa blessure quelques jours plus tard, ayant apparemment instruit que son agresseur, s'il survivait, ne soit pas torturé ou mutilé en représailles, seulement exécuté justement pour le meurtre.\n\nSa mort retira le dernier des quatre califes que le Prophète ﷺ avait personnellement connus, et laissa la question du leadership à nouveau non résolue à un moment de division continue entre ses partisans et le camp de Mou'awiya en Syrie.\n\nLa leçon : l'instruction d'Ali de limiter les représailles à une stricte justice, même pour son propre meurtrier, fait écho à une norme que le Prophète ﷺ lui-même avait établie après la conquête de la Mecque — la retenue même au moment de la plus grande perte personnelle.",
  },
  {
    title: "L'abdication d'Al-Hasan et la fin de l'ère Rashidun",
    location: "Koufa et Damas",
    body: "Après la mort d'Ali, le peuple de Koufa prêta allégeance à son fils aîné, Al-Hasan ibn Ali, comme calife. Face à une communauté divisée et à la probabilité d'une nouvelle effusion de sang contre les forces de Mou'awiya en Syrie, Al-Hasan, en quelques mois, choisit de renoncer à sa revendication du Califat en faveur de Mou'awiya dans l'intérêt de l'unité, accomplissant quelque chose que le Prophète ﷺ avait prédit des années plus tôt : « Ce fils qui est le mien est un chef (sayyid), et peut-être Allah opérera-t-il par lui la réconciliation entre deux grands groupes de musulmans » (Sahih al-Boukhari 3746).\n\nL'année où cette réconciliation eut lieu, 41 AH, devint connue comme Aam al-Jama'a, l'Année de l'Unité. Elle marque la fin du Califat Rashidun (« bien guidé ») — la période des quatre califes qui avaient personnellement connu le Prophète ﷺ — et le début de la dynastie omeyyade sous Mou'awiya, une période ultérieure hors du champ de cette chronologie.\n\nLa leçon : l'ère Rashidun, qui commença par une transition pacifique du leadership à Saqifa, se clôt ici par un autre acte délibéré de pacification plutôt qu'une bataille finale — une conclusion appropriée à trente années qui avaient testé l'unité de la communauté encore et encore.",
  },
];
