import type { IslamicHistoryEvent } from "../../types/islamic-history";
import type { DeepPartial } from "./localize";

// kk overlay for islamic-history. Index-aligned with ISLAMIC_HISTORY_EVENTS in ../islamic-history.ts.
// Scaffolded from English — refine literary quality in follow-up i18n polish.
export const ISLAMIC_HISTORY_EVENTS_KK: DeepPartial<IslamicHistoryEvent>[] = [
  {
    title: "The Prophet's ﷺ death and the succession",
    location: "Madinah",
    body: "When the Prophet ﷺ passed away in 11 AH, the young Muslim community faced its first major test without him: who would lead it? A group of the Ansar gathered at Saqifah Bani Sa'idah in Madinah to discuss the matter among themselves. Learning of this, Abu Bakr and Umar hurried to join them, and after discussion the gathering pledged allegiance to Abu Bakr — the wider community following the next day. Ali and some others pledged allegiance somewhat later, after burying the Prophet ﷺ, but the transition itself passed without violence.\n\nAbu Bakr's inaugural words to the people, preserved in the classical histories, set the tone for the office: \"I have been given authority over you, though I am not the best of you… if I do well, help me; if I do wrong, correct me.\" This is the origin point of the Caliphate — khilafah, meaning 'succession' — as a leadership chosen by and accountable to the community rather than inherited automatically by bloodline.\n\nThe lesson: even at its most fragile moment, the ummah resolved a leadership question through consultation (shura) rather than force, a precedent every account of the early Caliphate returns to.",
  },
  {
    title: "The Ridda wars",
    location: "Arabia",
    body: "Almost immediately after the Prophet's ﷺ death, several Arab tribes that had pledged loyalty to him treated that pledge as personal to him alone and renounced Islam or refused to pay zakat to the new Caliph, while a handful of individuals also claimed prophethood for themselves. Abu Bakr judged this an existential threat to the unity Islam had built and insisted, famously, that he would fight anyone who withheld even the value of a young she-goat that was due as zakat, if they had given it to the Prophet ﷺ.\n\nOver roughly a year of hard campaigning — the Ridda ('apostasy') wars — Muslim forces under commanders including Khalid ibn al-Walid restored the authority of Madinah across the Arabian Peninsula, defeating the rebel tribes and the false claimants to prophethood, most significantly at the Battle of al-Yamamah against the forces of Musaylimah.\n\nThe lesson: Abu Bakr's firmness held together a community that could easily have fractured tribe by tribe in its very first year — zakat and unified leadership were treated as inseparable from faith itself.",
  },
  {
    title: "The first written compilation of the Qur'an",
    location: "Madinah",
    body: "The Battle of Yamamah during the Ridda wars killed a large number of the companions who had memorized the Qur'an in full. Alarmed that a further battle could put parts of the Qur'an at risk of being lost from memory altogether, Umar urged Abu Bakr to have it gathered into a single written collection — something the Prophet ﷺ himself had never ordered, since the Qur'an had been preserved both in writing on scattered materials and in the memories of the huffaz during his lifetime.\n\nAbu Bakr commissioned Zayd ibn Thabit, one of the Prophet's ﷺ former scribes, for the task. Zayd later described it as the hardest thing he was ever asked to do, gathering verses from palm-leaf stalks, flat stones, pieces of leather, and the memories of those who had learned them directly from the Prophet ﷺ, cross-checking each portion carefully (Sahih al-Bukhari 4986). The resulting manuscript passed afterward to Umar, and then to his daughter Hafsa for safekeeping.\n\nThe lesson: the Qur'an's preservation combined both oral memorization and careful, cross-checked writing from the very start — a deliberate, verified process rather than a single person's private effort.",
  },
  {
    title: "The Battle of Yarmouk",
    location: "Yarmouk River, near the Syria–Jordan border",
    body: "As the Muslim armies pressed into the Levant under the Caliph Umar, the Byzantine Empire assembled a very large force to reverse their gains. The two sides met near the Yarmouk River in 15 AH. Early in the campaign Khalid ibn al-Walid, brought in to unify command of several Muslim detachments, restructured the smaller Muslim force into a more mobile and disciplined arrangement, and after days of hard fighting the Byzantine army broke and was decisively defeated.\n\nYarmouk effectively ended Byzantine rule over Syria and opened the way for the Muslim conquest of the wider Levant, including Damascus and, soon after, Jerusalem. It is remembered in the classical histories (al-Tabari) as one of the most consequential battles of the early conquests, achieved despite the Muslim forces being considerably outnumbered.\n\nThe lesson: disciplined organisation and unified command, more than sheer numbers, decided the outcome — a pattern the early Muslim generals relied on repeatedly during this period of rapid expansion.",
  },
  {
    title: "The Battle of al-Qadisiyyah",
    location: "near al-Qadisiyyah, Iraq",
    body: "Around the same period as Yarmouk, Muslim forces under the Caliph Umar also faced the Sasanian Persian Empire, whose army was reinforced with war elephants and vastly superior equipment. At al-Qadisiyyah, the Muslim army — commanded by Sa'd ibn Abi Waqqas, one of the Ten Promised Paradise — fought a multi-day battle that ended in a decisive Muslim victory.\n\nThe defeat broke the Sasanian Empire's ability to hold Iraq, and Sa'd went on to found the garrison city of Kufa as a new administrative and military centre for the region. Qadisiyyah is treated in the classical histories as the opening chapter of the conquest of Persia, which continued through further campaigns in the years that followed.\n\nThe lesson: as with Yarmouk, sustained discipline under a capable, faith-driven leadership — not superior weaponry — is credited in these accounts with the outcome.",
  },
  {
    title: "The conquest of Jerusalem and Umar's Covenant",
    location: "Jerusalem",
    body: "After the fall of Damascus and the wider Levant, Jerusalem's Christian Patriarch, Sophronius, agreed to surrender the city — but reportedly asked that the Caliph himself come to accept the surrender in person rather than a general. Umar travelled from Madinah for the occasion, and the terms he agreed with the Patriarch, remembered as the Covenant of Umar (al-'Ahd al-'Umari), guaranteed the city's Christian inhabitants safety for their lives, property, and churches, in exchange for the jizyah tax paid by non-Muslim subjects under Muslim rule.\n\nA well-known detail preserved in the historical accounts (al-Tabari, Ibn Kathir) is that when the time for prayer came while Umar was inside the Church of the Holy Sepulchre, he declined to pray there himself, out of concern that future generations might use his precedent to convert the church into a mosque — choosing instead to pray outside.\n\nThe lesson: the conquest was paired, in the same episode, with a deliberate act of restraint to protect the religious rights of a defeated population — a model of conduct the Caliph set personally rather than delegating.",
  },
  {
    title: "Umar establishes the Hijri calendar",
    location: "Madinah",
    body: "As the young Muslim state's administration grew — treaties, letters, and financial registers all needed consistent dating — Umar convened his senior companions to agree on a starting point for a unified Islamic calendar. Various options were discussed, including the Prophet's ﷺ birth, but the group settled on the Hijra, the emigration from Makkah to Madinah, as the epoch: the year of the Hijra (622 CE) became Year 1 AH (Anno Hegirae).\n\nThe calendar follows twelve lunar months, as the Qur'an describes (Qur'an 9:36), and remains the standard reckoning used across Islamic religious life today, including for Ramadan, Hajj, and zakat calculations.\n\nThe lesson: Umar's choice to date the ummah's history from an act of sacrifice and faith — leaving everything behind for Allah's sake — rather than from a birth or a battle, reflects what the early community considered its true founding moment.",
  },
  {
    title: "The assassination of Umar and the shura council",
    location: "Madinah",
    body: "In 23 AH, while leading the Fajr prayer in the mosque of Madinah, Umar was fatally stabbed by Abu Lu'lu'a, a Persian slave with a personal grievance against him. He lived for a few days afterward, during which — rather than name a single successor himself, as Abu Bakr had named him — he appointed a council (shura) of six senior companions, including Uthman, Ali, Talha, al-Zubayr, Abd al-Rahman ibn Awf, and Sa'd ibn Abi Waqqas, and instructed them to choose the next Caliph from among themselves within three days.\n\nAbd al-Rahman ibn Awf led the consultations, personally surveying opinion across Madinah, and the council's decision settled on Uthman ibn Affan, who was given the pledge of allegiance shortly afterward.\n\nThe lesson: Umar's choice to institutionalise consultation rather than simply naming his own preferred heir shows a leader deliberately limiting his own influence over what came after him, entrusting the decision to a wider, deliberate process.",
  },
  {
    title: "Uthman's Caliphate: expansion and the standard Qur'an",
    location: "Madinah and the wider empire",
    body: "Under Uthman, the borders of the Muslim state continued to expand significantly, reaching further into North Africa, Persia, and Central Asia, and a Muslim navy was organised for the first time to campaign in the Mediterranean. As the empire grew more diverse, a companion named Hudhayfah ibn al-Yaman, returning from campaigns in the east, reported to Uthman his concern that Muslims in different provinces were beginning to recite the Qur'an with noticeably different regional readings, and warned that the ummah risked the kind of scriptural division he had seen among Jews and Christians.\n\nUthman responded by requesting the original Qur'an manuscript kept by Hafsa and commissioning a small committee, again led by Zayd ibn Thabit, to produce a small number of standardized master copies in the dialect of Quraysh, which he then sent to the major provincial centres, ordering earlier partial or variant copies to be set aside in favour of the new standard text (Sahih al-Bukhari 4987).\n\nThe lesson: as the ummah became larger and more geographically spread out, Uthman acted early and decisively to protect the unity of its central text — the same instinct that had driven Abu Bakr's earlier compilation, now applied at empire-wide scale.",
  },
  {
    title: "Unrest and the assassination of Uthman",
    location: "Madinah",
    body: "In the later years of his rule, Uthman faced growing political discontent from several provinces, driven by a mix of grievances — disputes over the conduct of some of his appointed governors, and disagreements about the distribution of the new wealth flowing in from the conquests. Groups of aggrieved men travelled to Madinah to press their complaints directly, and the situation escalated into a prolonged siege of Uthman's own house.\n\nUthman, by most historical accounts, chose not to permit large-scale fighting in his defence inside Madinah itself, preferring to avoid bloodshed among Muslims even at the cost of his own life; he was killed inside his home in 35 AH while, as the histories record, he was reading from the Qur'an. His death shocked the wider ummah and left deep and lasting political wounds that the following years would have to reckon with.\n\nThe lesson: this episode, often called the Fitna (the great trial), marks a genuine turning point in early Islamic history — a reminder that even a community built on faith is not immune to internal political strain, and that the response to such strain shapes everything that follows it.",
  },
  {
    title: "Ali's Caliphate and the Battle of the Camel",
    location: "near Basra, Iraq",
    body: "After Uthman's death, the people of Madinah gave their pledge of allegiance to Ali ibn Abi Talib as the fourth Caliph. He inherited an ummah already shaken by the assassination and by disagreement over how justice for it should be pursued, and over how quickly those responsible should be identified and held accountable.\n\nAisha, along with the companions Talha ibn Ubaydullah and al-Zubayr ibn al-Awwam, moved toward Basra seeking accountability for Uthman's killing; Ali, seeking to resolve the matter through dialogue, moved to meet them, and negotiations reportedly made real progress. However, fighting broke out — accounts differ on exactly how it began — in what became known as the Battle of the Camel, named for the animal Aisha rode during the encounter. Talha and al-Zubayr were both killed, and Ali afterward treated Aisha with respect and arranged for her safe return to Madinah.\n\nThe lesson: even companions of the very highest standing could find themselves on opposing sides of a political crisis without any of them being simply 'in the wrong' — the classical accounts are careful to record their mutual respect before and after the fighting, rather than framing it as a contest between villains and heroes.",
  },
  {
    title: "The Battle of Siffin and its arbitration",
    location: "Siffin, on the Euphrates River",
    body: "Separately from the conflict over Uthman's death, Ali's Caliphate faced a challenge from Mu'awiyah ibn Abi Sufyan, the governor of Syria and a relative of Uthman, who declined to submit to Ali's authority until Uthman's killers were brought to justice. The two sides' armies met at Siffin in 37 AH, and after extended and largely inconclusive fighting, both sides agreed to settle the dispute through arbitration rather than continued battle.\n\nThe arbitration process itself dragged on without producing a resolution that either side fully accepted, and the underlying political division between Ali's and Mu'awiyah's camps persisted well beyond the battle itself.\n\nThe lesson: the willingness of both sides to halt outright warfare in favour of arbitration reflects an enduring value even amid deep crisis — that a negotiated process, however imperfect, was preferable to unlimited conflict between Muslims.",
  },
  {
    title: "The emergence of the Kharijites",
    location: "Iraq",
    body: "A portion of Ali's own supporters were dissatisfied with his decision to accept arbitration at Siffin at all, arguing that the matter should have been left to Allah's judgement through continued fighting rather than a human negotiation. This group broke away from Ali's camp, becoming known as the Kharijites ('those who went out'), and developed increasingly extreme positions, including declaring fellow Muslims who disagreed with them to be unbelievers.\n\nAli confronted this breakaway group in battle at Nahrawan in 38 AH, where most of their fighters were killed, but the movement's ideas persisted afterward in smaller groups across the wider region.\n\nThe lesson: this episode is remembered in mainstream Sunni scholarship as an early warning about the danger of extremism — treating disagreement over difficult political judgement calls as grounds for declaring fellow Muslims to be outside the faith altogether.",
  },
  {
    title: "The assassination of Ali",
    location: "Kufa, Iraq",
    body: "In 40 AH, a former Kharijite named Ibn Muljam struck Ali with a poisoned sword while he was on his way to lead the Fajr prayer in the main mosque of Kufa, in revenge for the defeat of the Kharijites at Nahrawan. Ali died from his wound a few days later, having reportedly instructed that his assailant, if he survived, should not be tortured or mutilated in retaliation, only executed justly for the killing.\n\nHis death removed the last of the four Caliphs the Prophet ﷺ had lived alongside personally, and left the question of leadership once again unsettled at a moment of continuing division between his supporters and Mu'awiyah's camp in Syria.\n\nThe lesson: Ali's instruction to limit retaliation to strict justice, even for his own killer, echoes a standard the Prophet ﷺ himself had set after the conquest of Makkah — restraint even in the moment of greatest personal loss.",
  },
  {
    title: "Al-Hasan's abdication and the end of the Rashidun era",
    location: "Kufa and Damascus",
    body: "After Ali's death, the people of Kufa gave their pledge of allegiance to his elder son, Al-Hasan ibn Ali, as Caliph. Facing a divided ummah and the likelihood of further bloodshed against Mu'awiyah's forces in Syria, Al-Hasan, within months, chose to relinquish his claim to the Caliphate to Mu'awiyah in the interest of unity, fulfilling something the Prophet ﷺ had foretold years earlier: \"This son of mine is a chief (sayyid), and perhaps Allah will bring about reconciliation between two great groups of Muslims through him\" (Sahih al-Bukhari 3746).\n\nThe year in which this reconciliation took place, 41 AH, became known as Aam al-Jama'ah, the Year of Unity. It marks the close of the Rashidun ('rightly guided') Caliphate — the period of the four Caliphs who had known the Prophet ﷺ personally — and the beginning of the Umayyad dynasty under Mu'awiyah, a later period outside the scope of this timeline.\n\nThe lesson: the Rashidun era, which began with a peaceful transition of leadership at Saqifah, closes here with another deliberate act of peacemaking rather than a final battle — a fitting bookend to thirty years that had tested the ummah's unity again and again.",
  },
];
