// Swahili translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_SW: DeepPartial<SeerahEvent>[] = [
  {
    title: "Uarabuni kabla ya Uislamu (Jahiliyyah)",
    body: 'Ili kumuelewa Mtume ﷺ kwanza inabidi upate taswira ya ulimwengu aliotumwa. Arabuni ya karne ya sita ilikuwa ni nchi ya makabila yaliyotawanyika yasiyo na dola kuu, iliyofungamana pamoja na nasaba, heshima, na patakatifu pa Ka’abah huko Makka—madhabahu iliyojengwa na Ibrahim na Isma’il kwa ajili ya kumwabudu Mungu mmoja, lakini hivi sasa imezungukwa na masanamu yapatayo mia tatu na sitini.\n\nEnzi hii inaitwa Jahiliyyah, "zama za ujinga" - sio kwa sababu Waarabu walikosa akili (mashairi na kumbukumbu zao zilikuwa za ajabu) lakini kwa sababu walikosa mwongozo. Ugomvi wa kikabila ungeweza kutokea kwa vizazi vingi, wenye nguvu kuwindwa na wanyonge, na mabinti wakati mwingine walizikwa wakiwa hai kwa sababu ya aibu au hofu ya umaskini - jambo ambalo Qur\'ani ingelilaani moja kwa moja (Qur\'ani 81:8-9). Kando ya ibada ya sanamu, "hunafa" wachache bado walitafuta imani takatifu ya Mungu mmoja wa Ibrahim, na jumuiya ndogo za Wayahudi na Wakristo ziliishi katika peninsula hiyo.\n\nSomo: ufunuo haukushuka katika ombwe bali katika jamii halisi yenye majeraha makubwa, na jambo la kwanza uliponya lilikuwa uhusiano kati ya mwanadamu na Muumba wake. Zingatia hali hii wakati ratiba inapoendelea - karibu kila marekebisho ya Mtume ﷺ ni jibu la moja kwa moja kwa dhulma ya Jahiliyyah.',
    location: "Uarabuni",
  },
  {
    title: "Kuzaliwa huko Makka",
    body: 'Mtume (Swalla Allaahu ‘alayhi wa aalihi wa sallam) alizaliwa Makka katika Mwaka wa Tembo (Am al-Fil), jina hilo kwa sababu mwaka huo Abraha, gavana wa Kihabeshi wa Yemen, aliandamana na jeshi lililokuwa na tembo kuiharibu Ka’aba na alirudishwa nyuma kimiujiza - tukio ambalo Qur’ani inakumbuka katika Surah al-Fil (Qur’ani 105). Ndani ya mwaka huu wenye mamlaka mtoto alizaliwa katika kabila la Maquraishi na ukoo wake wenye heshima sana, Banu Hashim.\n\nTayari alikuwa yatima wakati wa kuzaliwa: baba yake Abdullah alifariki miezi kadhaa kabla ya hapo alipokuwa anafanya biashara. Mama yake, Aminah binti Wahb, alimwita Muhammad - "aliyesifiwa sana" - jina ambalo karibu halijulikani miongoni mwa Waarabu. Kwa kuzingatia desturi ya Makka alitumwa kulelewa na kulelewa katika anga ya wazi ya jangwa kati ya Banu Sa\'d, chini ya uangalizi wa Halimah as-Sa\'diyyah.\n\nFunzo kwa Muumini: ukuu mbele ya Mwenyezi Mungu hauna uhusiano wowote na usalama wa dunia. Mtume wa mwisho alianza maisha ya kutokuwa na baba na hivi karibuni atakuwa hana mama, lakini Mwenyezi Mungu alikuwa mlinzi wake - "Je, hakukuta wewe yatima na akakupa hifadhi? (Kurani 93:6). Tazama pia "Kufariki kwa mama yake" na "Ulezi wa Abu Talib" zinazofuata.',
    location: "Makka",
  },
  {
    title: "Kupita kwa mama yake",
    body: "Alipokuwa na umri wa miaka sita hivi, Aminah alimchukua mwanawe kwenda kuwatembelea jamaa zake huko Yathrib (baadaye Madina) na kuliona kaburi la baba yake. Katika safari ya kurudi aliugua na akafa mahali paitwapo Abwa', kati ya Makka na Madinah, na akazikwa hapo. Kijana Muhammad ﷺ alikuwa amepoteza wazazi wote wawili.\n\nAlirudishwa Makka na Umm Ayman, mtumishi aliyeachwa huru wa familia hiyo, na akawekwa chini ya uangalizi wa babu yake Abd al-Muttalib, chifu anayeheshimika wa Maquraishi, ambaye alimpenda sana na alikuwa akimketisha kando yake kwenye Ka'bah.\n\nFunzo: Mtume ﷺ alionja, mapema na mara kwa mara, huzuni wanayobeba wanadamu wengi - kufiwa, kuhama, kutegemea wengine. Hii ilikuwa ni sehemu ya maandalizi yake. Moyo ambao umejua hasara ni moyo unaoweza kuhisi kwa yatima, mjane, na mgeni, na jamii yake baadaye ingejengwa juu ya huruma hiyo haswa. Uzi huu unaendelea katika \"Mwaka wa Huzuni.\"",
    location: "Abwa'",
  },
  {
    title: "Ulezi wa Abu Talib",
    body: "Miaka miwili baada ya mama yake, babu yake Abd al-Muttalib pia alifariki, wakati mvulana huyo akiwa na umri wa miaka minane hivi. Akiwa kwenye kitanda cha mauti alimkabidhi mjukuu wake kipenzi kwa mwanawe Abu Talib, ami wa baba yake Mtume. Ingawa Abu Talib hakuwa tajiri, alimchukua mtoto huyo na kumpeleka nyumbani kwake na kumchukulia kama mmoja wa watoto wake kipenzi.\n\nAbu Talib angebaki kuwa mlinzi wake kwa zaidi ya miaka arobaini, ndani ya miaka ile migumu sana ya mateso huko Makka. Ni yeye aliyemchukua kijana Muhammad (Swalla Allaahu 'alayhi wa aalihi wa sallam) katika safari za biashara hadi Syria, ambapo - kwa mujibu wa maelezo mashuhuri - mtawa Bahira aliona dalili za utume ndani yake (Ripoti ambayo Sirah inahifadhi, ingawa maelezo yake yanawasilishwa kwa nguvu tofauti).\n\nFunzo: Mwenyezi Mungu aliwaweka watu waaminifu na watukufu karibu na Mtume Wake (Swalla Allaahu 'alayhi wa aalihi wa sallam) katika kila hatua. Miongo ya ulinzi wa Abu Talib ilikuwa ni rehema - ukumbusho kwamba kuunga mkono ukweli na ujamaa ni kituo tukufu hata kwa wale ambao bado hawajaamini, na kwamba tunapaswa kuwaheshimu wale wanaotuhifadhi. Kupoteza kwake baadaye, katika Mwaka wa Huzuni, kungebadilisha kila kitu.",
    location: "Makka",
  },
  {
    title: "Ndoa kwa Khadijah",
    body: 'Akiwa kijana Muhammad (Swalla Allaahu ‘alayhi wa aalihi wa sallam) alijipatia sifa katika mji wa Makka ambayo hakuna mali inayoweza kununua: al-Sadiq, mkweli, na al-Amin, mwaminifu. Watu waliweka vitu vyao vya thamani kwake kwa ajili ya kuhifadhiwa na kulitumainia neno lake kabisa, hata wale walioabudu miungu mbalimbali.\n\nKhadija binti Khuwaylid (radhi za Allah ziwe juu yake), mfanyabiashara mtukufu na mwenye mafanikio makubwa wa Waquraishi, alimkodisha ili aongoze msafara wake kuelekea Syria. Akiwa amevutiwa na uaminifu na tabia yake, alituma pendekezo la ndoa kupitia kwa rafiki yake Khawlah binti Hakim. Alikuwa kama ishirini na tano na yeye kama arobaini; yao ikawa ndoa ya mapenzi mazito na ushirikiano. Alimzalia watoto wake na kubaki mke wake wa pekee kwa miaka ishirini na mitano, hadi kifo chake.\n\nSomo: tabia ni msingi wa kila kitu kilichofuata. Muda mrefu kabla hajaitwa nabii, Makka tayari ilimfahamu kama mtu mwaminifu zaidi miongoni mwao - ndiyo maana, katika ufunuo wa kwanza, imani ya papo hapo ya Khadija kwake ilikuwa ya maamuzi (ona "Ufunuo wa kwanza"). Uadilifu wa muumini katika mambo ya kawaida yenyewe ni aina ya da\'wah.',
    location: "Makka",
  },
  {
    title: "Hilf al-Fudul na Jiwe Jeusi",
    body: "Matukio mawili ya maisha yake ya kabla ya unabii yanaonyesha maadili ambayo angejenga taifa juu yake. Kwanza, Hilf al-Fudul: mapatano mazito yaliyoapishwa na koo kadhaa za Maquraishi kusimama na mtu yeyote aliyedhulumiwa huko Makka, mwenyeji au mgeni, hadi pale haki zao zitakaporejeshwa. Mtume ﷺ alishiriki na baadaye akasema bado angejibu mapatano hayo hata katika Uislamu - kwa sababu yanalinda haki.\n\nPili, kujengwa upya kwa Ka'bah baada ya mafuriko. Wakati koo hizo zilipokaribia kuvuma kwa heshima ya kunyanyua Jiwe jeusi tukufu (al-Hajar al-Aswad) mahali pake, zilikubali kukubali hukumu ya mtu anayefuata kuingia - na alikuwa ni Muhammad ﷺ. Suluhisho lake lilikuwa maarufu kwa hekima yake: aliweka jiwe juu ya kitambaa na kumfanya mkuu wa kila ukoo kuinua kona, kisha akaiweka kwa mikono yake mwenyewe, ili wote walishiriki heshima na hakuna hata mmoja aliyedharauliwa.\n\nSomo: haki na utatuzi wa migogoro ulikuwa silika yake kabla ya ufunuo kuyathibitisha. Muumini ni yule anayemtetea aliyedhulumiwa na kutafuta njia za kuungana badala ya kugawanya - Hilf al-Fudul ni kielelezo cha umma wa haki atakaoanzisha baada ya Hijra.",
    location: "Makka",
  },
  {
    title: "Ufunuo wa kwanza",
    body: 'Mwishoni mwa miaka ya thelathini, Mtume ﷺ alizidi kuacha kufanya ibada na kutafakari katika pango la Hira kwenye mlima wa Jabal an-Nur nje ya Makka. Huko, akiwa na umri wa miaka arobaini ndani ya mwezi wa Ramadhani, Malaika Jibril alitokea na kumwamrisha: "Soma!" Akajibu kuwa hajui kusoma; Malaika alimkumbatia kwa nguvu mara tatu na akaziteremsha aya za mwanzo za Surah al-\'Alaq - "Soma kwa jina la Mola wako aliyeumba..." (Qur\'ani 96:1-5), maneno ya kwanza kabisa ya Qur\'ani.\n\nAlirudi nyumbani huku akitetemeka, na Khadija akamfunika na kumtuliza kwa maneno yanayodhihirisha imani yake na tabia yake: Mwenyezi Mungu hatamfedhehesha, kwani aliweka mafungamano ya jamaa, alibeba mizigo ya wengine, na akawasaidia wanaostahiki. Alimpeleka kwa binamu yake Waraqah ibn Nawfal, mzee aliyejifunza katika maandiko yaliyotangulia, ambaye alimtambua mgeni huyo kama “Namus” (malaika) yule yule aliyekuja kwa Musa na kumwambia huu ulikuwa utume ulioahidiwa. Kipindi hiki chote kimeandikwa katika Sahih al-Bukhari 3.\n\nSomo: ufunuo haukuanza kwa kudai mamlaka bali kwa neno "Soma" - dini iliyojengwa juu ya elimu na unyenyekevu. Na kumbuka ni nani aliyeamini kwanza: mke na kaya mwaminifu. Ukweli unatambuliwa na wale ambao tayari wanaishi kwa uaminifu.',
    location: "Pango la Hira",
  },
  {
    title: "Miaka ya mahubiri binafsi",
    body: "Baada ya wahyi wa kwanza kukafuata kusimama (fatrah), kisha Mwenyezi Mungu akamuamuru Mtume (Swalla Allaahu ´alayhi wa sallam) aanze kuwalingania watu kumuabudu Yeye pekee. Kwa takriban miaka mitatu ya kwanza simu hii ilikuwa ya kimya na ya kibinafsi - iliongezwa kwa familia ya karibu na marafiki wanaoaminika badala ya kutangazwa mitaani.\n\nWaumini wa mwanzo kabisa, “as-Sabiqun al-Awwalun” (wa kwanza kabisa), walitoka katika kila sehemu ya jamii: Khadija mke wake; binamu yake mdogo Ali ibn Abi Talib; mtumishi wake aliyeachwa huru na mwana wa kulea Zayd ibn Harithah; na rafiki yake mwaminifu Abu Bakr as-Siddiq (Mwenyezi Mungu awe radhi nao wote). Abu Bakr naye aliwaleta wengine wengi kwenye Uislamu. Walikutana na kusali kwa busara, mara nyingi kwenye nyumba ya al-Arqam karibu na Ka'bah.\n\nSomo: Uislamu ulikua kwanza kupitia uaminifu na uhusiano, sio tamasha. Angalia upana wa mioyo hiyo ya kwanza - mwanamke tajiri, mtoto, mtumwa aliyeachwa huru, mfanyabiashara - onja ya imani ambayo ingefuta tofauti za rangi na vyeo. Da ́wah huanza karibu na nyumbani, kwa ikhlasi na subira.",
    location: "Makka",
  },
  {
    title: "Wito wa umma kwa Uislamu",
    body: "Mwenyezi Mungu alipoteremsha \"Na uwaonye jamaa zako walio karibu nawe\" (Qur'ani 26:214), Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) alipanda Mlima Safa kando ya Ka'aba na akawaita koo za Maquraishi. Kwanza aliuliza kama wangemwamini ikiwa alisema jeshi limejificha nyuma ya kilima; wakajibu kwamba hawakumjua kamwe kusema uwongo. Kisha akawaonya juu ya adhabu itakayokuja na akawalingania kwenye ibada ya Mwenyezi Mungu peke yake.\n\nUjumbe huu wa wazi uligusa kiini cha amri ya Makka. Masanamu hayakuwa tu dini bali riziki na ufahari - hali ya jiji kama mlinzi wa kaburi ilivutia mahujaji na biashara. Kusema masanamu hayana nguvu ilikuwa ni kuupinga uchumi wa Maquraishi, ukoo, na kiburi mara moja. Kuanzia hapa mateso yaliongezeka sana, yakiwaangukia wanyonge na watumwa miongoni mwa waumini, kama vile Bilal ibn Rabah na familia ya Yasir.\n\nSomo: ukweli unaosemwa kwa uwazi utasumbua masilahi yaliyoimarishwa. Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) kwanza alitoa ushuhuda wao wenyewe kwamba alikuwa mwaminifu - akili na uadilifu kabla ya vitisho - na kisha akashikilia msimamo. Kusimama kwa tawhid kunaweza kugharimu faraja ya kidunia, kama waumini wa Makka walivyojifunza. Ugumu huu unaongoza moja kwa moja kwa \"Uhamiaji wa Abyssinia.\"",
    location: "Mlima Safa",
  },
  {
    title: "Uhamiaji kwa Abyssinia",
    body: "Mateso yalipozidi kuwa magumu, Mtume ﷺ aliliambia kundi la masahaba wake kutafuta hifadhi kwa Negus (an-Najashi), mfalme Mkristo mwadilifu wa Abyssinia (Ethiopia ya sasa), akisema kwamba katika ardhi yake hakuna mtu aliyedhulumiwa. Kundi la kwanza lilivuka Bahari Nyekundu, likifuatiwa na uhamiaji mkubwa wa pili - Hijra ya kwanza katika Uislamu.\n\nMaquraishi walipotuma wajumbe kutaka wakimbizi warudishwe, Negus aliwaita. Jafar bin Abi Talib (radhi za Allah ziwe juu yake) alizungumza kwa ajili ya Waislamu, akieleza jinsi walivyotoka katika ujinga na kuingia katika imani ya ukweli, rehema, na tabia njema, kisha akasoma aya za Surah Maryam kuhusu Yesu na mama yake. Mfalme wa Kikristo alilia, akachora mstari chini, na kusema tofauti kati ya imani yao na yake haikuwa pana kuliko hiyo - na alikataa kuwasalimisha.\n\nFunzo: Hiki ni alama ya uvumilivu wa kidini na kujenga madaraja na Watu wa Kitabu. Pia inafundisha kwamba kutafuta usalama kutoka kwa ukandamizaji chini ya mamlaka ya haki isiyo ya Kiislamu ni halali kabisa. Angalia pia kwamba hoja iliyoshinda siku hiyo ilikuwa tabia nzuri na neno la Mwenyezi Mungu lililokaririwa - sio nguvu.",
    location: "Abyssinia",
  },
  {
    title: "Kususia Banu Hashim",
    body: "Hawakuweza kusimamisha kuenea kwa Uislamu au kumfikia Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) huku ukoo wake ukimlinda, viongozi wa Maquraishi walikimbilia kwenye adhabu ya pamoja. Waliandika mapatano na kuyatundika ndani ya Al-Ka'aba, wakiahidi kususia ukoo wote wa Banu Hashim (na washirika wao Banu al-Muttalib): hakuna ndoa nao, hakuna biashara, hakuna shughuli za kijamii, mpaka wamsalimishe Muhammad ﷺ.\n\nKwa takribani miaka mitatu ukoo huo - waumini na wasioamini wa Hashim sawa - walikuwa wamefungiwa kwenye bonde la mlima la Shi'b Abi Talib, wakistahimili njaa kali kiasi kwamba vilio vya watoto vilisikika na watu wakala majani. Ususiaji huo hatimaye uliporomoka wakati watu kadhaa wa Maquraishi wenye nia njema walipoikataa hadharani na ngozi hiyo ikapatikana kuwa imeliwa, isipokuwa maneno ambayo ndani yake jina la Mwenyezi Mungu lilionekana.\n\nSomo: uwongo hufikia kupita kiasi. Ukatili wa kususia ule ulidhihirisha tu udhalimu wa watesi na ukafanya uamuzi kuwa mgumu wa waumini. Pia inaonyesha heshima ya watu wachache tu ndani ya jamii chuki ambao walivunja safu ili kukomesha ukatili - ukumbusho kwamba dhamiri inaweza kudumu hata katika upinzani mkali zaidi.",
    location: "Shi'b Abi Talib",
  },
  {
    title: "Mwaka wa Huzuni",
    body: "Mara tu baada ya kususia kumalizika, Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) alipata hasara kubwa mbili ndani ya muda mfupi, na mwaka huo ukajulikana kama Am al-Huzn, Mwaka wa Huzuni. Kwanza ami yake na mlinzi wa maisha yake yote Abu Talib alikufa - mtu ambaye msimamo wake ulikuwa umemkinga na Maquraishi kwa miongo kadhaa. Kisha Khadija (radhi za Allah ziwe juu yake), mke wake wa miaka ishirini na mitano, Muumini wake wa kwanza na msaidizi wake wa karibu, naye pia alifariki dunia.\n\nPamoja na ulinzi wake wa kijamii na nanga yake ya kihisia vyote vikiwa vimetoweka, Maquraishi walikua na ujasiri katika unyanyasaji wao. Ilikuwa ni katika kipindi hiki ambapo alisafiri kwenda katika mji wa Ta'if akitumai watu wake wanaweza kuukubali ujumbe huo; badala yake walimfukuza na kuweka watoto wa kumpiga kwa mawe hadi miguu yake ikavuja damu. Hata wakati huo, alipotolewa uharibifu wa mji huo, aliwaombea vizazi vyao siku moja wamwabudu Mwenyezi Mungu - rehema inayomtambulisha.\n\nSomo: hata manabii wanajaribiwa kwa huzuni na kukataliwa nyuma kwa nyuma, na jibu ni uvumilivu bila uchungu. Hasara ya mwanadamu haimaanishi kuachwa na Mungu; unafuu ulifuata karibu nyuma, katika safari ya usiku inayofuata. Tazama \"Al-Isra wal-Mi'raj.\"",
    location: "Makka",
  },
  {
    title: "Al-Isra wal-Mi'raj",
    body: "Baada ya Mwaka wa Huzuni ulikuja usiku wa heshima isiyo ya kawaida. Huko Isra, Mtume ﷺ alibebwa katika usiku mmoja kutoka Msikiti Mtukufu wa Makka hadi al-Masjid al-Aqsa huko Jerusalem - tukio ambalo Qur'ani inafungua Surah al-Isra kwa (Qur'ani 17: 1). Huko aliwaongoza manabii waliotangulia katika maombi. Kisha, katika Mi'raj, alinyanyuliwa katika mbingu saba, akakutana na Manabii akiwemo Adam, Musa na Ibrahim, na akafika kituo kilicho karibu na Mola wake Mlezi kuliko kiumbe chochote.\n\nZawadi kuu ya usiku huo ilikuwa sala tano za kila siku. Kama ilivyoandikwa katika Sahih al-Bukhari 3887, walifaradhishwa kwanza wakiwa hamsini; kwa ushauri wa Musa Mtume (Swalla Allaahu ‘alayhi wa aalihi wa sallam) alirudi tena na tena kuomba afueni mpaka wakapunguzwa hadi watano kivitendo huku wakibeba malipo ya hamsini. Wanachuoni wanatofautiana juu ya tarehe halisi, wengi wakiiweka katika miaka kabla ya Hijra.\n\nFunzo: Zawadi iliyotolewa kwa ajili ya kumfariji Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) ni Swalah - sisi wenyewe kupanda kwa Mwenyezi Mungu kila usiku. Sala tano za kila siku hazikuteremshwa na Malaika duniani bali zilipandishwa mbinguni ili kuzipokea, ishara ya uzito wake katika maisha ya Muumini.",
    location: "Yerusalemu",
  },
  {
    title: "Ahadi ya Kwanza ya al-Aqabah",
    body: "Kila mwaka mahujaji walikusanyika Makka, na Mtume (Swalla Allaahu ´alayhi wa sallam) alikuwa akiwasilisha Uislamu kwa makabila yanayozuru. Katika sehemu iitwayo al-Aqabah karibu na Mina, kikundi kidogo cha wanaume kutoka Yathrib (Madinah) - mji ambao umekumbwa na mizozo kwa muda mrefu kati ya makabila yake ya Aws na Khazraj, na wenye ujuzi wa tauhidi kupitia jumuiya yake ya Kiyahudi - walisikiliza, wakaamini, na wakaupeleka ujumbe nyumbani.\n\nMsimu uliofuata kumi na wawili kati yao walirudi na kutoa Ahadi ya Kwanza ya al-Aqabah: kumwabudu Mwenyezi Mungu peke yake, kutoiba, kutofanya ngono haramu, kutoua mtoto, na kumtii Mtume ﷺ katika haki. Kisha akamtuma sahaba kijana Mus'ab ibn Umayr (radhi za Allah ziwe juu yake) arudi pamoja nao kama mwalimu wa kwanza wa Uislamu na balozi, na kupitia kwake imani ilienea kwa kasi katika kaya za Yathrib.\n\nSomo: mlango ambao ulionekana kuwa umefungwa huko Makka ulifunguliwa Madina. Angalia jinsi jumuiya ilijengwa - kwa kufundisha. Mwalimu mmoja kijana aliyejitolea, aliyetumwa na Kurani, alitayarisha mji mzima kuwa chimbuko la Uislamu. Hii inaweka moja kwa moja Ahadi ya Pili na Hijra.",
    location: "Mina",
  },
  {
    title: "Ahadi ya Pili ya al-Aqabah",
    body: 'Mwaka mmoja baada ya ahadi ya kwanza, wajumbe wengi zaidi kutoka Yathrib - wanaume sabini na watatu na wanawake wawili - walikuja kwa siri kwa Mtume ﷺ huko al-Aqabah wakati wa hijja. Wakati huu ahadi ilienda mbali zaidi: waliahidi kumlinda kama vile wangewalinda wake zao na watoto wao, na kuwapokea Waislamu wanaoteswa wa Makka ndani ya mji wao.\n\nHii ilikuwa hatua ya kugeuka. Kwa mara ya kwanza jumuiya hiyo changa ilikuwa na nchi na kundi la watu walioapa kuilinda. Kwa kuifahamu hatari hiyo, Mtume (Swalla Allaahu ´alayhi wa sallam) aliwaagiza maswahaba wake wa Makka kimya kimya waanze kuhamia Yathrib kwa makundi madogo madogo ili wasiwaogopeshe Waquraishi.\n\nSomo: kujitolea kwa dhati kunabeba wajibu. Ansari (“Wasaidizi” wa Madinah) waliweka rehani maisha na nyumba zao kabla hawajapata chochote, kwa ajili ya imani tu. Ukarimu wao ungekuwa mfano wa udugu wa Kiislamu - unaokumbukwa katika "Hijra hadi Madina" inayofuata, ambapo waliwakaribisha wahamiaji kama familia.',
    location: "Mina",
  },
  {
    title: "Hijra kwenda Madina",
    body: "Maquraishi walipopanga njama ya kumuua Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam), Mwenyezi Mungu alimruhusu kuhama. Akaondoka na rafiki yake wa karibu Abu Bakr (radhi za Allah ziwe juu yake), akimuacha Ali kitandani mwake ili kurudisha amana za watu. Wawili hao walijificha kwa siku tatu ndani ya pango la Thawr huku wafuasi walipofika karibu sana na Abu Bakr akawaogopa - na Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) akamtuliza: \"Je, unawaonaje wawili ambao wa tatu wao ni Mwenyezi Mungu?\" Wakati huu umeandikwa katika Sahih al-Bukhari 3653 na ikasema tena katika Qur'ani: \"...wa pili katika wawili, walipokuwa pangoni, alipomwambia sahibu yake, 'Usihuzunike; hakika Mwenyezi Mungu yu pamoja nasi'\" (Qur'ani 9:40).\n\nWalifika Quba, ambapo msikiti wa kwanza ulijengwa, kisha wakaingia Yathrib - baada ya hapo al-Madinah al-Munawwarah, \"Mji unaong'aa.\" Mtume (Swalla Allaahu ‘alayhi wa aalihi wa sallam) alimuoanisha kila mhajiri (Muhajir) na Msaidizi (Ansari) katika mafungamano ya udugu; ukarimu ulikuwa kamili kiasi kwamba Sa'd ibn al-Rabi' alijitolea kugawana nusu ya mali yake na Abdur-Rahman ibn Awf, ambaye badala yake aliomba tu kuonyeshwa sokoni (Sahih al-Bukhari 3780/3906).\n\nHijra ilikuwa muhimu sana kwamba Umar baadaye aliifanya kuwa mwanzo wa kalenda ya Kiislamu - mwaka wa 1 AH. Funzo: wakati mwingine imani inahitaji kuacha kila kitu kwa ajili ya Mwenyezi Mungu, kuamini kwamba yuko pamoja na wenye ikhlasi, na kujenga upya juu ya udugu badala ya damu.",
    location: "Madina",
  },
  {
    title: "Katiba ya Madina",
    body: 'Alipofika katika mji uliokuwa umevunjwa na vita vya kikabila, Mtume ﷺ hakuwaongoza tu Waislamu - alianzisha jumuiya. Alitengeneza mapatano yaliyoandikwa, yaliyohifadhiwa katika kitabu cha Ibn Ishaq na yanayojulikana kama Sahifah au Katiba ya Madinah, yakiwaunganisha pamoja Muhajirun, Ansari, na makabila ya Kiyahudi ya mji huo katika mkataba mmoja wa ulinzi wa pande zote mbili.\n\nMasharti yake yalikuwa ya ajabu kwa wakati wao: pande zote ziliunda "umma mmoja" kwa madhumuni ya mapatano, kila kundi lilishika dini yake, migogoro ipelekwe kwa Mtume (Swalla Allaahu \'alayhi wa aalihi wa sallam), uchokozi na dhulma vilikatazwa, na wote waliahidi kuulinda mji dhidi ya mashambulizi ya nje. Ilifanya Madina kuwa jimbo la jiji lenye haki na majukumu yaliyokubaliwa badala ya ugomvi usio na mwisho wa umwagaji damu.\n\nFunzo: Uislamu sio tu ibada ya kibinafsi bali ni mpangilio wa haki wa jamii. Mtume (Swalla Allaahu ´alayhi wa sallam) alitoa mfano wa kuishi pamoja kwa wingi, kanuni ya sheria iliyokubaliwa juu ya uasi wa kikabila, na kuheshimu maagano - kanuni ambazo zingejaribiwa katika miaka ya migogoro ijayo. Inakamilisha udugu wa "Hijra hadi Madina" kwa kueneza uadilifu kwa mji mzima.',
    location: "Madina",
  },
  {
    title: "Vita vya Badr",
    body: 'Kufikia mwaka wa pili baada ya Hijra, ruhusa ya kupigana katika kujilinda ilitolewa (Qur\'ani 22:39). Mnamo tarehe 17 Ramadhani 2 Hijria, kikosi cha Waislamu cha watu wapatao 313 - waliokuwa na silaha duni, wakiwa na farasi wachache tu - walikutana na jeshi la Waquraishi takriban elfu moja lenye nguvu kwenye visima vya Badr, kusini magharibi mwa Madina. Ilikuwa ni vita kuu ya kwanza ya Uislamu.\n\nKinyume na uwezekano huo Waislamu walishinda kwa uhakika, na watesi wakubwa kadhaa wa Maquraishi waliuawa. Qur’ani inauweka ushindi huo kuwa ni dalili, sio tu kitendo cha kijeshi: “Mwenyezi Mungu alikwisha kupeni ushindi katika Badr na hali nyinyi ni wanyonge, basi mcheni Mwenyezi Mungu ili mpate kushukuru” (Qur’ani 3:123), na inaeleza kuhusu msaada wa Malaika (Qur’ani 3:124–125). Badr alianzisha jumuiya ya vijana kama mamlaka halisi huko Uarabuni.\n\nSomo: matokeo ni ya Mwenyezi Mungu, sio kwa idadi au vifaa. Badr inakumbukwa kama "siku ya kigezo" (yawm al-furqan), siku ambayo ukweli na uwongo vilitofautishwa - uthibitisho kwamba kumtegemea Mwenyezi Mungu kwa bidii ya kweli ndio jambo la msingi. Kurudishwa huko Uhud mwaka uliofuata kungefundisha somo la nyongeza.',
    location: "Badr",
  },
  {
    title: "Vita vya Uhud",
    body: "Mwaka mmoja baada ya Badr, Maquraishi walirudi kwa ajili ya kulipiza kisasi na jeshi kubwa zaidi, na pande hizo mbili zilikutana chini ya Mlima Uhud karibu na Madina. Mtume (Swalla Allaahu ´alayhi wa sallam) aliweka wapiga mishale hamsini juu ya mlima kwa amri kali ya kutotoka katika nafasi zao, chochote kitakachotokea. Mapema katika vita Waislamu walikuwa na uwezo wa juu; lakini walipoona adui wanakimbia, wengi wa wapiga mishale waliacha kazi zao kukusanya nyara. Wapanda farasi wa Maquraishi chini ya Khalid ibn al-Walid (ambaye bado hajawa Mwislamu) walizunguka ubavu uliokuwa wazi, na wimbi likageuka kuwa siku ya gharama na chungu.\n\nMasahaba wengi waliuawa kishahidi, miongoni mwao ni ami kipenzi cha Mtume Hamzah (radhi za Allah ziwe juu yake), \"Simba wa Mwenyezi Mungu.\" Mtume ﷺ mwenyewe alijeruhiwa, jino lake lilivunjwa na uso ukiwa na damu. Baadaye Qur'ani ilizungumzia kizuizi hicho kwa uwazi, ikieleza kwamba ulikuwa mtihani na matokeo ya kuasi amri na kutamani ulimwengu (Qur'ani 3:152, 3:165–166).\n\nFunzo: Uhud ni somo kubwa katika nidhamu na utiifu. Kitendo kimoja cha utovu wa nidhamu, hata kama kilionekana kidogo, kiliondoa ushindi wa karibu. Na Mwenyezi Mungu hakuwaacha, akawafundisha, akawasamehe na akawakusanya. Kushindwa, kukabiliwa kwa uaminifu, kunaweza kufundisha zaidi kuliko ushindi.",
    location: "Mlima Uhud",
  },
  {
    title: "Vita vya Handaki",
    body: 'Katika mwaka wa tano, muungano wa Waquraishi, makabila mengine ya Waarabu, na makundi yenye uadui - "Mashirika" (al-Ahzab) - walikusanya jeshi kubwa zaidi ambalo bado limeonekana katika Arabia, labda elfu kumi na nguvu, ili kuiangamiza Madina mara moja na kwa wote. Akiwa amekabiliana na adui mkubwa sana kuweza kukutana naye katika vita vya wazi, Mtume ﷺ alikubali ushauri wa sahaba wa Uajemi Salman al-Farisi (radhi za Allah ziwe juu yake) za kuchimba handaki pana katika njia za kaskazini zilizokuwa wazi kuelekea mjini - mbinu ambayo Waarabu hawakuwahi kukutana nayo.\n\nMtaro ulisimamisha kuzingirwa. Majuma ya baridi, njaa, na hofu yalifuata, na Qur’ani inaeleza kwa uwazi majaribio ya waumini katika Sura al-Ahzab: “…macho yalipobadilika kwa hofu na mioyo ikafika kooni” (Qur’ani 33:10). Hatimaye upepo mkali na mfarakano wa ndani ulitawanya jeshi la muungano, na wakaondoka bila vita kali. Qur’ani inaupa ukombozi kwa Mwenyezi Mungu, ambaye “aliwapelekea upepo na majeshi msiyoyaona” (Qur’ani 33:9).\n\nSomo: mashauriano ya busara (shura) na uwazi kwa mawazo mazuri kutoka kwa mtu yeyote - hapa, uhandisi wa mgeni - ni sehemu ya imani. Na wakati juhudi za mwanadamu zimetolewa kikamilifu, ukombozi bado unatoka kwa Mwenyezi Mungu. Mzingiro huu uliovunjika kwa ufanisi ulimaliza uwezo wa Maquraishi wa kushambulia.',
    location: "Madina",
  },
  {
    title: "Mkataba wa Hudaybiyyah",
    body: "Katika mwaka wa sita Mtume ﷺ alitoka na masahaba wapatao 1,400 kwenda kufanya Umra, sio kupigana, kuingia katika hali ya ihram ili kuweka wazi dhamira ya amani. Maquraishi waliwazuia kwenye sehemu iitwayo Hudaybiyyah, pembezoni mwa patakatifu. Baada ya mazungumzo ya mvutano, mapatano ya miaka kumi yalikubaliwa kwa masharti ambayo yalionekana, kwa masahaba wengi, kuwafedhehesha: Waislamu wangerudi nyuma mwaka huo na kuufuata; yeyote anayekimbia Maquraishi kwa Waislamu angerudishwa, lakini si kinyume chake.\n\nLakini Mwenyezi Mungu aliteremsha kwa kurudi kwamba mkataba huu ulikuwa ni \"ushindi wa wazi\" (Qur'ani 48:1, Surah al-Fath). Maswahaba baadaye walisema hawakuwahi kuona ushindi mkubwa zaidi - kwa sababu katika amani iliyofuata, watu walichanganyika kwa uhuru, walisikia ujumbe kwa utulivu, na wakaingia Uislamu kwa wingi zaidi kuliko miaka yote ya mapigano; Ripoti ya Al-Bara' ibn Azib kuhusu hili imeandikwa katika Sahih al-Bukhari 4606. Makubaliano hayo pia yalitambua kwa uwazi kabisa Waislamu kama nguvu sawa.\n\nSomo: kile kinachoonekana kama kurudi nyuma kinaweza kuwa ufunguzi mkubwa zaidi. Mtume (Swalla Allaahu ´alayhi wa sallam) alichagua hasara ya muda mfupi kwa manufaa ya muda mrefu, na akaheshimu biashara ngumu hata ilipouma. Subira, kujizuia, na kushika neno la mtu kunaweza kufikia kile ambacho mapambano hayawezi.",
    location: "Hudaybiyyah",
  },
  {
    title: "Msafara wa kuelekea Khaybar",
    body: "Muda mfupi baada ya Hudaybiyyah, Mtume ﷺ aliigeukia Khaybar, chemchemi tajiri yenye ngome kaskazini mwa Madinah. Khaybar imekuwa kituo cha uadui - nyumbani kwa makabila ambayo yalikuwa yamesaidia kupanga kuzingirwa kwa Mashirikisho ya Madina na kuendelea kupanga njama dhidi ya jamii ya Kiislamu. Kampeni hiyo ililenga kumaliza tishio hilo.\n\nNgome zikaanguka moja baada ya nyingine baada ya mapigano makali; bendera katika siku ya maamuzi ilitolewa kwa Ali ibn Abi Talib (radhi za Allah ziwe juu yake). Baadaye Mtume (Swalla Allaahu ‘alayhi wa aalihi wa sallam) aliwaruhusu wakazi kubaki na kuendelea kulima ardhi hiyo kwa kubadilishana na sehemu ya mazao yake - mpango ambao uliihakikishia Madina chakula na utulivu badala ya kumfukuza kila mtu. Ilikuwa hapa pia, kwamba mwanamke alijaribu kumtia sumu kwa kondoo, ambayo alionywa.\n\nSomo: usalama na ushikaji wa mikataba ulienda sambamba. Hatua hiyo ilikuwa dhidi ya nguvu iliyothibitishwa ya uadui, lakini iliishia katika suluhu inayoweza kutekelezeka ambayo iliwaacha walioshindwa kuendelea na maisha yao. Nguvu katika Uislamu inakusudiwa kuweka usalama na uadilifu, sio kuangamiza.",
    location: "Khaybar",
  },
  {
    title: "Kutekwa kwa Makka",
    body: 'Wakati washirika wa Maquraishi walipovunja masharti ya Hudaybiyyah kwa kulishambulia kabila lililofungamana na Waislamu, mapatano yale yalibatilishwa. Katika mwezi wa Ramadhani wa mwaka wa nane Mtume (Swalla Allaahu ´alayhi wa sallam) alielekea Makka akiwa na jeshi la watu elfu kumi - jeshi kubwa zaidi - na mji ule uliomtesa, kumgomea, na kupigana naye kwa muda wa miaka ishirini ulisalimu amri bila kumwaga damu yoyote.\n\nAkiwa amesimama hatimaye kama mshindi juu ya watu waliomtoa nje, aliwauliza watu wa Makka kile walichotarajia kutoka kwake. Walitaraji rehema ya ndugu mtukufu, naye akawajibu kwa maneno ya Yusuf kuwaambia ndugu zake: "Si lawama kwenu leo" - na akasema: "Nendeni, kwa kuwa mmeko huru." Aliingia ndani ya Al-Kaaba na akaisafisha masanamu yake 360, huku akisoma “Haki imekuja na uwongo umetoweka” (Qur’ani 17:81), na kurudisha kaburi la Ibrahim kwenye ibada safi ya Mwenyezi Mungu. Surah an-Nasr (Qur\'ani 110) inazungumzia wakati huu ambapo watu "wanaingia katika dini ya Mwenyezi Mungu kwa wingi."\n\nSomo: hiki ni kilele cha rehema na msamaha wa kinabii. Kwa uwezo kamili wa kulipiza kisasi, alisamehe. Muumini hujifunza kwamba wenye nguvu ni wale wanaosamehe wanapoweza kuadhibu, na kwamba lengo halikuwa kamwe kulipiza kisasi bali uwongofu.',
    location: "Makka",
  },
  {
    title: "Msafara wa kuelekea Tabuk",
    body: 'Katika mwaka wa tisa, ripoti zilifika Madina kuhusu uwezekano wa uhamasishaji wa Byzantine (Kirumi) kwenye mpaka wa kaskazini. Katika joto kali la kiangazi, wakati mavuno yalipoiva na safari ilikuwa ndefu na ngumu, Mtume ﷺ aliliita jeshi kubwa zaidi alilowahi kuliongoza - labda elfu thelathini - liende kaskazini kuelekea Tabuk. Hii ilikuwa ni "saa ya shida" (Qur\'ani 9:117), na ilijaribu uaminifu kama hakuna hapo awali.\n\nHakuna vita vilivyofanyika; onyesho la azimio lilitosha, na machifu kadhaa wa kaskazini walifanya mapatano na Madina. Lakini kampeni hiyo inakumbukwa zaidi ya yote kwa kile ilichofichua kuhusu mioyo ya watu. Qur’ani inaweka sehemu kubwa ya Surah at-Tawbah kwayo — inawasifu wale waliotoa kila kitu (Abu Bakr inasemekana alitoa mali yake yote), kuwafichua wanafiki waliozua visingizio vya kukaa, na kusimulia kisa cha kusisimua cha Waumini watatu waaminifu, akiwemo Ka’b ibn Malik, ambaye alikiri kwa unyofu kwamba hawakuwa na udhuru na walisamehewa baada ya mtihani mgumu (18:9).\n\nSomo: utii ni rahisi wakati ni vizuri; ukweli wake unaonyesha wakati ni gharama. Tabuk aliwatenganisha wanyofu na watoa udhuru na akaashiria mwisho mzuri wa upinzani uliopangwa wa kuabudu masanamu huko Uarabuni. Uaminifu - hata uaminifu wa kukiri kushindwa - ndio njia ya kurudi kwa Mwenyezi Mungu.',
    location: "Tabuk",
  },
  {
    title: "Hija ya Kuaga",
    body: 'Katika mwaka wa kumi Mtume ﷺ alitekeleza Hijja yake pekee, akijumuika na masahaba zaidi ya laki moja, akiwafundisha ibada ana kwa ana. Akiwa amesimama kwenye uwanda wa Arafah, alitoa Khutbat al-Wada\', mukhtasari wa kila kitu ambacho Uislamu ulikuwa umekuja kuanzisha.\n\nAlitangaza utakatifu wa maisha ya kila mtu, mali, na heshima - "damu yako na mali yako ni takatifu kama siku hii, mwezi huu, ardhi hii" (Sahih al-Bukhari 1741). Aliondoa ugomvi wa damu na riba (riba) za Jahiliyyah, akaamrisha kuwatendea mema wanawake kama amana kutoka kwa Mwenyezi Mungu, akawakumbusha kwamba hakuna Mwarabu aliye mbora kuliko asiye Mwarabu isipokuwa kwa uchamungu, na akawaambia washike sana Qur-aan. Ilikuwa ni wakati wa hijja hii, Siku ya Arafa iliyoadhimishwa siku ya Ijumaa, ambapo Mwenyezi Mungu aliteremsha “Leo nimekukamilishieni dini yenu…” (Qur’ani 5:3) – aya ambayo Umar aliikumbuka na kuiandika kwa usahihi (Sahih al-Bukhari 45).\n\nSomo: Hotuba ya Kuaga ni hati ya Uislamu ya utu, uadilifu, na usawa, iliyotiwa muhuri na tangazo kwamba dini sasa imekamilika. Kazi ya mwamini kutoka hapa si kuiongeza bali kuiishi.',
    location: "Arafah",
  },
  {
    title: "Kupita kwake",
    body: "Miezi michache baada ya Hijja ya kuaga, Mtume ﷺ alishikwa na homa. Katika siku zake za mwisho aliomba ruhusa ya wake zake kwenda kulelewa katika chumba cha Aisha (radhi za Allah ziwe juu yake), na akamteua Abu Bakr kuongoza swala. Asubuhi yake ya mwisho alirudisha pazia kuona safu za waumini wakisali na kutabasamu, akiwa na furaha kwa jumuiya yake, kisha akaiacha ianguke. Aliaga dunia siku ya Jumatatu, 12 Rabi al-Awwal 11 AH, kichwa chake kikiwa kikiwa kati ya kifua na kidevu cha Aisha - kama alivyosimulia mwenyewe katika Sahih al-Bukhari 4449/4451.\n\nHuzuni ya Madina ilikuwa nyingi sana, na hata Umar alikataa mwanzoni kuikubali. Kisha Abu Bakr akainuka, akambusu uso wa Mtume, na akawahutubia watu kwa maneno ambayo yaliiweka sawa umma wote na yameandikwa katika Sahih al-Bukhari 1241/1242: \"Aliokuwa akimuabudu Muhammad, basi Muhammad amekufa; lakini anayemuabudu Mwenyezi Mungu, basi Mwenyezi Mungu ni hai na hafi. Akasoma “Muhammad si ila ni Mtume tu, wamepita Mitume kabla yake…” (Qur’ani 3:144).\n\nFunzo: ujumbe ulikuwa umekamilika na sasa ulikuwa wa ummah. Mtume (Swalla Allaahu 'alayhi wa aalihi wa sallam) alikuwa ni mtu, lakini alicholeta - Qur-aan na Sunnah zake - sivyo. Jibu la Abu Bakr ni jibu la kudumu kwa huzuni: kushikamana kwetu ni kwa Mwenyezi Mungu, ambaye hafi kamwe, na njia ya kumpenda Mtume ﷺ ni kuishi mwongozo wake.",
    location: "Madina",
  },
];
