// Uzbek translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_UZ: DeepPartial<SeerahEvent>[] = [
  {
    title: "Islomdan oldingi Arabiston (johiliyya)",
    body: "Payg'ambar sollallohu alayhi vasallamni tushunish uchun avvalo u yuborilgan dunyoni tasavvur qilish kerak. VI asrda Arabiston markaziy davlatga ega boʻlmagan tarqoq qabilalar mamlakati boʻlib, ular bir-biriga nasl-nasab, sharaf va Makkadagi Kaʼbaning muqaddas joyi — Ibrohim va Ismoil tomonidan yagona Xudoga sigʻinish uchun qurilgan ziyoratgoh boʻlgan, biroq hozirga qadar uch yuz oltmishtacha butlar bilan oʻralgan.\n\nBu davr arablarda aql-zakovat yo'qligi (ularning she'riyati va xotirasi g'ayrioddiy) emas, balki yo'l-yo'riq yo'qligi uchun \"johiliyat davri\" deb ataladi. Qabila janjallari avlodlar davomida davom etishi mumkin edi, kuchlilar kuchsizlarga o'lja bo'lishdi va qizlar ba'zan uyat yoki qashshoqlikdan qo'rqib tiriklayin ko'milgan - bu amaliyotni Qur'on keyinchalik to'g'ridan-to'g'ri qoralaydi (Qur'on 81:8–9). Butparastlik bilan bir qatorda, bir nechta \"hunafa\" hali ham Ibrohimning sof tavhidiga intilishdi va kichik yahudiy va nasroniy jamoalari yarim orol bo'ylab yashadilar.\n\nDars: Vahiy bo'shliqqa emas, balki chuqur yaralari bo'lgan haqiqiy jamiyatga tushdi va u davolagan birinchi narsa inson va uning Yaratuvchisi o'rtasidagi munosabatlar edi. Vaqt o'tishi bilan ushbu fonni yodda tuting - Payg'ambar sollallohu alayhi vasallamning deyarli har bir islohoti johiliyatning adolatsizligiga to'g'ridan-to'g'ri javobdir.",
    location: "Arabiston",
  },
  {
    title: "Makkada tug'ilgan",
    body: "Payg'ambarimiz sollallohu alayhi vasallam Makkada Fil yili (Am al-Fil)da tug'ilganlar, buning sababi o'sha yili Yamanning Habash hokimi Abraha fillar bilan qo'shin bilan Ka'bani vayron qilgani va mo''jizaviy tarzda ortga qaytarilgani uchun bu voqea Qur'onning Fil (Qur'on) surasida eslanadi. Bu mas'uliyatli yilda Quraysh qabilasi va uning eng hurmatli urug'i Banu Hoshim qabilasidan bir bola tug'ildi.\n\nU tug'ilganda allaqachon etim edi: otasi Abdulla bir necha oy oldin savdo bilan shug'ullanayotganda vafot etgan. Uning onasi Amina binti Vahb unga Muhammad deb ism qo'ydi - \"juda maqtovli\" - bu ism arablar orasida deyarli noma'lum. Makka odatiga ko'ra, u Halima as-Sa'diyya qaramog'ida bo'lgan Banu Sa'd qabilasining ochiq sahroda emizish va tarbiyalash uchun yuborilgan.\n\nMo‘min uchun ibrat: Alloh nazdida ulug‘likning dunyo xavfsizligiga aloqasi yo‘q. Oxirgi Payg'ambar hayotni otasiz boshladi va tez orada onasiz qoladi, lekin Allohning O'zi uning valiysi edi - \"U sizni yetim topib, panoh bermadimi?\" (Qur'on 93:6). Shuningdek, keyingi “Onasining o‘tishi” va “Abu Tolibning vasiyligi”ga qarang.",
    location: "Makka",
  },
  {
    title: "Onasining o'tishi",
    body: "Olti yoshga to'lganida, Omina o'g'lini Yasrib (keyinchalik Madina)dagi qarindoshlarinikiga, otasining qabrini ko'rishga olib bordi. Qaytishda u kasal bo'lib, Makka va Madina orasidagi Abvo' degan joyda vafot etdi va o'sha yerda dafn qilindi. Yosh Muhammad sollallohu alayhi vasallam ikkala ota-onasidan ham ayrilgan edi.\n\nU oilaning ozod qilingan xizmatkori Ummu Ayman tomonidan Makkaga olib kelindi va bobosi, Qurayshning hurmatli boshlig'i Abdulmuttalibning qaramog'iga topshirildi, u uni juda yaxshi ko'rar va Ka'bada yonma-yon o'tirardi.\n\nDars: Rasululloh sollallohu alayhi vasallam juda ko'p odamlar ko'targan qayg'uni erta va qayta-qayta tatib ko'rdilar - ayriliq, ko'chib ketish, boshqalarga qaramlik. Bu uning tayyorgarligining bir qismi edi. Yo'qotishni bilgan yurak yetim, beva va musofirni his qila oladigan yurakdir va uning jamiyati keyinchalik aynan shu rahm-shafqat ustiga quriladi. Bu mavzu \"G'am yili\"da davom etadi.",
    location: "Abva'",
  },
  {
    title: "Abu Tolibning vasiyligi",
    body: "Onasidan ikki yil o'tib, bobosi Abd al-Muttalib ham vafot etdi, bola sakkiz yoshga to'lganida. O‘lim to‘shagidayoq suyukli nabirasini o‘g‘li Abu Tolibga topshirdi. Abu Tolib boy bo‘lmasa-da, bolani o‘z xonadoniga olib, uni eng aziz farzandlaridan biridek tutgan.\n\nAbu Tolib Makkadagi eng og'ir quvg'in yillarida qirq yildan ortiq uning himoyachisi bo'lib qolaverdi. Aynan u yosh Muhammad sollallohu alayhi vasallamni Suriyaga savdo safarlariga olib borgan va u yerda - taniqli rivoyatga ko'ra - rohib Bahira unda payg'ambarlik alomatlarini payqagan (bu ma'lumotni sira saqlaydi, garchi uning tafsilotlari turli kuch bilan etkazilgan bo'lsa ham).\n\nDars: Alloh taolo har bir bosqichda Payg‘ambarimiz sollallohu alayhi vasallamning atrofiga sodiq, hurmatli kishilarni joylashtirgan. Abu Tolibning o'n yillik himoyasi rahm-shafqat edi - haqiqat va qarindoshlikni qo'llab-quvvatlash, hatto hali iymon keltirmaganlar uchun ham olijanob vazifa ekanligini va bizni panoh qilganlarni hurmat qilishimiz kerakligini eslatdi. Keyinchalik, qayg'u yilida uning yo'qolishi hamma narsani o'zgartiradi.",
    location: "Makka",
  },
  {
    title: "Xadichaga uylanish",
    body: "Muhammad sollallohu alayhi vasallam yoshligida Makkada hech qanday boylik sotib ololmaydigan obro'-e'tibor qozondilar: rostgo'y Sodiq va ishonchli al-Amin. Odamlar o'zlarining qimmatbaho buyumlarini saqlash uchun unga topshirdilar va hatto turli xudolarga sig'inadiganlar ham Uning so'ziga to'liq ishondilar.\n\nQurayshning olijanob va muvaffaqiyatli savdogarlaridan bo‘lgan Xadicha binti Xuvaylid (r.a.) uni Suriyaga o‘z karvoniga rahbarlik qilish uchun yolladi. Uning rostgo‘yligi va fe’l-atvoridan ta’sirlanib, dugonasi Xavla binti Hakim orqali turmush qurish taklifini yuboradi. U yigirma beshda, u esa qirqda edi; ularning nikohi chuqur sevgi va sheriklik nikohiga aylandi. U unga bolalarini tug'di va o'limigacha yigirma besh yil davomida uning yagona xotini bo'lib qoldi.\n\nDars: xarakter keyingi barcha narsalarning asosidir. U payg'ambar deb atalishidan ancha oldin Makka uni o'z ichida eng halol odam sifatida bilar edi - shuning uchun ham birinchi vahiyda Xadichaning unga bo'lgan ishonchi juda muhim edi (qarang: \"Birinchi vahiy\"). Mo'minning oddiy muomalada halolligining o'zi da'vatning bir ko'rinishidir.",
    location: "Makka",
  },
  {
    title: "Hilf al-Fudul va Qora tosh",
    body: "Uning payg'ambarlikdan oldingi hayotidagi ikkita voqea u keyinchalik xalqni quradigan qadriyatlarni ko'rsatadi. Birinchisi, Hilf al-Fudul: Qurayshning bir necha urugʻlari Makkadagi har qanday mazlum, xoh chet ellik boʻlsin, ularning huquqlari tiklanguniga qadar ular bilan birga turishga qasamyod qilgan tantanali ahddir. Rasululloh sollallohu alayhi vasallam ishtirok etdilar va keyin Islomda ham bunday ahdga javob berishini aytdilar - chunki u adolatni himoya qiladi.\n\nIkkinchidan, toshqindan keyin Ka’bani qayta qurish. Urug'lar muqaddas Qora toshni (al-Hajar al-Asvad) joyiga ko'tarish sharafiga urishga yaqin kelganlarida, keyingi odamning hukmini qabul qilishga rozi bo'ldilar - bu Muhammad s.a.v. Uning yechimi o'zining donoligi bilan mashhur edi: u toshni mato ustiga qo'ydi va har bir urug'ning boshlig'iga burchakni ko'tarishni buyurdi, keyin uni o'z qo'llari bilan o'rnatdi, shunda hamma hurmatga sazovor bo'ldi va hech kim e'tiborga olinmadi.\n\nDars: adolat va nizolarni hal qilish vahiy ularni tasdiqlashdan oldin uning instinkti edi. Mo'min - zulm qilinganlarni himoya qiladigan va bo'linishdan ko'ra birlashish yo'llarini topadigan kishi - Hilf al-fudul hijratdan keyin o'rnatadigan adolatli jamiyatni bashorat qiladi.",
    location: "Makka",
  },
  {
    title: "Birinchi vahiy",
    body: "Rasululloh sollallohu alayhi vasallam Makka tashqarisidagi Jabal an-Nur tog'idagi Hiro g'origa o'ttiz yoshdan oshganlarida ko'proq ibodat qilish va fikr yuritish uchun chekinib bordilar. U yerda Ramazon oyida qirq yoshlar chamasida farishta Jabroil alayhissalom zohir bo‘lib: “O‘qing!” deb amr qildi. U o'qiy olmasligimni aytdi; farishta uni uch marta mahkam quchoqladi va Qur'onning eng birinchi so'zlari bo'lgan \"Alaq\" surasining \"Yaratgan Robbing nomi bilan o'qing...\" (Qur'on 96:1-5) oyatlarini nozil qildi.\n\nU uyiga qaltirab qaytdi, Xadicha uni o'rab, uning iymoni va fe'l-atvorini ochib beruvchi so'zlar bilan tinchlantirdi: Alloh uni hech qachon sharmanda qilmas, chunki u qarindoshlik rishtalarini saqlagan, boshqalarning og'irini ko'targan va munosiblarga yordam berardi. U uni o'zining amakivachchasi Varaqa ibn Navfalning oldiga olib bordi, u avvalgi kitoblardan ma'lum bo'lgan keksa odamni Musoning oldiga kelgan \"Namus\" (farishta) ekanligini bilib, unga bu va'da qilingan payg'ambarlik ekanini aytdi. Bu voqea butun “Sahih al-Buxoriy” 3 da qayd etilgan.\n\nDars: vahiy hokimiyatga da'vo qilishdan emas, balki \"O'qing\" so'zi bilan boshlandi - bu ilm va kamtarlikka asoslangan din. Va birinchi bo'lib kim ishonganiga e'tibor bering: xotin va halol xonadon. Haqiqatni allaqachon chin dildan yashayotganlar tan oladi.",
    location: "Hira g'ori",
  },
  {
    title: "Shaxsiy va'zgo'ylik yillari",
    body: "Birinchi vahiylardan so'ng bir muncha vaqt to'xtab, Alloh taolo Payg'ambar sollallohu alayhi vasallamga odamlarni yolg'iz O'ziga ibodat qilishga chaqirishni boshlashni buyurdi. Taxminan dastlabki uch yil davomida bu qo'ng'iroq tinch va shaxsiy edi - ko'chalarda e'lon qilinganidan ko'ra yaqin oila va ishonchli do'stlar uchun cho'zildi.\n\nIlk dindorlar, ya'ni \"as-Sabiqun al-avvalun\" (eng oldingi) jamiyatning har bir qismidan: uning xotini Xadicha; uning yosh amakivachchasi Ali ibn Abu Tolib; ozod qilingan xizmatkori va asrab olingan o‘g‘li Zayd ibn Horisa; va uning sodiq do‘sti Abu Bakr as-Siddiq (r.a.) O'z navbatida Abu Bakr ham ko'plarni Islomga keltirdilar. Ular ko'pincha Ka'ba yaqinidagi al-Arqamning uyida uchrashib, ehtiyotkorlik bilan namoz o'qidilar.\n\nDars: Islom birinchi navbatda tomosha orqali emas, balki ishonch va munosabatlar orqali rivojlandi. O'sha birinchi yuraklarning kengligiga e'tibor bering - badavlat ayol, bola, ozod qilingan qul, savdogar - irq va martaba farqlarini yo'q qiladigan imonning oldindan sezilishi. Da'vat uyga yaqindan, ixlos va sabr bilan boshlanadi.",
    location: "Makka",
  },
  {
    title: "Xalqni Islomga da'vat qilish",
    body: "Alloh taolo “Yaqin qarindoshlaringni ogohlantir” (Qur’oni karim, 26:214) nozil qilganida, Rasululloh sollallohu alayhi vasallam Ka’ba yonidagi Safo tog‘iga chiqib, Quraysh qabilalariga nido qildilar. U birinchi navbatda tepalik orqasida qo'shin yashiringanini aytsa, ishonasizmi, deb so'radi; Ular uning yolg'on gapirganini hech qachon bilmaganliklarini aytishdi. So‘ng ularni azob kelishidan ogohlantirdi va yolg‘iz Allohga ibodat qilishga chaqirdi.\n\nBu ochiq xabar Makka amrining markaziga ta'sir qildi. Butlar nafaqat din, balki tirikchilik va obro'-e'tibor edi - shaharning ziyoratgohning qo'riqchisi sifatidagi maqomi ziyoratchilarni va savdo-sotiqni jalb qildi. Butlarni kuchsiz deb aytish Qurayshning iqtisodiga, nasl-nasabiga va g'ururiga birdaniga qarshi chiqish edi. Bu yerdan ta'qiblar keskin kuchayib, eng ko'p Bilol ibn Raboh va Yosir oilasi kabi mo'minlarning zaif va qullariga tushdi.\n\nDars: ochiq-oydin aytilgan haqiqat mustahkamlangan manfaatlarni yo'q qiladi. Rasululloh sollallohu alayhi vasallam avvalo ularning rostgo‘yligi, ya’ni do‘q-po‘pisadan avval aql va sofdil ekanligi haqidagi guvohliklariga murojaat qildilar, so‘ngra sobit turdilar. Makkalik mo'minlar o'rganganidek, tavhid uchun turish dunyoviy farovonlikka qimmatga tushishi mumkin. Bu mashaqqat to‘g‘ridan-to‘g‘ri “Habashistonga hijrat”ga olib keladi.",
    location: "Safo tog'i",
  },
  {
    title: "Habashistonga migratsiya",
    body: "Rasululloh sollallohu alayhi vasallam bir guruh sahobalariga Habashistonning (hozirgi Habashiston) adolatli nasroniy podshohi Najoshiy (an-Najoshiy)dan panoh so'rashlarini va uning yurtida hech kimga zulm qilinmasligini aytdilar. Birinchi guruh Qizil dengizni kesib o'tdi, keyin esa kattaroq ikkinchi hijrat - Islomdagi birinchi hijrat.\n\nQuraysh elchilarini yuborib, qochqinlarni qaytarib berishni talab qilganda, Najoshiy ularni chaqirtirdi. Jafar ibn Abu Tolib (r.a.) musulmonlar uchun nutq so‘zlab, ularning jaholatdan qanday qilib haq, rahm-shafqat va go‘zal xulq e’tiqodiga kirib kelganliklarini bayon qildi, so‘ngra “Maryam” surasidan Iso va uning onasi haqida oyatlarni tilovat qildi. Xristian shohi yig'lab, erga chiziq tortdi va ularning e'tiqodi bilan uning iymonlari o'rtasidagi farq bundan kattaroq emasligini aytdi va u ularni taslim qilishdan bosh tortdi.\n\nDars: bu diniy bag'rikenglik va samimiy ahli kitoblar bilan ko'prik qurish belgisidir. Shuningdek, u adolatli nomusulmon hokimiyat ostida zulmdan xavfsizlikni izlash mutlaqo qonuniy ekanligini o'rgatadi. Shuni ham e'tiborga olingki, kunning g'alabasi go'zal xarakter va Allohning kalomi - zo'rlik emas.",
    location: "Habashiston",
  },
  {
    title: "Banu Hoshimga boykot",
    body: "Nabiy sollallohu alayhi vasallamning qavmlari uni himoya qilgan holda Islomning tarqalishini to'xtata olmay yoki ularga yetib borolmadilar, Quraysh boshliqlari jamoaviy jazoga o'tdilar. Ular ahd tuzib, Ka'baga osib qo'yishdi va butun Banu Hoshim (va ularning ittifoqchilari Banu al-Muttalib) qabilasini boykot qilishga va'da berishdi: Muhammad sollallohu alayhi vasallamga taslim bo'lgunlaricha ular bilan nikoh, savdo-sotiq, savdo-sotiq qilmaslik.\n\nTaxminan uch yil davomida qabila - Hoshimning dindorlari ham, kofirlari ham - Shi'b Abu Tolib tog' vodiysida qamalib, shunchalik qattiq ochlikni boshdan kechirdilarki, bolalarning faryodlari eshitilib, odamlar barglarni yeydilar. Nihoyat, bir qancha adolatli Qurayshiylar buni rad etishlari va pergamentning Alloh nomi kelgan kalimalardan tashqari, yeb ketgani aniqlanganda, nihoyat, barbod bo'ldi.\n\nDars: yolg'onning haddan tashqari ko'pligi. Boykotning shafqatsizligi quvg'in qiluvchilarning adolatsizligini fosh qildi va mo'minlarning qarorini qattiqlashtirdi. Bu, shuningdek, vahshiylikka barham berish uchun saflarini buzgan dushman jamiyatdagi bir necha adolatli shaxslarning sharafini ko'rsatadi - vijdon hatto eng qattiq qarshilikda ham omon qolishi mumkinligini eslatadi.",
    location: "Shi'b Abu Tolib",
  },
  {
    title: "Qayg'u yili",
    body: "Boykot tugaganidan ko'p o'tmay, Rasululloh sollallohu alayhi vasallam qisqa vaqt ichida ikkita halokatli yo'qotishlarga duchor bo'ldilar va bu yil Am al-Huzn, qayg'u yili deb nomlandi. Avval uning amakisi va umrboqiy himoyachisi Abu Tolib vafot etdi - o'nlab yillar davomida uni Qurayshdan himoya qilgan odam. Shunda uning yigirma besh yillik umr yo‘ldoshi, birinchi mo‘min va eng yaqin suyanchi Xadicha (r.a.) ham olamdan o‘tdilar.\n\nIjtimoiy himoyasi va hissiy langari yo'qolgach, Quraysh ularni suiiste'mol qilishda jasoratli bo'ldi. Aynan shu davrda u Toif shahriga borib, uning aholisi xabarni qabul qiladi degan umidda edi. Buning o'rniga ular uni haydab, oyoqlari qon ketguncha toshbo'ron qilish uchun bolalarni qo'yishdi. Shunda ham, shaharni vayron qilish taklif qilinganida, u ularning avlodlari uchun bir kun Allohga ibodat qilishlari uchun ibodat qildi - bu uni belgilaydigan rahm-shafqatdir.\n\nDars: hatto payg'ambarlar ham qayg'u va rad etish bilan sinovdan o'tadilar va javob achchiqliksiz sabrdir. Insonni yo'qotish ilohiy tark etishni anglatmaydi; yengillik yaqin orqada, keyingi keladigan tungi sayohatda kuzatildi. Qarang: “Al-Isro val-Mi’roj”.",
    location: "Makka",
  },
  {
    title: "Al-Isro val-Mi'roj",
    body: "Qayg'u yilidan keyin g'ayrioddiy sharaf kechasi keldi. Isroda Payg'ambarimiz sollallohu alayhi vasallamni bir kechada Makkadagi Masjidul Haromdan Quddusdagi Masjidul-Aqsoga olib ketishdi - bu voqea Qur'onda \"Isro\" surasi bilan ochiladi (Qur'on 17:1). U yerda oldingi payg‘ambarlarga imomlik qildi. So‘ngra Me’rojda yetti osmondan ko‘tarilib, Odam Ato, Muso va Ibrohim kabi payg‘ambarlar bilan uchrashdi va Parvardigoriga har qanday mavjudotdan ham yaqinroq mavqega yetdi.\n\nO'sha kechaning asosiy sovg'asi besh vaqt namoz edi. “Sahih al-Buxoriy”da 3887-yilda qayd etilganidek, ular birinchi marta ellik deb farz qilinganlar; Musoning maslahati bilan Rasululloh sollallohu alayhi vasallam qayta-qayta yengillik so'rab qaytdilar, toki ular amalda beshtaga kamaytirildilar va ellik savob ko'tardilar. Olimlar aniq sana bo'yicha turlicha fikr bildirishadi, ko'pchilik buni hijratdan oldingi yillarga qo'yishadi.\n\nDars: Rasululloh sollallohu alayhi vasallamning qayg'uga botgan tasallisi uchun berilgan sovg'a namoz bo'ldi, bu bizning tunda Alloh taologa ko'tarilishimiz edi. Besh vaqt namoz yerga farishta tomonidan tushirilmagan, balki qabul qilish uchun osmonga ko'tarilgan, bu ularning mo'minning hayotidagi og'irligidan dalolat beradi.",
    location: "Quddus",
  },
  {
    title: "Al-Aqabaning birinchi bay'ati",
    body: "Har yili ziyoratchilar Makkaga to'planishar va Rasululloh sollallohu alayhi vasallam ziyorat qiluvchi qabilalarga Islom dinini taqdim qilar edilar. Mino yaqinidagi al-Aqaba degan joyda, Yasrib (Madina) dan kichik bir guruh erkaklar - Avs va Xazraj qabilalari o'rtasidagi nizolar tufayli uzoq vaqtdan beri parchalanib ketgan va yahudiylar jamoasi orqali tavhidga yaxshi tanish bo'lgan shahar - bu xabarni tinglashdi, iymon keltirdilar va uylariga etkazishdi.\n\nKeyingi mavsumda ulardan o'n ikki nafari qaytib kelib, birinchi Aqaba bay'atini berdilar: yolg'iz Allohga ibodat qilish, o'g'irlik qilmaslik, harom jinsiy aloqa qilmaslik, bolani o'ldirmaslik va Payg'ambarimiz sollallohu alayhi vasallamga to'g'ri yo'lda itoat qilish. Keyin u yosh sahoba Mus'ab ibn Umayrni (r.a.) Islomning birinchi ustozi va elchisi sifatida ular bilan birga qaytarib yubordi va u orqali Yasrib xonadonlarida imon tez tarqaldi.\n\nDars: Makkada yopilgandek tuyulgan eshik Madinada ochildi. Jamiyat qanday qurilganiga e'tibor bering - o'qitish orqali. Qur'on bilan yuborilgan bir fidoyi yosh muallim butun bir shaharni Islom beshigi bo'lish uchun tayyorladi. Bu to'g'ridan-to'g'ri Ikkinchi Bay'at va Hijratni o'rnatadi.",
    location: "Mina",
  },
  {
    title: "Ikkinchi al-Aqaba bay’ati",
    body: "Birinchi bay’atdan bir yil o‘tib, Yasribdan ancha kattaroq hay’at — yetmish uch erkak va ikki ayol — Haj safari chog‘ida Payg‘ambarimiz sollallohu alayhi vasallamning huzurlariga Aqabada yashirincha kelishdi. Bu safar majburiyat yanada uzoqlashdi: ular xuddi o'z xotinlari va bolalarini himoya qilganidek, uni ham himoya qilishga va zulmga uchragan Makka musulmonlarini o'z shaharlariga qabul qilishga va'da berishdi.\n\nBu burilish nuqtasi edi. Yangi shakllangan jamoa birinchi marta vatanga va uni himoya qilishga qasamyod qilgan odamlarga ega bo'ldi. Rasululloh sollallohu alayhi vasallam Makkadagi sahobalariga Qurayshni xavotirga solib qo‘ymaslik uchun kichik guruhlar bo‘lib Yasribga hijrat qilishni boshlashni ko‘rsatma berdilar.\n\nDars: samimiy sodiqlik mas'uliyatni o'z zimmasiga oladi. Ansorlar (Madinaning “Yordamchilari”) hech narsaga erishmay turib, faqat iymon uchun jon va uy-joylarini garovga oldilar. Ularning saxovatliligi islomiy birodarlikning namunasiga aylanadi - keyingi \"Hijra to Madina\"da esga olinadi va u erda ular muhojirlarni oila sifatida kutib olishadi.",
    location: "Mina",
  },
  {
    title: "Madinaga hijrat",
    body: "Quraysh Rasululloh sollallohu alayhi vasallamni o‘ldirmoqchi bo‘lganida, Alloh unga hijrat qilishga izn berdi. Odamlarning omonatlarini qaytarish uchun Alini to‘shagida qoldirib, eng yaqin do‘sti Abu Bakr (r.a.) bilan yo‘lga chiqdi. Ikkovi uch kecha Savr g‘orida yashirinib qolishdi, ta’qibchilar shu qadar yaqinlashib qolishdiki, Abu Bakr ular uchun qo‘rqib ketishdi va Rasululloh sollallohu alayhi vasallam: “Ikkitasi, uchinchisi Alloh ekani haqida nima deb o‘ylaysiz?” deb tinchlantirdilar. Bu lahza “Sahih al-Buxoriy”da 3653-oyatda qayd etilgan va Qur’oni karimda shunday aks-sado berilgan: “...ikkinchisi, g‘orda bo‘lganlarida, u o‘z sherigiga: “G‘amgin bo‘lmang, albatta, Alloh biz bilandir”, dedi” (Qur’on 9:40).\n\nUlar birinchi masjid qurilgan Quboga yetib kelishdi, so‘ng Yasribga, so‘ngra Madina al-Munavvaraga, ya’ni “Nurli shahar”ga kirishdi. Rasululloh sollallohu alayhi vasallam har bir muhojirni (Muhojirni) bir yordamchi (ansoriy) bilan birodarlik bog'lab qo'ydilar. Saxiylik shu qadar to'la ediki, Sa'd ibn ar-Rabiy o'z boyligining yarmini Abdurrahmon ibn Avfga bo'lishishni taklif qildi, u esa faqat bozorni ko'rsatishni so'radi (Sahih al-Buxoriy 3780/3906).\n\nHijrat shu qadar muhim ediki, keyinchalik Umar uni islom taqvimining boshlanishi — hijriy 1-yilga aylantirdi. Dars: Ba'zida iymon hamma narsani Alloh uchun qoldirib, Uning ixlos bilan ekanligiga ishonch hosil qilishni va qondan ko'ra birodarlikni tiklashni talab qiladi.",
    location: "Madina",
  },
  {
    title: "Madina konstitutsiyasi",
    body: "Janob Rasululloh sollallohu alayhi vasallam qabilaviy urushda vayron bo'lgan shaharga kelib, musulmonlarga oddiygina rahbarlik qilmadilar, balki jamoat tuzdilar. U Ibn Ishoqning siralarida saqlanib qolgan va Madinaning “Sahifasi” yoki Konstitutsiyasi nomi bilan mashhur boʻlgan, muhojirlar, ansorlar va shahardagi yahudiy qabilalarni oʻzaro mudofaa boʻyicha yagona shartnoma tuzgan yozma shartnoma tuzdi.\n\nUning shartlari o'z davri uchun ajoyib edi: tomonlar shartnoma maqsadlari uchun \"bir jamoa (ummat)\" tuzdilar, har bir guruh o'z dinini saqlab qoldi, nizolar Payg'ambar sollallohu alayhi vasallamga havola qilinsin, tajovuz va adolatsizlik man qilindi va barcha shaharni tashqi hujumdan himoya qilishga va'da berdi. Bu Madinani cheksiz qon to'qnashuvi emas, balki kelishilgan huquq va majburiyatlarga ega bo'lgan shahar-davlatga aylantirdi.\n\nDars: Islom nafaqat shaxsiy ibodat, balki jamiyatning adolatli tartibidir. Payg'ambar sollallohu alayhi vasallam ko'p qirrali birga yashashni, qabilaviy qasoslarga nisbatan kelishilgan qonun ustuvorligini va ahdlarga rioya qilishni - kelgusi mojaro yillarida sinovdan o'tkaziladigan tamoyillarni namuna qildilar. Butun shaharga insofni yoyish orqali “Madinaga hijrat” birodarligini toʻldiradi.",
    location: "Madina",
  },
  {
    title: "Badr jangi",
    body: "Hijratdan keyingi ikkinchi yilga kelib, o'zini himoya qilish uchun jang qilish uchun ruxsat berildi (Qur'on 22:39). Hijriy 2-yilning 17-ramazonida 313 nafarga yaqin musulmon qoʻshinlari Madinaning janubi-gʻarbidagi Badr quduqlarida bir necha ming kishidan iborat quraysh qoʻshini bilan uchrashdi. Bu Islomning birinchi yirik jangi edi.\n\nMusulmonlar g'alaba qozonishdi va Qurayshning bir qancha quvg'inchilari o'ldirildi. Qur'on g'alabani shunchaki harbiy jasorat sifatida emas, balki alomat sifatida ifodalaydi: \"Alloh sizlarga Badrda zaif bo'lganingizda g'alaba bergan edi, Allohdan qo'rqing, shoyadki shukr qiling\" (Olim surasi, 123-oyat) va farishtalarning yordami tasvirlangan (3:124–125). Badr Arabistonda yosh jamoani haqiqiy kuchga aylantirdi.\n\nDars: Natijalar raqamlarga yoki jihozlarga emas, Allohnikidir. Badr \"Farqon kuni\" (yavm al-furqon) sifatida esga olinadi, haqiqat va botil ajratilgan kun - bu Allohga sidqidildan tavakkal qilish, sidqidildan harakat qilish muhimligidan dalolatdir. Kelgusi yilgi Uhuddagi teskari holat qo'shimcha saboq beradi.",
    location: "Badr",
  },
  {
    title: "Uhud jangi",
    body: "Badrdan bir yil o‘tib Quraysh ancha katta qo‘shin bilan qasos olish uchun qaytib keldi va ikki tomon Madina yaqinidagi Uhud tog‘ining etagida uchrashdi. Rasululloh sollallohu alayhi vasallam ellikta kamonchini tepaga qo'yib, nima bo'lgan taqdirda ham o'z joylarini tark etmasliklarini qat'iy buyurdilar. Jangning boshida musulmonlarning qo'li baland edi; Ammo dushman qochib ketayotganini ko‘rgan kamonchilarning ko‘pchiligi o‘lja yig‘ish uchun o‘z postini tashlab ketishdi. Xolid ibn al-Volid (hali musulmon emas) boshchiligidagi Quraysh otliqlari ochiq qanotni aylanib o‘tishdi va suv to‘lqini qimmat va og‘riqli kunga aylandi.\n\nKo'p sahobalar shahid bo'ldilar, ular orasida Payg'ambarning suyukli amakilari Hamza (r.a.) \"Allohning arsloni\" ham bor edi. Rasululloh sollallohu alayhi vasallamning o'zlari yaralangan, tishlari singan va yuzlari qonga belangan edi. Shundan so'ng Qur'on muvaffaqiyatsizlikka ochiqchasiga murojaat qilib, bu amrga bo'ysunmaslik va dunyoga havas qilishning sinovi va natijasi ekanligini tushuntirdi (Qur'on 3:152, 3:165-166).\n\nDars: Uhud intizom va itoatdagi buyuk saboqdir. Birgina intizomsizlik harakati, qanchalik kichik bo'lsa ham, deyarli g'alabani yo'qotdi. Lekin Alloh ularni tark etmadi - ularni o'rgatdi, kechirdi va to'pladi. Halollik bilan duch kelgan mag'lubiyat g'alabadan ko'ra ko'proq ibratli bo'lishi mumkin.",
    location: "Uhud tog'i",
  },
  {
    title: "Xandaq jangi",
    body: "Beshinchi yilda Quraysh, boshqa arab qabilalari va dushman guruhlar ittifoqi - \"Konfederatsiyalar\" (al-Ahzob) Madinani butunlay vayron qilish uchun Arabistonda hali ko'rilmagan eng katta, ehtimol o'n ming kishilik qo'shinni to'pladi. Rasululloh sollallohu alayhi vasallam ochiq jangda uchrashib bo‘lmaydigan darajada ko‘p bo‘lgan dushmanga duch kelganlarida, fors hamrohi Salmon al-Forsiyning (r.a.) maslahatini qabul qilib, shaharga shimol tarafdagi ochiq yo‘llardan keng xandaq qazishdi – arablar hech qachon uchramagan taktika.\n\nXandaq qamalni to'xtatdi. Haftalar davomida sovuq, ochlik va qoʻrquv hukm surdi va Qurʼoni Karim “Ahzob” surasida moʻminlarning sinovini yorqin tasvirlab beradi: “...Oʻshanda koʻzlar qoʻrquvdan oʻgirilib, dillar boʻgʻizlarga yetib bordi” (Qur’on 33:10). Nihoyat, shiddatli shamol va ichki kelishmovchilik konfederatsiya armiyasini tarqatib yubordi va ular jangsiz chekinishdi. Qur'on najotni \"ularga shamol va siz ko'rmagan qo'shinlarni yuborgan\" Allohga hisoblaydi (Qur'on 33:9).\n\nDars: dono maslahat (shuro) va har kimdan yaxshi g'oyalarga ochiqlik - bu erda, chet ellik muhandislik - iymonning bir qismidir. Insonning sa'y-harakati to'liq berilgan bo'lsa ham, najot Allohdan keladi. Bu buzilgan qamal Qurayshning hujumga kirishish qobiliyatini samarali ravishda tugatdi.",
    location: "Madina",
  },
  {
    title: "Hudaybiya shartnomasi",
    body: "Oltinchi yili Rasululloh sollallohu alayhi vasallam 1400 ga yaqin sahobalari bilan urush qilish uchun emas, umra qilish uchun yo'lga chiqdilar va tinchlik niyatini aniq qilish uchun ehromga kirdilar. Quraysh ularni harom chetidagi Hudaybiya degan joyda to‘sdi. Keskin muzokaralardan so'ng, ko'p sahobalar uchun xo'rlovchi bo'lib ko'ringan shartlar bo'yicha o'n yillik sulhga kelishib olindi: musulmonlar o'sha yili orqaga qaytib, keyingi yili kelishadi; Qurayshdan musulmonlarga qochgan kimsa qaytariladi, aksincha emas.\n\nAmmo Alloh taolo qaytib kelganida aynan mana shu shartnoma «aniq g'alaba» ekanini vahiy qildi (Qur'on 48:1, Fath surasi). Keyinchalik sahobalar bundan katta g'alabani ko'rmaganliklarini aytishdi - chunki keyingi tinchlikda odamlar bemalol aralashdilar, bu xabarni xotirjam eshitdilar va barcha urush yillaridan ko'ra ko'proq Islomga kirdilar; Al-Baro' ibn Azibning bu haqdagi xabari \"Sahih al-Buxoriy\"da 4606-yilda qayd etilgan. Sulh ham musulmonlarni teng huquqli deb tan oldi.\n\nDars: muvaffaqiyatsizlikka o'xshash narsa eng katta ochilish bo'lishi mumkin. Rasululloh sollallohu alayhi vasallam uzoq muddatli yaxshilik uchun qisqa muddatli zohiriy ziyonni tanladilar va og'ir savdoni u tishlaganda ham hurmat qildilar. Sabr-toqat, vazminlik va so'zda turish qarama-qarshilik qila olmaydigan narsaga erishadi.",
    location: "Hudaybiya",
  },
  {
    title: "Hukmdorlarga xatlar",
    body: "Hudaybiya sulhi musulmonlarga urushdan nafas olish imkonini berganidan so'ng, Rasululloh sollallohu alayhi vasallam e'tiborini Arabiston tashqarisiga qaratdilar. Hijratning 6-7-yillari atrofida u ishonchli sahobalarini elchi sifatida yubordi, ularning har biri o'z muhri bilan muhrlangan xat olib borar edi va o'z davrining buyuk hukmdorlarini Islomni qabul qilishga da'vat etardi: Bizantiya imperatori Geraklius; Fors shohi Xisrav II; Bizantiyaning Misrdagi noibi al-Muqawqis; ilgari musulmon muhojirlarga boshpana bergan Habashiston Najoshiysi; hamda Bahrayn va Ummon hukmdorlari.\n\nGeraklusga yozilgan xat hadis adabiyotida deyarli so'zma-so'z saqlanib qolgan: \"Men seni Islomga chaqiraman. Islomni qabul qil, omon bo'lasan... Islomni qabul qil, Alloh senga ikki hissa mukofot bersin\" (Sahih al-Buxoriy 7). Ushbu rivoyat, shuningdek, Geraklusning hali musulmon bo'lmagan Makkalik savdogar Abu Sufyondan Payg'ambarimizning nasabi va xarakteri haqida so'ragan uzoq suhbatini ham saqlab qolgan; halol javoblardan u bu xususiyatlar haqiqiy payg'ambarga to'g'ri kelishini anglagan, ammo shu ishonchiga qarab harakat qilmagan. Xisrav esa, aksincha, siyratda xatni g'azab bilan yirtib tashlagan holda eslanadi, Najoshiy esa elchini hurmat bilan qabul qilgan.\n\nDars: oxirgi Rasulning vazifasi hech qachon Arabiston bilan chegaralanmagan - Madina xavfsiz bo'lgach, da'vat butun taniqli dunyoga yoyildi, xuddi Qur'onda u \"barcha insoniyatga\" yuborilgani aytilganidek (Qur'on 34:28). Ba'zi hukmdorlar halol tinglashdi, ba'zilari odob bilan javob berdi, ba'zilari esa mag'rurlik bilan - va har bir javob ularning saltanatlari kelajakda Islom bilan qanday uchrashishini oldindan ko'rsatardi.",
    location: "Madina",
  },
  {
    title: "Xaybarga ekspeditsiya",
    body: "Hudaybiyadan ko'p o'tmay, Rasululloh sollallohu alayhi vasallam Madina shimolidagi mustahkam qal'alardan iborat boy voha bo'lgan Xaybarga yuzlandilar. Xaybar adovat bazasiga aylangan edi - Konfederatsiyalarning Madinani qamal qilishda yordam bergan va musulmon jamoasiga qarshi fitna uyushtirishda davom etgan qabilalar vataniga aylangan edi. Kampaniya ushbu tahdidni bartaraf etishga qaratilgan edi.\n\nQal’alar qattiq janglardan keyin birin-ketin qulab tushdi; hal qiluvchi kundagi bayroq Ali ibn Abu Tolibga (r.a.) berildi. Shundan so'ng, Payg'ambarimiz sollallohu alayhi vasallam aholiga o'z mahsulotidan bir ulush evaziga erlarda qolib, dehqonchilik qilishni davom ettirishga ruxsat berdilar. Aynan shu yerda ham bir ayol uni qo‘y bilan zaharlamoqchi bo‘lgan, undan ogohlantirilgan.\n\nDars: xavfsizlik va shartnomaga rioya qilish yonma-yon borardi. Harakat isbotlangan dushman kuchga qarshi edi, ammo u mag'lubiyatga uchraganlarga o'z tirikchiligini saqlab qolish imkonini beradigan amaliy kelishuv bilan yakunlandi. Islomda kuch yo'q qilish uchun emas, balki xavfsizlik va adolatni o'rnatish uchun mo'ljallangan.",
    location: "Xaybar",
  },
  {
    title: "Qazo Umrasi (Umrat al-Qazo)",
    body: "Hudaybiya shartnomasi musulmonlarni hijratning 6-yilida umradan qaytargan, ammo keyingi yili qaytishlari mumkinligiga va'da bergan edi. Hijratning 7-yili Zulqa'da oyida, aynan kelishilganidek, Rasululloh sollallohu alayhi vasallam taxminan ikki ming sahoba bilan ulardan mahrum qilingan haj amallarini bajarish uchun yana Makkaga qaytdilar - bu Umrat al-Qazo, \"qazo\" umrasi sifatida eslanadi (ba'zi manbalarda Umrat al-Qisos ham deyiladi).\n\nSulhning o'z tomonini hurmat qilib, Quraysh musulmonlar marosimlarini tinch o'tkazishlari uchun shaharni uch kunga bo'shatdi, atrofdagi tepaliklardan bir vaqtlar quvib chiqargan jamoaning endi to'liq xavfsizlikda Ka'ba atrofida tavof qilayotganini kuzatib turdilar. Aynan shu tashrif chog'ida Payg'ambarimizning amakisi Abbos u kishining Maymuna binti Horis bilan nikohini tashkil qildi va hojilarning sidqidilligini va tartib-intizomini ko'rgan bir qancha Makkaliklar chuqur ta'sirlandilar.\n\nDars: berilgan va'daga rioya qilishning o'zi bir turdagi da'vatdir. Yigirma yillik da'vat qila olmagan qalblarni - Hudaybiyaning \"aniq g'alabasi\"ning (Qur'on 48:1) bevosita mevasi bo'lgan - bitta tinch, sha'nli umra yumshatdi. Bu jimgina tashrif keyingi yili Makkaning deyarli qonsiz taslim bo'lishiga zamin tayyorlashga yordam berdi.",
    location: "Makka",
  },
  {
    title: "Makkaning fathi",
    body: "Qurayshning ittifoqchilari musulmonlarga ittifoqchi qabilaga hujum qilib, Hudaybiya shartlarini buzganlarida, sulh bekor boʻldi. Sakkizinchi yil Ramazon oyida Payg'ambarimiz sollallohu alayhi vasallam o'n minglik qo'shin bilan Makkaga yurish qildilar - bu hali eng katta qo'shin - va yigirma yil davomida uni quvg'in qilgan, boykot qilgan va unga qarshi urush olib borgan shahar deyarli qon to'kilmagan holda taslim bo'ldi.\n\nNihoyat, uni quvib chiqargan qavm ustidan g'olib bo'lib, Makkaliklardan undan nima kutishlarini so'radi. Ular olijanob birodarning rahm-shafqatiga umid qilishdi va u Yusufning birodarlariga: \"Bugun sizlarga ayb yo'q\", deb javob berdi va: \"Boringlar, ozodsizlar\", dedi. Ka’baga kirdi va uni 360 ta butdan tozaladi, “Haq keldi va botil yo‘qoldi” (Qur’on 17:81)ni o‘qib, Ibrohim ziyoratgohini Allohning pok ibodatiga tikladi. “Nasr” surasi (Qur’oni karim, 110-oyat) odamlarning “Allohning diniga ko‘p-ko‘p kiradigan” payti haqida so‘z boradi.\n\nDars: bu bashoratli rahm-shafqat va kechirim cho'qqisidir. Qasos olish uchun mutlaq kuch bilan u kechirdi. Mo'min kuchlilar jazolashga qodir bo'lsa kechiradiganlar ekanligini va maqsad hech qachon qasos olish emas, balki hidoyat ekanligini bilib oladi.",
    location: "Makka",
  },
  {
    title: "Hunayn jangi",
    body: "Makkaning tinch fathidan bir necha hafta o'tgach, musulmonlar qudratining kutilmagan o'sishidan xavotirlangan va oxirigacha jang qilishga qaror qilgan Havozin va Saqif qabilalari ittifoqi katta qo'shin to'plab, oilalari, mollari va boyliklarini o'zlari bilan olib, Makka va Toif orasidagi tor Hunayn vodiysida Payg'ambarimizning ancha katta qo'shiniga qarshi chiqdi.\n\nHavozinlar kamonchilarini dovonlarda pistirma qilib yashirgan edilar, va tongda kutilmaganda o'q yog'dirganlarida, musulmonlarning ilg'or qismi tarqalib, chalkashib ketdi; bir lahza musulmonlar to'plagan eng katta qo'shin faqat kutilmaganlik tufayli tor-mor bo'lishi mumkin bo'lib ko'rindi. Qur'on aynan shu keskin o'zgarishni tasvirlaydi: \"...va Hunayn kuni, ko'pchiligingiz sizga hech qanday foyda keltirmagan va yer o'z kengligiga qaramay sizga tor kelib, orqaga qarab qochgan edingiz\" (Qur'on 9:25). Rasululloh sollallohu alayhi vasallam o'zlari mustahkam turdilar va amakilari Abbosga Ansor va Madina qabilalarini ism-sharifi bilan chaqirishni buyurdilar; shu chaqiruv sahobalarni qaytarib keltirdi, safni qayta tikladi va jang Qur'on Alloh yuborgan xotirjamlik va ko'rinmas yordamga bog'lagan hal qiluvchi musulmon g'alabasiga aylandi (Qur'on 9:26).\n\nDars: son va qurol-yarog' jangning natijasini belgilamaydi - Badr buni kichik qo'shin bilan allaqachon o'rgatgan, Hunayn esa buning aksini ko'rsatdi, hatto ulkan qo'shin ham Allohning yordami va jang maydonidagi tartib-intizomsiz yiqilishi mumkin. Shundan keyin qo'lga tushirilgan katta o'ljalar, jumladan yaqinda musulmon bo'lgan Makkaliklarga ham, boylik yig'ish uchun emas, qalblarni qozonish uchun saxovat bilan taqsimlandi.",
    location: "Hunayn",
  },
  {
    title: "Tabuk safari",
    body: "To'qqizinchi yili Madinaga shimoliy chegarada Vizantiya (Rim)ning ehtimoliy safarbarligi haqida xabarlar keldi. Yozning jazirama jaziramasida, hosil pishib, yo‘l uzoq va mashaqqatli bo‘lganida, Rasululloh sollallohu alayhi vasallam o‘zlari boshchiligidagi eng katta, ehtimol o‘ttiz ming qo‘shinni shimolga Tabuk tomon yurishga chaqirdilar. Bu \"qiyinchilik soati\" edi (Qur'on 9:117) va u ilgari hech narsa kabi samimiyatni sinab ko'rdi.\n\nHech qanday jang bo'lmadi; Qat'iylik ko'rsatish etarli bo'ldi va bir qancha shimoliy boshliqlar Madina bilan shartnoma tuzdilar. Ammo kampaniya avvalambor odamlarning qalbini ochib bergani bilan yodda qoldi. Qur'on Tavba surasining ko'p qismini unga bag'ishlaydi - hamma narsani berganlarni maqtadi (Abu Bakr barcha mol-mulkini bergan), qolish uchun bahonalar o'ylab topgan munofiqlarni fosh qiladi va uchta samimiy mo'minlar, jumladan Ka'b ibn Molik, ular haqiqatni tan olganlar va uchlikdan keyin hech qanday uzr yo'q edilar. 9:118).\n\nDars: itoatkorlik qulay bo'lganda oson; uning haqiqati qachon qimmat bo'lishini ko'rsatadi. Tabuk samimiylarni bahonachilardan ajratdi va Arabistondagi uyushgan butparastlik qarshiligini samarali yakunladi. Halollik - hatto o'z muvaffaqiyatsizligini tan olishning halolligi - Allohga qaytish yo'lidir.",
    location: "Tabuk",
  },
  {
    title: "Elchilar yili (Om al-Vufud)",
    body: "Hijratning to'qqizinchi yilida, Makkaning taslim bo'lishi va Tabukdagi kuch namoyishidan so'ng, Arabiston qabilalari yangi tartibga qarshilik ko'rsatish endi real emasligini angladilar. Elchilik ketidan elchilik - Bani Tamim, Bani Amir, Yaman qabilalari va boshqa ko'plab qabilalardan - Islomni qabul qilganlarini va Rasulullohga sollallohu alayhi vasallam sodiqliklarini e'lon qilish uchun Madinaga kelib turdilar, shu qadar ko'p ediki, bu yil siyratda Om al-Vufud, Elchilar yili sifatida eslanadi.\n\nRasululloh sollallohu alayhi vasallam har bir guruhni mehmondo'stlik va sabr bilan o'qitish orqali qabul qildilar, ularni kuch bilan boshqaradigan hokimlar o'rniga, o'z xalqlariga Qur'on va namozni o'rgatish uchun sahobalarni ular bilan qaytardilar. Qur'on bu lahzaga Nasr surasida bevosita ishora qiladi: \"Allohning yordami va g'alaba kelganida, odamlarning to'da-to'da bo'lib Alloh diniga kirayotganini ko'rganingda, Robbingga hamd ayt va Undan mag'firat so'ra\" (Qur'on 110:1-3) - bu surani sahobalar, Ibn Abbos Umarga tushuntirganidek, Rasulullohning sollallohu alayhi vasallam umri oxiriga yaqinlashganining nishonasi sifatida tushunganlar (Sahih al-Buxoriy 4430).\n\nDars: o'nlab yillar davomida ko'pchilik rad etgan va ozchilik qabul qilgan xabar, Allohning va'dasi bir vaqtning o'zida keldi - sabr va muvaffaqiyatni to'g'ri anglash haqidagi dars. Nasr surasining g'alabaga bergan javobi bayram emas, balki hamd va tavbadir, bu mo'min hayotidagi har qanday muvaffaqiyatga qanday munosabatda bo'lishi kerakligining namunasidir. Bu keyin keladigan Vidolashuv hajiga zamin yaratadi.",
    location: "Madina",
  },
  {
    title: "Vidolashuv haji",
    body: "O'ninchi yili Rasululloh sollallohu alayhi vasallam o'zlarining yagona to'liq hajlarini ado etdilar, unga yuz mingdan ortiq sahobalar qo'shilib, ularga marosimlarni shaxsan o'rgatdilar. Arafa tekisligida turib, Islom o'rnatish uchun kelgan hamma narsaning qisqacha mazmuni bo'lgan Vidolashuv xutbasini o'qidi.\n\nU har bir insonning jonini, mulkini, or-nomusini muqaddas deb e’lon qilgan — “Sening qoning va moling shu kun, shu oy, shu zamin kabi muqaddasdir” (Sahih al-Buxoriy 1741). U zot qonxoʻrlik va johiliylik manfaatini (riba) bekor qildi, Alloh taoloning omonati sifatida ayollarga yaxshi muomala qilishni buyurdi, hech bir arab arab boʻlmagandan faqat taqvodan ustun emasligini eslatdi va Qurʼonni mahkam ushlashlarini aytdi. Aynan mana shu haj ziyorati chog‘ida, juma kuniga to‘g‘ri kelgan Arafa kunida Alloh taolo “Bugun sizlar uchun diningizni mukammal qildim...” (Qur’on, 5:3) oyatini nozil qildi – Umar eslagan va sanasi aniq (Sahih al-Buxoriy 45).\n\nDars: Vidolashuv xutbasi Islomning inson qadr-qimmati, adolat va tenglik to'g'risidagi nizomi bo'lib, dinning endi to'liq bo'lganligi e'lon qilingan. Bu erdan mo'minning vazifasi unga qo'shish emas, balki yashashdir.",
    location: "Arafa",
  },
  {
    title: "Uning o'tishi",
    body: "Vidolashuv hajidan bir necha oy o‘tgach, Rasululloh sollallohu alayhi vasallam isitmasi bilan kasal bo‘lib qoldilar. U umrining oxirgi kunlarida xotinlaridan Oisha roziyallohu anhoning hujralarida emizish uchun ruxsat so‘radi va Abu Bakrni namoz o‘qishga imom etib tayinladi. Oxirgi tongida u namoz o'qiyotgan mo'minlar safini ko'rish uchun pardani orqaga tortdi va ummatiga xursand bo'lib tabassum qildi, so'ngra uni qulab tushdi. U kishi hijriy 11-yil rabi ul-avval oyining 12-dushanba kuni vafot etdi, boshi Oisha onamizning ko‘kragi va iyagi orasiga qo‘yilgan holda vafot etdilar — deb o‘zi Sahih al-Buxoriyda 4449/4451 rivoyat qilgan.\n\nMadinadagi qayg‘u g‘am-g‘ussa bo‘ldi, hatto Umar ham avvaliga buni qabul qilmadi. Shunda Abu Bakr o‘rnidan turib, Payg‘ambar alayhissalomning yuzlarini o‘pib, butun ummatni mustahkamlagan va “Sahih al-Buxoriy”da 1241/1242 rivoyat qilingan so‘zlar bilan odamlarga xitob qildilar: “Kim Muhammadga ibodat qilsa, Muhammad o‘ldi, kim Allohga ibodat qilsa, Alloh barhayotdir va o‘lmaydi”. “Muhammad payg‘ambardir, undan oldin ham payg‘ambarlar o‘tgan...” (Olim surasi, 144-oyat) ni o‘qidi.\n\nDars: xabar to'liq bo'ldi va endi ummatga tegishli edi. Rasululloh sollallohu alayhi vasallam o'lgan edilar, lekin u keltirgan narsa - Qur'on va sunnatlari - emas. Abu Bakr roziyallohu anhuning javobi qayg'uga sobit javobdir: bizning bog'lanishimiz hech qachon o'lmaydigan Allohgadir, Payg'ambar sollallohu alayhi vasallamni sevishning yo'li esa uning hidoyati bilan yashashdir.",
    location: "Madina",
  },
];
