// Somali translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_SO: DeepPartial<SeerahEvent>[] = [
  {
    title: "Carabta Islaamka ka hor (Jaahiliyada)",
    body: "Si aad u fahanto nabiga ﷺ waa inaad marka hore sawirtaa aduunka loo soo diray. Carabtii qarnigii lixaad waxay ahayd dhul ay ku nool yihiin qabaa'il kala firdhisan oo aan lahayn dawlad dhexe, waxay isku xidhi jireen abtirsiinyo, sharaf, iyo xaramka Kacbada ee Makkah - macbad ay Ibraahim iyo Ismaaciil u dhiseen cibaadada Ilaaha keliya, laakiin hadda waxaa ku hareeraysan ilaa saddex boqol iyo lixdan sanam.\n\nWaagaas waxa loogu yeeraa Jaahiliyada, “Waagii Jaahiliga” – ma ahan in Carabtu ay ka maqneyd caqli-galnimo (Maansadooda iyo xusuustooda ayaa ahaa mid aan caadi ahayn) balse waa ay waayeen hanuun. Qabyaaladu waxay socon kartaa qarniyo badan, kuwa xoogga badana waxay ugaadhsan jireen kuwa daciifka ah, gabdhahana mararka qaarkood waxaa lagu aasay iyagoo nool ceeb ama cabsi ay ka qabaan saboolnimada - dhaqanka Qur'aanka ayaa hadhow si toos ah u cambaareeyay (Qur'aanka 81: 8-9). Sanam caabudka waxa weheliya dhawr \"hunafa\" ayaa wali raadiyay tawxiidka saafiga ah ee Ibraahim, iyo bulshooyin yar oo Yuhuud iyo Masiixiyiin ah ayaa ku noolaa jasiiradda oo dhan.\n\nCasharkii: Waxyigu kuma soo degin meel bannaan ee waxay ku soo degtay bulsho dhab ah oo nabarro qoto dheer leh, waxa ugu horreeya ee ay bogsiiseyna waxay ahayd xidhiidhka ka dhexeeya bani'aadamka iyo abuurihiisa. Maskaxda ku hay dulucdan sida uu waqtigu u dhacayo - ku dhawaad ​​dibuhabayn kasta oo lagu sameeyo Nabiga ﷺ waxay jawaab toos ah u tahay dulmiga Jaahiliyada.",
    location: "Carabta",
  },
  {
    title: "Dhalashada Makkah",
    body: 'Nebigu ﷺ wuxuu ku dhashay Makka sannadkii Maroodiga (Am al-Fil), waxaana loogu magac daray sanadkaas Abraha oo ahaa guddoomiyihii Xabashida ee Yaman, wuxuu la soo baxay ciidan maroodi wata si uu u burburiyo Kacbada, si mucjiso ah ayaana dib loogu noqday — dhacdo uu Qur’aanku ku xusay suuradda al-Fil (Qur’aanka 105). Sannadkan la dalacsiiyay waxaa u dhashay qabiilka Qureysh iyo qabiilkeeda ugu sharafta badan ee Banu Haashim.\n\nWaxa uu ahaa agoon markii uu dhashay: Aabihiis Abdullah waxa uu dhintay bilo ka hor isaga oo ka ganacsanayay. Hooyadii, Aamina bint Wahb, waxay u bixisay Muxammad - "kan aadka loo ammaanay" - magac aan laga aqoon Carabta dhexdooda. Iyadoo la ilaalinayo caadada Makka ayaa loo diray in lagu naasnuujiyo oo lagu koriyo hawada bannaan ee saxaraha ah ee reer banii Sacad, oo ay daryeelayso Xalimah As-Sacdiyah.\n\nCashar u ah qofka mu’minka ah: weynaanta Alle agtiisa shaqo kuma laha amniga adduunyada. Rasuulkii ugu dambeeyay wuxuu bilaabay nolol aabbe la\'aan, wuxuuna dhawaan noqon doonaa hooyo la\'aan, haddana Eebbe laftiisa ayaa mas\'uul ka ahaa - "Miyaanu ku helin agoon oo ku siinin magan?" (Quraanka 93:6). Eeg sidoo kale "Martida hooyadiis" iyo "Mas\'uulka Abu Daalib" ee soo socda.',
    location: "Makkah",
  },
  {
    title: "Maraya hooyadii",
    body: 'Markii uu lix jir ahaa ayay Aamina wiilkeedii kaxaysatay si uu ugu soo booqdo ehelkiisii ​​oo joogay Yathrib (Madiino ka dib) oo ay soo aragto qabriga aabihiis. Soo noqodkeedii ayey xanuunsatay, waxayna ku geeriyootay meel la yiraahdo Abwaac oo u dhaxaysa Makka iyo Madiina, halkaas ayaana lagu aasay. Wiilka yar ee Muxammad ﷺ wuxuu hadda waayay labada waalid.\n\nWaxaa Makka ku soo celisay Ummu Ayman oo ahayd addoontii reerka ee la xoreeyay, waxayna u dhiibtay awoowgiis Cabdil-mudhalib oo ahaa madaxdii Qureysh ee la ixtiraami jiray, aadna u jeclaa oo kacbada agtiisa fadhiisan jiray.\n\nCasharkii: Nebigu ﷺ dhadhamiyey, goor hore oo ku celcelinayey, murugada ay bani-aadmigu sidaan - murugo, barakac, ku tiirsanaanta dadka kale. Tani waxay qayb ka ahayd diyaarintiisa. Qalbiga khasaaraha yaqaan waa qalbi dareemi kara agoonta, carmalka iyo shisheeyaha, bulshadiisuna waxay hadhow ku dhismi lahayd naxariista saxda ah. Dulucdani waxay ku sii socotaa "Sanadka murugada."',
    location: "Abwa'",
  },
  {
    title: "Mas'uuliyadda Abuu Daalib",
    body: "Laba sano ka dib hooyadii, awoowgiis Cabdil-mudhalib ayaa isna dhintay, isagoo wiilku da'diisu ku dhowdahay siddeed. Sariirtiisii ​​geerida ayuu ku wakiishay wiilkiisii ​​uu jeclaa ee Abuu Daalib oo ahaa Nabiga adeerkiis. In kasta oo Abuu Daalib aanu ahayn maalqabeen, haddana waxa uu u kaxaystay reerkiisii ​​oo uu ula dhaqmay sidii mid ka mid ah carruurtiisa ugu qaalisan.\n\nAbu Daalib waxa uu ilaalintiisa sii ahaan lahaa in ka badan afartan sano, iyada oo la marayo sannadihii ugu adkaa ee cadaadiska Makkah. Waxa uu ahaa kii u kaxaystay da'da yar ee Muxammad ﷺ safarro ganacsi oo uu ku tagayo Shaam, halkaas oo - sida laga soo xigtay xisaabaadka caanka ah - Bahira wuxuu arkay calaamado nabinnimo isaga (warbixinta seerah ayaa ilaalinaysa, inkastoo faahfaahinteeda lagu kala qaado xoog kala duwan).\n\nCasharka: Allaah wuxuu Nebigiisa ﷺ ku hareereeyey dad daacad ah oo karaamo leh marxalad kasta. Dhowr iyo tobankii sano ee Abu Daalib ilaalinayey waxay u ahayd naxariis - waa xasuusin in taageeridda runta iyo qaraabanimada ay tahay xarun sharaf leh xitaa kuwa aan weli rumaysan, iyo inaan ixtiraamno kuwa na gabanaya. Waayidiisa dambe, Sannadka Murugada, wax walba wuu beddeli lahaa.",
    location: "Makkah",
  },
  {
    title: "Guurka Khadiija",
    body: "Intii uu yaraa Muxammad ﷺ waxa uu Makkah oo dhan kasbaday sumcad aysan wax xoolo ah iibsan karin: al-Saadiq, runlow, iyo al-Amin, oo la aamini karo. Dadku waxay isaga u kaydiyeen alaabtoodii qaaliga ahayd si ay u badbaadiyaan, oo eraygiisay si buuxda isugu halleeyeen, xataa kuwa ilaahyo kala duwan caabudi jiray.\n\nKhadiijah bintu Khuweylid (Alle ha ka raalli noqdee) oo ahayd ganacsatadii Qureysh ee sharafta iyo liibaantay, ayaa u soo kiraysatay inuu u hoggaamiyo safarkeedii Shaam. Iyada oo la dhacsan daacadnimadiisa iyo dabeecadiisa, ayay dalab guur u soo dirtay saaxiibkeed Khawlah bint Xakiim. Isagu wuxuu ahaa abbaaraha shan iyo labaatan, iyaduna afartan; Waxayna noqdeen guur jacayl iyo shuraako qoto dheer. Oo waxay u dhashay carruurtiisii, oo naag keliya ayuu u ahaa shan iyo labaatan sannadood, ilaa ay dhimatey.\n\nCasharka: dabeecaddu waa aasaaska wax kasta oo raacay. Waqti dheer ka hor inta aan nebi loogu yeerin, Makkah waxay horey u garaneysay inuu yahay ninka ugu daacadsan dhexdooda - waana sababta, muujintii ugu horreysay, kalsoonida degdegga ah ee Khadiijah isaga ayaa ahayd mid go'aansan (eeg \"waxyigii ugu horreeyay\"). Daacadnimada mu'minka ee macaamilka caadiga ah lafteedu waa nooc ka mid ah dacwooyinka.",
    location: "Makkah",
  },
  {
    title: "Hilf al-Fudul iyo Dhagaxa Madow",
    body: "Laba dhacdo oo ka mid ah noloshiisii ​​nebinimada ka hor ayaa muujinaysa qiyamka uu hadhow qaran ku dhisi doono. Ugu horrayn, Hilif al-Fudul: waa axdi adag oo ay dhowr qabiil oo Qureysh ah ku dhaarteen in ay garab istaagaan qof kasta oo lagu dulman yahay Makka, waddan iyo shisheeye, inta xuquuqdooda loo soo celinayo. Nebigu ﷺ wuu ka qayb qaatay oo markii dambe sheegay inuu weli ka jawaabi doono heshiiskaas xitaa Islaamka - sababtoo ah waxay difaacday caddaaladda.\n\nLabo, dib u dhiska Kacbada daad ka dib. Markay qabiilooyinku ku sigteen inay afuufo sharaftii kor u qaadida Dhagaxa Madoow ee xurmada leh (al-Xajar al-Aswad) dib loogu celiyo, waxay isku raaceen inay aqbalaan xukunka ninka xiga inuu galo - wuxuuna ahaa Muxammad ﷺ. Xalkiisu waxa uu caan ku ahaa xikmaddiisa: waxa uu dhagax dhigay maro oo uu qolo walba madax u soo saaray, ka dibna gacmihiisa ayuu meel ku dhigay, si ay dhammaan sharaftii u wada qaybsadaan oo aan midna la fududayn.\n\nCasharka: caddaaladda iyo xallinta khilaafku waxay ahaayeen dareenkiisa ka hor intaan waxyigu xaqiijin. Mu’minku waa kan difaaca qofka la dulmiyey oo hela habab uu ku midoobo intii uu kala qaybin lahaa – Hilf al-Fudul waxa uu hormood u yahay bulshadii xaqa ahayd ee uu dhisi lahaa Hijrada ka dib.",
    location: "Makkah",
  },
  {
    title: "Waxyigii ugu horeeyey",
    body: 'Dabayaaqadii soddonaadkii ayuu Nebigu ﷺ si isa soo taraysa uga baxay inuu cibaadeysto oo uu ka milicsado godka Xiira ee buurta Jabal an-Nuur ee Makka ka baxsan. Meeshaas, isagoo da\'diisu ku dhowdahay afartan jir bishii Ramadaan ayaa waxaa u soo baxay malag Jibriil oo ku amray: "Akhri!" Wuxuu ku jawaabay ma akhriyi karo; Malaa\'igtii ayaa si adag u laabatay saddex jeer, waxayna soo deysay aayadaha furitaanka ee suuradda Al-calaq - "ku akhri magaca Eebahaa abuuray..." (Qur\'aanka 96:1-5) oo ah erayadii ugu horreeyay ee Qur\'aanka.\n\nGurigiisii ​​ayuu ku noqday isagoo gariiraya, markaasay Khadiija duubtay oo ay ku niciifisay hadallo muujinaya iimaankeeda iyo akhlaaqdeeda: Eebbe weligiis ma ceebayn doono, maxaa yeelay wuxuu dhawray xidhiidhka qaraabada, culaabta dadka kale, wuxuuna u gargaari jiray kuwii mudnaa. Waxay u geysay ina-adeerkeed Waraqah bin Nawfal, oo ahaa nin da’ ah oo kitaabkii hore wax ku bartay, oo u aqoonsaday ninkii soo booqday inuu yahay isla “Namus” (malag) u yimid Muuse una sheegay inay tani tahay nabinimadii loo ballan qaaday. Dhacdadan oo dhan waxay ku qoran tahay Saxiixul Bukhaari 3.\n\nCasharka: waxyigu kuma bilaaban awood sheegasho ee waxay ku bilaabantay ereyga "Akhri" - diin ku dhisan aqoon iyo is-hoosaysiin. Ogowna yaa rumaystay horta: naag iyo reer daacad ah. Runta waxaa garwaaqsan kuwii hore ugu noolaa si daacad ah.',
    location: "Cave of Hira",
  },
  {
    title: "Sannado wacdi gaar ah",
    body: "Waxyigii ugu horeeyey ka dib waxaa hakad ku yimid (Fatrah), markaas ayuu Alle amray Nabiga ﷺ inuu dadka ugu yeero cibaadada isaga oo keliya. Qiyaastii seddexdii sano ee ugu horeysay wicitaankani wuxuu ahaa mid degan oo gaar ah - waxaa lagu fidiyay qoyska dhow iyo saaxiibada la aaminsan yahay halkii looga dhawaaqi lahaa waddooyinka.\n\nMu’miniintii ugu horreysay, “as-Sabiquun Al-Awwaluun” (oo ugu horreeyo), waxay ka kala yimaadeen qayb kasta oo bulshada ka mid ah: Khadiija xaaskiisa; ina-adeerkiis Cali bin Abii Daalib; addoonkiisii ​​la xoreeyey oo uu korsaday Zayd bin Xaarithah; iyo saaxiibkii daacadda ahaa ee Abuu Bakar As-Siddiiq (Alle haka raalli noqdee dhammaantood). Abuu Bakar isna wuxuu keenay islaamo kale oo badan. Waxay ku kulmeen oo ku tukadeen si qarsoodi ah, inta badan waxay ku tukanayeen guriga al-Arqam oo u dhow Kacbada.\n\nCasharkii: Islaamku wuxuu ku koray marka hore is-aaminaad iyo xidhiidh, ee ma ahayn mid daawasho ah. U fiirso ballaadhka qalbiyadaas ugu horreeya - naag hodan ah, ilmo, addoon la xoreeyey, baayacmushtar - odoroska iimaanka oo tirtiraya faraqa u dhexeeya jinsiyadda iyo darajada. Dacwadu waxay ku bilaabataa meel u dhow guriga, iyadoo leh daacad iyo dulqaad.",
    location: "Makkah",
  },
  {
    title: "Baaqa dadweynaha ee Islaamka",
    body: 'Markii Eebe soo dejiyay "Una dig qaraabadaada kuugu dhow" (Qur\'aanka 26:214), Nebigu ﷺ wuxuu fuulay buurta Safa ee Kacbada agteeda, wuxuuna u yeedhay qolooyinkii Quraysh. Waxa uu marka hore waydiiyay inay rumaysan doonaan haddii uu yidhi ciidan ku qarsoon buurta gadaasheeda; Waxay ugu jawaabeen in aanay weligood garanayn inuu been sheegayo. Dabadeedna wuxuu uga digay inay u yimaadaan ciqaab, wuxuuna ugu yeedhay cibaadada Eebbe oo keliya.\n\nFariintan furan ayaa ku dhacday xudunta amarka Makkah. Sanamyadu diin kaliya ma ahayn ee waxay ahaayeen nolol iyo sharaf -maqaamkii magaalada ee ahaa ilaaliyaha macbadka ayaa soo jiiday xujaajta iyo ganacsiga. In la yiraahdo sanamyadu awood ma lahayn waxay ahayd in qureysh dhaqaalaheedii, abtirsiinteedii iyo faankeediiba hal mar la dagaallamo. Halkaa waxaa ka sii xoogaystay dhibaatadii, waxayna ku dhacday kuwii taagta darnaa iyo kuwii mu’miniinta ahaa ee la addoonsanayay, sida Bilaal bin Rabaax iyo reer Yaasir.\n\nCasharka: Runta si cad loogu hadlo waxay dejinaysaa danaha xididaysan. Nebigu ﷺ waxa uu marka hore ka codsaday maraggooda in uu ahaa daacad - caqli iyo daacadnimo ka hor hanjabaad - ka dibna uu ku adkaystay. U istaagidda tawxiidka waxa laga yaabaa inay ku kacdo raaxada adduun, sida ay rumaysteen reer Makkan ay barteen. Dhibaatadani waxay si toos ah u horseedaysaa "U haajiridda Abyssinia."',
    location: "Buurta Safa",
  },
  {
    title: "U haajiridda Abyssinia",
    body: "Markii ay dhibaatadu sii korodhay oo aan loo adkaysan karin, ayuu Nebigu ﷺ u sheegay koox ka mid ah asxaabtiisa inay magan galaan Negus (an-Najashi), oo ahaa boqorkii xaqa ahaa ee Masiixiga ahaa ee Abyssinia (xabashida casriga ah), isagoo sheegay in dhulkiisa aan cidna lagu dulmin. Kooxdii ugu horreysay ayaa ka gudubtay badda cas, waxaana ku xigay hijradii labaad oo ka weyn - hijradii ugu horreysay ee Islaamka.\n\nQureysh markay ergo u dirtay oo dalbanaysa in qaxootiga loo soo celiyo, Negus baa u yeedhay. Jacfar Binu Abii Daalib (Alle haka raali noqdee) ayaa u hadlay Muslimiinta isagoo ka sheekeeyay sida ay jaahiliga uga soo baxeen iimaanka xaqa, naxariista iyo akhlaaqda suuban, ka dibna wuxuu akhriyay aayado ka mid ah suuradda Maryam oo ka hadlaysa Nabi Ciise iyo hooyadii. Boqorkii Kirishtaanka ayaa ooyay, dhulka ayuu xarriiqay, wuxuuna sheegay in faraqa u dhexeeya iimaankooda iyo kiisa uusan ka sii weyneyn – wuuna diiday inuu dhiibo.\n\nCasharka: tani waa calaamad muujinaysa dulqaadka diinta iyo dhisidda buundooyinka Ehlu-Kitaabka ee daacadda ah. Waxa kale oo ay baraysaa in ka badbaado laga raadiyo dulmiga hoos yimaada maamulka cadaalada ah ee aan muslimka ahayn ay gabi ahaanba sharci tahay. U fiirso sidoo kale in doodda maalintaas ku guulaysatay ay ahayd dabeecad qurux badan iyo ereyga Alle ee la akhriyay - maahan xoog.",
    location: "Xabashida",
  },
  {
    title: "Qaadacaada Banu Haashim",
    body: "Markii ay awoodi waayeen in ay joojiyaan fiditaanka Islaamka ama ay gaaraan Nabiga ﷺ iyadoo ay qabiilkiisu ilaalinayaan, madaxdii Qureysh waxay galeen ciqaab wadareed. Waxay qoreen axdi, waxayna ku dhejiyeen Kacbada, iyagoo ku ballamay inay qaadacaan dhammaan reer Banu Haashim (iyo xulafadooda Banu Al-Mudhalib): guur la'aan, ganacsi la'aan, xiriir bulsho, ilaa ay ka dhiibaan Muxammad ﷺ.\n\nMuddo ku dhow saddex sano ayaa qabiilku - mu'miniinta iyo gaalada Haashimba - waxay ku koobnaayeen dooxada buurta ee Shi'ib Abii-dhaalib, iyagoo gaajo aad u daran ugu adkaystay ilaa qaylada carruurta la maqlo dadkuna waxay cuneen caleemo. Qaadacadaas ayaa ugu dambayntii burburtay markii dhawr nin oo Qurayshi ah oo caddaaladda ku dhaqnaa ay si cad u diideen, waxaana la ogaaday in xaashidii la cunay, marka laga reebo erayadii magaca Alle ku soo baxay.\n\nCasharkii: Beentii way badatay. Dulmiga qaadacadu waxa uu daaha ka fayday cadaalad darada ay ku kacayaan dadka silcinaya,waxana ay sii adkaysay go’aanadii Mu’miniinta. Waxa kale oo ay muujinaysaa sharafta dhawr qof oo cadaalad ah oo ku dhex jira bulsho cadaawad ah oo jabiyay darajooyin si ay u joojiyaan xasuuqii - xasuusin in damiirku uu ku noolaan karo xitaa mucaaradka ugu daran.",
    location: "Shiib Abii Daalib",
  },
  {
    title: "Sanadka Murugada",
    body: "Wax yar ka dib markii ay dhammaatay qaadacaadii, Nebigu ﷺ waxa soo gaadhay laba khasaare oo aad u xun muddo gaaban gudaheed, sanadkaas waxa loo yaqaan Am al-Xusn, sannadkii murugada. Marka hore adeerkiis iyo ilaaliyaha cimriga oo dhan Abuu Daalib ayaa dhintay - waa ninkii taagnida ka ilaalinayay Qureysh tobanaan sano. Dabadeed Khadiijah (Alle ha ka raalli noqdee), xaaskiisii ​​oo shan iyo labaatan jir ah, isla markaana ahayd mu’minkiisii ​​ugu horreeyay, uguna dhowaa, iyana way geeriyootay.\n\nIlaalintiisii ​​bulsheed iyo barroosinkiisii ​​shucuureed labaduba way baxeen, Quraysh waxay ku sii dhiirantay xadgudubkooda. Waxa ay ahayd muddadaas markii uu u safray magaalada Taa'if isagoo rajeynaya in dadkeedu ay aqbalaan farriinta; Halkii bay ka eryeen oo carruur dhigeen inay dhagaxaan ku tuuraan ilaa cagtu ka dhiig baxayso. Xataa markaas, markii loo fidiyay burburinta magaalada, wuxuu u duceeyay faracooda inay maalin uun caabudaan Allaah - naxariista isaga qeexaysa.\n\nCasharka: Xataa nebiyada waxaa lagu imtixaamaa murugo iyo diidmo dib loogu celiyo, jawaabtuna waa dulqaad aan qadhaadh lahayn. Waayida bini'aadamku macnaheedu maaha in Ilaah laga tagay; nafis ayaa daba socotay oo gadaal ka dhow, safarka habeenimo ee soo socda. Eeg \"Al-Isra wal-Miraaj.\"",
    location: "Makkah",
  },
  {
    title: "Al-Israa wal-Miraaj",
    body: "Sannadkii Murugada ka dib waxaa yimid habeen sharafeed aan caadi ahayn. Israa'iil dhexdeeda, Nabiga ﷺ waxaa hal habeen laga soo qaaday Masjidka Xaramka ee Makkah oo loo waday al-Masjid al-Aqsa ee Jerusalem - dhacdo Qur'aanku ku furay suuradda al-Isra (Qur'aanka 17:1). Halkaas ayuu nebiyadii hore ugu duceeyey. Kaddibna Miraajka dhexdiisa waxaa lagu koryeelay Samooyinka Todobada ah, wuxuuna la kulmay Nabiyo ay ka mid yihiin Aadam, Muuse iyo Ibraahim, wuxuuna gaaray meel Eebihiis uga dhaw wax abuur ah.\n\nHibada dhexe ee habeenkaas waxay ahayd shanta salaadood. Sida ku xusan Saxiixul Bukhaari 3887, waxaa markii hore lagu amray konton; Taladii Nabi Muuse ayaa Nebigu s.c.w ku soo noqnoqday si uu u gargaaro ilaa ay shan ka noqdeen ficil ahaan iyagoo wata ajar konton ah. Culimadu way ku kala duwan yihiin taariikhda saxda ah, badankooduna waxay dhigaan sannadihii ka hor Hijriyada.\n\nCasharka: Hibada la siiyay si loogu tacsiyeeyo Nebigii murugaysnaa waxay ahayd salaad - habeennimo aynu u fuulno Alle. Shanta salaadood ma soo dejin malaa’ig dhulka ee waxa loo qaaday samada si uu u qaabilo, waana calaamad muujinaysa miisaanka ay ku leeyihiin nolosha qofka mu’minka ah.",
    location: "Yeruusaalem",
  },
  {
    title: "Ballanqaadka koowaad ee al-Aqabah",
    body: "Sannad kasta xujaydu waxay isugu iman jireen Makkah, Nebiguna ﷺ wuxuu u bandhigi jiray Islaamka qabaa'ilka soo booqda. Meesha la yiraahdo al-Aqabah oo Mina u dhaw, koox yar oo ka mid ah dadka Yathrib (Madiina) - magaalo ay muddo dheer ka taagnaayeen colaado u dhexeeya qabiiladeeda Aws iyo Khazraj, aqoonna u leh tawxiidka iyada oo adeegsanaysa bulshada Yuhuudda ah - waxay dhegaysteen, rumaysteen, oo fariinta u qaadeen guriga.\n\nLaba iyo toban ka mid ah way soo noqdeen oo waxay ballan qaadeen Al-Caqaba: inay Eebe kaligiis caabudaan, waxna xadin, oo aan galmo xaaraan ah samayn, ilmona dilin, Nabigana ﷺ adeecaan xaqa. Markaasuu u diray saxaabigii yaraa ee Muscab ibnu Cumeyr (Alle haka raali noqdee) isagoo wata macalinkii iyo safiirkii ugu horeeyay ee Islaamka, wuxuuna iimaanku si degdeg ah ugu faafay reerkii Yathrib.\n\nCasharkii: Albaabkii u ekaa in Makkah xidhan ayaa ka furmay Madiina. U fiirso sida bulshada loo dhisay - iyadoo wax la baro. Mid ka mid ah macallimiinta da'da yar, oo loo soo diray Qur'aanka, ayaa diyaariyey magaalo dhan si ay u noqoto saldhigga Islaamka. Tani waxay si toos ah u dejinaysaa Ballanqaadka Labaad iyo Hijrada.",
    location: "Mina",
  },
  {
    title: "Ballanqaadka labaad ee al-Aqabah",
    body: "Hal sano ka dib ballan qaadkii ugu horreeyay, wafdi aad uga ballaaran oo Yathrib ka socday -- todobaatan iyo saddex rag ah iyo laba dumar ah - ayaa si qarsoodi ah ugu yimid Nabiga ﷺ isagoo ku sugan al-Aqabah intii lagu jiray xajka. Markan ballanku wuu sii socday: waxay ballan qaadeen inay si sax ah u ilaalinayaan sida ay u ilaalinayaan xaasaskooda iyo carruurtooda, iyo inay soo dhoweeyaan Muslimiinta Makka ee lagu dhibaateeyay magaaladooda.\n\nTani waxay ahayd bar-rogid. Waa markii ugu horeysay ee beesha curdinka ahi ay yeelato dhul iyo dad loo dhaariyey inay difaacaan. Isagoo og khatarta jirta ayuu Nebigu ﷺ si aamusnaan ah ugu amray asxaabtiisii ​​Makkah ku sugnaa inay billaabaan inay u hijroodaan Yathrib iyagoo koox-koox ah si aysan Qureysh uga digin.\n\nCasharka: ka go'naan daacad ah ayaa qaadaya mas'uuliyadda. Ansaartii (“Kaalmeeyayaashii” Madiina) waxay ballan-qaadeen naftoodii iyo guryahoodii ka hor intaanay waxba ka faa’iidaysan, oo kaliya danta iimaanka. Deeqsinimadooda waxay noqon doontaa tusaalaha walaaltinimada Islaamka - oo lagu xasuusto \"Hijrada ilaa Madiina\" ee soo socota, halkaas oo ay ku soo dhaweeyeen muhaajiriinta qoys ahaan.",
    location: "Mina",
  },
  {
    title: "Hijrada ilaa Madiina",
    body: 'Qureysh markay damacday inay Nabiga (scw) dilaan, Alle wuu u fasaxay inuu hijroodo. Wuxuu la baxay saaxiibkiis ugu dhowaa ee Abuu Bakar (Alle haka raalli noqdee), wuxuuna uga tagay Cali sariirtiisa si uu u soo celiyo kaydkii dadka. Labaduba saddex habeen ayay ku dhuunteen godka Thawr, iyadoo daba-galayaashu ay aad ugu soo dhawaadeen, markaas buu Abuu Bakar u baqay, nabiguna wuxuu u nisbeeyay, "Maxaad u malaynaysaa laba, saddexdooduna waa Eebbe?" Daqiiqadan waxa lagu qoray Saxiix Al-Bukhaari 3653 oo uu Qur’aanka ku yiri: “… Labadii labaad, markay godka ku jireen, markuu saaxiibkii ku yidhi, Ha murugoon, illeen Eebbe waa nala jiraa” (Qur’an 9:40).\n\nWaxay gaadheen Quba, halkaas oo masaajidkii ugu horreeyay laga dhisay, ka dibna waxay galeen Yathrib - ka dibna al-Madinah al-Munawwarah, "Magaalada Iftiinka." Rasuulku ﷺ waxa uu muhaajir kasta (Muhaajir) ku lammaaniyay Gargaare (Ansaari) oo xidhiidh walaaltinimo ah; Deeqsinimadu aad bay u dhammaatay oo Sacad bin Al-Rabiic waxa uu u soo bandhigay in uu C/Raxmaan bin Cowf la wadaago hantidiisa kala badh, taas beddelkeedana waxa uu codsaday in la tuso suuqa (Saxiixul Bukhaari 3780/3906).\n\nHijradu waxay ahayd mid aad muhiim u ah oo Cumar ka dib wuxuu ka dhigay bilawga taariikhda Islaamka - sannadkii 1aad ee Hijriyada. Casharka: Mararka qaarkood iimaanku wuxuu u baahan yahay in wax walba loo daayo Allaah, lana aamino inuu la jiro kuwa daacadda ah, iyo dib u dhis walaalnimo oo aan ahayn dhiig.',
    location: "Madiina",
  },
  {
    title: "Dastuurka Madiina",
    body: 'Markii uu yimid magaalo ay burburiyeen dagaal beeleed, Nebigu ﷺ si fudud uguma hoggaansamin muslimiinta - wuxuu aasaasay bulsho. Wuxuu dejiyay heshiis qoraal ah, oo lagu xafiday Seerah Ibnu Isxaaq loona yaqaan Saxiifa ama Dastuurka Madiina, isagoo isku xiraya Muhaajiriinta, Ansaarta iyo Qabaa’ilka Yahuudda ee magaalada oo laga dhigay hal is-difaac.\n\nShuruucdeedu waxay ahaayeen kuwo cajiib ah waqtigoodii: Xisbiyadu waxay samaysteen "hal beel (ummah)" ujeedooyinka heshiiska, koox kastaa waxay ilaalisay diinteeda, khilaafaadkiina waa in loo gudbiyo Nabiga s.c. Waxay si wax ku ool ah uga dhigtay Madiina dawlad-magaaleed leh xuquuq iyo waajibaad lagu heshiiyey halkii ay ka ahaan lahayd dhiig-diid aan dhammaad lahayn.\n\nCasharka: Islaamku ma aha oo kaliya cibaadada gaarka ah ee waa nidaamka cadaalad ah ee bulshada. Nebigu ﷺ wuxuu qaabeeyay wada noolaanshaha jamac, xukunka sharciga lagu heshiiyey ee ku saabsan vendetta qabiilka, iyo ixtiraamka axdiga - mabaadi\'da la tijaabin doono sanadaha colaadaha soo socda. Waxay dhamaystiraysaa walaaltinimada "Hijrada ilaa Madiina" iyada oo si cadaalad ah u fidinaysa magaalada oo dhan.',
    location: "Madiina",
  },
  {
    title: "Dagaalkii Badar",
    body: "Sannadkii labaad ee Hijrada ka dib, waxaa la siiyay oggolaanshaha dagaalka is-difaaca (Qur'aanka 22:39). 17kii Ramadaan 2dii Hijriyada, ciidan muslimiin ah oo ka koobnaa ilaa 313 nin — oo aad u hubaysan, isla markaana wata fardo faro-ku-tiris ah - ayaa la kulmay ciidan qureysh ah oo qiyaas ahaan kun xoog leh ku sugnaa ceelasha Badar ee koonfur-galbeed ka xiga magaalada Madiina. Wuxuu ahaa dagaalkii ugu weynaa ee Islaamka.\n\nIska hor imaadka ayaa Muslimiintii si adag ugu guulaysteen, waxaana la dilay dhowr ka mid ah dabadhilifyadii Quraysh. Qur’aanku waxa uu guusha u dhigay calaamad, ma aha oo kaliya geesinimo: “Ilaahay mar hore ayuu idiinku guuleeyey Badar idinkoo tabaryar, ee ka cabsada Eebbe waxaad u dhawdihiin inaad shukridaan” (Qur’an 3:123), wuxuuna qeexayaa gargaarka malaa’igta (Qur’an 3:124-125). Badar waxay aasaastay beesha da'yarta oo ah awood dhab ah oo ku taal Carabta.\n\nCasharka: Natiijooyinka waxaa iska leh Allaah, ma aha tirooyin ama qalab. Badar waxa lagu xusuustaa “maalintii kala-saaridda” (yawm al-furqaan), maalinta runta iyo beenta la kala saari jiray – taas oo daliil u ah in Eebbe si dhab ah loogu talo-saarto dadaal dhab ah ay tahay waxa mudan. Dib u noqoshada Uxud sanadka soo socda ayaa dhigi doona casharka dhammaystirka ah.",
    location: "Badar",
  },
  {
    title: "Dagaalkii Uxud",
    body: "Badar sannad ka dib, Qureysh waxay u soo noqotay aargoosi iyo ciidan aad u tiro badan, waxayna labada dhinac ku kulmeen buurta Uxud salkeeda oo Madiina u dhow. Nabigu ﷺ wuxuu dul dhigay buur konton qaansoley ah oo uu si adag ugu amray in aysan ka tagin booskooda, wax kasta oo dhacay. Bilowgii dagaalka waxaa gacanta sare lahaa Muslimiinta; laakiin markii ay arkeen cadawgii oo cararaya ayay qaansoleydii badankoodu ka tageen booskoodii si ay wax u urursadaan. Fardooleydii Qureysh ee uu hoggaaminayey Khaalid bin Al-Walid (oo aan weli Muslimin) ayaa dhinacii dacalka ahaa ku wareegay, mawjaddaasi waxay isu beddeshay maalin qaali ah oo xanuun badan.\n\nWaxaa ku shahiiday saxaabo badan oo uu ka mid ahaa xabiibkii nabiga adeerkiis Xamzah (Alle haka raali noqdee) “Libaaxa Alle”. Nabiga ﷺ laftiisu wuu dhaawacmay, iliggiisii ​​waa jabeen, wejiguna dhiig baa ka da’ay. Ka dib Qur'aanku wuxuu si run ah uga hadlay dib u dhacaas, isagoo ku macneeyay inay tahay imtixaan iyo cawaaqib ka dhashay amar diidid iyo damac adduunyo (Qur'aanka 3:152, 3:165-166).\n\nCasharka: Uxud waa casharka ugu wayn xagga edebta iyo addeecidda. Hal fal anshax-darro ah, haba yaraatee, waxay u ekayd, guul-ku-dhawaad. Haddana Eebbe kama uu tegin iyaga - wuu baray, wuu cafiyey, wuuna ururiyey. Guuldarada, si daacad ah loo wajaho, waxay noqon kartaa mid wax barasho ka badan guusha.",
    location: "Buurta Uxud",
  },
  {
    title: "Dagaalkii Qodabka",
    body: "Sannadkii shanaad, isbahaysi Qureysh, qabiilo kale oo Carab ah, iyo kooxihii colka ahaa - \"Confederates\" (al-Axzab) - waxay soo ururiyeen ciidamadii ugu badnaa ee weli Carabta lagu arko, laga yaabee toban kun oo xoog ah, si ay u burburiyaan Madiina hal mar. Isaga oo la kulmaya cadaw aad u weyn oo aan ku kulmi karin dagaal furan, Nebigu (scw) waxa uu aqbalay talada saxaabiga Faaris ee Salmaan Al-Fariisi (Alle haka raali noqdee) ee ahaa in uu dhufeys ballaadhan ka qodo waddooyinka woqooyi ee magaalada loo soo galo - xeeladdaas oo aanay Carabtu waligood la kulmin.\n\nQodabka ayaa hakiyay go'doominta. Toddobaadyo qabow, gaajo iyo cabsi ayaa daba socotay, Quraankuna wuxuu si cad u qeexayaa imtixaamkii Mu'miniinta ee suuradda Al-Axzaab: \"...markay indhuhu gariireen cabsi, qalbiguna uu gaadhay dhuunta\" (Qur'aanka 33:10). Ugu dambayntiina dabaylo aad u kulul iyo isqabqabsi gudaha ah ayaa kala firdhiyey ciidankii gaashaanbuurta ahaa, wayna ka baxeen iyagoon dagaal ka dhicin. Qur'aanku wuxuu ammaanay samatabbixinta Eebbe, kaasoo \"ku soo diray dabayl iyo ciidan aydaan arkin\" (Qur'aanka 33:9).\n\nCasharka: la tashi xigmad leh (shura) iyo furfurnaanta fikradaha wanaagsan ee qof kasta - halkan, injineernimada shisheeye - waa qayb iimaanka. Oo markii dadaalka bani'aadamku si buuxda loo bixiyo, samatabbixintu waxay weli ka timaadaa xagga Eebbe. Go'doomintan jabtay waxay si wax ku ool ah u soo afjartay awooddii Quraysh ay ku qaadi lahayd weerarka.",
    location: "Madiina",
  },
  {
    title: "Heshiiskii Xudeybiyah",
    body: 'Sannadkii lixaad ayuu Nebigu (scw) la baxay ilaa 1,400 oo saxaabi si ay u soo gutaan cumrada, ma aha inay dagaallamaan, iyagoo galay xaaladdii ixraamka si uu u caddeeyo niyadda nabadda. Qureysh waxay ku dhufatay meel Xudeybiyah la yiraahdo oo xaramka qarkeeda ku taal. gorgortan adag ka dib waxaa lagu heshiiyey heshiis toban sano ah oo lagu heshiiyey shuruudo u ekaa, saxaabo badan, oo bahdilayey: Muslimiintu sanadkaa dib bay u noqonayaan oo soo socdaa; Qof kasta oo Qureysh uga carara Muslimiinta waa loo soo celinayaa, laakiin ma noqonayso mid kale.\n\nHaddana Eebbe soo noqodkiisii ​​wuxuu daaha ka qaaday in heshiiskani yahay "guul cad" (Qur\'aanka 48:1, suuradda al-Fath). Asxaabtu markii dambe waxay yiraahdeen weligood ma arkin guul ka weyn - sababtoo ah nabadda ka dib, dadku si xor ah ayaa isku qasan, farriinta si deggan bay u maqleen, oo waxay soo galeen Islaamka tiro aad uga badan sannadihii dagaalka; Al-Baraa bin Caziib warbixintiisa ku saabsan arrintan waxay ku qoran tahay Saxiixul Bukhaari 4606. Xabbad-joojintu waxay kaloo si maldahan u aqoonsatay Muslimiinta inay yihiin awood siman.\n\nCasharka: waxa u eg dib u dhac ayaa noqon kara furitaanka ugu weyn. Rasuulku ﷺ wuxuu u doortay khasaare muuqata oo waqti-gaaban ah wanaag muddada dheer ah, wuxuuna sharfay baayacmushtar adag xitaa markuu kufsado. Dulqaadka, is-xakamaynta iyo ilaalinta ereyada waxay gaari karaan wax aan iska horimaadku dhici karin.',
    location: "Xudeybiyah",
  },
  {
    title: "Waraaqihii loo diray boqorrada",
    body: 'Ka dib markii heshiiskii Xudeybiyah uu Muslimiinta siiyay fasax dagaalka ka, Nebigu ﷺ wuxuu feejignaantiisa u jeediyay Carabta ka baxsan. Qiyaastii sannadkii lixaad ilaa toddobaad ee Hijradda, wuxuu diray saxaabo la aamin yahay iyagoo ah wafdi, mid kastaana sitay warqad ku shaabadaysan kaatunkiisa, isagoo ku casuumaya boqorrada waaweyn ee wakhtigaas inay Islaam noqdaan: Heraclius, Boqorka Bysantine; Khosrow II, Boqorka Faaris; al-Muqawqis, taliyaha Bysantine ee Masar; Najaashigii Xabashida, oo horeba u magangaliyey Muslimiinta u haajiray; iyo boqorrada Baxreyn iyo Cumaan.\n\nWarqaddii Heraclius waxay ku dhawaaqday ereykiiba erey ku jira suugaanta xadiiska: "Waxaan kugu casumayaa Islaamka. Islaam noqo, waxaad ammaan noqonaysaa... Islaam noqo, Eebbe wuxuu ku siin doonaa abaal laba jibbaaran ah" (Saxiixul Bukhaari 7). Warbixintaas oo kale waxay sidoo kale ilaalisay wadaxaajoodkii dheeraa ee Heraclius uu la yeeshay ganacsade Makkaawi ah oo la yiraahdo Abuu Sufyaan - oo weli gaal ahaa - isagoo weydiiyay abtirsiinyo iyo dabeecadda Nebiga ﷺ, wuxuuna ka soo gaaray jawaabihii daacadda ahaa in sifooyinkaas la mid yihii nebi run ah, in kastoo aanu ku dhaqmin qancintaas. Khosrow, taas oo iska horjeedda, waxaa lagu xusaa siiradda inuu warqaddii cadho ku dildilaacshay, halka Najaashigu uu wafdigiisa sharaf ku ansixiyey.\n\nCasharka: hawlgalka Rasuulkii ugu dambeeyay waligiis kuma koobnayn Carabta - marka Madiina ammaan noqotay, casuunku wuxuu u baxay dunidii la aqoonsan oo dhan, sida Quraanku u sheegayo in la diray isaga "dadka oo dhan" (Qur\'aanka 34:28). Boqorro qaar si daacad ah bay u dhagaysteen, qaarna si edeb leh bay ugu jawaabeen, qaarna kibir - jawaab kastana waxay sii sheegtay sida boqortooyooyinkoodu ay markii dambe ula kulmi lahaayeen Islaamka.',
    location: "Madiina",
  },
  {
    title: "Safarkii Khaybar",
    body: "Wax yar ka dib Xudeybiyah, nabigu ﷺ wuxuu u jeestay Khaybar, oo ah dhul hodan ah oo dhufaysyo adag ku leh waqooyiga Madiina. Khaybar waxa uu noqday saldhig colaadeed – oo ay degan yihiin qabaa’il gacan ka geystay abaabulka go’doomintii Confederaterna ee Madiina oo sii waday dhagarta ka dhanka ah bulshada Muslimiinta. Ololaha ayaa looga dan lahaa in lagu soo afjaro khatartaas.\n\nDagaal adag ka dib, qalcadaha ayaa midba midka kale u dhacay; Calankii maalinta qiyaamaha lahaa waxaa la siiyay Cali bin Abii Daalib (Alle haka raalli noqdee). Dabadeed nabigu ﷺ wuxuu u oggolaaday dadkii degganaa inay sii joogaan oo ay sii wadaan tacbashada dhulka si ay ugu beddelaan qayb ka mid ah wax soo saarkiisa - nidaam sugayay cunto iyo xasillooni Madiina halkii qof walba laga eryi lahaa. Sidoo kale, halkan ayay haweenay isku dayday inay neef ido ah ku sumayso, taasoo looga digay.\n\nCasharka: Nabadgelyada iyo ilaalinta heshiisyada ayaa wada socday. Falkaasi wuxuu ahaa mid liddi ku ah awood cadawtinimo oo la caddeeyey, haddana waxay ku dhammaatay is-afgarad laga shaqayn karo oo kuwii laga adkaaday u oggolaadeen inay noloshooda ilaashadaan. Xooga Islaamku waxa loola jeedaa in la dhiso badbaado iyo caddaalad, ee maaha in la baabi'iyo.",
    location: "Khaybar",
  },
  {
    title: "Cumradii dib loo sameeyay (Cumrat al-Qadaa)",
    body: "Heshiiskii Xudeybiyah wuxuu ka celiyay Muslimiinta cumrada sannadkii lixaad ee Hijradda, isagoo balan qaaday inay soo noqon karaan sannadka soo socda. Bishii Dhul-Qacda ee sannadkii toddobaad ee Hijradda, sida sida loo heshiiyey, Nebigu ﷺ wuxuu horseeday ku dhawaad laba kun oo saxaabi si ay ugu noqdaan Makkah oo ay u wataan xajkii laga diiday - taasoo loo yaqaan Cumrat al-Qadaa, cumrada 'dib-u-samaynta' (halka ilo qaarna loogu yeero Cumrat al-Qisaas).\n\nQureysh, iyagoo sharfaya qaybtoodii heshiiska, waxay magaalada ka baxeen saddex maalmood si Muslimiintu u sameeyaan cibaadooyinkooda si nabdoon, iyagoo ka fiirinaya buuraha ku wareegsan siday bulshadii mar loo saaray ay hadda ku wareegto Kacbada si ammaan ah oo dhamaystiran. Waxaa xilligan booqashadan ah, adeerkii Nebiga ﷺ, al-Cabbaas, uu qabsooma guurkiisii ​​Maymuunah bint al-Haarith, dhowr Makkaawi ah oo arkay daacadnimada iyo nidaamka xujaajta ayaana si run ah la taabtay wixii ay arkeen.\n\nCasharka: balan la oofiyay waa nooc dacwad ah. Meeshii labaatan sano wacdi ku guuldareysatay inay qalbiyada dhaliliso, hal cumro nabdoon oo sharaf leh - oo ah midhihii toosan ee \"guushii cad\" ee Xudeybiyah (Qur'aanka 48:1) - waxay dhaliisay qalbiyo aan xoogu weligiis taaban karin. Booqashadan aamusan ayaa ka caawisay in la dhiso jidka loogu talagalay in Makkah dib-u-dhac dhiig ah la'aan sannadka soo socda lagu qabsado.",
    location: "Makkah",
  },
  {
    title: "Qabashadii Makkah",
    body: 'Markii xulafadii Qureysh ay jebiyeen shuruudihii Xudeybiyah oo ay weerar ku qaadeen qabiil ay isbahaysi la ahaayeen Muslimiinta, waxaa meesha ka baxay xabbad joojintii. Bishii Ramadaan ee sannadkii siddeedaad ayuu Nebigu ﷺ ku dhaqaaqay Makkah isagoo wata ciidan gaaraya toban kun - oo ahaa ciidankii ugu badnaa - iyo magaaladii silica, qaadacday, iyo dagaalka ka soo horjeeday labaatan sano ayaa isdhiibay iyadoo aan wax dhiig ah ku daadan.\n\nIsaga oo ugu dambayntii ka adkaaday dadkii ka saaray, ayuu reer Makana weydiiyey waxa ay ka filayaan. Waxay u rajeeyeen naxariis walaal oo akhyaar ah, wuxuuna ugu jawaabay hadalkii Yuusuf walaalihiis: “Maanta dambi kuguma taal”—wuxuuna ku dhawaaqay: “Taga adigaa xor ah”. Waxa uu galay Kacbada oo uu ka saaray 360 sanam oo ay ku jirtay, isaga oo akhrinaya "xaqii baa yimid, baadilkiina waa la waayay" (Qur\'aanka 17:81), isagoo soo celinaya macbudkii Ibraahiim cibaadadii Alle ee daahirka ahayd. Suuradda An-Nasr (Qur\'aanka 110) waxay ka hadlaysaa xilligan marka dadku "ku soo galaan diinta Eebbe iyagoo tiro badan."\n\nCasharka: kani waa meesha ugu sarraysa ee naxariista nebiyada iyo dembi-dhaafka. Isaga oo leh awood buuxda oo uu kaga aargoosan karo, ayuu cafiyay. Mu’minku waxa uu bartaa in kuwa xoogga leh ay yihiin kuwa cafiya marka ay awoodaan in ay ciqaabaan, ujeedaduna waligood ma ahayn aargoosi ee waa hanuun.',
    location: "Makkah",
  },
  {
    title: "Dagaalkii Xunayn",
    body: "Dhowr toddobaad ka dib qabashadii nabdoon ee Makkah, isbahaysigii qabiillada Hawaasin iyo Thaqiif - oo ka welwelsanaa kacdoonka lama filaanka ah ee awoodda Muslimiinta oo go'aan ku qaatay inay ku dagaallamaan ilaa xagga ugu dambeeya - waxay soo ururiyeen ciidan weyn, iyagoo la keenay qoysaskooda, xoolahooda, iyo maalkooda, waxayna la kulmeen ciidankii aad uga weynaa ee Nebiga ﷺ dooxada cidhiidhiga ah ee Xunayn oo u dhaxaysa Makkah iyo Taa'if.\n\nHawaasin waxay qariyeen qaansoole gudaha mareegaha, markay bilaabeen inay tuur si lama filaan ah barqadii, ciidankii hore ee Muslimiinta ayaa kala jabay oo kala firdhay; ilbiriqsi ayay u muuqatay in ciidankii ugu weynaa ee Muslimiinta abid soo ururshay ay ku fiicnaan lahayd yaab kaliya. Quraanku wuxuu si sax ah u qeexayaa isbeddelkan: \"...iyo maalintii Xunayn, markii tirakoodii badnayd aan waxba idiin taraysay, dhulkiina aad wanaagsanaanteeda oo dhan idiin ciriiryeeyay, markaas aad dib ugu jeesateen carar\" (Qur'aanka 9:25). Nebigu ﷺ qudhiisu wuxuu adkaystay, wuxuuna amray adeerkiisa al-Cabbaas inuu magacooda ugu dhawaaqo Ansaarka iyo qabiilooyinka Madiina; qaylada taasi waxay saxaabadii dib u soo celisay, waxayna dib u abaabuleen, dagaalkuna wuxuu u rogmaday guul cad oo Muslimiin ah, oo Quraanku u aaneeyo xasilloonida iyo gargaarka aan la arki karin ee Eebbe soo diray (Qur'aanka 9:26).\n\nCasharka: tiro iyo qalab dagaal ma go'aamiyaan natiijada dagaal - Badar ayaa horeba u baray casharkaas ciidan yar, Xunayn wuxuuna muujiyay taariikhda ka soo horjeeda, in xitaa ciidan weyn uu kufi karo haddii uusan lahayn gargaarka Eebbe iyo nidaamka goobta dagaalka. Ka dib, maalkii badnaa ee la qabsaday ayaa si deeqsinimo leh loo qaybiyay, oo ay ku jireen musharaxiinta cusub ee Makkah, si loo helo qalbiyada oo aan ahaan kaydinta maalka.",
    location: "Xunayn",
  },
  {
    title: "Socdaalkii Tabuuk",
    body: "Sannadkii sagaalaad, waxaa Madiina soo gaaray warbixinno ku saabsan abaabulka Byzantine (Roman) ee suurtagalka ah ee soohdinta waqooyi. Kuleyl aad u kulul oo xagaa ah, markii beergoosku bislaaday, safarkuna ahaa mid dheer oo adag, Nebigu ﷺ wuxuu u yeedhay ciidankii ugu badnaa ee uu abid hoggaamiyo - laga yaabee soddon kun - inay u socdaan xagga woqooyi ilaa Tabuuk. Tani waxay ahayd \"saacaddii dhibka\" (Qur'aanka 9:117), oo waxay tijaabisay daacadnimada si aan hore loo arag.\n\nDagaal ma dhicin; tusmada go'aanka ayaa ku filan, dhowr madax oo reer waqooyi ah ayaa heshiis la galay Madiina. Laakin ololaha waxaa lagu xusuustaa wax kasta oo uu muujiyey quluubta dadka. Qur’aanku wax badan oo ka mid ah suuradda At-Tawbah waxa uu ku soo qaatay – isaga oo ammaanaya kuwa wax walba siiyey (Abuu Bakar waxa la wariyey in uu bixiyey maalkiisii ​​oo dhan), waxa uu bannaanka soo dhigay munaafiqiinta marmarsiyo ka dhigtay in ay sii joogaan, waxa kale oo uu ka sheekeeyey qiso dhab ah oo saddexdii mu’miniinta ah oo uu ka mid ahaa Kacab ibnu Maalik, kuwaas oo si dhab ah u qirtay in aanay wax cudur daar ah haysan oo loo cafiyey imtixaan adag ka dib (18).\n\nCasharka: addeeciddu way fududahay marka ay raaxo leedahay; runteedu waxay muujinaysaa marka ay qaali tahay. Tabuuk wuxuu ka soocay kuwa daacadda ah cudurdaar-sameeyayaasha wuxuuna calaamadeeyay dhammaadka wax ku oolka ah ee iska caabinnimada sanamyada abaabulan ee Carabta. Daacadnimada - xitaa daacadnimada qirashada guul-darrada - waa dariiqa dib loogu noqonayo Alle.",
    location: "Tabuuk",
  },
  {
    title: "Sannadkii Wufuudka (Caam al-Wufuud)",
    body: "Sannadkii sagaalaad ee Hijradda, ka dib qabashadii Makkah iyo muujinta xoogga ee Tabuuk, qabiilooyinka Carabta waxay fahmeen in iska caabinta nidaamka cusub aysan hadda ahayn wax macquul ah. Wufuud ka dib wufuud - oo ka socda Bani Tamiim, Bani Caamir, qabiilooyinka Yemen, iyo kuwo kale oo badan - waxay yimaadeen Madiina si ay u sheegtaan aqbalkoodii Islaamka iyo daacadnimadooda Nebiga ﷺ, tiro badan oo tan kama yaraan, taasoo keentay in sannadkani lagu xusuusto siiradda inuu yahay Caam al-Wufuud, Sannadkii Wufuudka.\n\nNebigu ﷺ wuxuu koox kasta ku qaabilay marti-galinta iyo waxbarasho dulqaad leh, isagoo ku celiyay saxaabo la socda si ay ugu bareen dadkooda Quraanka iyo salaadda halkii uu u diri lahaa taliyayaal xoog ku talin lahaa. Quraanku wuxuu si toos ah ugala hadlayaa xilligan suuradda An-Nasr: \"Marka Eebbe timaado gargaarkiisa iyo guushu, oo aad aragto dadka oo galaya diinta Eebbe kooxo kooxo ah, markaas ku ammaan Rabbigaa oo dambidhaaf weyddiiso\" (Qur'aanka 110:1-3) - suurad saxaabadu, sida Ibnu Cabbaas ugu sharraxay Cumar, ay u fahmeen calaamad tilmaamaysa in nolosha Nebiga ﷺ ay ku dhawaanayso dhammaadkeeda (Saxiixul Bukhaari 4430).\n\nCasharka: ka dib tobanaan sano oo farriintii lagu diiday inta badan iyo lagu aqbalay tiro yar, ballankii Eebbe waxa uu yimid mar keliya - casharo ku saabsan dulqaadka iyo akhriska saxda ah ee guusha. Jawaabta suuradda An-Nasr ee guusha ma ahan dabaaldeg ee waa ammaan iyo tuubaad, tusaale u ah sida mu'mimku ula kulmi lahaa guul kasta oo nolosha. Tani waxay dejinaysaa dhawaaqa Xajkii Sagootinta ee ku xiga.",
    location: "Madiina",
  },
  {
    title: "Xajka sagootinta",
    body: 'Sannadkii tobnaad ee Nebigu (scw) waxa uu guday xajkiisii ​​kaliya ee dhamaystiran, oo ay ku biireen in ka badan boqol kun oo saxaabi ah, isaga oo qof ahaan u baray cibaadada. Isagoo taagan bannaanka Carrafo ayuu ka jeediyay khudbaddii sagootinta (Khutbat al-Wadaac), taasoo kooban oo ku saabsan wax kasta oo Islaamku u yimid inuu dhidbo.\n\nWaxa uu ku dhawaaqay xurmada qof kasta naftiisa, maalkiisa iyo sharaftiisa - "dhiiggiina iyo maalkiinu waa xurmada maanta, bishan, dhulkan" (Saxiix Al-Bukhaari 1741). Wuxuu meesha ka saaray khilaafkii dhiigga iyo danta (ribada) ee Jaahiliga, wuxuuna faray in haweenka loo wanajiyo ammaan Alle ka timid, wuxuuna xusuusiyay inuusan Carab Carab ahayn uusan ka sareyn cibaado mooyee, wuxuuna u sheegay inay Qur’aanka ku dhegaan. Waxay ahayd xajkan, maalintii Carafa oo ku beegnayd maalin Jimce ah, markuu Eebbe soo dajiyay "Maalintan waxaan idiin dhammeeyey diintiinna..." (Qur\'aanka 5:3) - Aayad Cumar ayaa xasuusisay oo si sax ah u taariikhaysay (Saxiix al-Bukhaari 45).\n\nCasharka: Khudbadda Sagootinta waa axdiga Islaamka ee sharafta aadanaha, caddaaladda iyo sinnaanta, kuna shaabadeeyey in diintu hadda dhammaystiran tahay. Mu\'minka hawshiisa halkan ka socotaa maaha inuu wax ku kordhiyo ee waa inuu noolaado.',
    location: "Carafa",
  },
  {
    title: "Dhicistiisa",
    body: 'Dhawr bilood ka dib xajkii sagootinta, nabigu ﷺ waxa ku dhacay qandho. Maalmihiisii ​​ugu dambeeyay ayuu ka codsaday xaaskiisii ​​in lagu nuujiyo qolka Caa’isha (Alle haka raalli noqdee), wuxuuna u magacaabay Abuu Bakar inuu tujiyo. Subixii u dambeeyay ayuu daaha dib u celiyay si uu u arko safafka mu’miniinta oo tukanaya oo dhoola cadeynaya, isaga oo ku faraxsan bulshadiisa, ka dibna ha soo dhaco. Wuxu dhintay maalin isniin ah, 12 Rabii al-Awwal 11 hijriyada, isagoo madaxiisu xabadka iyo gadhka Caa’isha dhexdooda taagan-sida ay iyada lafteedu ku warantay Saxiixul Bukhaari 4449/4451.\n\nMurugada Madiina waxay ahayd mid xad dhaaf ah, xitaa Cumar wuu diiday markii hore inuu aqbalo. Markaas buu Abuu Bakar kacay oo dhunkaday wejigii Nabiga, wuxuuna dadkii kula hadlay erayo bulshada oo dhan xasiliya oo ku sugan Saxiixul Bukhaari 1241/1242: "Ruuxii caabudi jiray Muxammad, Nabi Muxammadna wuu dhintay, ruuxii Alle caabudana Alle waa nool yahay mana dhiman." Wuxuu akhriyey "Maxammed ma aha waxaan Rasuul ahayn, waxaana tagay hortiis rasuullo" (Qur\'aanka 3:144).\n\nCasharkii: dhambaalku wuxuu ahaa mid dhammaystiran oo hadda ummadda iska leh. Nebigu ﷺ wuxuu ahaa bakhti, laakiin waxa uu keenay - Qur\'aanka iyo Sunnadiisa - maaha. Jawaabta Abuu Bakar waa jawaabta waarta ee murugada: ku xidhnaantayadu waa Alle oo aan dhiman, dariiqa loo jecel yahayna Nabiga ﷺ waa inaan ku noolaano hanuunkiisa.',
    location: "Madiina",
  },
];
