import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

// Indonesian translation overlay for the Seerah timeline. Mirrors the order of
// SEERAH_EVENTS in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, years and Hijri
// numbers stay in the English source.
export const SEERAH_EVENTS_ID: DeepPartial<SeerahEvent>[] = [
  {
    title: "Arab sebelum Islam (Zaman Jahiliyah)",
    body: "Untuk memahami Nabi ﷺ, kita perlu membayangkan terlebih dahulu dunia tempat beliau diutus. Jazirah Arab pada abad keenam adalah negeri suku-suku yang tersebar tanpa pemerintahan pusat, disatukan oleh garis keturunan, kehormatan, dan kesucian Ka'bah di Makkah — rumah ibadah yang dibangun oleh Ibrahim dan Isma'il untuk menyembah satu Tuhan, namun kini telah dikelilingi sekitar tiga ratus enam puluh berhala.\n\nMasa ini disebut Jahiliyah, \"zaman kebodohan\" — bukan karena orang Arab kurang cerdas (syair dan daya ingat mereka luar biasa), melainkan karena mereka tidak memiliki petunjuk. Permusuhan antarsuku bisa berlangsung turun-temurun, yang kuat menindas yang lemah, dan anak perempuan terkadang dikubur hidup-hidup karena rasa malu atau takut miskin — sebuah praktik yang kelak dikecam secara tegas oleh Al-Qur'an (Al-Qur'an 81:8–9). Di tengah penyembahan berhala, beberapa \"hunafa\" masih mencari tauhid murni ajaran Ibrahim, dan komunitas Yahudi serta Nasrani yang kecil tersebar di seluruh jazirah.\n\nPelajarannya: wahyu tidak turun ke ruang hampa, melainkan ke tengah masyarakat nyata yang penuh luka, dan hal pertama yang diperbaikinya adalah hubungan antara manusia dan Penciptanya. Ingatlah latar belakang ini seiring kisah ini bergulir — hampir setiap perbaikan yang dibawa Nabi ﷺ adalah jawaban langsung atas ketidakadilan zaman Jahiliyah.",
    location: "Jazirah Arab",
  },
  {
    title: "Kelahiran di Makkah",
    body: 'Nabi ﷺ lahir di Makkah pada Tahun Gajah (Am al-Fil), dinamai demikian karena pada tahun itu Abrahah, gubernur Habasyah untuk Yaman, memimpin pasukan bergajah untuk menghancurkan Ka\\\'bah namun secara ajaib dipukul mundur — peristiwa yang diabadikan Al-Qur\\\'an dalam Surah al-Fil (Al-Qur\\\'an 105). Pada tahun yang penuh makna ini, lahirlah seorang anak dari suku Quraisy, dari kabilah yang paling terhormat, Bani Hasyim.\\n\\nBeliau telah menjadi yatim sejak lahir: ayahnya, Abdullah, wafat beberapa bulan sebelumnya ketika sedang berdagang di negeri jauh. Ibunya, Aminah binti Wahb, menamainya Muhammad — "yang banyak dipuji" — sebuah nama yang hampir tidak dikenal di kalangan orang Arab. Sesuai kebiasaan Makkah, beliau dikirim untuk disusui dan dibesarkan di udara terbuka padang pasir bersama Bani Sa\\\'d, dalam asuhan Halimah as-Sa\\\'diyyah.\\n\\nPelajaran bagi seorang mukmin: kemuliaan di sisi Allah tidak ada kaitannya dengan jaminan duniawi. Rasul terakhir memulai hidupnya tanpa ayah dan tak lama kemudian juga tanpa ibu, namun Allah sendiri yang menjadi penjaganya — "Bukankah Dia mendapatimu sebagai yatim, lalu Dia melindungimu?" (Al-Qur\\\'an 93:6). Lihat juga "Wafatnya sang ibu" dan "Perwalian Abu Thalib" berikutnya.',
    location: "Makkah",
  },
  {
    title: "Wafatnya sang ibu",
    body: "Ketika beliau berusia sekitar enam tahun, Aminah membawa putranya mengunjungi kerabat mereka di Yatsrib (yang kelak menjadi Madinah) dan melihat makam ayahnya. Dalam perjalanan pulang, Aminah jatuh sakit dan wafat di sebuah tempat bernama Abwa', antara Makkah dan Madinah, dan dimakamkan di sana. Muhammad ﷺ yang masih kecil kini telah kehilangan kedua orang tuanya.\n\nBeliau dibawa kembali ke Makkah oleh Ummu Aiman, pelayan keluarga yang telah dimerdekakan, dan diasuh oleh kakeknya, Abdul Muthalib, pemimpin Quraisy yang disegani, yang sangat mencintainya dan biasa mendudukkannya di sisinya di dekat Ka'bah.\n\nPelajarannya: Nabi ﷺ merasakan, sejak dini dan berulang kali, duka yang dipikul begitu banyak manusia — kehilangan orang tercinta, keterlantaran, ketergantungan pada orang lain. Ini adalah bagian dari persiapan hidupnya. Hati yang pernah mengenal kehilangan adalah hati yang mampu merasakan penderitaan anak yatim, janda, dan orang asing, dan umatnya kelak dibangun di atas rahmat yang sama itu. Kisah ini berlanjut pada \"Tahun Kesedihan\".",
    location: "Abwa'",
  },
  {
    title: "Perwalian Abu Thalib",
    body: "Dua tahun setelah wafatnya sang ibu, kakeknya, Abdul Muthalib, juga wafat, ketika beliau berusia sekitar delapan tahun. Menjelang wafatnya, sang kakek mempercayakan cucu tercintanya kepada putranya, Abu Thalib, paman Nabi ﷺ dari pihak ayah. Meski Abu Thalib bukan orang kaya, ia menerima anak itu ke dalam rumahnya dan memperlakukannya seperti anak yang paling ia sayangi.\n\nAbu Thalib tetap menjadi pelindungnya selama lebih dari empat puluh tahun, bahkan sepanjang tahun-tahun penganiayaan terberat di Makkah. Dialah yang membawa Muhammad ﷺ muda dalam perjalanan dagang ke Syam, di mana — menurut riwayat yang masyhur — pendeta Bahira melihat tanda-tanda kenabian padanya (sebuah riwayat yang dipertahankan dalam sirah, meski rincinya diriwayatkan dengan tingkat kekuatan yang berbeda-beda).\n\nPelajarannya: Allah menempatkan orang-orang yang setia dan terhormat di sekeliling Nabi-Nya ﷺ pada setiap tahapan. Perlindungan Abu Thalib selama puluhan tahun adalah sebuah rahmat — pengingat bahwa membela kebenaran dan menjaga tali kekerabatan adalah kedudukan mulia bahkan bagi mereka yang belum beriman, dan bahwa kita harus menghormati orang-orang yang melindungi kita. Kehilangannya kelak, pada Tahun Kesedihan, akan mengubah segalanya.",
    location: "Makkah",
  },
  {
    title: "Pernikahan dengan Khadijah",
    body: 'Sebagai pemuda, Muhammad ﷺ meraih reputasi di seluruh Makkah yang tidak dapat dibeli dengan harta apa pun: al-Sadiq, yang jujur, dan al-Amin, yang tepercaya. Orang-orang menitipkan barang berharga mereka kepadanya dan sepenuhnya memercayai perkataannya, bahkan mereka yang menyembah tuhan-tuhan lain.\n\nKhadijah binti Khuwailid (semoga Allah meridainya), seorang pedagang Quraisy yang terhormat dan sukses, mempekerjakannya untuk memimpin kafilah dagangnya ke Syam. Terkesan oleh kejujuran dan akhlaknya, ia mengirimkan lamaran pernikahan melalui sahabatnya, Khaulah binti Hakim. Saat itu beliau berusia sekitar dua puluh lima tahun dan Khadijah sekitar empat puluh tahun; pernikahan mereka menjadi pernikahan yang penuh cinta mendalam dan kemitraan sejati. Khadijah melahirkan anak-anak beliau dan tetap menjadi satu-satunya istri beliau selama kurang lebih dua puluh lima tahun, hingga wafatnya.\n\nPelajarannya: akhlak adalah fondasi dari segala yang mengikutinya. Jauh sebelum disebut nabi, Makkah telah mengenalnya sebagai orang paling jujur di antara mereka — itulah sebabnya, pada wahyu pertama, kepercayaan Khadijah yang seketika kepadanya begitu menentukan (lihat "Wahyu pertama"). Kejujuran seorang mukmin dalam urusan sehari-hari itu sendiri adalah bentuk dakwah.',
    location: "Makkah",
  },
  {
    title: "Hilful Fudhul dan Hajar Aswad",
    body: "Dua peristiwa dari kehidupannya sebelum kenabian menunjukkan nilai-nilai yang kelak akan beliau bangun menjadi sebuah bangsa. Pertama, Hilful Fudhul: sebuah perjanjian sakral yang disumpahkan oleh beberapa kabilah Quraisy untuk membela siapa pun yang tertindas di Makkah, baik penduduk asli maupun pendatang, hingga hak mereka dikembalikan. Nabi ﷺ turut serta dan kelak bersabda bahwa beliau akan tetap memenuhi perjanjian semacam itu bahkan dalam Islam — karena perjanjian itu menegakkan keadilan.\n\nKedua, pembangunan kembali Ka'bah setelah banjir. Ketika kabilah-kabilah hampir baku hantam memperebutkan kehormatan mengangkat Hajar Aswad ke tempatnya, mereka sepakat menerima keputusan orang pertama yang memasuki area itu — dan orang itu adalah Muhammad ﷺ. Penyelesaiannya terkenal karena kebijaksanaannya: beliau meletakkan batu itu di atas selembar kain dan meminta pemimpin setiap kabilah mengangkat satu sudutnya, lalu dengan tangannya sendiri beliau menaruhnya ke tempatnya, sehingga semua ikut serta dalam kehormatan itu dan tak seorang pun merasa direndahkan.\n\nPelajarannya: keadilan dan penyelesaian konflik sudah menjadi naluri beliau bahkan sebelum wahyu menegaskannya. Seorang mukmin adalah orang yang membela yang teraniaya dan mencari cara untuk mempersatukan, bukan memecah belah — Hilful Fudhul adalah bayangan awal dari masyarakat adil yang kelak beliau dirikan setelah Hijrah.",
    location: "Makkah",
  },
  {
    title: "Wahyu pertama",
    body: 'Menjelang akhir usia tiga puluhan, Nabi ﷺ semakin sering mengasingkan diri untuk beribadah dan merenung di Gua Hira di Jabal an-Nur, luar kota Makkah. Di sanalah, pada usia sekitar empat puluh tahun, di bulan Ramadan, malaikat Jibril datang dan memerintahkan: "Bacalah!" Beliau menjawab bahwa beliau tidak bisa membaca; malaikat itu mendekapnya erat sebanyak tiga kali dan menurunkan ayat-ayat pembuka Surah al-\\\'Alaq — "Bacalah dengan nama Tuhanmu yang menciptakan…" (Al-Qur\\\'an 96:1–5), kata-kata pertama Al-Qur\\\'an.\\n\\nBeliau pulang dalam keadaan menggigil, dan Khadijah menyelimutinya serta menenangkannya dengan kata-kata yang menyingkap keimanannya dan akhlak beliau: Allah tidak akan pernah menghinakannya, karena beliau menyambung tali silaturahmi, menanggung beban orang lain, dan menolong mereka yang berhak dibantu. Khadijah membawanya menemui sepupunya, Waraqah bin Naufal, seorang tua yang mendalami kitab-kitab terdahulu, yang mengenali bahwa yang datang itu adalah "Namus" (malaikat) yang sama yang pernah datang kepada Musa, dan memberitahunya bahwa ini adalah kenabian yang telah dijanjikan. Seluruh kisah ini tercatat dalam Shahih al-Bukhari 3.\\n\\nPelajarannya: wahyu dimulai bukan dengan klaim kekuasaan, melainkan dengan kata "Bacalah" — sebuah agama yang dibangun di atas ilmu dan kerendahan hati. Dan perhatikan siapa yang pertama beriman: seorang istri dan sebuah rumah tangga yang jujur. Kebenaran dikenali oleh mereka yang sudah lebih dahulu hidup dengan tulus.',
    location: "Gua Hira",
  },
  {
    title: "Tahun-tahun dakwah secara rahasia",
    body: 'Setelah wahyu-wahyu pertama turun, ada masa jeda (fatrah), lalu Allah memerintahkan Nabi ﷺ untuk mulai mengajak manusia menyembah-Nya semata. Selama kurang lebih tiga tahun pertama, seruan ini bersifat tenang dan pribadi — disampaikan kepada keluarga dekat dan sahabat tepercaya, bukan diserukan di jalanan.\\n\\nOrang-orang yang beriman paling awal, "as-Sabiqun al-Awwalun" (para pendahulu), berasal dari seluruh lapisan masyarakat: Khadijah, istrinya; sepupunya yang masih muda, Ali bin Abi Thalib; pelayannya yang telah dimerdekakan dan anak angkatnya, Zaid bin Haritsah; serta sahabatnya yang setia, Abu Bakar ash-Shiddiq (semoga Allah meridai mereka semua). Abu Bakar pada gilirannya membawa banyak orang lain memeluk Islam. Mereka berkumpul dan salat secara diam-diam, sering kali di rumah al-Arqam dekat Ka\\\'bah.\\n\\nPelajarannya: Islam tumbuh pertama kali melalui kepercayaan dan hubungan, bukan melalui pertunjukan. Perhatikan betapa luasnya kalangan hati-hati pertama itu — seorang perempuan kaya, seorang anak kecil, seorang budak yang telah dimerdekakan, seorang pedagang — sebuah gambaran awal dari sebuah keyakinan yang kelak akan menghapus perbedaan ras dan status. Dakwah dimulai dari lingkungan terdekat, dengan ketulusan dan kesabaran.',
    location: "Makkah",
  },
  {
    title: "Seruan Islam secara terang-terangan",
    body: 'Ketika Allah menurunkan ayat "Dan berilah peringatan kepada kerabat-kerabatmu yang terdekat" (Al-Qur\\\'an 26:214), Nabi ﷺ mendaki Bukit Shafa di dekat Ka\\\'bah dan menyerukan kepada kabilah-kabilah Quraisy. Beliau lebih dahulu bertanya apakah mereka akan mempercayainya bila beliau mengatakan ada pasukan bersembunyi di balik bukit; mereka menjawab bahwa mereka tidak pernah mendapatinya berdusta. Kemudian beliau memperingatkan mereka akan azab yang akan datang dan menyeru mereka untuk menyembah Allah semata.\\n\\nPesan terbuka ini mengguncang inti tatanan Makkah. Berhala-berhala itu bukan sekadar agama, tetapi juga mata pencaharian dan kehormatan — status kota sebagai penjaga rumah suci itu menarik jamaah haji dan perdagangan. Mengatakan bahwa berhala-berhala itu tidak berdaya sama saja dengan menantang ekonomi, garis keturunan, dan kebanggaan Quraisy sekaligus. Sejak saat itu penganiayaan meningkat tajam, menimpa paling keras kaum lemah dan budak di kalangan orang-orang beriman, seperti Bilal bin Rabah dan keluarga Yasir.\\n\\nPelajarannya: kebenaran yang disampaikan secara terang-terangan akan mengusik kepentingan yang telah mengakar. Nabi ﷺ pertama-tama meminta mereka bersaksi sendiri bahwa beliau jujur — akal sehat dan integritas sebelum ancaman — lalu tetap teguh. Berpegang pada tauhid bisa berharga mahal secara duniawi, sebagaimana yang dipelajari kaum mukmin Makkah. Kesulitan ini langsung membawa kita pada "Hijrah ke Habasyah".',
    location: "Bukit Shafa",
  },
  {
    title: "Hijrah ke Habasyah",
    body: "Ketika penganiayaan menjadi tak tertahankan, Nabi ﷺ memerintahkan sekelompok sahabatnya untuk mencari perlindungan kepada Najasyi, raja Nasrani yang adil di Habasyah (kini Ethiopia), dengan mengatakan bahwa di negerinya tidak ada seorang pun yang dizalimi. Rombongan pertama menyeberangi Laut Merah, diikuti oleh migrasi kedua yang lebih besar — hijrah pertama dalam Islam.\n\nKetika Quraisy mengirim utusan menuntut agar para pengungsi itu dikembalikan, Najasyi memanggil mereka menghadap. Ja'far bin Abi Thalib (semoga Allah meridainya) berbicara mewakili kaum muslimin, menjelaskan bagaimana mereka keluar dari kebodohan menuju sebuah keyakinan yang penuh kebenaran, rahmat, dan akhlak mulia, lalu membacakan ayat-ayat dari Surah Maryam tentang Isa dan ibunya. Raja Nasrani itu menangis, menggoreskan garis di tanah, dan berkata bahwa perbedaan antara keyakinannya dan keyakinan mereka tidak lebih lebar dari garis itu — dan ia menolak menyerahkan mereka.\n\nPelajarannya: ini adalah tonggak toleransi beragama dan membangun jembatan dengan Ahli Kitab yang tulus. Ini juga mengajarkan bahwa mencari keselamatan dari penindasan di bawah kekuasaan non-muslim yang adil sepenuhnya dibolehkan. Perhatikan juga bahwa argumen yang memenangkan keadaan itu adalah akhlak yang indah dan firman Allah yang dibacakan — bukan kekuatan senjata.",
    location: "Habasyah",
  },
  {
    title: "Pemboikotan Bani Hasyim",
    body: "Karena gagal menghentikan penyebaran Islam atau menjangkau Nabi ﷺ selagi kabilahnya melindunginya, para pemimpin Quraisy melakukan hukuman kolektif. Mereka menulis sebuah perjanjian dan menggantungkannya di Ka'bah, bersumpah akan memboikot seluruh kabilah Bani Hasyim (dan sekutu mereka Bani al-Muthalib): tidak ada pernikahan dengan mereka, tidak ada perdagangan, tidak ada pergaulan sosial, sampai mereka menyerahkan Muhammad ﷺ.\n\nSelama kurang lebih tiga tahun, kabilah itu — baik yang beriman maupun yang belum, sesama Bani Hasyim — terkurung di lembah pegunungan Syi'b Abi Thalib, menahan kelaparan yang begitu parah hingga tangisan anak-anak terdengar dan orang-orang memakan dedaunan. Boikot itu akhirnya runtuh ketika beberapa orang Quraisy yang berhati adil secara terbuka menolaknya dan lembaran perjanjian itu ditemukan telah rusak dimakan rayap, kecuali kata-kata yang memuat nama Allah.\n\nPelajarannya: kebatilan selalu melampaui batas. Kekejaman boikot itu justru menyingkap ketidakadilan para penindas dan mengukuhkan tekad kaum mukmin. Ini juga menunjukkan kemuliaan segelintir orang yang adil di tengah masyarakat yang bermusuhan, yang berani keluar dari barisan untuk mengakhiri sebuah kezaliman — pengingat bahwa hati nurani dapat bertahan bahkan di tengah perlawanan yang paling sengit.",
    location: "Syi'b Abi Thalib",
  },
  {
    title: "Tahun Kesedihan",
    body: 'Tak lama setelah boikot berakhir, Nabi ﷺ mengalami dua kehilangan yang menghancurkan dalam waktu singkat, dan tahun itu dikenal sebagai Am al-Huzn, Tahun Kesedihan. Pertama, pamannya sekaligus pelindungnya seumur hidup, Abu Thalib, wafat — orang yang kedudukannya telah melindunginya dari Quraisy selama puluhan tahun. Kemudian Khadijah (semoga Allah meridainya), istrinya selama kurang lebih dua puluh lima tahun, orang pertama yang beriman kepadanya dan penopang terdekatnya, juga wafat.\n\nDengan hilangnya perlindungan sosial dan sandaran batinnya sekaligus, Quraisy menjadi semakin berani dalam penganiayaan mereka. Pada masa inilah beliau pergi ke kota Thaif dengan harapan penduduknya mau menerima pesan itu; namun mereka justru mengusirnya dan menyuruh anak-anak melemparinya dengan batu hingga kakinya berdarah. Bahkan saat itu, ketika ditawari kehancuran kota tersebut, beliau justru berdoa agar keturunan mereka kelak menyembah Allah — sebuah kasih sayang yang menjadi ciri khas beliau.\n\nPelajarannya: bahkan para nabi diuji dengan kesedihan dan penolakan secara beruntun, dan jawabannya adalah kesabaran tanpa kepahitan. Kehilangan yang bersifat manusiawi bukan berarti ditinggalkan oleh Allah; kelegaan datang segera setelahnya, dalam perjalanan malam yang akan menyusul. Lihat "Isra dan Mikraj".',
    location: "Makkah",
  },
  {
    title: "Isra dan Mikraj",
    body: "Setelah Tahun Kesedihan, datanglah sebuah malam kehormatan yang luar biasa. Dalam Isra, Nabi ﷺ diperjalankan dalam satu malam dari Masjidil Haram di Makkah menuju Masjidil Aqsa di Yerusalem — peristiwa yang menjadi pembuka Surah al-Isra dalam Al-Qur'an (Al-Qur'an 17:1). Di sana beliau mengimami para nabi terdahulu dalam salat. Kemudian, dalam Mikraj, beliau diangkat melewati tujuh lapis langit, bertemu para nabi termasuk Adam, Musa, dan Ibrahim, dan mencapai kedudukan yang lebih dekat dengan Tuhannya daripada makhluk mana pun.\n\nHadiah utama malam itu adalah salat lima waktu. Sebagaimana tercatat dalam Shahih al-Bukhari 3887, salat itu mula-mula diwajibkan sebanyak lima puluh kali; atas saran Musa, Nabi ﷺ berulang kali kembali memohon keringanan hingga jumlahnya dikurangi menjadi lima dalam pelaksanaannya namun tetap membawa pahala lima puluh. Para ulama berbeda pendapat mengenai tanggal pastinya, kebanyakan menempatkannya pada tahun-tahun tepat sebelum Hijrah.\n\nPelajarannya: hadiah yang diberikan untuk menghibur seorang Nabi ﷺ yang sedang berduka adalah salat — perjalanan naik kita sendiri menuju Allah setiap malamnya. Salat lima waktu tidak diturunkan oleh malaikat ke bumi, melainkan diangkat naik ke langit untuk diterima, sebuah tanda betapa besarnya bobotnya dalam kehidupan seorang mukmin.",
    location: "Yerusalem",
  },
  {
    title: "Baiat Aqabah Pertama",
    body: "Setiap tahun para jamaah haji berkumpul di Makkah, dan Nabi ﷺ akan menyampaikan Islam kepada kabilah-kabilah yang berkunjung. Di sebuah tempat bernama al-Aqabah dekat Mina, sekelompok kecil orang dari Yatsrib (Madinah) — sebuah kota yang telah lama terpecah oleh permusuhan antara kabilah Aus dan Khazraj, dan telah mengenal tauhid melalui komunitas Yahudinya — mendengarkan, beriman, dan membawa pulang pesan itu.\n\nPada musim berikutnya, dua belas orang dari mereka kembali dan mengucapkan Baiat Aqabah Pertama: untuk menyembah Allah semata, tidak mencuri, tidak berzina, tidak membunuh anak, dan menaati Nabi ﷺ dalam kebaikan. Beliau kemudian mengutus sahabat muda Mush'ab bin Umair (semoga Allah meridainya) untuk kembali bersama mereka sebagai guru dan duta pertama Islam, dan melaluinya, iman menyebar dengan cepat ke rumah-rumah di Yatsrib.\n\nPelajarannya: pintu yang tampak tertutup di Makkah terbuka di Madinah. Perhatikan bagaimana komunitas itu dibangun — melalui pendidikan. Seorang guru muda yang berdedikasi, diutus bersama Al-Qur'an, mempersiapkan seluruh kota untuk menjadi tempat lahirnya Islam. Ini secara langsung membuka jalan bagi Baiat Kedua dan Hijrah.",
    location: "Mina",
  },
  {
    title: "Baiat Aqabah Kedua",
    body: 'Setahun setelah baiat pertama, sebuah delegasi yang jauh lebih besar dari Yatsrib — tujuh puluh tiga pria dan dua wanita — datang secara diam-diam menemui Nabi ﷺ di al-Aqabah selama musim haji. Kali ini komitmen mereka melangkah lebih jauh: mereka berjanji akan melindungi beliau persis seperti mereka melindungi istri dan anak-anak mereka sendiri, dan akan menerima kaum muslimin Makkah yang teraniaya ke kota mereka.\n\nIni adalah titik balik yang menentukan. Untuk pertama kalinya, komunitas yang masih muda ini memiliki tanah air dan sekelompok orang yang bersumpah untuk membelanya. Menyadari bahaya yang ada, Nabi ﷺ secara diam-diam mengarahkan para sahabatnya di Makkah untuk mulai berhijrah ke Yatsrib dalam kelompok-kelompok kecil agar tidak menimbulkan kewaspadaan Quraisy.\n\nPelajarannya: komitmen yang tulus membawa tanggung jawab. Kaum Anshar ("Para Penolong" dari Madinah) mempertaruhkan nyawa dan rumah mereka sebelum mereka memperoleh apa pun, semata-mata demi keyakinan mereka. Kemurahan hati mereka kelak menjadi teladan persaudaraan dalam Islam — dikenang dalam "Hijrah ke Madinah" berikutnya, tempat mereka menyambut para muhajirin layaknya keluarga sendiri.',
    location: "Mina",
  },
  {
    title: "Hijrah ke Madinah",
    body: "Ketika Quraisy berkomplot untuk membunuh Nabi ﷺ, Allah mengizinkan beliau untuk berhijrah. Beliau berangkat bersama sahabat terdekatnya, Abu Bakar (semoga Allah meridainya), dengan meninggalkan Ali di tempat tidurnya untuk mengembalikan barang-barang titipan orang-orang. Keduanya bersembunyi selama tiga malam di Gua Tsur ketika para pengejar sudah begitu dekat hingga Abu Bakar mengkhawatirkan keselamatan mereka — dan Nabi ﷺ menenangkannya, \"Bagaimana pendapatmu tentang dua orang yang ketiganya adalah Allah?\" Momen ini tercatat dalam Shahih al-Bukhari 3653 dan bergema dalam Al-Qur'an: \"…yang kedua dari dua orang ketika keduanya berada di dalam gua, ketika dia berkata kepada sahabatnya, 'Jangan bersedih, sesungguhnya Allah bersama kita'\" (Al-Qur'an 9:40).\n\nMereka tiba di Quba, tempat masjid pertama dibangun, lalu memasuki Yatsrib — yang sejak itu disebut al-Madinah al-Munawwarah, \"Kota yang Bercahaya\". Nabi ﷺ mempersaudarakan setiap muhajir dengan seorang anshar dalam ikatan persaudaraan; kemurahan hati mereka begitu sempurna hingga Sa'd bin Rabi' menawarkan untuk membagi separuh hartanya dengan Abdurrahman bin Auf, yang justru hanya meminta ditunjukkan ke pasar (Shahih al-Bukhari 3780/3906).\n\nHijrah begitu penting hingga Umar kelak menjadikannya awal penanggalan Islam — tahun 1 Hijriah. Pelajarannya: terkadang keimanan menuntut kita meninggalkan segalanya demi Allah, dengan keyakinan bahwa Dia bersama orang-orang yang tulus, dan membangun kembali di atas persaudaraan, bukan hubungan darah.",
    location: "Madinah",
  },
  {
    title: "Piagam Madinah",
    body: 'Tiba di sebuah kota yang telah hancur oleh perang antarsuku, Nabi ﷺ tidak sekadar memimpin kaum muslimin — beliau mendirikan sebuah komunitas. Beliau menyusun sebuah perjanjian tertulis, yang terpelihara dalam sirah Ibnu Ishaq dan dikenal sebagai Shahifah atau Piagam Madinah, yang mengikat kaum Muhajirin, Anshar, dan kabilah-kabilah Yahudi di kota itu dalam satu perjanjian pertahanan bersama.\n\nKetentuan-ketentuannya luar biasa untuk zamannya: semua pihak membentuk "satu umat" untuk tujuan perjanjian tersebut, setiap kelompok mempertahankan agamanya masing-masing, perselisihan harus diserahkan kepada Nabi ﷺ, permusuhan dan ketidakadilan dilarang, dan semua pihak berjanji membela kota itu dari serangan luar. Perjanjian ini secara efektif menjadikan Madinah sebuah negara-kota dengan hak dan kewajiban yang disepakati bersama, bukan permusuhan darah yang tiada akhir.\n\nPelajarannya: Islam bukan hanya ibadah pribadi, tetapi juga penataan masyarakat yang adil. Nabi ﷺ mencontohkan hidup berdampingan secara majemuk, supremasi hukum yang disepakati bersama di atas dendam antarsuku, dan menepati perjanjian — prinsip-prinsip yang akan diuji pada tahun-tahun konflik yang akan datang. Ini melengkapi persaudaraan dalam "Hijrah ke Madinah" dengan memperluas keadilan ke seluruh kota.',
    location: "Madinah",
  },
  {
    title: "Perang Badar",
    body: "Pada tahun kedua setelah Hijrah, izin untuk berperang membela diri telah diturunkan (Al-Qur'an 22:39). Pada 17 Ramadan tahun 2 Hijriah, sebuah pasukan muslim berjumlah sekitar 313 orang — dengan persenjataan yang minim dan hanya beberapa ekor kuda — bertemu dengan pasukan Quraisy yang berjumlah sekitar seribu orang di sumur-sumur Badar, barat daya Madinah. Ini adalah pertempuran besar pertama dalam Islam.\n\nDi luar dugaan, kaum muslimin menang telak, dan beberapa tokoh utama penindas dari Quraisy tewas. Al-Qur'an menggambarkan kemenangan ini bukan sekadar sebagai capaian militer, melainkan sebagai sebuah tanda: \"Dan sungguh, Allah telah menolongmu di Badar, padahal kamu dalam keadaan lemah. Maka bertakwalah kepada Allah agar kamu bersyukur\" (Al-Qur'an 3:123), dan menyebutkan bantuan para malaikat (Al-Qur'an 3:124–125). Badar menegakkan komunitas yang masih muda itu sebagai kekuatan nyata di jazirah Arab.\n\nPelajarannya: hasil akhir berada di tangan Allah, bukan pada jumlah pasukan atau perlengkapan. Badar dikenang sebagai \"hari pembeda\" (yaum al-furqan), hari ketika kebenaran dan kebatilan dipisahkan dengan jelas — bukti bahwa tawakal yang tulus kepada Allah disertai usaha yang sungguh-sungguh itulah yang sesungguhnya menentukan. Kekalahan di Uhud setahun kemudian akan mengajarkan pelajaran yang saling melengkapi.",
    location: "Badar",
  },
  {
    title: "Perang Uhud",
    body: "Setahun setelah Badar, Quraisy kembali untuk membalas dendam dengan pasukan yang jauh lebih besar, dan kedua pihak bertemu di kaki Gunung Uhud dekat Madinah. Nabi ﷺ menempatkan lima puluh pemanah di sebuah bukit dengan perintah tegas agar tidak pernah meninggalkan posisi mereka, apa pun yang terjadi. Di awal pertempuran, kaum muslimin memegang keunggulan; namun melihat musuh melarikan diri, sebagian besar pemanah meninggalkan posnya untuk mengumpulkan harta rampasan. Pasukan berkuda Quraisy di bawah pimpinan Khalid bin Walid (yang saat itu belum memeluk Islam) berputar melalui sisi yang terbuka itu, dan keadaan berbalik menjadi hari yang berat dan menyakitkan.\n\nBanyak sahabat gugur sebagai syuhada, di antaranya paman tercinta Nabi ﷺ, Hamzah (semoga Allah meridainya), \"Singa Allah\". Nabi ﷺ sendiri terluka, giginya patah dan wajahnya berdarah. Setelah itu, Al-Qur'an membahas kemunduran ini secara terus terang, menjelaskan bahwa itu adalah sebuah ujian dan akibat dari ketidaktaatan terhadap perintah serta ketamakan terhadap dunia (Al-Qur'an 3:152, 3:165–166).\n\nPelajarannya: Uhud adalah pelajaran besar tentang disiplin dan ketaatan. Satu tindakan kelalaian disiplin, sekecil apa pun tampaknya, dapat membalikkan kemenangan yang hampir diraih. Namun Allah tidak meninggalkan mereka — Dia mengajarkan, mengampuni, dan menyatukan kembali mereka. Kekalahan yang dihadapi dengan jujur bisa lebih banyak mengajarkan daripada kemenangan.",
    location: "Gunung Uhud",
  },
  {
    title: "Perang Khandaq",
    body: 'Pada tahun kelima, sebuah aliansi Quraisy, suku-suku Arab lainnya, dan kelompok-kelompok yang bermusuhan — "Al-Ahzab" (kaum sekutu) — menghimpun pasukan terbesar yang pernah dilihat di jazirah Arab, mungkin sepuluh ribu orang, untuk menghancurkan Madinah selamanya. Menghadapi musuh yang terlalu besar untuk dilawan dalam pertempuran terbuka, Nabi ﷺ menerima saran sahabat Persia, Salman al-Farisi (semoga Allah meridainya), untuk menggali parit lebar di sepanjang jalur utara kota yang terbuka — sebuah taktik yang belum pernah dijumpai orang Arab sebelumnya.\\n\\nParit itu menghentikan pengepungan. Berminggu-minggu dingin, kelaparan, dan ketakutan menyusul, dan Al-Qur\\\'an menggambarkan dengan begitu hidup ujian kaum mukmin dalam Surah al-Ahzab: "…ketika pandangan mata terbelalak karena takut dan hati naik menyesak sampai ke tenggorokan" (Al-Qur\\\'an 33:10). Akhirnya angin kencang dan perpecahan internal mencerai-beraikan pasukan sekutu itu, dan mereka mundur tanpa terjadi pertempuran besar. Al-Qur\\\'an menyandarkan keselamatan itu kepada Allah, yang "mengirimkan kepada mereka angin dan bala tentara yang tidak dapat kamu lihat" (Al-Qur\\\'an 33:9).\\n\\nPelajarannya: musyawarah yang bijak (syura) dan keterbukaan terhadap gagasan baik dari siapa pun — di sini, dari keahlian teknik seorang asing — adalah bagian dari keimanan. Dan ketika usaha manusia telah dicurahkan sepenuhnya, pertolongan tetap datang dari Allah. Pengepungan yang gagal ini secara efektif mengakhiri kemampuan Quraisy untuk melancarkan serangan.',
    location: "Madinah",
  },
  {
    title: "Perjanjian Hudaibiyah",
    body: "Pada tahun keenam, Nabi ﷺ berangkat bersama sekitar 1.400 sahabat untuk melaksanakan umrah, bukan untuk berperang, dengan mengenakan ihram agar niat damai itu jelas terlihat. Quraisy menghadang mereka di sebuah tempat bernama Hudaibiyah, di tepi tanah suci. Setelah perundingan yang tegang, disepakati gencatan senjata selama sepuluh tahun dengan syarat-syarat yang, bagi banyak sahabat, tampak merendahkan: kaum muslimin akan kembali pulang tahun itu dan datang lagi tahun berikutnya; siapa pun yang lari dari Quraisy menuju kaum muslimin akan dikembalikan, tetapi tidak berlaku sebaliknya.\n\nNamun Allah menurunkan wahyu dalam perjalanan pulang bahwa perjanjian inilah yang merupakan \"kemenangan yang nyata\" (Al-Qur'an 48:1, Surah al-Fath). Para sahabat kelak berkata bahwa mereka tidak pernah melihat kemenangan yang lebih besar — karena dalam kedamaian yang menyusul, orang-orang bercampur bebas, mendengarkan pesan itu dengan tenang, dan memeluk Islam dalam jumlah yang jauh lebih besar dibanding sepanjang tahun-tahun peperangan; riwayat al-Bara' bin Azib tentang hal ini tercatat dalam Shahih al-Bukhari 4606. Gencatan senjata itu juga secara tersirat mengakui kaum muslimin sebagai kekuatan yang setara.\n\nPelajarannya: apa yang tampak seperti kemunduran bisa menjadi peluang terbesar. Nabi ﷺ memilih kerugian jangka pendek yang tampak nyata demi kebaikan jangka panjang, dan menepati kesepakatan yang berat itu bahkan ketika terasa menyakitkan. Kesabaran, pengendalian diri, dan menepati janji dapat mencapai apa yang tidak bisa dicapai oleh konfrontasi.",
    location: "Hudaibiyah",
  },
  {
    title: "Surat-surat kepada para penguasa",
    body: "Setelah gencatan senjata Hudaibiyah memberi masa tenang dari perang, Nabi ﷺ mengalihkan perhatiannya ke luar Jazirah Arab. Sekitar tahun 6-7 H, beliau mengutus para sahabat tepercaya sebagai utusan, masing-masing membawa surat yang dibubuhi cap cincin beliau, mengundang para penguasa besar zaman itu untuk memeluk Islam: Heraklius, Kaisar Bizantium; Khosrow II, Kaisar Persia; al-Muqawqis, gubernur Bizantium di Mesir; Najasyi, raja Habasyah yang telah melindungi para muhajirin; serta para penguasa Bahrain dan Oman.\n\nSurat kepada Heraklius terekam hampir kata demi kata dalam literatur hadis: 'Aku mengundangmu kepada Islam. Masuklah Islam, niscaya engkau akan selamat... Masuklah Islam, niscaya Allah akan memberimu pahala berlipat ganda' (Sahih al-Bukhari 7). Riwayat ini juga menyimpan percakapan panjang ketika Heraklius menanyai pedagang Makkah, Abu Sufyan — yang saat itu masih kafir — tentang garis keturunan dan akhlak Nabi ﷺ, lalu menyimpulkan dari jawaban yang jujur itu bahwa sifat-sifat tersebut sesuai dengan seorang nabi sejati, meski ia sendiri tidak mengikuti keyakinannya itu. Khosrow, sebaliknya, dikenang dalam sirah karena merobek suratnya dengan marah, sementara Najasyi menyambut utusan Nabi ﷺ dengan penuh kehormatan.\n\nPelajarannya: misi Rasul terakhir tidak pernah terbatas pada Jazirah Arab — begitu Madinah aman, dakwah menyebar ke seluruh dunia yang dikenal saat itu, sebagaimana Al-Qur'an menggambarkan beliau diutus 'untuk seluruh manusia' (Al-Qur'an 34:28). Sebagian penguasa mendengarkan dengan jujur, sebagian menjawab dengan sopan, dan sebagian dengan kesombongan — dan setiap tanggapan itu menjadi pertanda bagaimana kerajaan mereka kelak akan berhadapan dengan Islam.",
    location: "Madinah",
  },
  {
    title: "Ekspedisi ke Khaibar",
    body: "Tidak lama setelah Hudaibiyah, Nabi ﷺ mengarahkan perhatian ke Khaibar, sebuah oasis kaya dengan benteng-benteng pertahanan di utara Madinah. Khaibar telah menjadi basis permusuhan — tempat tinggal kabilah-kabilah yang membantu mengorganisasi pengepungan Madinah oleh kaum sekutu dan terus berkomplot melawan komunitas muslim. Ekspedisi ini bertujuan mengakhiri ancaman tersebut.\n\nBenteng-benteng itu jatuh satu demi satu setelah pertempuran sengit; panji kemenangan pada hari yang menentukan diberikan kepada Ali bin Abi Thalib (semoga Allah meridainya). Setelah itu, Nabi ﷺ mengizinkan penduduknya tetap tinggal dan melanjutkan bercocok tanam di tanah itu dengan imbalan sebagian hasil panennya — sebuah kesepakatan yang menjamin pangan dan kestabilan bagi Madinah, alih-alih mengusir semua orang. Di sinilah pula seorang wanita mencoba meracuninya lewat daging kambing, namun beliau diberi tahu sebelumnya.\n\nPelajarannya: keamanan dan menepati perjanjian berjalan beriringan. Tindakan ini ditujukan terhadap sebuah kekuatan yang terbukti bermusuhan, namun berakhir dengan penyelesaian yang bisa diterima, yang membiarkan pihak yang kalah tetap mempertahankan mata pencaharian mereka. Kekuatan dalam Islam dimaksudkan untuk menegakkan keamanan dan keadilan, bukan untuk memusnahkan.",
    location: "Khaibar",
  },
  {
    title: "Umrah pengganti (Umrat al-Qada)",
    body: "Perjanjian Hudaibiyah telah menghalangi umat Islam dari Umrah pada tahun 6 H, dengan jaminan bahwa mereka dapat kembali tahun berikutnya. Pada bulan Dzulqa'dah tahun 7 H, tepat sesuai kesepakatan itu, Nabi ﷺ memimpin sekitar dua ribu sahabat kembali ke Makkah untuk menjalankan ibadah yang sebelumnya ditolak — dikenal sebagai Umrat al-Qada, Umrah 'pengganti' (disebut juga Umrat al-Qisas dalam beberapa sumber).\n\nMenepati bagian mereka dari perjanjian, Quraisy mengosongkan kota selama tiga hari agar umat Islam dapat menjalankan ibadah dengan tenang, sambil menyaksikan dari perbukitan sekitar bagaimana komunitas yang pernah mereka usir itu kini bertawaf mengelilingi Ka'bah dengan aman sepenuhnya. Dalam kunjungan inilah paman Nabi ﷺ, al-Abbas, mengatur pernikahan beliau dengan Maimunah binti al-Harits, dan beberapa penduduk Makkah yang menyaksikan kekhusyukan serta kedisiplinan para jamaah pun tersentuh hatinya.\n\nPelajarannya: menepati janji itu sendiri adalah bentuk dakwah. Ketika dua puluh tahun dakwah dan peperangan tidak berhasil melunakkan hati, satu kali Umrah yang damai dan bermartabat — buah langsung dari 'kemenangan yang nyata' di Hudaibiyah (Al-Qur'an 48:1) — justru melunakkan hati yang tak tersentuh kekuatan. Kunjungan yang tenang ini turut membuka jalan bagi penaklukan Makkah yang hampir tanpa pertumpahan darah setahun kemudian.",
    location: "Makkah",
  },
  {
    title: "Pembebasan Makkah",
    body: 'Ketika sekutu-sekutu Quraisy melanggar syarat Perjanjian Hudaibiyah dengan menyerang sebuah kabilah yang bersekutu dengan kaum muslimin, gencatan senjata pun batal. Pada bulan Ramadan tahun kedelapan, Nabi ﷺ berangkat menuju Makkah dengan pasukan sepuluh ribu orang — yang terbesar yang pernah ada — dan kota yang telah menganiaya, memboikot, dan memeranginya selama dua puluh tahun itu menyerah hampir tanpa pertumpahan darah.\\n\\nBerdiri akhirnya sebagai pemenang di hadapan orang-orang yang telah mengusirnya, beliau bertanya kepada penduduk Makkah apa yang mereka harapkan darinya. Mereka berharap akan belas kasih seorang saudara yang mulia, dan beliau menjawab dengan kata-kata yang pernah diucapkan Yusuf kepada saudara-saudaranya: "Tidak ada cercaan atasmu hari ini" — dan menyatakan, "Pergilah, kalian bebas." Beliau memasuki Ka\\\'bah dan membersihkannya dari 360 berhala, sambil membaca "Yang benar telah datang dan yang batil telah lenyap" (Al-Qur\\\'an 17:81), mengembalikan rumah suci Ibrahim itu kepada penyembahan murni kepada Allah. Surah an-Nashr (Al-Qur\\\'an 110) berbicara tentang momen ini, ketika orang-orang "masuk ke dalam agama Allah secara berbondong-bondong".\\n\\nPelajarannya: ini adalah puncak dari kasih sayang dan pengampunan kenabian. Dengan kekuasaan penuh untuk membalas dendam, beliau justru mengampuni. Seorang mukmin belajar bahwa orang yang kuat adalah mereka yang mengampuni ketika mampu menghukum, dan bahwa tujuannya tidak pernah berupa balas dendam, melainkan hidayah.',
    location: "Makkah",
  },
  {
    title: "Perang Hunain",
    body: "Hanya beberapa minggu setelah pembebasan Makkah secara damai, suku-suku gabungan Hawazin dan Tsaqif — yang gelisah melihat kekuatan umat Islam yang tiba-tiba membesar dan bertekad bertempur sampai akhir — mengumpulkan pasukan besar, membawa serta keluarga, ternak, dan harta mereka, lalu menghadapi pasukan Nabi ﷺ yang jauh lebih besar di lembah Hunain yang sempit, antara Makkah dan Thaif.\n\nHawazin telah menyembunyikan pemanah di celah-celah bukit, dan ketika mereka melepaskan tembakan mendadak saat subuh, garis depan pasukan Muslim pecah dan bercerai-berai; sesaat terlihat seakan pasukan terbesar yang pernah dikumpulkan umat Islam akan dikalahkan hanya oleh kejutan itu. Al-Qur'an melukiskan pembalikan ini dengan tepat: '...dan (ingatlah) perang Hunain, ketika kamu menjadi congkak karena banyaknya jumlahmu, maka jumlah yang banyak itu tidak memberi manfaat apa pun kepadamu, dan bumi yang luas itu terasa sempit bagimu, kemudian kamu lari ke belakang dengan bercerai-berai' (Al-Qur'an 9:25). Nabi ﷺ sendiri tetap tegar dan menyuruh pamannya, al-Abbas, memanggil nama-nama kaum Anshar dan suku-suku Madinah; seruan itu membuat para sahabat kembali, menyusun kembali barisan, dan pertempuran berbalik menjadi kemenangan telak yang oleh Al-Qur'an disandarkan pada ketenangan dan bantuan gaib yang diturunkan Allah (Al-Qur'an 9:26).\n\nPelajarannya: jumlah dan perlengkapan tidak menentukan hasil sebuah pertempuran — Badar telah mengajarkan hal itu dengan pasukan kecil, dan Hunain mengajarkan kebalikannya, bahwa pasukan besar sekalipun dapat goyah tanpa pertolongan Allah dan disiplin di medan perang. Setelahnya, harta rampasan yang besar dibagikan dengan penuh kemurahan, termasuk kepada penduduk Makkah yang baru memeluk Islam, demi merangkul hati, bukan menimbun kekayaan.",
    location: "Hunain",
  },
  {
    title: "Ekspedisi ke Tabuk",
    body: "Pada tahun kesembilan, kabar sampai ke Madinah tentang kemungkinan mobilisasi pasukan Bizantium (Romawi) di perbatasan utara. Di tengah teriknya musim panas, ketika hasil panen sedang matang dan perjalanan jauh serta berat, Nabi ﷺ menyerukan pasukan terbesar yang pernah beliau pimpin — mungkin tiga puluh ribu orang — untuk berbaris ke utara menuju Tabuk. Ini adalah \"saat kesulitan\" (Al-Qur'an 9:117), dan ia menguji ketulusan seperti belum pernah terjadi sebelumnya.\n\nTidak terjadi pertempuran; unjuk keteguhan itu sudah cukup, dan beberapa pemimpin di utara membuat perjanjian dengan Madinah. Namun ekspedisi ini dikenang terutama karena apa yang diungkapkannya tentang isi hati manusia. Al-Qur'an mencurahkan sebagian besar Surah at-Taubah untuk peristiwa ini — memuji mereka yang memberikan segalanya (Abu Bakar konon menyerahkan seluruh hartanya), menyingkap kaum munafik yang mengarang-ngarang alasan untuk tidak ikut serta, dan menceritakan kisah yang menyentuh tentang tiga mukmin yang jujur, termasuk Ka'b bin Malik, yang dengan jujur mengakui bahwa mereka tidak punya alasan dan akhirnya diampuni setelah ujian yang berat (Al-Qur'an 9:118).\n\nPelajarannya: ketaatan itu mudah ketika nyaman; kebenarannya teruji ketika harus mengorbankan sesuatu. Tabuk memisahkan yang tulus dari yang mencari-cari alasan dan menandai berakhirnya secara efektif perlawanan penyembahan berhala yang terorganisasi di jazirah Arab. Kejujuran — bahkan kejujuran mengakui kesalahan diri sendiri — adalah jalan kembali kepada Allah.",
    location: "Tabuk",
  },
  {
    title: "Tahun Para Utusan (Am al-Wufud)",
    body: "Pada tahun kesembilan setelah Hijrah, menyusul penyerahan Makkah dan unjuk kekuatan di Tabuk, suku-suku Arab menyadari bahwa melawan tatanan baru itu sudah tidak realistis lagi. Utusan demi utusan — dari Bani Tamim, Bani Amir, suku-suku Yaman, dan banyak lainnya — datang ke Madinah untuk menyatakan keislaman dan kesetiaan mereka kepada Nabi ﷺ, sedemikian banyaknya sehingga tahun itu dikenal dalam sirah sebagai Am al-Wufud, Tahun Para Utusan.\n\nNabi ﷺ menyambut setiap rombongan dengan keramahan dan pengajaran yang sabar, mengutus para sahabat bersama mereka untuk mengajarkan Al-Qur'an dan salat kepada kaum mereka, bukan mengirim penguasa untuk memerintah dengan kekerasan. Al-Qur'an berbicara langsung tentang momen ini dalam Surah an-Nasr: 'Apabila telah datang pertolongan Allah dan kemenangan, dan engkau melihat manusia berbondong-bondong masuk agama Allah, maka bertasbihlah dengan memuji Tuhanmu dan mohonlah ampun kepada-Nya' (Al-Qur'an 110:1-3) — sebuah surah yang dipahami para sahabat, sebagaimana dijelaskan Ibnu Abbas kepada Umar, sebagai tanda bahwa kehidupan Nabi ﷺ semakin mendekati akhir (Sahih al-Bukhari 4430).\n\nPelajarannya: setelah puluhan tahun pesan itu ditolak oleh banyak orang dan diterima oleh segelintir, janji Allah datang sekaligus — sebuah pelajaran tentang kesabaran, dan tentang cara memaknai kesuksesan dengan benar. Tanggapan Surah an-Nasr terhadap kemenangan bukanlah perayaan, melainkan pujian dan permohonan ampun, sebuah teladan bagaimana seorang mukmin seharusnya menyambut setiap kesuksesan dalam hidupnya. Ini menjadi pengantar bagi Haji Wada' yang menyusul kemudian.",
    location: "Madinah",
  },
  {
    title: "Haji Wada'",
    body: "Pada tahun kesepuluh, Nabi ﷺ melaksanakan satu-satunya haji lengkap dalam hidupnya, didampingi lebih dari seratus ribu sahabat, mengajarkan tata cara ibadah haji itu secara langsung kepada mereka. Berdiri di padang Arafah, beliau menyampaikan Khutbah Wada', sebuah ringkasan dari segala hal yang datang untuk ditegakkan oleh Islam.\n\nBeliau menyatakan kesucian jiwa, harta, dan kehormatan setiap orang — \"darah dan hartamu sesuci hari ini, bulan ini, dan negeri ini\" (Shahih al-Bukhari 1741). Beliau menghapuskan dendam darah dan riba peninggalan Jahiliyah, mewajibkan perlakuan baik terhadap para perempuan sebagai amanah dari Allah, mengingatkan bahwa tidak ada keunggulan orang Arab atas non-Arab kecuali dalam ketakwaan, dan memerintahkan mereka untuk berpegang teguh pada Al-Qur'an. Pada haji inilah, di hari Arafah yang jatuh pada hari Jumat, Allah menurunkan ayat \"Pada hari ini telah Aku sempurnakan untukmu agamamu…\" (Al-Qur'an 5:3) — sebuah ayat yang diingat dan ditentukan waktunya secara tepat oleh Umar (Shahih al-Bukhari 45).\n\nPelajarannya: Khutbah Wada' adalah piagam Islam tentang martabat manusia, keadilan, dan kesetaraan, disegel dengan pengumuman bahwa agama ini kini telah sempurna. Tugas seorang mukmin sejak saat itu bukanlah menambahkannya, melainkan menjalankannya.",
    location: "Arafah",
  },
  {
    title: "Wafatnya Nabi ﷺ",
    body: 'Beberapa bulan setelah Haji Wada\', Nabi ﷺ jatuh sakit demam. Pada hari-hari terakhirnya, beliau meminta izin kepada para istrinya untuk dirawat di kamar Aisyah (semoga Allah meridainya), dan beliau menunjuk Abu Bakar untuk mengimami salat. Pada pagi terakhirnya, beliau menyingkap tirai untuk melihat barisan kaum mukmin yang sedang salat dan tersenyum, gembira melihat umatnya, lalu membiarkan tirai itu tertutup kembali. Beliau wafat pada hari Senin, 12 Rabiul Awal tahun 11 Hijriah, dengan kepalanya bersandar di antara dada dan dagu Aisyah — sebagaimana ia sendiri riwayatkan dalam Shahih al-Bukhari 4449/4451.\n\nKesedihan di Madinah tak terlukiskan, dan bahkan Umar pada mulanya menolak menerima kenyataan itu. Kemudian Abu Bakar bangkit berdiri, mencium wajah Nabi ﷺ, dan berbicara kepada orang-orang dengan kata-kata yang menenangkan seluruh komunitas dan tercatat dalam Shahih al-Bukhari 1241/1242: "Siapa yang dahulu menyembah Muhammad, maka sesungguhnya Muhammad telah wafat; tetapi siapa yang menyembah Allah, maka sesungguhnya Allah Maha Hidup dan tidak akan pernah mati." Ia lalu membacakan ayat "Muhammad hanyalah seorang rasul; sungguh telah berlalu sebelumnya beberapa rasul…" (Al-Qur\'an 3:144).\n\nPelajarannya: pesan itu telah sempurna dan kini menjadi milik umat. Nabi ﷺ adalah manusia biasa yang fana, namun apa yang beliau bawa — Al-Qur\'an dan Sunnahnya — tidak akan pernah fana. Jawaban Abu Bakar adalah obat abadi bagi kesedihan: keterikatan kita adalah kepada Allah, yang tidak pernah mati, dan jalan untuk mencintai Nabi ﷺ adalah dengan menjalankan petunjuknya.',
    location: "Madinah",
  },
];
