// Hausa translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_HA: DeepPartial<SeerahEvent>[] = [
  {
    title: "Larabawa kafin Musulunci (Jahiliyyah)",
    body: "Don fahimtar Annabi SAW sai ka fara kwatanta duniyar da aka aiko shi. Ƙasar Larabawa ta ƙarni na shida, ƙasa ce mai warwatsewar ƙabilun da ba ta da wata ƙasa ta tsakiya, an haɗa ta da nasaba, daraja, da kuma hurumin Ka'aba a Makkah - wurin bauta da Ibrahim da Isma'il suka gina don bautar Allah ɗaya, amma a yanzu kewaye da gumaka ɗari uku da sittin.\n\nAna kiran wannan zamanin jahiliyyah, “zamanin jahiliyya” – ba don Larabawa ba su da hankali (waƙarsu da ƙwaƙwalwarsu ta ban mamaki) amma don rashin shiriya. Rikicin kabilanci zai iya gudana har tsawon tsararraki, masu karfi suna cin karensu babu babbaka, kuma a wasu lokuta ana binne 'ya'ya mata da rai saboda kunya ko tsoron talauci - al'adar da Kur'ani zai yanke hukunci kai tsaye (Alkur'ani 81:8-9). Tare da bautar gumaka wasu ‘yan “hunafa” har yanzu suna neman tsarkakakkiyar tauhidi na Ibrahim, kuma kananan al’ummomin Yahudawa da Kirista sun rayu a fadin yankin.\n\nDarasi: Wahayi bai sauko cikin vuya ba, sai dai ya shiga cikin al’umma ta hakika mai rauni mai zurfi, kuma farkon abin da ya warke shi ne alakar dan Adam da mahaliccinsa. Ku tuna da wannan taswirar yayin da lokaci ya bayyana - kusan duk wani gyara na Annabi SAW amsa ce kai tsaye ga zaluncin Jahiliyyah.",
    location: "Arabiya",
  },
  {
    title: "Haihuwa a Makkah",
    body: 'An haifi Manzon Allah SAW a Makkah a shekarar giwaye (Am al-Fil), saboda a waccan shekarar Abraha, gwamnan Abyssiniya na Yaman, ya taka wata runduna da giwaye domin su rusa dakin Ka’aba, aka mayar da shi ta hanyar mu’ujiza – lamarin da Alkur’ani ya tuna a cikin Suratul Fil (Alkur’ani 105). A cikin wannan shekarar an haifi yaro ga kabilar Kuraishawa da mafi girman zuriyarta Banu Hashim.\n\nYa riga ya kasance maraya tun lokacin da aka haife shi: mahaifinsa Abdullah ya rasu watannin baya yana kasuwanci. Mahaifiyarsa, Aminah bint Wahb, ta sa masa suna Muhammad - "wanda aka fi yabo" - sunan da ba a san shi ba a tsakanin Larabawa. Kamar yadda al’adar Makka ce aka tura shi renonsa, a tashe shi a sararin sahara a cikin Banu Sa’ad, karkashin kulawar Halimah As-Sa’adiyyah.\n\nDarasi ga mumini: Girma a wurin Allah ba shi da alaka da tsaron duniya. Manzo na ƙarshe ya fara rayuwa mara uba kuma ba da jimawa ba zai zama marar uwa, duk da haka Allah da kansa ne majiɓincinsa - "Shin bai same ka maraya ba, sa\'an nan Ya ba ka mafaka?" (Alkur\'ani 93:6). Duba kuma "Watsewar Mahaifiyarsa" da "Mai Kula da Abu Talib" wanda ya biyo baya.',
    location: "Makkah",
  },
  {
    title: "Wucewa mahaifiyarsa",
    body: "Yayin da yake da shekara shida, sai Amina ta dauki danta don ziyartar 'yan uwansa a Yasriba (daga baya Madina) don ganin kabarin mahaifinsa. Dawowar ta ta yi rashin lafiya, ta rasu a wani wuri da ake kira Abwa’, tsakanin Makka da Madina, aka binne ta a can. Matashi Muhammad ﷺ ya rasa iyayensa biyu.\n\nUmmu Ayman, baiwar gidan da aka 'yanta ce ta dawo da shi Makkah, ta sanya shi a hannun kakansa Abd al-Muttalib, babban sarkin Kuraishawa, wanda yake matukar kaunarsa kuma ya kan zaunar da shi a dakin Ka'aba.\n\nDarasi: Annabi SAW ya dandana, da wuri kuma ya maimaita, baqin cikin da mutane da yawa ke ɗauke da su - baƙin ciki, ƙaura, dogaro da wasu. Wannan yana cikin shirye-shiryensa. Zuciyar da ta san hasara, ita ce zuciyar da za ta iya ji ga maraya, da gwauruwa, da baƙo, kuma daga baya za a gina al'ummarsa a kan ainihin wannan rahamar. Wannan zaren yana ci gaba a cikin \"Shekarar Bakin Ciki.\"",
    location: "Abwa'",
  },
  {
    title: "Waliyyin Abu Talib",
    body: "Shekaru biyu da mahaifiyarsa, shi ma kakansa Abd al-Muttalib ya rasu, a lokacin da yaron ya kai kimanin takwas. A kan gadon rasuwarsa ya ba da amanar jikansa ga dansa Abu Talib, kawun Manzon Allah. Duk da cewa Abu Talib ba mai arziki ba ne, sai ya kai yaron gidansa ya dauke shi a matsayin daya daga cikin ’ya’yansa mafi soyuwa.\n\nAbu Talib zai kasance majibincinsa sama da shekaru arba'in, daidai lokacin da aka shafe shekaru mafi tsanani na zalunci a Makka. Shi ne ya dauki matashin Muhammad ﷺ akan tafiye-tafiyen kasuwanci zuwa kasar Sham, inda - a cewar sanannen labari - Bahira ya lura da alamun annabci a cikinsa (rahoton da seerah ta adana, ko da yake ana yada bayanansa da karfi daban-daban).\n\nDarasi: Allah ya sanya mutane masu aminci, masu daraja a wajen AnnabinSa (SAW) a kowane mataki. Shekaru da dama da Abu Talib ya yi na kariya ya kasance rahama - tunatarwa cewa goyon bayan gaskiya da dangi wani tasha ce mai daraja hatta ga wadanda ba su yi imani ba, kuma mu girmama wadanda suka ba mu mafaka. Rashinsa daga baya, a cikin Shekarar baƙin ciki, zai canza komai.",
    location: "Makkah",
  },
  {
    title: "Auren Khadijah",
    body: "Tun yana matashi Muhammad ﷺ ya yi suna a fadin Makkah wanda babu wata dukiya da za ta iya saya: al-Sadik, mai gaskiya, da al-Amin, amintacce. Mutane sun ajiye dukiyarsu a wurinsa domin ya kiyaye su kuma sun amince da maganarsa sarai, har da waɗanda suke bauta wa alloli dabam-dabam.\n\nKhadijah bint Khuwaylid (Allah Ya yarda da ita) yar kasuwan Kuraishawa mai daraja da nasara, ta dauke shi ya jagoranci ayarinta zuwa Sham. Ganin gaskiyarsa da halayensa sun burge ta, ta aika da maganar aure ta hannun kawarta Khawlah bint Hakim. Yana wajen ashirin da biyar ita kuma ta kai wajen arba'in. nasu ya zama auren soyayya mai zurfi da zumunci. Ta haifa masa 'ya'yansa, ta kasance matarsa ​​tilo har tsawon shekaru ashirin da biyar, har zuwa rasuwarta.\n\nDarasi: Hali shine tushen duk abin da ya biyo baya. Tun kafin a kira shi Annabi, Makkah ta rigaya ta san shi a matsayin mutumin da ya fi kowa gaskiya a cikinsu - shi ya sa, a farkon wahayin, amincewar Khadijah a gare shi nan take ya kasance mai yanke hukunci (duba \"Ru'ya ta farko\"). Muhimmancin mumini a cikin mu'amalar yau da kullum shi kansa nau'i ne na da'awah.",
    location: "Makkah",
  },
  {
    title: "Hilf al-Fudul da Black Stone",
    body: "Abubuwa guda biyu daga rayuwarsa kafin annabci sun nuna kimar da zai gina al'umma a kai. Na farko, Hilf al-Fudul: yarjejeniya ce mai girma da wasu dangogin kuraishawa da dama suka lashi takobin tsayawa da duk wani wanda aka zalunta a Makkah, na gida ko na waje, har sai an kwato musu hakkinsu. Annabi ﷺ ya shiga kuma daga baya ya ce zai amsa irin wannan yarjejeniya ko da a Musulunci - domin ya kare adalci.\n\nNa biyu, sake gina Ka'aba bayan ambaliya. Lokacin da dangogin suka kusa yin busa kan daukakar dage dutse mai alfarma (al-Hajar al-Aswad) zuwa wurinsu, sai suka amince su amince da hukuncin wanda zai shiga - kuma Muhammad SAW ne. Maganinsa ya shahara da hikimarsa: ya aza dutse a kan tufa, ya sa shugaban kowace dangi ya ɗaga kusurwa, sa'an nan ya kafa shi da hannunsa, ta yadda kowa ya raba daraja kuma ba a ko'ina.\n\nDarasi: Adalci da warware rikice-rikice su ne illolinsa kafin wahayi ya tabbatar da su. Mumini shi ne wanda yake kare wanda aka zalunta kuma ya nemo hanyoyin hadin kai maimakon rarraba - Hilf al-Fudul yana kwatanta al'ummar adalci da zai kafa bayan Hijira.",
    location: "Makkah",
  },
  {
    title: "Wahayi na farko",
    body: "A cikin shekarunsa talatin, Manzon Allah ﷺ ya ƙara janyewa don yin ibada da tunani a cikin kogon Hira da ke kan dutsen Jabal an-Nur a wajen Makka. Can sai ga Mala'ika Jibrilu yana da kimanin shekara arba'in a cikin watan Ramadan ya bayyana, ya umarce shi da cewa: \"Karanta!\" Ya amsa da cewa bai iya karantawa ba; Mala'ikan ya rungume shi sosai sau uku kuma ya saukar da ayoyin farko na surar Al'alak - \"Ka yi karatu da sunan Ubangijinka wanda ya yi halitta...\" (Alkur'ani 96:1-5), kalmomin farko na Kur'ani.\n\nYa koma gida yana girgiza, sai Khadijah ta nade shi, ta kuma tabbatar masa da kalmomin da ke bayyana imaninta da halayensa: Allah ba zai taba tozarta shi ba, domin yana da alaka da zumunta, yana daukar nauyin wasu, yana taimakon wadanda suka cancanta. Sai ta kai shi wurin dan uwanta Waraqah bn Nawfal, wani dattijo wanda ya koya a littafin da ya gabata, wanda ya gane baƙon a matsayin \"Namus\" (mala'ika) wanda ya zo wurin Musa ya gaya masa wannan shine Annabcin da aka yi alkawari. An rubuta wannan duka a cikin Sahihul Bukhari 3.\n\nDarasi: wahayi ya fara ba da da'awar iko ba amma da kalmar \"Karanta\" - addinin da aka kafa bisa ilimi da tawali'u. Kuma ka lura da wanda ya fara yin imani: mata da wani gida mai gaskiya. Waɗanda suka riga sun rayu da gaske sun gane gaskiya.",
    location: "Kogon Hira",
  },
  {
    title: "Shekaru na wa'azi na sirri",
    body: "Bayan wahayin farko sai aka dakata (fatrah), sai Allah ya umarci Annabi SAW da ya fara kiran mutane zuwa ga bautar Shi kadai. A cikin kusan shekaru uku na farko wannan kiran shiru ne kuma na sirri - an mika shi ga dangi na kusa da amintattun abokai maimakon yin shela a kan tituna.\n\nFarkon muminai, “as-Sabiqun al-Awwalun” (mafi kowa), sun fito daga kowane vangare na al’umma: Khadijah matarsa; dan baffansa Ali bn Abi Talib; bawansa da ya ‘yantacce kuma dansa Zayd bn Harithah; da amininsa Abu Bakr as-Siddiq (Allah Ya yarda da su baki daya). Shi kuma Abubakar ya kawo wasu da dama a Musulunci. Sun hadu kuma sun yi addu'a a hankali, sukan yi a gidan al-Arqam kusa da Ka'aba.\n\nDarasin: Musulunci ya fara girma ta hanyar amincewa da dangantaka, ba abin kallo ba. Ka lura da faɗin waɗannan zukata na farko—mace mai arziki, yaro, ’yantacciyar bawa, ɗan kasuwa—ƙaddamar bangaskiya da za ta shafe bambancin launin fata da matsayi. Da'awa ta fara daf da gida, cikin gaskiya da hakuri.",
    location: "Makkah",
  },
  {
    title: "Kiran jama'a zuwa ga Musulunci",
    body: 'Lokacin da Allah ya saukar da “Kuma ka yi gargaɗi ga makusantaka” (Alkur’ani 26:214), Annabi SAW ya hau Dutsen Safa kusa da Ka’aba ya kira ga dangin Kuraishawa. Da farko ya tambaye shi ko za su yarda da shi idan ya ce sojoji sun boye a bayan tudun; suka amsa da cewa basu taba sanin karya ba. Sannan ya gargade su da wata azaba da za su zo ya kira su zuwa ga bautar Allah Shi kadai.\n\nWannan budaddiyar sakon ya ratsa zuciyar umarnin Makka. Gumakan ba addini kaɗai ba ne amma rayuwa da daraja - matsayin birnin a matsayin mai kula da wurin ibada ya jawo mahajjata da kasuwanci. A ce gumaka ba su da ƙarfi shi ne kalubalantar tattalin arzikin Kuraishawa, zuriyarsu, da girman kai lokaci guda. Daga nan fitina ta yi tsanani, ta fi tsanani a kan raunana da bayi daga cikin muminai, kamar Bilal bn Rabah da iyalan Yasir.\n\nDarasi: Gaskiyar magana a sarari za ta wargaza bukatu masu tushe. Annabi SAW ya fara kira ga shaidarsu cewa shi mai gaskiya ne - hankali da mutunci kafin barazana - sannan ya tsaya kyam. Tsayuwa ga tauhidi na iya kashe jin daɗin duniya, kamar yadda muminai Makka suka koya. Wannan wahala tana kaiwa kai tsaye zuwa "Hijira zuwa Abyssinia."',
    location: "Dutsen Safa",
  },
  {
    title: "Hijira zuwa Abyssinia",
    body: "Yayin da zalunci ya kasa jurewa, Manzon Allah SAW ya gaya wa gungun sahabbansa cewa su nemi tsari da Negus (an-Najashi), adali na Sarkin Abyssinia (Habasha ta zamani), yana mai cewa a kasarsa ba a zalunce kowa ba. Rukunin farko sun haye Tekun Bahar Rum, sai kuma hijira ta biyu mafi girma - hijra ta farko a Musulunci.\n\nLokacin da Kuraishawa suka aika da wakilai suna neman a mayar da 'yan gudun hijirar, Negus ya kira su. Jafar bn Abi Talib (ra) ya yi jawabi ga musulmi, inda ya bayyana yadda suka fita daga jahilci zuwa imani na gaskiya da rahama da kyawawan halaye, sannan ya karanta ayoyi daga suratu Maryam dangane da Annabi Isa da mahaifiyarsa. Sarkin Kirista ya yi kuka, ya ja layi a kasa, ya ce bambancin imaninsu da nasa bai wuce shi ba - kuma ya ki mika musu wuya.\n\nDarasin: wannan alama ce ta juriya ta addini da gina gadoji tare da Ahlul Kitabi masu gaskiya. Haka nan kuma tana karantar da cewa neman tsira daga zalunci a qarqashin hukuma mai adalci wadda ba ta musulmi ba ta halalta ce gaba xaya. Ka lura kuma cewa hujjar da ta yi nasara a ranar kyakkyawan hali ne kuma kalmar Allah da ake karantawa - ba karfi ba.",
    location: "Abyssiniya",
  },
  {
    title: "Kauracewa Banu Hashim",
    body: "Ba su iya hana yaduwar Musulunci ko isa ga Annabi SAW alhalin danginsa suna ba shi kariya, sai shugabannin kuraishawa suka dauki hukuncin gamayya. Sai suka rubuta yarjejeniya, suka rataye shi a cikin Ka'aba, suna masu alkawarin kauracewa dukkan dangin Banu Hashim (da majibintansu Banu al-Muddalib): ba aure a tare da su, ba kasuwanci, ba mu'amala, har sai sun mika wuya Muhammad SAW.\n\nTsawon shekaru kusan uku da dangi - muminai da kafiran Hashim - sun kasance a cikin kwarin dutsen Shi'b Abi Talib, suna jurewa yunwa mai tsanani har aka ji kukan yara kuma mutane suna cin ganye. A karshe kauracewa taron ya ruguje ne yayin da wasu masu adalci na Kuraishawa suka fito fili suka yi watsi da ita, aka gano an cinye tallar, banda kalmomin da sunan Allah ya bayyana.\n\nDarasi: Qarya ta yi yawa. Zaluntar kaurace wa kawai ya fallasa zaluncin masu zalunci da taurare kudurin muminai. Hakanan yana nuna darajar wasu ƴan ƴan adam a cikin al'umma masu ƙiyayya waɗanda suka karya matsayi don kawo ƙarshen zalunci - tunatarwa cewa lamiri na iya tsira har ma a cikin mafi munin adawa.",
    location: "Shi'b Abi Talib",
  },
  {
    title: "Shekarar Bakin Ciki",
    body: "Ba da dadewa ba bayan kauracewa taron, Annabi SAW ya gamu da munanan asara guda biyu cikin kankanin lokaci, kuma shekarar ta zama shekarar bakin ciki da suna Am al-Huzn. Da farko kawunsa kuma mai kare rayuwarsa Abu Talib ya rasu - mutumin da tsayawarsa ta kare shi daga kuraishawa shekaru da yawa. Sannan Khadijah (Allah Ya yarda da ita), matar sa ta yi shekaru kusan ashirin da biyar, kuma mumininsa na farko kuma mafi kusancinsa, ita ma ta rasu.\n\nTare da kariyarsa ta zamantakewa da anginsa na zuci duk sun tafi, Kuraishawa sun yi ƙarfin hali wajen cin zarafi. A cikin wannan lokaci ne ya yi tattaki zuwa garin Ta'if yana fatan mutanensa su karbi sakon; A maimakon haka sai suka kore shi suka sa yara su jefe shi da duwatsu har kafafunsa suka yi jini. Ko da a lokacin, da aka yi wa halakar garin, ya yi addu’a ga zuriyarsu wata rana su bauta wa Allah- rahama ce ta siffanta shi.\n\nDarasi: Hatta annabawa ana jarraba su da bakin ciki da kin komawa baya, kuma amsar ita ce hakuri ba da daci ba. Rasuwar mutum ba yana nufin watsi da Allah ba; taimako ya biyo baya a baya, a cikin tafiyar dare mai zuwa. Duba \"Al-Isra wal-Mi'raj.\"",
    location: "Makkah",
  },
  {
    title: "Al-Isra wal-Mi'raj",
    body: "Bayan Shekarar Bakin Ciki ya zo wani dare na ban mamaki. A cikin Isra'i, an dauke Annabi SAW a cikin dare guda daga Masallacin Harami a Makka zuwa al-Masjid al-Aqsa a birnin Kudus - lamarin da Kur'ani ya bude Suratul Isra'i da (Alkur'ani 17:1). A nan ne ya ja-goranci annabawan farko a addu’a. Sannan a cikin Mi’iraji, an tayar da shi a cikin sammai bakwai, yana haduwa da annabawa wadanda suka hada da Adam da Musa da Ibrahim, kuma ya kai ga wani matsayi mafi kusa da Ubangijinsa fiye da kowane halitta.\n\nBabban kyautar wannan dare ita ce salloli biyar. Kamar yadda ya zo a cikin Sahihul Bukhari 3887, an fara wajabta musu hamsin; bisa nasihar Musa Annabi ﷺ ya sake komawa yana neman agaji har sai da suka rage su biyar a aikace suna dauke da ladan hamsin. Malamai sun yi sabani kan hakikanin kwanan watan, mafi yawansu suna sanya ta a shekarun kafin Hijira.\n\nDarasi: Kyautar da aka bayar don ta'aziyyar Annabi SAW shine salati - hawan mu da dare zuwa ga Allah. Salloli biyar din nan ba mala'ika ne ya saukar da su zuwa duniya ba, sai dai an dauke su zuwa sama domin karba, alamar nauyinsu a rayuwar mumini.",
    location: "Urushalima",
  },
  {
    title: "Alkawarin farko na al-Aqabah",
    body: "A kowace shekara mahajjata suna taruwa a Makkah, kuma Manzon Allah SAW yana gabatar da addinin Musulunci ga kabilun da suke ziyara. A wani wuri da ake kira al-Aqabah kusa da Mina, wasu ƴan tsirarun maza daga Yathrib (Madina) - birni ne da ya daɗe yana fama da tashe-tashen hankula tsakanin kabilunsa na Aws da Khazraj, kuma sun san tauhidi ta wurin al'ummar Yahudawa - suka saurare, suka yi imani, kuma suka ɗauki saƙon gida.\n\nSai kuma goma sha biyu daga cikinsu suka dawo, suka yi alqawarin farko na al-Aqabah: su bauta wa Allah Shi kaɗai, kada su yi sata, kada su yi zina, kada su kashe ɗa, kuma kada su yi biyayya ga Annabi Sallallahu Alaihi Wasallama a kan abin da ya dace. Sannan ya aika saurayin sahabi Mus’ab bn Umayr (ra) ya dawo tare da su a matsayin malami kuma jakadan Musulunci na farko, kuma ta hanyarsa imani ya bazu cikin iyalan Yathrib.\n\nDarasi: Kofar da kamar a rufe a Makka ta bude a Madina. Lura yadda aka gina al'umma - ta hanyar koyarwa. Wani matashi malami mai sadaukarwa, wanda aka aiko shi da Alkur'ani, ya shirya wani gari gaba daya domin ya zama mahaifar Musulunci. Wannan kai tsaye ya kafa Alkawari na Biyu da Hijira.",
    location: "Mina",
  },
  {
    title: "Alkawari na biyu na al-Aqabah",
    body: "Shekara guda bayan mubaya'ar farko, wata tawaga mafi girma daga Yasriba - maza saba'in da uku da mata biyu - sun zo wurin Annabi SAW a asirce a al-Aqabah yayin aikin hajji. A wannan karon alkawari ya ci gaba da cewa: sun yi alkawarin ba shi kariya kamar yadda za su kare matansu da ‘ya’yansu, tare da karbar musulmin Makka da ake zalunta a cikin garinsu.\n\nWannan wani juyi ne. A karon farko al'ummar da aka kafa sun sami kasa ta asali da kuma taron jama'a da aka yi rantsuwar kare ta. Fahimtar hatsarin, Annabi SAW ya umurci Sahabbansa da ke Makkah da su fara yin hijira zuwa Yathrib a gungu-gungu domin kada su tsorata Kuraishawa.\n\nDarasi: sadaukarwa ta gaskiya tana ɗaukar nauyi. Ansar (\"Masu Taimaka\" na Madina) sun yi alkawalin rayuwarsu da gidajensu kafin su sami wani abu, kawai saboda imani. Karimcinsu zai zama abin koyi na ‘yan’uwantaka na Musulunci – wanda ake tunawa da shi a “Hijira zuwa Madina” wanda ya biyo baya, inda suka tarbi muhajirai a matsayin iyali.",
    location: "Mina",
  },
  {
    title: "Hijira zuwa Madina",
    body: 'Lokacin da Kuraishawa suka yi niyyar kashe Annabi SAW, sai Allah ya ba shi izinin yin hijira. Ya tashi tare da babban amininsa Abubakar (Allah Ya yarda da shi), ya bar Ali a kan gadonsa ya mayar da dukiyar mutane. Su biyun sun buya tsawon dare uku a cikin kogon Thawr yayin da mahara suka matso kusa da su Abubakar ya ji tsoronsu – sai Annabi SAW ya kara tabbatar masa da cewa, “Me kake tunanin biyu, na ukun su Allah ne? Wannan lokacin yana a cikin Sahihul Bukhari 3653 kuma ya zo a cikin Alkur’ani cewa: “… na biyun biyu, a lokacin da suke cikin kogo, a lokacin da ya ce wa abokinsa, ‘Kada ka yi bakin ciki, lallai Allah yana tare da mu” (k:9:40).\n\nSuka isa Quba, inda aka gina masallacin farko, sannan suka shiga Yathrib - daga nan kuma al-Madina al-Munawwarah, "Birnin Radiant." Annabi Sallallahu Alaihi Wasallama ya haxa kowane Muhajiri (Muhajir) da mataimaka (Ansari) cikin ‘yan’uwantaka; wannan karamci ya cika har Sa’ad bn al-Rabi’ ya ba da rabin dukiyarsa ga Abdurrahman bn Awf, wanda maimakon haka ya nemi a nuna masa kasuwa (Sahihul Bukhari 3780/3906).\n\nHijira ta kasance mai muhimmanci har daga baya Umar ya sanya ta zama farkon kalandar Musulunci - shekara ta 1 bayan hijira. Darasi: Wani lokaci imani yana bukatar barin komai ga Allah, da dogaro da cewa yana tare da masu gaskiya, da sake gina ‘yan’uwantaka maimakon jini.',
    location: "Madinah",
  },
  {
    title: "Kundin Tsarin Mulkin Madina",
    body: "Da ya isa garin da yakin kabilanci ya ruguza, Annabi SAW bai jagoranci musulmi kawai ba - ya kafa al'umma. Ya tsara wata yarjejeniya a rubuce, wadda aka tanadar a cikin seerah na Ibn Ishaq wadda aka fi sani da Sahifah ko Tsarin Mulkin Madina, inda ya hade Muhajirun, da Ansar, da Yahudawa na birnin zuwa wata yarjajjeniyar kare juna.\n\nSharuɗɗansa sun kasance masu ban sha'awa a lokacinsu: ƙungiyoyi sun kafa \"al'umma ɗaya (al'ummah)\" don manufar yarjejeniyar, kowace ƙungiya ta kiyaye addininta, an mayar da sabani zuwa ga Annabi SAW, zalunci da zalunci an haramta, kuma duk sun yi alkawarin kare birnin daga hare-haren waje. Ta yadda ya sanya Madina ta zama kasa ta gari mai hakki da aiki da aka amince da ita a maimakon zubar da jini mara iyaka.\n\nDarasi: Musulunci ba ibada ce ta kebanta kadai ba, a'a, tsari ne na adalci na al'umma. Annabi ﷺ ya misalta zaman tare na jam’i, da tsarin dokar da aka yarda da ita kan vendetta na kabilanci, da kuma girmama alkawura - ƙa’idodin da za a gwada a cikin shekaru masu zuwa. Yana cika ‘yan’uwantakar “Hijira zuwa Madina” ta hanyar shimfida adalci ga daukacin garin.",
    location: "Madinah",
  },
  {
    title: "Yakin Badar",
    body: "A shekara ta biyu bayan Hijira, an ba da izinin yin yaƙi don kariyar kai (Alkur'ani 22:39). A ranar 17 ga watan Ramadan shekara ta 2 bayan hijira, rundunar musulmi ta kimanin mutane 313 - marasa makami, da dawakai kadan kawai - sun hadu da sojojin Kuraishawa kusan dubu daya a rijiyoyin Badar, kudu maso yammacin Madina. Shi ne babban yakin farko na Musulunci.\n\nA kan rashin jituwar musulmi sun yi nasara sosai, kuma an kashe da dama daga cikin masu tsananta wa Kuraishawa. Kur’ani ya siffata cin nasara a matsayin wata alama, ba kawai aikin soja ba: “Allah ya riga ya ba ku nasara a Badar, alhali kuwa kuna raunana, saboda haka ku bi Allah da takawa, tsammaninku za ku yi godiya” (Alkur’ani 3:123), ya kuma bayyana taimakon mala’iku (Alkur’ani 3:124–125). Badar ya kafa al'ummar matasa a matsayin babban iko a Larabawa.\n\nDarasi: Sakamako na Allah ne, ba na lambobi ko kayan aiki ba. Ana tunawa da Badar a matsayin “ranar tantancewa” (yawm al-furqan), ranar da aka kebance gaskiya da karya – hujjar cewa tawakkali na gaske ga Allah tare da kokari na gaskiya shi ne abin da ya dace. Juyawar da aka yi a Uhudu a shekara mai zuwa zai koyar da ƙarin darasi.",
    location: "Badar",
  },
  {
    title: "Yakin Uhudu",
    body: "Shekara guda bayan Badar Kuraishawa ta dawo daukar fansa tare da babbar runduna, bangarorin biyu suka hadu a gindin dutsen Uhud kusa da Madina. Manzon Allah SAW ya dora maharba hamsin a kan wani tsauni tare da umarni masu tsauri akan kada su bar matsayinsu, komai ya faru. A farkon yakin musulmi ne ke da rinjaye; amma ganin yadda abokan gaba suka gudu, sai akasarin maharba suka bar ofishinsu domin tattara ganima. Dawakan kuraishawa a karkashin Khalid bn al-Walid (wanda har yanzu bai musulunta ba) suka zagaya gefen gefen da ba a bayyana ba, ruwan ya rikide ya zama rana mai tsada, mai zafi.\n\nSahabbai da dama sun yi shahada, daga cikinsu akwai baffan Manzon Allah Hamzah (Allah Ya yarda da shi), “Zakin Allah”. Shi kansa Annabi SAW ya samu rauni, hakori ya karye kuma fuskarsa ta zubar da jini. Bayan haka Alkur'ani ya yi magana kan koma bayan da aka samu a zahiri, inda ya bayyana cewa jarrabawa ce da kuma sakamakon saba wa umarni da kwadayin duniya (Alkur'ani 3:152; 3:165-166).\n\nDarasi: Uhudu shine babban darasi a cikin tarbiyya da biyayya. Wani mataki na rashin da'a, komai kankantarsa, bai yi kusan nasara ba. Kuma amma Allah bai yashe su ba, Ya karantar da su, kuma Ya gafarta musu, kuma Ya tãra su. Cin nasara, fuskantar gaskiya, zai iya zama darasi fiye da nasara.",
    location: "Dutsen Uhud",
  },
  {
    title: "Yakin Rarara",
    body: 'A cikin shekara ta biyar, kawancen Kuraishawa, da sauran kabilun Larabawa, da gungun makiya - "Kungiyoyi" (al-Ahzab) - suka tattara karfi mafi girma da aka gani a Larabawa, watakila mai karfi dubu goma, don halakar da Madina gaba daya. Da yake fuskantar abokan gaba da ya fi girma da yawa ba zai iya haduwa a fili ba, Manzon Allah SAW ya karbi shawarar sahabi Salman al-Farisi (Allah Ya yarda da shi) na sahabi Farisa (Allah Ya yarda da shi) na ya tona wani rami mai fadi a kan hanyoyin arewa da aka fallasa zuwa birnin - dabarar Larabawa ba su taba cin karo da ita ba.\n\nRamin ya dakatar da kewaye. Sakon sanyi da yunwa da tsoro sun biyo baya, kuma Kur\'ani a fili ya yi bayanin jarrabawar muminai a cikin suratu Ahzab cewa: "...lokacin da idanu suka karkata saboda tsoro, zukata suka kai ga makogwaro" (Qur\'ani 33:10). Daga karshe dai wata iska mai tsananin zafi da rashin jituwa ta cikin gida ta warwatsa rundunonin sojojin hadin gwiwa, suka ja da baya ba tare da an gwabza fada ba. Kur\'ani ya ba da tabbacin ceto ga Allah, wanda "ya aiko musu da iska da runduna ba ku gani ba" (Alkur\'ani 33:9).\n\nDarasi: shawarwari na hikima (shura) da buɗaɗɗen ra\'ayi mai kyau daga kowa - a nan, injiniyan baƙo - ɓangare ne na imani. Kuma idan ƙoƙarin ɗan adam ya cika, kuɓuta har yanzu yana zuwa daga Allah. Wannan watsewar yaƙin ya kawo ƙarshen iyawar Kuraishawa na kai farmakin.',
    location: "Madinah",
  },
  {
    title: "Yarjejeniyar Hudaibiyyah",
    body: "A shekara ta shida Manzon Allah ﷺ ya tashi tare da wasu Sahabbai kimanin 1,400 don yin aikin Umra, ba wai don yin yaqi ba, suka shiga cikin harama domin bayyana niyyar aminci. Kuraishawa sun tare su a wani wuri da ake kira Hudaibiyyah, a gefen haramin. Bayan tattaunawa mai tsanani sai aka amince da tsagaita wuta na tsawon shekaru goma akan sharuddan da suka shafi sahabbai da dama, suna wulakanta su: Musulmi za su juya baya a waccan shekarar su zo mai zuwa; duk wanda ya gudu daga Kuraishawa zuwa ga musulmi za a mayar da shi, amma ba a mayar da shi ba.\n\nAmma duk da haka Allah ya bayyana a kan komowar cewa wannan yarjejeniya “nasara ce bayyananna” (Qur’an 48:1, suratu al-Fath). Daga baya Sahabbai sun ce ba su taba ganin wata nasara da ta fi girma ba - domin a cikin zaman lafiyar da ya biyo baya, mutane sun gauraya cikin 'yanci, suka ji sakon cikin natsuwa, suka shiga Musulunci da yawa fiye da na tsawon shekarun da suka gabata; A cikin Sahihul Bukhari 4606 ne aka rubuta rahoton Al-Barra' bn Azib a kan haka.\n\nDarasi: abin da ke kama da koma baya zai iya zama mafi girma budewa. Manzon Allah ﷺ ya zavi hasarar da ta bayyana na gajeriyar lokaci don alheri mai tsawo, kuma ya girmama ciniki mai tsanani ko da ta yi tsiro. Hakuri, kamewa, da kiyaye maganar mutum na iya cimma abin da sabani ba zai iya ba.",
    location: "Hudaibiyyah",
  },
  {
    title: "Tafiya zuwa Khaybar",
    body: "Ba da dadewa ba bayan Hudaibiyyah, Manzon Allah ﷺ ya juya zuwa Khaybar, wata arziƙi mai arziƙi mai kagara daga arewacin Madina. Khaybar ya zama ginshiƙin ƙiyayya - gida ga ƙabilun da suka taimaka wajen shirya yaƙin Confederates na Madina tare da ci gaba da kulla makirci ga al'ummar musulmi. An yi yakin neman zaben ne domin kawo karshen wannan barazana.\n\nGaruruwan sun fado daya bayan daya bayan an gwabza kazamin fada; An bai wa Ali bn Abi Talib (Allah Ya yarda da shi) tuta a ranar qiyama. Bayan haka Annabi ﷺ ya ƙyale mazauna ƙasar su zauna su ci gaba da noman ƙasar don musanyawa da rabon amfanin gonarta - tsarin da ya tabbatar da abinci da kwanciyar hankali ga Madina maimakon korar kowa. A nan ne ma wata mata ta yi yunkurin sanya masa guba da rago, wanda aka gargade shi.\n\nDarasi: tsaro da kiyaye yarjejeniya sun tafi kafada da kafada. Matakin ya sabawa wani tabbataccen iko na abokan gaba, duk da haka ya ƙare a cikin daidaitawa wanda zai bar waɗanda aka sha kaye su ci gaba da rayuwarsu. Ƙarfi a Musulunci ana nufin tabbatar da aminci da adalci, ba don halakarwa ba.",
    location: "Khaibar",
  },
  {
    title: "Yakin Makkah",
    body: "A lokacin da abokan Kuraishawa suka karya sharuddan Hudaibiyya ta hanyar kai hari ga wata kabilar da ke kawance da musulmi, sulhun ya lalace. A cikin watan Ramadan na shekara ta takwas Manzon Allah ﷺ ya yi tattaki zuwa Makka da runduna dubu goma - mafi girman runduna - kuma birnin da ya yi zalunci, ya kaurace masa, da yakarsa tsawon shekaru ashirin ya mika wuya ba tare da zubar da jini ba.\n\nA karshe ya tsaya yana mai nasara akan mutanen da suka kore shi, ya tambayi mutanen Makka me suke tsammani daga gare shi. Sai suka yi fatan rahamar wani ɗan’uwa maɗaukaki, sai ya amsa da faxin Yusufu ga ‘yan’uwansa: “Babu laifi a kanku a yau” – kuma ya ce: “Ku tafi, lalle ne ku, kuna ’yantattu.” Ya shiga dakin Ka’aba ya share ta daga gumaka guda 360, yana mai karanta “Gaskiya ta zo, kuma karya ta gushe” (k:17:81), ya maido da haramin Ibrahim zuwa ga tsarkakkiyar bautar Allah. Suratun Nasr (Alkur'ani 110) yayi magana akan wannan lokacin da mutane \"suna shiga addinin Allah jama'a.\"\n\nDarasi: wannan shi ne kolin rahama da gafarar annabci. Da cikakken ikon ɗaukar fansa, ya yafe. Mumini yana sanin cewa masu ƙarfi su ne masu gafartawa idan sun sami damar yin azaba, kuma manufar ba ta kasance ramuwa ba face shiriya.",
    location: "Makkah",
  },
  {
    title: "Tafiya zuwa Tabuka",
    body: "A cikin shekara ta tara, rahotanni sun isa birnin Madina na yuwuwar yunkurin Rumawa (Romawa) a kan iyakar arewa. A cikin tsananin zafi na lokacin rani, lokacin da girbi ya cika kuma tafiyar ta yi tsayi da wuya, Annabi SAW ya yi kira ga rundunar da ya fi girma - watakila dubu talatin - su yi tattaki zuwa arewa zuwa Tabuka. Wannan shi ne “lokacin wahala” (Qur’ani 9:117), kuma ya gwada ikhlasi kamar ba komai a da.\n\nBa a yi yaƙi ba; Nuna azama ya isa, kuma da yawa daga cikin sarakunan arewa sun yi yarjejeniya da Madina. Amma ana tunawa da yaƙin neman zaɓe sama da duka don abin da ya bayyana game da zukatan mutane. Kur’ani ya kebance da yawa daga cikin Suratul Taubah a kansa – yabon wadanda suka ba da komai (An ruwaito cewa Abubakar ya ba da dukkan dukiyarsa), da fallasa munafukai da suka kirkiri uzuri na zama, da kuma ba da labari mai ratsa jiki na muminai salihai guda uku, ciki har da Ka’ab bn Malik, wadanda suka yarda da cewa ba su da uzuri kuma an gafarta musu bayan jarrabawa mai tsanani: 9:18.\n\nDarasi: biyayya yana da sauƙi idan ya ji daɗi; gaskiyarsa tana nuna lokacin da tsada. Tabuk ya raba masu gaskiya da masu ba da uzuri kuma ya nuna kyakkyawan ƙarshen gwagwarmayar bautar gumaka a Larabawa. Gaskiya - hatta gaskiyar yarda da gazawar mutum - ita ce hanyar komawa zuwa ga Allah.",
    location: "Tabuk",
  },
  {
    title: "Hajjin bankwana",
    body: "A shekara ta goma Manzon Allah ﷺ ya yi aikin Hajjinsa daya tilo, tare da sahabbai sama da dubu dari, yana karantar da su a kai tsaye. Yana tsaye a filin Arafah ya gabatar da Hudubar bankwana (Khutbat al-Wada'), takaitacciyar duk wani abu da Musulunci ya zo ya tabbatar da shi.\n\nYa bayyana tsarkakar ran kowane mutum da dukiyarsa da darajarsa – “Jininku da dukiyoyinku suna da tsarki kamar wannan rana, wannan da wannan qasa.” (Sahihul Bukhari 1741). Ya kawar da fitinar jini da maslaha (riba) na Jahiliyyah, ya kuma yi umarni da kyautatawa mata a matsayin amana daga Allah, ya tunatar da su cewa babu Balarabe da ya fi wanda ba Balarabe ba sai da takawa, ya ce su yi riko da Alkur’ani. A cikin wannan aikin hajjin ne a ranar Arafah da ta faxi ranar Juma’a, Allah Ya saukar da “A yau na kammala muku addininku.” (Alkur’ani 5:3) — ayar Umar ya tuna kuma ta yi kwananta daidai (Sahihul Bukhari 45).\n\nDarasi: Hudubar bankwana ita ce ka’idar Musulunci ta mutunta mutum, adalci da daidaito, wanda aka hatimce ta da sanarwar cewa addini ya cika. Aikin mumini daga nan ba shine ya karawa kansa ba sai dai ya rayu.",
    location: "Arafah",
  },
  {
    title: "Wucewa yayi",
    body: "Bayan 'yan watanni da hajjin bankwana Annabi SAW ya kamu da zazzabi. A kwanakinsa na karshe ya nemi izinin matansa a shayar da shi a dakin Aisha (Allah Ya yarda da ita), kuma ya nada Abubakar ya jagoranci Sallah. A safiyarsa ta karshe ya ja labule domin yaga jerin gwanon muminai suna addu'a yana murmushi, yana murna da al'ummarsa, sannan ya bar ta ta fadi. Ya rasu a ranar litinin 12 ga Rabi al-Awwal shekara ta 11 bayan hijira, kansa yana kwance a tsakanin qirji da hantar Aisha – kamar yadda ita da kanta ta rawaito a cikin Sahihul Bukhari 4449/4451.\n\nBakin cikin Madina ya yi yawa, har Umar ya ki amincewa da farko. Sai Abubakar ya tashi ya sumbaci fuskar Manzon Allah (saww) sannan ya yi wa mutane magana da kalmomin da suka tabbatar da al’umma gaba daya kuma suna cikin Sahihul Bukhari 1241/1242 cewa: “Wanda ya kasance yana bauta wa Muhammadu, to Muhammadu ya rasu, amma wanda ya bauta wa Allah, to, Allah Rayayye ne, kuma ba Ya mutuwa”. Ya karanta “Muhammad bai zama ba face manzo, manzanni sun shuɗe gabaninsa…” (k:3:144).\n\nDarasi: Sakon ya cika kuma yanzu na umma ne. Annabi SAW ya kasance mai mutu’a, amma abin da ya zo da shi – Alkur’ani da Sunnarsa – ba haka ba ne. Martanin Abubakar ita ce amsa mai dawwama ga bakin ciki: nasabarmu ga Allah ne, wanda ba ya mutuwa, kuma hanyar son Annabi SAW ita ce mu rayu da shiriyarsa.",
    location: "Madinah",
  },
];
