// French translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_FR: DeepPartial<SeerahEvent>[] = [
  {
    title: "L'Arabie avant l'Islam (la Jahiliyyah)",
    body: "Pour comprendre le Prophète ﷺ, vous devez d’abord imaginer le monde dans lequel il a été envoyé. L'Arabie du VIe siècle était une terre de tribus dispersées sans État central, liées entre elles par le lignage, l'honneur et le sanctuaire de la Ka'bah à Makkah - un sanctuaire construit par Ibrahim et Isma'il pour le culte du Dieu unique, mais désormais entouré de quelque trois cent soixante idoles.\n\nCette époque est appelée Jahiliyyah, « l’âge de l’ignorance » – non pas parce que les Arabes manquaient d’intelligence (leur poésie et leur mémoire étaient extraordinaires), mais parce qu’ils manquaient de conseils. Les querelles tribales pouvaient durer des générations, les forts s'en prenaient aux faibles, et les filles étaient parfois enterrées vivantes par honte ou par peur de la pauvreté – une pratique que le Qur'an condamnerait plus tard directement (Qur'an 81 : 8-9). A côté de l'idolâtrie, quelques « hunafa » recherchaient encore le pur monothéisme d'Ibrahim, et de petites communautés juives et chrétiennes vivaient à travers la péninsule.\n\nLa leçon : la révélation n'est pas descendue dans le vide mais dans une société réelle avec de profondes blessures, et la première chose qu'elle a guérie a été la relation entre l'être humain et son Créateur. Gardez ce contexte à l’esprit au fur et à mesure que la chronologie se déroule : presque chaque réforme du Prophète ﷺ est une réponse directe à une injustice de la Jahiliyyah.",
    location: "Arabie",
  },
  {
    title: "Naissance à Makkah",
    body: "Le Prophète ﷺ est né à Makkah l'année de l'éléphant (Am al-Fil), ainsi nommé parce que cette année-là, Abraha, le gouverneur abyssin du Yémen, a fait marcher une armée avec des éléphants pour détruire la Ka'bah et a été miraculeusement refoulé - un événement que le Qur'an rappelle dans la sourate al-Fil (Qur'an 105). Au cours de cette année chargée, un enfant est né dans la tribu de Quraysh et son clan le plus honoré, Banu Hashim.\n\nIl était déjà orphelin à la naissance : son père Abdullah était décédé quelques mois plus tôt alors qu'il faisait du commerce. Sa mère, Aminah bint Wahb, l'a nommé Muhammad – « celui qui est très loué » – un nom presque inconnu parmi les Arabes. Conformément à la coutume mecquoise, il fut envoyé pour être soigné et élevé en plein air du désert parmi les Banu Sa'd, sous la garde de Halimah as-Sa'diyyah.\n\nLa leçon pour un croyant : la grandeur aux yeux d'Allah n'a rien à voir avec la sécurité du monde. Le dernier Messager a commencé sa vie sans père et allait bientôt le devenir sans mère, mais Allah Lui-même était son tuteur : « Ne t'a-t-Il pas trouvé orphelin et ne t'a-t-Il pas trouvé orphelin et ne t'a-t-Il pas donné refuge ? » (Qur'an 93 : 6). Voir aussi « Décès de sa mère » et « Tutelle d'Abu Talib » qui suivent.",
    location: "Makkah",
  },
  {
    title: "Décès de sa mère",
    body: "Quand il avait environ six ans, Aminah emmena son fils rendre visite à ses proches à Yathrib (plus tard Madinah) et voir la tombe de son père. Sur le chemin du retour, elle tomba malade et mourut à un endroit appelé Abwa', entre Makkah et Madinah, et y fut enterrée. Le jeune Muhammad ﷺ avait désormais perdu ses deux parents.\n\nIl fut ramené à Makkah par Umm Ayman, le serviteur affranchi de la famille, et placé sous la garde de son grand-père Abd al-Muttalib, le chef respecté de Quraysh, qui l'aimait profondément et le faisait asseoir à côté de lui à la Kaaba.\n\nLa leçon : le Prophète ﷺ a goûté très tôt et à plusieurs reprises au chagrin que portent tant d’êtres humains – le deuil, le déplacement, la dépendance à l’égard des autres. Cela faisait partie de sa préparation. Un cœur qui a connu la perte est un cœur qui peut ressentir de la compassion pour l’orphelin, la veuve et l’étranger, et sa communauté sera plus tard construite précisément sur cette miséricorde. Ce fil continue dans \"L'année du chagrin\".",
    location: "Abwa'",
  },
  {
    title: "Tutelle d'Abu Talib",
    body: "Deux ans après sa mère, son grand-père Abd al-Muttalib est également décédé, alors que le garçon avait environ huit ans. Sur son lit de mort, il confia son petit-fils bien-aimé à son fils Abu Talib, l'oncle paternel du Prophète. Bien qu'Abu Talib ne soit pas riche, il emmena l'enfant dans sa propre maison et le traita comme l'un de ses enfants les plus chers.\n\nAbu Talib restera son protecteur pendant plus de quarante ans, tout au long des années de persécution les plus dures à Makkah. C'est lui qui emmena le jeune Mahomet ﷺ dans des voyages commerciaux en Syrie, où, selon le récit bien connu, le moine Bahira remarqua chez lui des signes de prophétie (un rapport que la Seerah conserve, bien que ses détails soient transmis avec une force variable).\n\nLa leçon : Allah a placé des personnes loyales et honorables autour de Son Prophète ﷺ à chaque étape. Les décennies de protection d'Abu Talib ont été une miséricorde – un rappel que soutenir la vérité et la parenté est une position noble, même pour ceux qui n'ont pas encore cru, et que nous devons honorer ceux qui nous abritent. Sa perte plus tard, au cours de l’Année du chagrin, allait tout changer.",
    location: "Makkah",
  },
  {
    title: "Mariage avec Khadija",
    body: "En tant que jeune homme, Muhammad ﷺ s'est forgé une réputation à travers la Makkah qu'aucune richesse ne pouvait acheter : al-Sadiq, le véridique, et al-Amin, le digne de confiance. Les gens déposaient leurs objets de valeur auprès de lui pour les garder en sécurité et faisaient absolument confiance à sa parole, même ceux qui adoraient différents dieux.\n\nKhadijah bint Khuwaylid (qu'Allah l'agrée), une noble et prospère marchande de Quraysh, l'engagea pour conduire sa caravane en Syrie. Impressionnée par son honnêteté et son caractère, elle lui envoya une demande en mariage par l'intermédiaire de son amie Khawlah bint Hakim. Il avait environ vingt-cinq ans et elle environ quarante ans ; leur mariage est devenu un amour profond et un partenariat. Elle lui donna ses enfants et resta sa seule épouse pendant environ vingt-cinq ans, jusqu'à sa mort.\n\nLa leçon : le caractère est le fondement de tout ce qui a suivi. Bien avant qu'il ne soit appelé prophète, Makkah le connaissait déjà comme l'homme le plus honnête d'entre eux — c'est pourquoi, lors de la première révélation, la confiance instantanée de Khadijah en lui fut si décisive (voir « La première révélation »). L'intégrité d'un croyant dans ses relations ordinaires est en soi une forme de Da'wah.",
    location: "Makkah",
  },
  {
    title: "Hilf al-Fudul et la pierre noire",
    body: "Deux incidents de sa vie pré-prophétique montrent les valeurs sur lesquelles il bâtira plus tard une nation. Premièrement, le Hilf al-Fudul : un pacte solennel juré par plusieurs clans de Quraysh de se tenir aux côtés de toute personne opprimée à Makkah, locale ou étrangère, jusqu'à ce que ses droits soient rétablis. Le Prophète ﷺ y a participé et a déclaré plus tard qu'il répondrait toujours à un tel pacte même en Islam – parce qu'il défendait la justice.\n\nDeuxièmement, la reconstruction de la Kaaba après une inondation. Lorsque les clans en sont presque venus aux mains pour l’honneur de remettre en place la Pierre Noire sacrée (al-Hajar al-Aswad), ils ont accepté le jugement du prochain homme à entrer – et c’était Muhammad ﷺ. Sa solution était célèbre pour sa sagesse : il posa la pierre sur un tissu et demanda à un chef de chaque clan d'en soulever un coin, puis de la mettre en place de ses propres mains, afin que tous partagent l'honneur et qu'aucun ne soit lésé.\n\nLa leçon : la justice et la résolution des conflits étaient son instinct avant que la révélation ne les confirme. Un croyant est celui qui défend les lésés et trouve des moyens de s'unir plutôt que de se diviser – le Hilf al-Fudul préfigure la communauté juste qu'il établirait après la Hijrah.",
    location: "Makkah",
  },
  {
    title: "La première révélation",
    body: "Vers la fin de la trentaine, le Prophète ﷺ se retirait de plus en plus pour adorer et réfléchir dans la grotte de Hira, sur la montagne de Jabal an-Nur, à l'extérieur de Makkah. Là, vers l'âge de quarante ans, pendant le mois de Ramadan, l'ange Jibril apparut et lui ordonna : « Lis ! Il répondit qu'il ne savait pas lire ; l'ange l'embrassa fermement trois fois et révéla les premiers versets de la sourate al-'Alaq — « Lis au nom de ton Seigneur qui a créé… » (Qur'an 96 : 1-5), les tout premiers mots du Qur'an.\n\nIl rentra chez lui en tremblant, et Khadijah l'enveloppa et le rassura avec des paroles qui révèlent sa foi et son caractère : Allah ne le déshonorerait jamais, car il gardait les liens de parenté, portait les fardeaux des autres et aidait les méritants. Elle l'emmena chez son cousin Waraqah ibn Nawfal, un homme âgé instruit dans les écritures antérieures, qui reconnut le visiteur comme étant le même \"Namus\" (ange) qui était venu à Musa et lui dit que c'était la prophétie promise. Cet épisode entier est enregistré dans Sahih al-Bukhari 3.\n\nLa leçon : la révélation a commencé non pas avec une prétention au pouvoir mais avec le mot « Lire » – une religion fondée sur la connaissance et l’humilité. Et notez qui a cru le premier : une femme et une maison honnête. La vérité est reconnue par ceux qui vivent déjà sincèrement.",
    location: "Grotte de Hira",
  },
  {
    title: "Des années de prédication privée",
    body: "Après les premières révélations, il y a eu une pause (fatrah), puis Allah a ordonné au Prophète ﷺ de commencer à appeler les gens à L'adorer seul. Pendant environ les trois premières années, cet appel était discret et personnel – étendu à la famille proche et aux amis de confiance plutôt que proclamé dans la rue.\n\nLes premiers croyants, les « as-Sabiqun al-Awwalun » (les premiers), venaient de toutes les couches de la société : Khadijah, sa femme ; son jeune cousin Ali ibn Abi Talib ; son serviteur affranchi et fils adoptif Zayd ibn Harithah ; et son fidèle ami Abu Bakr as-Siddiq (qu'Allah soit satisfait d'eux tous). Abu Bakr, à son tour, en a amené beaucoup d’autres à l’Islam. Ils se réunissaient et priaient discrètement, souvent dans la maison d'al-Arqam, près de la Kaaba.\n\nLa leçon : l’Islam s’est développé d’abord grâce à la confiance et aux relations, et non au spectacle. Remarquez l’ampleur de ces premiers cœurs – une femme riche, un enfant, un esclave affranchi, un marchand – un avant-goût d’une foi qui effacerait les distinctions de race et de rang. La Da'wah commence près de chez soi, avec sincérité et patience.",
    location: "Makkah",
  },
  {
    title: "L’appel public à l’Islam",
    body: "Lorsqu'Allah révéla « Et avertissez vos proches parents » (Qur'an 26 : 214), le Prophète ﷺ gravit le mont Safa à côté de la Kaaba et appela les clans de Quraysh. Il a d'abord demandé s'ils le croiraient s'il disait qu'une armée se cachait derrière la colline ; ils répondirent qu'ils ne l'avaient jamais vu mentir. Puis il les avertit d'un châtiment à venir et les appela à l'adoration d'Allah Seul.\n\nCe message ouvert a frappé au cœur de l'ordre de Makkah. Les idoles n'étaient pas seulement une religion, mais aussi un moyen de subsistance et un prestige : le statut de la ville en tant que gardienne du sanctuaire attirait les pèlerins et le commerce. Dire que les idoles étaient impuissantes revenait à remettre en question à la fois l’économie, l’ascendance et la fierté de Quraysh. À partir de là, la persécution s'est fortement intensifiée, frappant plus durement les faibles et les esclaves parmi les croyants, tels que Bilal ibn Rabah et la famille de Yasir.\n\nLa leçon : la vérité exprimée clairement ébranlera les intérêts bien établis. Le Prophète ﷺ a d'abord fait appel à leur propre témoignage selon lequel il était honnête – raison et intégrité avant la menace – et a ensuite tenu bon. Défendre le tawhid peut coûter du confort mondain, comme l'ont appris les croyants de Makkah. Ces difficultés mènent directement à la « migration vers l’Abyssinie ».",
    location: "Mont Safa",
  },
  {
    title: "Migration vers l'Abyssinie",
    body: "Alors que la persécution devenait insupportable, le Prophète ﷺ a dit à un groupe de ses compagnons de chercher refuge auprès du Négus (an-Najashi), le juste roi chrétien d'Abyssinie (Éthiopie moderne), affirmant que dans son pays, personne n'était lésé. Un premier groupe a traversé la mer Rouge, suivi d’une deuxième migration plus importante : la première hijrah de l’Islam.\n\nLorsque Quraysh envoya des envoyés exigeant que les réfugiés soient restitués, le Négus les convoqua. Jafar ibn Abi Talib (qu'Allah l'agrée) a parlé au nom des musulmans, décrivant comment ils étaient sortis de l'ignorance pour adopter une foi de vérité, de miséricorde et de bonne moralité, puis il a récité des versets de la sourate Maryam sur Jésus et sa mère. Le roi chrétien a pleuré, a tracé une ligne sur le sol et a déclaré que la différence entre leur foi et la sienne n’était pas plus grande que cela – et il a refusé de les abandonner.\n\nLa leçon : c'est un jalon de tolérance religieuse et de construction de ponts avec des Gens du Livre sincères. Il enseigne également que chercher à se protéger de l’oppression sous une autorité juste et non musulmane est tout à fait légitime. Notez également que l’argument qui a gagné était la beauté du caractère et la parole d’Allah récitée – et non la force.",
    location: "Abyssinie",
  },
  {
    title: "Le boycott de Banu Hashim",
    body: "Incapables d'arrêter la propagation de l'Islam ou d'atteindre le Prophète ﷺ alors que son clan le protégeait, les dirigeants de Quraysh ont eu recours à la punition collective. Ils ont écrit un pacte et l'ont accroché dans la Kaaba, s'engageant à boycotter tout le clan des Banu Hashim (et leurs alliés Banu al-Muttalib) : pas de mariage avec eux, pas de commerce, pas de relations sociales, jusqu'à ce qu'ils rendent Muhammad ﷺ.\n\nPendant environ trois ans, le clan – croyants et non-croyants de Hashim – fut confiné dans la vallée montagneuse de Shi'b Abi Talib, endurant une faim si grave que les cris des enfants se faisaient entendre et que les gens mangeaient des feuilles. Le boycott a finalement échoué lorsque plusieurs hommes Qurayshi équitables l'ont publiquement répudié et que le parchemin s'est avéré avoir été rongé, à l'exception des mots dans lesquels le nom d'Allah apparaissait.\n\nLa leçon : le mensonge va trop loin. La cruauté du boycott n'a fait que révéler l'injustice des persécuteurs et durcir la détermination des croyants. Cela montre également l’honneur de quelques individus justes au sein d’une société hostile qui ont brisé les rangs pour mettre fin à une atrocité – un rappel que la conscience peut survivre même dans l’opposition la plus féroce.",
    location: "Shi'b Abi Talib",
  },
  {
    title: "L'année du chagrin",
    body: "Peu de temps après la fin du boycott, le Prophète ﷺ a subi deux pertes dévastatrices en peu de temps, et l'année est devenue connue sous le nom d'Am al-Huzn, l'année du chagrin. Tout d’abord, son oncle et protecteur de toujours, Abu Talib, est mort – l’homme dont la position l’avait protégé des Quraysh pendant des décennies. Puis Khadijah (qu'Allah l'agrée), son épouse depuis vingt-cinq ans, sa première croyante et son plus proche soutien, est également décédée.\n\nAvec la disparition de sa protection sociale et de son ancrage émotionnel, Quraysh est devenu plus audacieux dans ses abus. C'est à cette époque qu'il se rendit dans la ville de Ta'if, espérant que ses habitants accepteraient le message ; au lieu de cela, ils l'ont chassé et ont demandé aux enfants de lui jeter des pierres jusqu'à ce que ses pieds saignent. Même alors, lorsqu'on lui proposa la destruction de la ville, il pria pour que leurs descendants adorent un jour Allah – une miséricorde qui le définit.\n\nLa leçon : même les prophètes sont éprouvés tour à tour par le chagrin et le rejet, et la réponse est la patience sans amertume. La perte humaine ne signifie pas l’abandon divin ; le soulagement suivit de près, dans le voyage nocturne qui suivit. Voir « Al-Isra wal-Mi'raj ».",
    location: "Makkah",
  },
  {
    title: "Al-Isra wal-Mi'raj",
    body: "Après l’Année de la Douleur est venue une nuit d’honneur extraordinaire. En Israël, le Prophète ﷺ a été transporté en une seule nuit de la Mosquée sacrée de Makkah à al-Masjid al-Aqsa à Jérusalem – un événement avec lequel le Qur'an ouvre la sourate al-Isra (Qur'an 17 : 1). Là, il conduisit les premiers prophètes dans la salah. Puis, dans le Mi'raj, il fut élevé à travers les sept cieux, rencontrant des prophètes dont Adam, Musa et Ibrahim, et atteignit une station plus proche de son Seigneur que n'importe quel être créé.\n\nLe don central de cette nuit-là était les cinq salah quotidiennes. Comme indiqué dans le Sahih al-Bukhari 3887, il leur a d'abord été recommandé d'être cinquante ; sur les conseils de Moïse, le Prophète ﷺ revenait encore et encore pour demander du secours jusqu'à ce qu'ils soient réduits à cinq en pratique tout en portant la récompense de cinquante. Les érudits diffèrent sur la date exacte, la plupart la plaçant dans les années juste avant l'Hégire.\n\nLa leçon : le cadeau offert pour consoler un Prophète ﷺ en deuil était salah – notre propre ascension nocturne vers Allah. Les cinq salah quotidiennes n'étaient pas descendues par un ange sur terre mais montées au ciel pour les recevoir, signe de leur poids dans la vie du croyant.",
    location: "Jérusalem",
  },
  {
    title: "Le premier serment d'Al-Aqabah",
    body: "Chaque année, les pèlerins se rassemblaient à Makkah et le Prophète ﷺ présentait l'Islam aux tribus en visite. À un endroit appelé al-Aqabah près de Mina, un petit groupe d’hommes de Yathrib (Madinah) – une ville longtemps déchirée par les querelles entre ses tribus d’Aws et de Khazraj, et familière avec le monothéisme à travers sa communauté juive – a écouté, cru et transmis le message à sa maison.\n\nLa saison suivante, douze d'entre eux revinrent et donnèrent le premier engagement d'al-Aqabah : adorer Allah seul, ne pas voler, ne pas commettre de relations sexuelles illégales, ne tuer aucun enfant et obéir au Prophète ﷺ dans ce qui est juste. Il renvoya ensuite avec eux le jeune compagnon Mus'ab ibn Umayr (qu'Allah l'agrée) en tant que premier professeur et ambassadeur de l'Islam, et grâce à lui, la foi se répandit rapidement dans les foyers de Yathrib.\n\nLa leçon : la porte qui semblait fermée à Makkah s'est ouverte à Madinah. Remarquez comment la communauté s'est construite : par l'enseignement. Un jeune professeur dévoué, envoyé avec le Qur'an, a préparé une ville entière à devenir le berceau de l'Islam. Cela établit directement le Deuxième Serment et la Hijrah.",
    location: "Mina",
  },
  {
    title: "Le deuxième serment d'Al-Aqabah",
    body: "Un an après le premier engagement, une délégation beaucoup plus importante de Yathrib – soixante-treize hommes et deux femmes – est venue secrètement auprès du Prophète ﷺ à al-Aqabah pendant le pèlerinage. Cette fois, l'engagement est allé plus loin : ils se sont engagés à le protéger exactement comme ils protégeraient leurs propres femmes et enfants, et à accueillir dans leur ville les musulmans persécutés de Makkah.\n\nCe fut un tournant. Pour la première fois, la jeune communauté avait une patrie et un corps de personnes ayant juré de la défendre. Comprenant le danger, le Prophète ﷺ ordonna discrètement à ses compagnons de Makkah de commencer à émigrer vers Yathrib en petits groupes afin de ne pas alarmer les Quraysh.\n\nLa leçon : un engagement sincère entraîne des responsabilités. Les Ansar (les « Aides » de Madinah) ont promis leur vie et leur foyer avant d'avoir gagné quoi que ce soit, uniquement pour le bien de la foi. Leur générosité deviendra le modèle de fraternité islamique — rappelé dans « L'Hégire à Madinah » qui suit, où ils accueillirent les émigrés comme une famille.",
    location: "Mina",
  },
  {
    title: "L'Hégire à Madinah",
    body: "Lorsque Quraysh complota pour assassiner le Prophète ﷺ, Allah lui permit d'émigrer. Il partit avec son ami le plus proche, Abu Bakr (qu'Allah l'agrée), laissant Ali dans son lit pour restituer les dépôts des gens. Les deux hommes se cachèrent pendant trois nuits dans la grotte de Thawr tandis que leurs poursuivants s'approchaient si près qu'Abu Bakr craignit pour eux. Le Prophète ﷺ le rassura : « Que penses-tu de deux, dont le troisième est Allah ? Ce moment est enregistré dans le Sahih al-Bukhari 3653 et fait écho dans le Qur'an : « …le deuxième des deux, alors qu'ils étaient dans la grotte, quand il dit à son compagnon : 'Ne t'afflige pas, car Allah est avec nous' » (Qur'an 9 :40).\n\nIls atteignirent Quba, où fut construite la première mosquée, puis entrèrent à Yathrib – par la suite al-Madinah al-Munawwarah, « la Ville Rayonnante ». Le Prophète ﷺ a associé chaque émigrant (Muhajir) à un assistant (Ansari) dans des liens de fraternité ; la générosité était si complète que Sa'd ibn al-Rabi' proposa de partager la moitié de sa richesse avec Abdur-Rahman ibn Awf, qui demanda seulement à ce qu'on lui montre le marché (Sahih al-Bukhari 3780/3906).\n\nL’Hégire était si cruciale qu’Umar en a fait plus tard le début du calendrier islamique – l’année 1 AH. La leçon : parfois, la foi exige de tout laisser derrière soi pour Allah, de croire qu'Il est avec les sincères et de reconstruire sur la fraternité plutôt que sur le sang.",
    location: "Madinah",
  },
  {
    title: "La Constitution de Madinah",
    body: "Arrivé dans une ville détruite par la guerre tribale, le Prophète ﷺ ne se contenta pas de diriger les musulmans : il fonda une communauté. Il rédigea un accord écrit, conservé dans la Seerah d'Ibn Ishaq et connu sous le nom de Sahifah ou Constitution de Madinah, liant les Muhajirun, les Ansar et les tribus juives de la ville en un seul pacte de défense mutuelle.\n\nSes termes étaient remarquables pour l'époque : les parties formaient « une seule communauté (oumma) » aux fins du traité, chaque groupe gardait sa propre religion, les différends devaient être soumis au Prophète ﷺ, l'agression et l'injustice étaient interdites, et tous s'engageaient à défendre la ville contre les attaques extérieures. Cela a effectivement fait de Madinah une cité-État dotée de droits et de devoirs convenus plutôt que d’une vendetta sans fin.\n\nLa leçon : l’Islam n’est pas seulement un culte privé mais la juste organisation d’une société. Le Prophète ﷺ a modelé la coexistence pluraliste, la primauté du droit convenu sur la vendetta tribale et le respect des alliances – des principes qui seraient mis à l’épreuve dans les années de conflit à venir. Il complète la fraternité de « L'Hégire à Madinah » en étendant l'équité à l'ensemble de la ville.",
    location: "Madinah",
  },
  {
    title: "La bataille de Badr",
    body: "Dès la deuxième année après l'Hégire, l'autorisation de combattre en état de légitime défense avait été accordée (Qur'an 22 : 39). Le 17 Ramadan de l'an 2 de l'Hégire, une force musulmane d'environ 313 hommes – mal armés, avec seulement une poignée de chevaux – rencontra une armée Quraysh forte d'environ un millier de personnes aux puits de Badr, au sud-ouest de Madinah. Ce fut la première grande bataille de l'Islam.\n\nContre toute attente, les musulmans ont gagné de manière décisive et plusieurs des principaux persécuteurs de Quraysh ont été tués. Le Qur'an présente la victoire comme un signe, et non comme un simple exploit militaire : « Allah vous avait déjà donné la victoire à Badr alors que vous étiez faible, alors craignez Allah afin que vous soyez reconnaissants » (Qur'an 3 : 123), et décrit l'aide des anges (Qur'an 3 : 124-125). Badr a fait de la jeune communauté une véritable puissance en Arabie.\n\nLa leçon : les résultats appartiennent à Allah, et non aux chiffres ou à l’équipement. Badr est considéré comme « le jour du critère » (yawm al-furqan), le jour où la vérité et le mensonge ont été distingués – une preuve que ce qui compte est la confiance sincère en Allah avec un effort sincère. Le renversement d’Uhud l’année suivante enseignerait une leçon complémentaire.",
    location: "Badr",
  },
  {
    title: "La bataille d'Uhud",
    body: "Un an après Badr, Quraysh revint pour se venger avec une armée bien plus nombreuse, et les deux camps se rencontrèrent au pied du mont Uhud, près de Madinah. Le Prophète ﷺ a posté cinquante archers sur une colline avec l'ordre strict de ne jamais quitter leur position, quoi qu'il arrive. Au début de la bataille, les musulmans avaient le dessus ; mais voyant l'ennemi fuir, la plupart des archers quittèrent leur poste pour ramasser du butin. La cavalerie Quraysh dirigée par Khalid ibn al-Walid (pas encore musulman) a balayé le flanc exposé, et la marée s'est transformée en une journée coûteuse et douloureuse.\n\nDe nombreux compagnons furent martyrisés, parmi lesquels l'oncle bien-aimé du Prophète, Hamzah (qu'Allah l'agrée), « le Lion d'Allah ». Le Prophète ﷺ lui-même a été blessé, la dent cassée et le visage ensanglanté. Ensuite, le Qur'an a abordé franchement ce revers, expliquant qu'il s'agissait d'une épreuve et d'une conséquence de la désobéissance au commandement et de la convoitise du monde (Qur'an 3 : 152, 3 : 165-166).\n\nLa leçon : Uhud est la grande leçon de discipline et d'obéissance. Un seul acte d’indiscipline, aussi minime soit-il, a annulé une quasi-victoire. Pourtant, Allah ne les a pas abandonnés. Il les a enseignés, leur a pardonné et les a ralliés. La défaite, affrontée honnêtement, peut être plus instructive que la victoire.",
    location: "Mont Uhud",
  },
  {
    title: "La bataille de la tranchée",
    body: "Au cours de la cinquième année, une alliance de Quraysh, d'autres tribus arabes et de factions hostiles – les « confédérés » (al-Ahzab) – rassembla la plus grande force jamais vue en Arabie, forte d'environ dix mille hommes, pour détruire Madinah une fois pour toutes. Face à un ennemi bien trop grand pour être affronté dans une bataille ouverte, le Prophète ﷺ a accepté le conseil de son compagnon persan Salman al-Farisi (qu'Allah l'agrée) de creuser une large tranchée à travers les approches nord exposées de la ville – une tactique que les Arabes n'avaient jamais rencontrée.\n\nLa tranchée a stoppé le siège. Des semaines de froid, de faim et de peur ont suivi, et le Qur'an décrit de manière vivante l'épreuve des croyants dans la sourate al-Ahzab : « …quand les yeux se sont déplacés dans la peur et que les cœurs ont atteint la gorge » (Qur'an 33 : 10). Finalement, un vent violent et une discorde interne dispersèrent l'armée confédérée, et ils se retirèrent sans bataille rangée. Le Qur'an attribue la délivrance à Allah, qui « a envoyé sur eux un vent et des armées que vous n'avez pas vues » (Qur'an 33 : 9).\n\nLa leçon : une sage consultation (shura) et une ouverture aux bonnes idées de chacun – ici, l'ingénierie d'un étranger – font partie de la foi. Et lorsque l’effort humain a été pleinement déployé, la délivrance vient toujours d’Allah. Ce siège brisé a effectivement mis fin à la capacité de Quraysh à prendre l'offensive.",
    location: "Madinah",
  },
  {
    title: "Traité de Hudaybiyyah",
    body: "Au cours de la sixième année, le Prophète ﷺ partit avec quelque 1 400 compagnons pour accomplir la Umrah, et non pour se battre, entrant dans l'état d'ihram pour clarifier son intention pacifique. Quraysh les a interdits à un endroit appelé Hudaybiyyah, à la limite du sanctuaire. Après des négociations tendues, une trêve de dix ans fut conclue dans des conditions qui semblaient humiliantes aux yeux de nombreux compagnons : les musulmans rebrousseraient chemin cette année-là et reviendraient l'année suivante ; toute personne fuyant Quraysh vers les musulmans serait renvoyée, mais pas l'inverse.\n\nPourtant, Allah a révélé au retour que ce même traité était « une nette victoire » (Qur'an 48 : 1, sourate al-Fath). Les compagnons ont déclaré plus tard qu’ils n’avaient jamais vu une plus grande victoire – parce que dans la paix qui a suivi, les gens se sont mélangés librement, ont entendu le message calmement et sont entrés dans l’Islam en bien plus grand nombre que pendant toutes les années de combat ; Le rapport d'Al-Bara' ibn Azib à cet effet est enregistré dans Sahih al-Bukhari 4606. La trêve reconnaissait également implicitement les musulmans comme une puissance égale.\n\nLa leçon : ce qui ressemble à un revers peut être la plus grande ouverture. Le Prophète ﷺ a choisi une perte apparente à court terme pour un bien à long terme, et a honoré un marché difficile même lorsque cela piquait. La patience, la retenue et le respect de la parole peuvent permettre de réaliser ce que la confrontation ne peut pas réaliser.",
    location: "Hudaybiyyah",
  },
  {
    title: "L'expédition à Khaybar",
    body: "Peu de temps après Hudaybiyyah, le Prophète ﷺ se tourna vers Khaybar, une riche oasis de forteresses fortifiées au nord de Madinah. Khaybar était devenu une base d'hostilité, abritant des tribus qui avaient aidé à organiser le siège de Madinah par les confédérés et continuaient de comploter contre la communauté musulmane. La campagne visait à mettre fin à cette menace.\n\nLes forteresses tombèrent les unes après les autres après de durs combats ; la bannière du jour décisif a été donnée à Ali ibn Abi Talib (qu'Allah l'agrée). Par la suite, le Prophète ﷺ a permis aux habitants de rester et de continuer à cultiver la terre en échange d'une part de ses produits – un arrangement qui a assuré la nourriture et la stabilité à Madinah plutôt que d'expulser tout le monde. C'est ici aussi qu'une femme tenta de l'empoisonner avec un mouton, ce dont il fut prévenu.\n\nLa leçon : la sécurité et le respect des traités allaient de pair. L'action était menée contre une puissance hostile avérée, mais elle s'est soldée par un règlement viable qui a permis aux vaincus de conserver leurs moyens de subsistance. Dans l’Islam, la force vise à établir la sécurité et la justice, et non à anéantir.",
    location: "Khaybar",
  },
  {
    title: "La conquête de Makkah",
    body: "Lorsque les alliés de Quraysh ont rompu les termes de Hudaybiyyah en attaquant une tribu alliée aux musulmans, la trêve a été annulée. Au cours du Ramadan de la huitième année, le Prophète ﷺ marcha sur Makkah avec une armée de dix mille personnes – la plus grande force à ce jour – et la ville qui l'avait persécuté, boycotté et combattu pendant vingt ans se rendit sans effusion de sang.\n\nDevenu enfin vainqueur du peuple qui l'avait chassé, il demanda aux Mecquois ce qu'ils attendaient de lui. Ils espéraient la miséricorde d'un noble frère, et il répondit avec les paroles de Yusuf à ses frères : « Aucun blâme ne vous est imputé aujourd'hui » – et déclara : « Partez, car vous êtes libre ». Il entra dans la Kaaba et la débarrassa de ses 360 idoles, récitant « La vérité est venue et le mensonge a disparu » (Qur'an 17 : 81), rétablissant le sanctuaire d'Ibrahim au pur culte d'Allah. La sourate an-Nasr (Qur'an 110) parle de ce moment où les gens « entrent en multitude dans la religion d'Allah ».\n\nLa leçon : c’est le sommet de la miséricorde et du pardon prophétiques. Ayant le pouvoir absolu de se venger, il a gracié. Le croyant apprend que les forts sont ceux qui pardonnent lorsqu’ils sont capables de punir, et que le but n’a jamais été la vengeance mais plutôt la guidance.",
    location: "Makkah",
  },
  {
    title: "L'expédition à Tabuk",
    body: "Au cours de la neuvième année, des rapports parvinrent à Madinah faisant état d'une éventuelle mobilisation byzantine (romaine) à la frontière nord. Dans la chaleur féroce du plein été, alors que la récolte était mûre et que le voyage était long et difficile, le Prophète ﷺ a appelé la plus grande armée qu'il ait jamais dirigée – peut-être trente mille – à marcher vers le nord jusqu'à Tabuk. C'était « l'heure des difficultés » (Qur'an 9 : 117), et cela mettait la sincérité à l'épreuve comme jamais auparavant.\n\nAucune bataille n'a eu lieu ; la démonstration de détermination était suffisante et plusieurs chefs du nord ont conclu des traités avec Madinah. Mais on se souvient surtout de cette campagne pour ce qu'elle a révélé sur le cœur des gens. Le Qur'an y consacre une grande partie de la sourate at-Tawbah – louant ceux qui ont tout donné (Abu Bakr aurait donné toutes ses richesses), dénonçant les hypocrites qui ont inventé des excuses pour rester et racontant l'histoire émouvante de trois croyants sincères, dont Ka'b ibn Malik, qui ont honnêtement admis qu'ils n'avaient aucune excuse et ont été pardonnés après une dure épreuve (Qur'an 9 : 118).\n\nLa leçon : l’obéissance est facile quand elle est confortable ; sa vérité montre quand cela coûte cher. Tabuk séparait les sincères de ceux qui cherchaient des excuses et marquait la fin effective de la résistance organisée de l'idolâtrie en Arabie. L'honnêteté – même l'honnêteté d'admettre son échec – est le chemin qui mène à Allah.",
    location: "Tabouk",
  },
  {
    title: "Le pèlerinage d'adieu",
    body: "Au cours de la dixième année, le Prophète ﷺ accomplit son seul Hajj complet, rejoint par plus de cent mille compagnons, leur enseignant les rites en personne. Debout dans la plaine d'Arafah, il prononça le sermon d'adieu (Khutbat al-Wada'), un résumé de tout ce que l'Islam était venu établir.\n\nIl a déclaré le caractère sacré de la vie, des biens et de l'honneur de chaque personne : « votre sang et vos biens sont aussi sacrés que ce jour, ce mois, cette terre » (Sahih al-Bukhari 1741). Il a aboli les vendettas et les intérêts (riba) de la Jahiliyyah, a enjoint le bon traitement des femmes comme un mandat d'Allah, leur a rappelé qu'aucun Arabe n'est supérieur à un non-Arabe sauf en piété, et leur a dit de s'en tenir fermement au Qur'an. C'est lors de ce pèlerinage, le jour d'Arafah qui tombait un vendredi, qu'Allah révéla « Aujourd'hui, j'ai perfectionné pour vous votre religion… » (Qur'an 5 : 3) — un verset rappelé et daté précisément par Umar (Sahih al-Bukhari 45).\n\nLa leçon : le sermon d'adieu est la charte islamique de la dignité humaine, de la justice et de l'égalité, scellée par l'annonce que la religion était désormais achevée. La tâche du croyant à partir de là n'est pas d'y ajouter mais de la vivre.",
    location: "Arafa",
  },
  {
    title: "Son décès",
    body: "Quelques mois après le Hajj d'adieu, le Prophète ﷺ tomba malade de fièvre. Dans ses derniers jours, il demanda à ses épouses la permission d'être allaitées dans la chambre d'Aïcha (qu'Allah l'agrée) et il chargea Abu Bakr de diriger les salah. Lors de son dernier matin, il a tiré le rideau pour voir les rangs des croyants en salah et a souri, joyeux à sa communauté, puis l'a laissé retomber. Il est décédé un lundi 12 Rabi al-Awwal 11 AH, sa tête reposant entre la poitrine et le menton d'Aisha - comme elle l'a elle-même raconté dans Sahih al-Bukhari 4449/4451.\n\nLe chagrin à Madinah était accablant et même Omar refusa au début de l’accepter. Puis Abu Bakr se leva, embrassa le visage du Prophète et s'adressa au peuple avec des paroles qui stabilisèrent toute la communauté et qui sont enregistrées dans le Sahih al-Bukhari 1241/1242 : « Celui qui adorait Mahomet, alors Mahomet est mort ; mais celui qui adore Allah, alors Allah est éternel et ne meurt jamais. » Il a récité « Muhammad n'est qu'un messager ; des messagers sont décédés avant lui… » (Qur'an 3 : 144).\n\nLa leçon : le message était complet et appartenait désormais à la Oumma. Le Prophète ﷺ était mortel, mais ce qu'il a apporté – le Qur'an et sa Sunna – ne l'est pas. La réponse d'Abu Bakr est la réponse durable au chagrin : notre attachement est à Allah, qui ne meurt jamais, et la façon d'aimer le Prophète ﷺ est de vivre selon sa direction.",
    location: "Madinah",
  },
];
