// Azerbaijani translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_AZ: DeepPartial<SeerahEvent>[] = [
  {
    title: "İslamdan əvvəl Ərəbistan (cahiliyyə)",
    body: "Peyğəmbəri başa düşmək üçün əvvəlcə onun göndərildiyi dünyanı təsəvvür etmək lazımdır. VI əsr Ərəbistan heç bir mərkəzi dövləti olmayan dağınıq qəbilələr ölkəsi idi, bir-birinə nəsil, şərəf və Məkkədə Kəbə ziyarətgahı - İbrahim və İsmayıl tərəfindən bir Allaha ibadət etmək üçün tikilmiş ziyarətgah, lakin indi təxminən üç yüz altmış bütlə əhatə olunmuşdur.\n\nBu dövr cahiliyyə, \"cahiliyyət dövrü\" adlanır - ərəblərin ağılsızlığına görə deyil (onların şeirləri və yaddaşları fövqəladə idi), hidayətə malik olmadıqları üçün. Qəbilə çəkişmələri nəsillər boyu davam edə bilərdi, güclülər zəifləri ovlayırdı və qızlar bəzən utandıqları üçün və ya yoxsulluq qorxusundan diri-diri basdırılırdılar – bu, Qur'anın daha sonra birbaşa olaraq pisləyəcəyi bir təcrübədir (Qur'an 81:8-9). Bütpərəstliklə yanaşı, bir neçə “hünəfa” hələ də İbrahimin xalis tövhidinə can atırdı və yarımadanın hər tərəfində kiçik yəhudi və xristian icmaları yaşayırdı.\n\nDərs: Vəhy boşluğa yox, dərin yaraları olan həqiqi bir cəmiyyətə enmişdir və onun sağaltdığı ilk şey insanla onun Yaradanı arasındakı münasibət idi. Zaman cədvəli inkişaf etdikcə bu fonu yadda saxlayın - Peyğəmbərin ﷺ hər bir islahatı cahiliyyənin ədalətsizliyinə birbaşa cavabdır.",
    location: "Ərəbistan",
  },
  {
    title: "Məkkədə doğuldu",
    body: 'Peyğəmbər (salləllahu aleyhi və səlləm) Fil ilində (Əmül-Fil) Məkkədə anadan olmuşdur və belə adlandırılmışdır ki, həmin il Yəmənin Həbəş valisi Əbrahə fillərlə bir ordu ilə Kəbəni dağıtmaq üçün yürüş etmiş və möcüzəvi şəkildə geri dönmüşdür. Bu məsuliyyətli ildə Qureyş qəbiləsinin və onun ən şərəfli qəbiləsi olan Bəni Haşimdən bir uşaq dünyaya gəldi.\n\nO, doğulanda artıq yetim idi: atası Abdulla aylar əvvəl ticarətlə məşğul olarkən vəfat etmişdi. Anası Əminə bint Vəhb ona Məhəmməd adını verdi - "çox təriflənən" - ərəblər arasında demək olar ki, bilinməyən bir ad. Məkkə adətinə uyğun olaraq o, Həlimə əs-Sədiyyənin himayəsində Bəni Səd tayfası arasında açıq səhrada süd vermək və böyütmək üçün göndərildi.\n\nMömin üçün dərs: Allah yanında böyüklüyün dünya təhlükəsizliyi ilə heç bir əlaqəsi yoxdur. Axırıncı elçi atasız yaşamağa başladı və tezliklə anasız qalacaqdı, lakin Allah Özü onun himayədarı idi – “Səni yetim tapıb sığınacaq vermədimi?” (Qur\'an 93:6). Sonrakı "Ananın vəfatı" və "Əbu Talibin qəyyumluğu"na da baxın.',
    location: "Məkkə",
  },
  {
    title: "Anasının keçməsi",
    body: "Təxminən altı yaşında olanda Əminə oğlunu Yəsribdəki (sonradan Mədinə) qohumlarının yanına və atasının qəbrini görməyə apardı. Qayıdışda o, xəstələndi və Məkkə ilə Mədinə arasında yerləşən Əbva adlı yerdə vəfat etdi və orada dəfn edildi. Gənc Məhəmməd (salləllahu aleyhi və səlləm) artıq hər iki valideynini itirmişdi.\n\nO, ailənin azad edilmiş nökəri Ümmü Əymən tərəfindən Məkkəyə qaytarıldı və babası, Qureyşin hörmətli başçısı Əbdül-Müttəlibin himayəsinə verildi, onu dərindən sevən və Kəbədə yanında əyləşdirərdi.\n\nDərs: Peyğəmbər (sallallahu aleyhi və səlləm) bu qədər insanın daşıdığı kədəri - yas, köçkünlük, başqalarından asılılıq kimi erkən və dəfələrlə daddı. Bu, onun hazırlığının bir hissəsi idi. Zərərini bilən ürək, yetimə, dul qadına, qəribə hiss edə bilən ürəkdir və onun ümməti sonradan məhz bu mərhəmət üzərində qurulacaqdır. Bu mövzu “Qədər ili”ndə davam edir.",
    location: "Əbva'",
  },
  {
    title: "Əbu Talibin qəyyumluğu",
    body: "Anasından iki il sonra babası Əbdül-Müttəlib də vəfat etdi, oğlan təxminən səkkiz yaşında idi. Ölüm yatağında sevimli nəvəsini Peyğəmbərin əmisi oğlu Əbu Talibə əmanət etdi. Əbu Talib varlı olmasa da, uşağı öz evinə götürdü və ona ən əziz övladlarından biri kimi baxdı.\n\nƏbu Talib Məkkədə ən ağır zülm illərində qırx ildən çox onun himayədarı olaraq qalacaqdı. Məhz o, gənc Məhəmmədi (sallallahu aleyhi və səlləm) Suriyaya ticarət səfərlərinə apardı və orada - məşhur rəvayətə görə - rahib Bahira onda peyğəmbərlik əlamətlərini gördü (sirənin təfərrüatları müxtəlif qüvvələrlə nəql olunsa da, rəvayətdə mühafizə olunur).\n\nDərs: Allah hər mərhələdə öz Peyğəmbərinin (sallallahu aleyhi və səlləm) ətrafına sadiq, şərəfli insanlar qoydu. Əbu Talibin onilliklər boyu müdafiəsi bir mərhəmət idi - həqiqəti və qohumluğu dəstəkləməyin hətta hələ iman etməyənlər üçün də nəcib bir vəzifə olduğunu və bizə sığınacaq verənlərə hörmət etməyimizi xatırlatdı. Sonradan, Kədər ilində itkisi hər şeyi dəyişəcəkdi.",
    location: "Məkkə",
  },
  {
    title: "Xədicə ilə evlilik",
    body: 'Muhəmməd ﷺ gənc ikən Məkkədə heç bir var-dövlətin satın ala bilməyəcəyi bir şöhrət qazandı: Sadiq, doğru danışan və əl-Əmin, etibarlı. İnsanlar qiymətli əşyalarını saxlamaq üçün ona əmanət edirdilər və hətta müxtəlif tanrılara sitayiş edənlər belə Onun sözünə tam etibar edirdilər.\n\nQüreyşin nəcib və müvəffəqiyyətli taciri Xədicə bint Xuveylid (Allah ondan razı olsun) onu öz karvanını Suriyaya aparmaq üçün işə götürdü. Onun dürüstlüyünə və xasiyyətinə heyran qalaraq dostu Xövlə bint Həkim vasitəsilə evlənmək təklifi göndərdi. Onun iyirmi beş, o isə qırx yaşı vardı; onların evliliyi dərin sevgi və tərəfdaşlıq oldu. O, ona uşaqlarını doğdu və ölümünə qədər təxminən iyirmi beş il onun yeganə arvadı olaraq qaldı.\n\nDərs: xarakter sonrakı hər şeyin təməlidir. O, peyğəmbər adlandırılmadan çox-çox əvvəl Məkkə onu öz aralarında ən dürüst insan kimi tanıyırdı - buna görə də ilk vəhydə Xədicənin ona olan inamı bu qədər qəti idi (bax: "İlk vəhy"). Möminin adi işlərdə düzgünlüyü özü də bir növ dəvətdir.',
    location: "Məkkə",
  },
  {
    title: "Hilf əl-Fudul və Qara Daş",
    body: "Onun peyğəmbərlikdən əvvəlki həyatında baş verən iki hadisə, onun daha sonra bir millət quracağı dəyərləri göstərir. Birincisi, Hilf əl-Fudul: Qureyşin bir neçə qəbiləsinin Məkkədə yerli və ya əcnəbi hər hansı bir məzlumun hüquqları bərpa olunana qədər yanında olmaq üçün and içdiyi təntənəli əhd. Peyğəmbər (s) iştirak etdi və sonralar belə bir əhd-peymana İslamda belə cavab verəcəyini söylədi - çünki o, ədaləti müdafiə edirdi.\n\nİkincisi, daşqından sonra Kəbənin yenidən tikilməsi. Klanlar müqəddəs Qara Daşı (əl-Həcərül-Əsvədi) yenidən yerinə qaldırmaq şərəfinə az qala vuruşmağa gələndə, içəri girəcək növbəti kişinin hökmünü qəbul etməyə razılaşdılar – və bu, Məhəmməd ﷺ idi. Onun həlli öz müdrikliyi ilə məşhur idi: daşı bir parçanın üstünə qoydu və hər qəbilə başçısından bir künc qaldırdı, sonra onu öz əlləri ilə yerinə qoydu ki, hamı şərəfə şərik oldu və heç biri laqeyd qalmadı.\n\nDərs: ədalət və münaqişənin həlli vəhy onları təsdiq etməmişdən əvvəl onun instinkti idi. Mömin o kəsdir ki, zülmə məruz qalanı müdafiə edir və parçalamaq yox, birləşmək yollarını axtarır - Hilful-fudul onun hicrətdən sonra quracağı ədalətli cəmiyyətdən xəbər verir.",
    location: "Məkkə",
  },
  {
    title: "İlk ifşa",
    body: 'Otuz yaşlarının sonlarında Peyğəmbər (s) Məkkədən kənarda Cəbəl ən-Nur dağındakı Hira mağarasında daha çox ibadət etmək və düşünmək üçün geri çəkildi. Orada Ramazan ayında təxminən qırx yaşında Cəbrayıl mələk peyda olub ona buyurdu: “Oxu!” Cavab verdi ki, oxuya bilmir; mələk onu üç dəfə möhkəm qucaqladı və Qur\'anın ilk kəlmələri olan "Ələq" surəsinin başlanğıc ayələrini - "Yaradan Rəbbinin adı ilə oxu..." (Qur\'an 96:1-5) nazil etdi.\n\nO, titrəyərək evə qayıtdı və Xədicə onu sardı və onun imanını və xasiyyətini göstərən sözlərlə əmin etdi: Allah onu heç vaxt rüsvay etməz, çünki o, qohumluq əlaqələrini saxlayır, başqalarının yükünü daşıyır və layiq olanlara kömək edirdi. O, onu öz əmisi oğlu Varaqə ibn Nəvfəlin yanına apardı, o, ziyarətçini Musaya gələn eyni "Namus" (mələk) kimi tanıdı və ona vəd edilmiş peyğəmbərlik olduğunu söylədi. Bütün bu epizod Səhih əl-Buxari 3-də qeyd edilmişdir.\n\nDərs: vəhy güc iddiası ilə deyil, bilik və təvazökarlığa əsaslanan bir din olan "Oxu" sözü ilə başladı. İlk kimin inandığına diqqət yetirin: arvad və namuslu ailə. Həqiqəti artıq səmimi yaşayanlar tanıyır.',
    location: "Hira mağarası",
  },
  {
    title: "Şəxsi təbliğat illəri",
    body: "İlk vəhylərdən sonra bir fasilə (fətrə) gəldi, sonra Allah Peyğəmbərə (sallallahu aleyhi və səlləm) insanları yalnız Ona ibadət etməyə çağırmağa başlamağı əmr etdi. Təxminən ilk üç il ərzində bu zəng sakit və şəxsi idi - küçələrdə elan olunmaqdansa yaxın ailə və etibarlı dostlara şamil edildi.\n\nƏn ilk möminlər, “əs-Sabiqunul-əvvəlun” (əvvəllər) cəmiyyətin hər yerindən gəlmişdilər: arvadı Xədicə; onun gənc əmisi oğlu Əli ibn Əbi Talib; azad edilmiş qulu və övladlığa götürdüyü oğlu Zeyd ibn Harisə; və onun sadiq dostu Əbu Bəkr əs-Siddiq (Allah onların hamısından razı olsun). Əbu Bəkr öz növbəsində bir çoxlarını İslama gətirdi. Onlar tez-tez Kəbənin yaxınlığındakı əl-Ərqamın evində görüşür və təmkinlə namaz qılırdılar.\n\nDərs: İslam ilk olaraq tamaşa ilə deyil, inam və əlaqə ilə böyüdü. Bu ilk ürəklərin genişliyinə diqqət yetirin - varlı bir qadın, uşaq, azad edilmiş bir qul, tacir - irq və rütbə fərqlərini siləcək bir imanın əvvəlcədən dadını verir. Də'vət evə yaxından, səmimiyyət və səbirlə başlayır.",
    location: "Məkkə",
  },
  {
    title: "Xalqın İslama çağırışı",
    body: "Allah “Ən yaxın qohumlarını qorxut” (Qur'an, 26/214) nazil etdikdə Peyğəmbər (s) Kəbənin yanındakı Səfa dağına çıxıb Qureyş qəbilələrini səslədi. O, əvvəlcə təpənin arxasında bir ordunun gizləndiyini desə, ona inanacaqlarını soruşdu; Cavab verdilər ki, onun yalan danışdığını heç vaxt tanımayıblar. Sonra onları gələcək bir əzabdan xəbərdar etdi və onları yalnız Allaha ibadət etməyə çağırdı.\n\nBu açıq mesaj Məkkənin əmrinin ürəyinə zərbə vurdu. Bütlər təkcə din deyil, həm də dolanışıq və prestij idi - şəhərin ziyarətgahın qoruyucusu statusu zəvvarları və ticarəti cəlb edirdi. Bütlərin gücsüz olduğunu söyləmək Qureyşin iqtisadiyyatına, nəslinə və qüruruna bir anda meydan oxumaq idi. Buradan təqiblər kəskin şəkildə gücləndi, ən çox Bilal ibn Rəbah və Yasir ailəsi kimi möminlərin zəif və qullarına düşdü.\n\nDərs: açıq-aşkar deyilən həqiqət kök salmış maraqları sarsıdacaq. Həzrət Peyğəmbər (s) əvvəlcə onların öz şəhadətlərinə müraciət edərək, onun dürüst olduğuna – təhdiddən əvvəl ağıl və düzgünlüyünə – müraciət etdi, sonra isə möhkəm dayandı. Məkkəli möminlərin öyrəndiyi kimi, tövhid üçün dayanmaq dünya rahatlığına başa gələ bilər. Bu sıxıntı birbaşa “Həbəşistana köç”ə gətirib çıxarır.",
    location: "Səfa dağı",
  },
  {
    title: "Həbəşistana köç",
    body: "Zülmlər dözülməz olduqca, Peyğəmbər (s) bir qrup səhabəsinə Həbəşistanın (müasir Efiopiya) ədalətli xristian padşahı Nəcaşiyə (ən-Nəcaşiyə) sığınmağı əmr etdi və onun ölkəsində heç kəsə zülm edilmədiyini söylədi. Birinci qrup Qırmızı dənizi keçdi, ardınca daha böyük ikinci hicrət - İslamda ilk hicrət.\n\nQureyş qaçqınların geri qaytarılmasını tələb edən elçilər göndərəndə Nəcaşi onları yanına çağırdı. Cəfər ibn Əbi Talib (Allah ondan razı olsun) müsəlmanlar üçün danışdı, onların cahillikdən necə haqq, mərhəmət və gözəl əxlaq imanına necə gəldiklərini təsvir etdi, sonra İsa və anası haqqında Məryəm surəsindən ayələri oxudu. Xristian padşah ağladı, yerə bir xətt çəkdi və onların imanı ilə onun inancı arasındakı fərqin ondan daha geniş olmadığını söylədi və onları təslim etməkdən imtina etdi.\n\nDərs: bu, dini tolerantlığın və səmimi Kitab Əhli ilə körpülərin qurulmasının əlamətidir. O, həmçinin ədalətli qeyri-müsəlman hakimiyyəti altında zülmdən təhlükəsizlik axtarmağın tamamilə qanuni olduğunu öyrədir. Diqqət yetirin ki, gündə qalib gələn mübahisə gözəl xarakter və Allah kəlamı deyildi – zorla deyil.",
    location: "Həbəşistan",
  },
  {
    title: "Bənu Haşimin boykot edilməsi",
    body: "Qüreyş başçıları İslamın yayılmasının qarşısını ala bilməyən və ya Peyğəmbərin (s) qəbiləsini qoruduğu halda ona yaxınlaşa bilməyən Qureyş başçıları kollektiv cəzaya əl atdılar. Onlar əhd-peyman yazıb onu Kəbədə asdılar və bütün Bəni Haşim (və onların müttəfiqləri Bənu əl-Müttəlib) qəbiləsini boykot edəcəklərini vəd etdilər: onlar Məhəmmədə (s) təslim olana qədər onlarla evlənməyəcək, ticarət etməyəcək, ictimai iş görməyəcəksiniz.\n\nTəxminən üç il ərzində qəbilə - həm möminlər, həm də Haşimin kafirləri - Şi'b Əbi Talib dağ vadisində məskunlaşdılar, o qədər şiddətli aclığa dözdülər ki, uşaqların qışqırıqları eşidildi və insanlar yarpaqları yedilər. Boykot nəhayət, bir neçə insaflı Qureyşi kişisi bunu açıq şəkildə rədd etdikdə və Allahın adının keçdiyi sözlər istisna olmaqla, perqamentin yeyilmiş olduğu aşkar edildikdə, nəhayət dağıldı.\n\nDərs: yalan həddindən artıqdır. Boykotun qəddarlığı yalnız zülm edənlərin haqsızlığını üzə çıxardı və möminlərin əzmini sərtləşdirdi. Bu, həmçinin vəhşiliyə son qoymaq üçün sıralarını qıran düşmən cəmiyyətdə bir neçə ədalətli şəxsin şərəfini göstərir - bu, vicdanın ən şiddətli müxalifətdə belə sağ qala biləcəyini xatırladır.",
    location: "Şi'b Əbi Talib",
  },
  {
    title: "Kədər ili",
    body: 'Boykot bitdikdən az sonra Peyğəmbər (s) qısa müddət ərzində iki böyük itki verdi və bu il Am əl-Huzn, Qəm ili kimi tanındı. Əvvəlcə əmisi və ömürlük himayədarı olan Əbu Talib vəfat etdi - onilliklər boyu onu Qüreyşdən qoruyan adam. Sonra onun ilk mömin və ən yaxın dayağı, təxminən iyirmi beş illik həyat yoldaşı Xədicə (Allah ondan razı olsun) vəfat etdi.\n\nHəm sosial müdafiəsi, həm də emosional lövbəri getdikcə, Qureyş onların sui-istifadəsində daha cəsarətli oldu. Məhz bu dövrdə o, Taif şəhərinin əhalisinin xəbəri qəbul edəcəyinə ümid edərək ona getdi; əvəzinə onu qovdular və ayaqları qanana qədər daş atmaq üçün uşaq qoydular. Hətta o zaman, şəhərin dağıdılmasını təklif edəndə o, onların nəslinin bir gün Allaha ibadət etmələri üçün dua etdi - bu, onu müəyyən edən bir rəhmətdir.\n\nDərs: hətta peyğəmbərlər də arxa-arxa qəm və inkarla sınanır və cavab acısız səbirdir. İnsan itkisi ilahi tərk etmək demək deyil; relyef yaxın arxada, sonrakı gələn gecə səfərində izlədi. Bax "Əl-İsra vəl-Mi\'rac".',
    location: "Məkkə",
  },
  {
    title: "Əl-İsra vəl-Mirac",
    body: "Kədər ilindən sonra fövqəladə şərəfli bir gecə gəldi. İsrada Peyğəmbər (s) bir gecədə Məkkədəki Məscidülhəramdan Qüdsdəki Məscidül-Əqsaya aparıldı. Orada əvvəlki peyğəmbərlərə namaz qıldırdı. Sonra o, Meracda yeddi səmada ucaldı, Adəm, Musa və İbrahim kimi peyğəmbərlərlə görüşdü və Rəbbinə bütün yaradılmışlardan daha yaxın bir məqama çatdı.\n\nO gecənin əsas hədiyyəsi beş vaxt namaz idi. “Səhih əl-Buxari”də 3887-ci ildə qeyd olunduğu kimi, onlar ilk dəfə əlli olaraq vəsiyyət edilmişlər; Musanın məsləhəti ilə Peyğəmbər ﷺ əlli savabı daşıyarkən əməldə beşə endirilənə qədər, təkrar-təkrar yardım dilədi. Alimlər dəqiq tarixlə bağlı ixtilaf edirlər, əksəriyyət onu hicrətdən bir qədər əvvəlki illərə yerləşdirirlər.\n\nDərs: Kədərli Peyğəmbərə (sallallahu aleyhi və səlləm) təsəlli vermək üçün verilən hədiyyə namaz idi - bizim gecə Allaha yüksəlişimiz. Beş vaxt namazı bir mələk yerə endirməmiş, qəbul etmək üçün göylərə qaldırmışdır ki, bu da onların möminin həyatındakı ağırlığını göstərir.",
    location: "Yerusəlim",
  },
  {
    title: "Əl-Əqabənin ilk beyəti",
    body: "Hər il zəvvarlar Məkkəyə toplaşır və Peyğəmbər (s) ziyarətə gələn qəbilələrə İslamı təqdim edirdi. Mina yaxınlığındakı Əl-Əqabə adlanan yerdə, Yəsribdən (Mədinə) kiçik bir qrup kişi - uzun müddətdir Evs və Xəzrəc qəbilələri arasında çəkişmələrlə parçalanmış və yəhudi icması vasitəsilə tövhidlə tanış olan bir şəhər - dinlədi, inandı və xəbəri evlərinə çatdırdı.\n\nSonrakı mövsümdə onlardan on iki nəfər qayıdıb Əqəbənin ilk beyətini verdilər: Tək Allaha ibadət etmək, oğurluq etməmək, haram cinsi əlaqədə olmamaq, uşaq öldürməmək və Peyğəmbərə (s) doğru işdə itaət etmək. Sonra o, gənc səhabə Mus'ab ibn Umeyr (Allah ondan razı olsun) İslamın ilk müəllimi və səfiri olaraq onlarla birlikdə geri göndərdi və onun vasitəsilə Yəsrib evlərində iman sürətlə yayıldı.\n\nDərs: Məkkədə bağlı görünən qapı Mədinədə açıldı. Cəmiyyətin necə qurulduğuna diqqət yetirin - öyrətməklə. Quranla göndərilmiş bir fədakar gənc müəllim İslamın beşiyi olmaq üçün bütöv bir şəhər hazırladı. Bu, bilavasitə İkinci beyəti və hicri təyin edir.",
    location: "Mina",
  },
  {
    title: "İkinci əl-Əqabə beyəti",
    body: 'İlk beyətdən bir il sonra Yəsribdən daha böyük bir heyət - yetmiş üç kişi və iki qadın həcc ziyarəti zamanı Əqəbəyə gizli şəkildə Peyğəmbərin (s) yanına gəldi. Bu dəfə öhdəlik daha da irəli getdi: onlar öz arvadlarını və uşaqlarını qoruduqları kimi onu da qoruyacaqlarını və Məkkə müsəlmanlarının zülmə məruz qalanlarını öz şəhərlərinə qəbul edəcəklərini əhd etdilər.\n\nBu dönüş nöqtəsi idi. İlk dəfə olaraq yenicə formalaşan icmanın vətəni və onu müdafiə etməyə and içmiş xalqı var idi. Təhlükəni başa düşən Peyğəmbər (s) Məkkədə olan səhabələrinə Qureyşi təşvişə salmamaq üçün kiçik qruplar halında Yəsribə hicrət etməyə başlamağı əmr etdi.\n\nDərs: səmimi öhdəlik məsuliyyət daşıyır. Ənsar (Mədinənin “Köməkçiləri”) sırf iman xatirinə heç bir şey əldə etmədən canlarını və evlərini girov qoymuşdular. Onların səxavətləri İslam qardaşlığının nümunəsi olacaqdı - mühacirləri ailə kimi qarşıladıqları "Mədinəyə hicrət" kitabında xatırlandı.',
    location: "Mina",
  },
  {
    title: "Mədinəyə hicrət",
    body: 'Qureyş Peyğəmbərə (s) sui-qəsd hazırlayanda Allah ona hicrət etməyə icazə verdi. O, insanların əmanətlərini qaytarmaq üçün Əlini yatağında qoyub ən yaxın dostu Əbu Bəkr (Allah ondan razı olsun) ilə yola düşdü. Təqibçilər o qədər yaxınlaşdıqca ikisi Səvr mağarasında üç gecə gizləndilər ki, Əbu Bəkr onlar üçün qorxdu və Peyğəmbər (s) onu sakitləşdirdi: "İki nəfər, üçüncüsü Allahdır?" Bu an Səhih əl-Buxari 3653-də qeyd olunub və Quranda əksini tapıb: “...ikincisi, mağarada olduqları zaman yoldaşına: “Kədərlənmə, şübhəsiz ki, Allah bizimlədir” dedikdə” (Qur\'an, 9:40).\n\nOnlar ilk məscidin tikildiyi Qubaya çatdılar, sonra Yəsribə - daha sonra Mədinə əl-Münəvvərəyə, "Nurlu Şəhər"ə daxil oldular. Peyğəmbər (salləllahu aleyhi və səlləm) hər bir mühaciri (mühaciri) bir köməkçi (Ənsari) ilə qardaşlıq bağında qoşdu. səxavət o qədər tam idi ki, Səd ibn ər-Rəbi sərvətinin yarısını Əbdürrəhman ibn Ovfla bölüşməyi təklif etdi, o isə əvəzində yalnız bazarın göstərilməsini istədi (Səhih əl-Buxari 3780/3906).\n\nHicrət o qədər mühüm idi ki, Ömər sonralar onu İslam təqviminin başlanğıcı etdi - hicri 1-ci il. Dərs: Bəzən iman hər şeyi Allah üçün tərk etməyi, Onun ixlasla olduğuna təvəkkül etməyi və qan əvəzinə qardaşlığı bərpa etməyi tələb edir.',
    location: "Mədinə",
  },
  {
    title: "Mədinə Konstitusiyası",
    body: 'Qəbilə müharibəsi nəticəsində darmadağın olmuş bir şəhərə gələn Peyğəmbər (s) sadəcə olaraq müsəlmanlara rəhbərlik etməklə kifayətlənməyib, bir icma qurdu. O, İbn İshaqın sirrində qorunan və “Səhifə” və ya Mədinənin Konstitusiyası kimi tanınan, şəhərin mühacirləri, ənsarları və yəhudi qəbilələrini vahid qarşılıqlı müdafiə müqaviləsinə bağlayan yazılı bir müqavilə tərtib etdi.\n\nOnun şərtləri öz dövrləri üçün diqqətəlayiq idi: tərəflər müqavilənin məqsədləri üçün "bir ümmət (ümmət)" yaratdılar, hər qrup öz dinini saxladı, mübahisələr Peyğəmbərə sövq edilməli, təcavüz və haqsızlıq qadağan edildi və hamısı şəhəri xarici hücumlardan qoruyacaqlarına söz verdilər. Bu, faktiki olaraq Mədinəyə sonsuz qan davasından daha çox razılaşdırılmış hüquq və vəzifələri olan bir şəhər dövlətinə çevrildi.\n\nDərs: İslam təkcə şəxsi ibadət deyil, cəmiyyətin ədalətli nizamıdır. Peyğəmbər (sallallahu aleyhi və səlləm) plüralist birgəyaşayışı, qəbilə intiqamı üzərində razılaşdırılmış qanunun aliliyini və əhd-peymanlara əməl etməyi modelləşdirdi - bu prinsiplər gələcək qarşıdurma illərində sınaqdan keçiriləcək. Bütün şəhərə insafı yaymaqla “Mədinəyə hicrət” qardaşlığını tamamlayır.',
    location: "Mədinə",
  },
  {
    title: "Bədr döyüşü",
    body: "Hicrətdən sonrakı ikinci ildə özünümüdafiə üçün döyüşməyə icazə verildi (Qur'an 22:39). Hicri 2-ci Ramazan ayının 17-də, təxminən 313 nəfərdən ibarət, zəif silahlanmış, yalnız bir ovuc atı olan bir müsəlman qüvvəsi, Mədinənin cənub-qərbində, Bədr quyularında təxminən min nəfərlik Qureyş ordusu ilə qarşılaşdı. İslamın ilk böyük döyüşü idi.\n\nEhtimallara baxmayaraq, müsəlmanlar qətiyyətlə qalib gəldilər və Qureyşin əzəmətli təqibçilərindən bir neçəsi öldürüldü. Qur'an qələbəni sadəcə hərbi bir şücaət olaraq deyil, bir əlamət kimi qələmə verir: “Allah sizə Bədrdə zəif ikən qələbə çalmışdı, Allahdan qorxun ki, şükür edəsiniz” (Qur'an, 3:123) və mələklərin köməyini təsvir edir (Qur'an, 3:124-125). Bədr gənc icmanı Ərəbistanda əsl güc kimi qurdu.\n\nDərs: nəticələr rəqəmlərə və avadanlıqlara deyil, Allaha məxsusdur. Bədr “haqqla batili ayırd edən gün” (yəvmül-furqan) kimi xatırlanır ki, bu da Allaha ixlasla təvəkkülün vacib olduğunun sübutudur. Gələn il Uhudda baş verənlərin tərsinə çevrilməsi əlavə dərs verəcəkdir.",
    location: "Bədr",
  },
  {
    title: "Uhud döyüşü",
    body: "Bədrdən bir il sonra Qüreyş qisas almaq üçün daha böyük bir ordu ilə geri qayıtdı və hər iki tərəf Mədinə yaxınlığındakı Uhud dağının ətəyində qarşılaşdı. Peyğəmbər əlli oxçunu bir təpənin üstünə yerləşdirdi və nə olursa olsun, heç vaxt mövqelərini tərk etməmələrini əmr etdi. Döyüşün əvvəlində müsəlmanlar üstünlük təşkil edirdi; lakin düşmənin qaçdığını görən oxatanların çoxu qənimət toplamaq üçün postunu tərk etdilər. Xalid ibn əl-Valid (hələ müsəlman deyil) başçılığı altında olan Qureyş süvariləri açıq cinahın ətrafında dolaşdılar və dalğalar bahalı, ağrılı günə çevrildi.\n\nÇoxlu səhabə şəhid oldu ki, onların arasında Peyğəmbərin sevimli əmisi “Allahın Aslanı” Həmzə (Allah ondan razı olsun). Peyğəmbərin özü də yaralanmış, dişi qırılmış və üzü qan içində idi. Daha sonra Qur'an uğursuzluğa açıq şəkildə müraciət edərək bunun əmrə tabe olmamağın və dünyaya tamah salmağın imtahanı və nəticəsi olduğunu izah etdi (Qur'an 3:152, 3:165-166).\n\nDərs: Uhud intizam və itaətdə böyük dərsdir. Bircə intizamsızlıq, nə qədər kiçik görünsə də, az qala qələbəni ləğv etdi. Lakin Allah onları tərk etmədi, onları öyrətdi, bağışladı və topladı. Dürüstlüklə üzləşən məğlubiyyət qələbədən daha ibrətamiz ola bilər.",
    location: "Uhud dağı",
  },
  {
    title: "Xəndək döyüşü",
    body: "Beşinci ildə Qureyşin, digər ərəb qəbilələrinin və düşmən qrupların ittifaqı - \"Konfederasiyalar\" (əl-Əhzab) - Mədinəyə birdəfəlik məhv etmək üçün Ərəbistanda indiyədək görünən ən böyük qüvvəni, bəlkə də on min nəfəri topladı. Açıq döyüşdə qarşılaşa bilməyəcək qədər böyük bir düşmənlə qarşılaşan Peyğəmbər (s) fars yoldaşı Salman əl-Farisinin (Allah ondan razı olsun) şəhərə açılan şimal yolları boyunca geniş bir xəndək qazmaq məsləhətini qəbul etdi - ərəblərin heç vaxt qarşılaşmadığı bir taktika.\n\nSəngər mühasirəni dayandırdı. Soyuq, aclıq və qorxu həftələri keçdi və Qurani-Kərim Əhzab surəsində möminlərin imtahanını parlaq şəkildə təsvir edir: “... o zaman ki, gözlər qorxudan tərpəndi, ürəklər boğaza çatdı” (Qur'an, 33:10). Nəhayət, şiddətli külək və daxili nifaq konfederasiya ordusunu darmadağın etdi və onlar heç bir döyüş olmadan geri çəkildilər. Quranda qurtuluş “onların üzərinə külək və sizin görmədiyiniz ordular göndərən” Allaha məxsusdur (Qur'an 33:9).\n\nDərs: müdrik məsləhət (şura) və hər kəsdən yaxşı fikirlərə açıq olmaq - burada, əcnəbi mühəndislik - imanın bir hissəsidir. İnsanın zəhməti tam olaraq verildikdə, xilas yenə də Allahdan gəlir. Bu qırılan mühasirə Qüreyşin hücuma keçmə qabiliyyətinə təsirli şəkildə son qoydu.",
    location: "Mədinə",
  },
  {
    title: "Hudeybiyyə müqaviləsi",
    body: "Altıncı ildə Peyğəmbər (salləllahu aleyhi və səlləm) 1400-ə yaxın səhabə ilə döyüşmək üçün deyil, ümrə etmək üçün yola çıxdı, sülh niyyətini aydınlaşdırmaq üçün ehrama girdi. Qureyş onları hərəmin kənarındakı Hudeybiyyə adlı yerdə qadağan etdi. Gərgin danışıqlardan sonra bir çox səhabələr üçün alçaldıcı görünən şərtlərlə on illik atəşkəs razılaşdırıldı: müsəlmanlar həmin il geri dönüb, növbəti ildə gələcək; Qureyşdən müsəlmanlara qaçan hər kəs geri qaytarılacaq, əksinə deyil.\n\nLakin Allah geri dönərkən bu müqavilənin “aydın bir qələbə” olduğunu bildirdi (Qur'an 48:1, Əl-Fəth surəsi). Səhabələr daha sonra heç vaxt daha böyük qələbə görmədiklərini söylədilər - çünki sonrakı sülhdə insanlar sərbəst şəkildə qarışdılar, mesajı sakitcə eşitdilər və bütün döyüş illərindən daha çox sayda İslama daxil oldular; Əl-Bəra ibn Azibin bu barədə verdiyi xəbər “Səhih əl-Buxari”də 4606-cı ildə qeyd edilmişdir. Barışıq müqaviləsi də dolayısı ilə müsəlmanları bərabər güc kimi tanıdı.\n\nDərs: uğursuzluq kimi görünən şey ən böyük açılış ola bilər. Peyğəmbər (salləllahu aleyhi və səlləm) uzunmüddətli xeyir üçün zahiri qısa müddətli itkiləri seçdi və çətin sövdələşməni dişlədiyi zaman belə şərəfləndirdi. Səbir, təmkin və sözə əməl etmək qarşıdurmanın bacara bilmədiyi şeylərə nail ola bilər.",
    location: "Hudeybiyyə",
  },
  {
    title: "Xeybər səfəri",
    body: "Hüdeybiyyədən az sonra Peyğəmbər (s) Mədinənin şimalında möhkəm qalalardan ibarət zəngin bir vahə olan Xeybərə üz tutdu. Xeybər düşmənçilik bazasına çevrilmişdi - Konfederasiyaların Mədinənin mühasirəsini təşkil etməyə kömək edən və müsəlman icmasına qarşı sui-qəsdi davam etdirən qəbilələrin məskəni. Kampaniyanın məqsədi həmin təhlükəni aradan qaldırmaq idi.\n\nQalalar şiddətli döyüşlərdən sonra bir-birinin ardınca dağıldı; həlledici gündə bayraq Əli ibn Əbi Talibə (Allah ondan razı olsun) verildi. Bundan sonra Peyğəmbər (s) sakinlərə məhsullarından bir pay müqabilində torpaqda qalmağa və əkinçiliklə məşğul olmağa icazə verdi - bu, hamını qovmaqdansa, Mədinə üçün ərzaq və sabitliyi təmin edən bir tənzimləmə idi. Elə burada da bir qadın onu qoyunla zəhərləməyə cəhd edib və ona xəbərdarlıq edilib.\n\nDərs: təhlükəsizlik və müqaviləyə riayət əl-ələ verib. Hərəkət sübut edilmiş düşmən gücə qarşı idi, lakin o, məğlub olanların dolanışıqlarını saxlamağa imkan verən işlək bir həll yolu ilə başa çatdı. İslamda qüvvət məhv etmək deyil, əmin-amanlıq və ədaləti bərqərar etmək üçündür.",
    location: "Xeybər",
  },
  {
    title: "Məkkənin fəthi",
    body: "Qüreyşin müttəfiqləri müsəlmanlara müttəfiq olan qəbiləyə hücum edərək Hudeybiyyənin şərtlərini pozduqda, atəşkəs pozuldu. Səkkizinci ilin Ramazan ayında Peyğəmbər  on minlik ordu ilə - indiyədək ən böyük qüvvə ilə - Məkkəyə yürüş etdi və iyirmi il ərzində ona qarşı zülm edən, boykot edən və döyüşən şəhər, demək olar ki, qan tökülmədən təslim oldu.\n\nNəhayət, onu qovmuş xalqa qalib gəlib Məkkəlilərdən ondan nə gözlədiklərini soruşdu. Onlar alicənab bir qardaşın rəhmətinə ümid bəslədilər və o, Yusifin qardaşlarına: “Bu gün sizə heç bir günah yoxdur” sözləri ilə cavab verdi və “Gedin, azadsınız” dedi. O, Kəbəyə daxil oldu və onu 360 bütdən təmizlədi, “Haqq gəldi və batil yox oldu” (Qur'an 17:81) sözlərini söyləyərək, İbrahimin hərəmini Allaha pak ibadət üçün bərpa etdi. Ən-Nəsr surəsi (Qur'an 110) insanların “Allahın dininə dəstə-dəstə daxil olduqları” bu andan bəhs edir.\n\nDərs: bu, peyğəmbərlik mərhəmətinin və bağışlanmasının zirvəsidir. Mütləq qisas almaq gücü ilə o, əfv etdi. Mömin öyrənir ki, güclülər cəzalandırmaq gücündə olduqda bağışlayanlardır və məqsəd heç vaxt intiqam deyil, hidayətdir.",
    location: "Məkkə",
  },
  {
    title: "Təbuk səfəri",
    body: "Doqquzuncu ildə bizansın (Roma) şimal sərhədində mümkün səfərbərliyi barədə xəbərlər Mədinəyə çatdı. Yayın şiddətli istisində, məhsul yetişdiyi və yolun uzun və çətin olduğu bir vaxtda, Peyğəmbər (s) rəhbərlik etdiyi ən böyük ordunu - bəlkə də otuz min nəfəri - şimala Təbuka doğru yürüş etməyə çağırdı. Bu, \"çətinlik saatı\" idi (Qur'an 9:117) və o, əvvəlki heç kimi səmimiyyəti sınayırdı.\n\nHeç bir döyüş olmadı; qətiyyət nümayişi kifayət etdi və bir neçə şimal sərkərdəsi Mədinə ilə müqavilə bağladı. Amma kampaniya hər şeydən əvvəl insanların ürəyini açdığı ilə yadda qalıb. Qur'an Tövbə surəsinin çox hissəsini ona həsr edir - hər şeyi verənləri tərifləyir (Əbu Bəkr bütün var-dövlətini verir), qalmaq üçün bəhanələr uyduran münafiqləri ifşa edir və üç səmimi möminin, o cümlədən Kəb ibn Malikin təsirli hekayəsini izah edir. 9:118).\n\nDərs: itaət rahat olanda asandır; onun həqiqəti nə vaxt baha başa gəldiyini göstərir. Təbuk ixlaslıları bəhanə gətirənlərdən ayırdı və Ərəbistandakı mütəşəkkil bütpərəstliyin müqavimətinin təsirli sonunu qeyd etdi. Dürüstlük - hətta uğursuzluğunu etiraf etmək dürüstlüyü - Allaha gedən yoldur.",
    location: "Təbuk",
  },
  {
    title: "Vida Həcc ziyarəti",
    body: "Onuncu ildə Peyğəmbər (s) yeganə tam həccini yerinə yetirdi və yüz mindən çox səhabə onlara ayinləri şəxsən öyrətdi. O, Ərəfa düzündə dayanaraq İslamın bərqərar etmək üçün gəldiyi hər şeyin xülasəsi olan Vida Xütbəsini (Xütbətül-Vəda) söylədi.\n\nO, hər bir insanın canının, malının və namusunun müqəddəs olduğunu bəyan etmişdir — “Sizin qanınız və malınız bu gün, bu ay, bu torpaq qədər müqəddəsdir” (Səhih əl-Buxari 1741). O, qan davasını və cahiliyyə faizini (riba) aradan qaldırdı, Allahdan bir əmanət olaraq qadınlara gözəl rəftar etməyi əmr etdi, onlara heç bir ərəbin ərəb olmayandan təqvadan başqa üstün olmadığını xatırlatdı və onlara Qurandan möhkəm yapışmağı əmr etdi. Məhz bu həcc ziyarətində, cümə gününə təsadüf edən Ərəfə günündə Allah “Bu gün sizin üçün dininizi kamil etdim...” (Qur'an, 5:3) – Ömərin xatırladığı və dəqiq tarixə malik olduğu ayəni nazil etdi (Səhih əl-Buxari 45).\n\nDərs: Vida xütbəsi İslamın insan ləyaqəti, ədalət və bərabərlik nizamnaməsidir və dinin artıq tamamlandığını elan etməklə möhürlənmişdir. Buradan möminin vəzifəsi ona əlavə etmək deyil, onu yaşamaqdır.",
    location: "Ərəfə",
  },
  {
    title: "Onun keçməsi",
    body: "Vida həccindən bir neçə ay sonra Peyğəmbər (s) qızdırması ilə xəstələndi. Ömrünün son günlərində arvadlarından Aişənin (Allah ondan razı olsun) otağında süd vermək üçün icazə istədi və Əbu Bəkri namaza imam təyin etdi. O, son səhəri möminlərin namaz qılan cərgələrini görmək üçün pərdəni geri çəkdi və ümmətinə sevinərək gülümsədi, sonra onu buraxdı. O, hicri 11-ci il, rəbiül-əvvəl ayının 12-si bazar ertəsi günü, başı Aişənin sinəsi ilə çənəsi arasında dayanmış vəziyyətdə vəfat etdi – o, “Səhih əl-Buxari”də 4449/4451-də rəvayət etdiyi kimi.\n\nMədinənin qəm-qüssəsi böyük idi və hətta Ömər də əvvəlcə bunu qəbul etməkdən imtina etdi. Sonra Əbu Bəkr ayağa qalxdı, Peyğəmbərin üzündən öpdü və bütün ümməti sabitləşdirən və “Səhih əl-Buxari” 1241/1242-də qeyd olunan sözlərlə insanlara xitab etdi: “Hər kim Muhəmmədə ibadət edərdisə, Məhəmməd öldü; kim Allaha ibadət edərsə, Allah diridir və heç vaxt ölməz”. O, “Məhəmməd ancaq bir elçidir, ondan əvvəl də elçilər gəlib...” (Qur'an, 3:144) oxudu.\n\nDərs: risalət tamamlandı və indi ümmətə məxsus idi. Peyğəmbər (sallallahu aleyhi və səlləm) fani idi, lakin onun gətirdiyi Qur'an və sünnəti deyil. Əbu Bəkrin cavabı qəm-qüssə əbədi cavabdır: Bizim bağlılığımız heç vaxt ölməyən Allahadır, Peyğəmbəri sevməyin yolu isə onun hidayətini yaşamaqdır.",
    location: "Mədinə",
  },
];
