// Turkmen translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_TK: DeepPartial<SeerahEvent>[] = [
  {
    title: "Yslamdan öň Arabystan (Jahiliýa)",
    body: 'Pygambere düşünmek üçin ilki bilen iberilen dünýäsini göz öňüne getirmeli. Altynjy asyr Arabystan, merkezi döwleti bolmadyk, nesil, hormat we Mekgedäki Käbäniň mukaddes ýerleri bilen birleşdirilen dargadylan taýpalaryň ýurdy - Ybraýym we Ysmaýyl tarapyndan bir Hudaýa ybadat etmek üçin gurlan, ýöne häzirki wagtda üç ýüz altmyş but bilen gurşalan.\n\nBu döwür "Jahiliýa" diýilýär, "nadanlyk döwri" - araplaryň akyl ýetmezçiligi sebäpli däl (poeziýasy we ýady adatdan daşary) däl-de, eýsem ýol görkezmeleriniň ýoklugy sebäpli. Tire-taýpa dawa-jenjelleri nesiller üçin dowam edip biler, güýçli ejizlere awlanýar, gyzlar käwagt utanç ýa-da garyplyk gorkusy sebäpli diri gömülýär - bu Gurhanyň soň göni ýazgaryljakdygy (Gurhan 81: 8–9). Butparazlyk bilen bir hatarda birnäçe "hunafa" Ybraýymyň arassa monoteizmini gözledi we ýarym adada kiçijik ýewreý we hristian jemagatlary ýaşaýardy.\n\nSapak: wahy boşluga däl-de, çuňňur ýaralary bolan hakyky jemgyýete girdi we ilkinji sapar adam bilen Creatoraradanyň arasyndaky gatnaşyk boldy. Wagtyň geçmegi bilen bu ýagdaýy ýatda saklaň - Pygamberimiziň her bir reformasy Jahilýanyň adalatsyzlygyna göni jogap.',
    location: "Arabystan",
  },
  {
    title: "Mekgede dogulmak",
    body: 'Pygamber alaýhyssalam Mekgede Pil ýylynda doguldy (Am al-Fil), şeýle atlandyrylýar, sebäbi şol ýyl Yemenemeniň abyssin gubernatory Ybraýym, Käbäni ýok etmek üçin piller bilen goşun ýöriş edip, gudrat bilen yzyna gaýdyp geldi - Gurhanyň 105-nji süresinde ýatlaýan waka. Bu zarýadly ýylda Kuraýş taýpasyndan we iň abraýly urugy Banu Haşimden bir çaga dünýä indi.\n\nOl dogulanda eýýäm ýetimdi: kakasy Abdylla birnäçe aý öň söwda edip ýörkä aradan çykypdy. Ejesi Aminah bint Wahb oňa Muhammet - "iň öwgüli" diýip at dakdy, bu araplaryň arasynda diýen ýaly belli däldi. Makkanyň däp-dessuryna laýyklykda, Halima as-Sa\'diýanyň garamagynda Banu Sa\'diň arasynda açyk çöl howasynda terbiýelenmäge we ulalmaga iberildi.\n\nBir mömin üçin sapak: Allanyň nazarynda beýikligiň dünýä howpsuzlygy bilen hiç hili baglanyşygy ýok. Iň soňky Resul atasyz durmuşy başlady we tiz wagtdan ejesiz bolar, ýöne Allanyň Özi hossarlyk etdi - "Ol sizi ýetim tapmady we size gaçybatalga bermedimi?" (Gurhan 93: 6). Şeýle hem "Ejesiniň aradan çykmagy" we "Ebu Talybyň hossarlygy" -na serediň.',
    location: "Mekge",
  },
  {
    title: "Ejesiniň aradan çykmagy",
    body: 'Alty ýaşyndaka, Amina ogluny athatribdäki garyndaşlaryny (soňra Madinada) görmek we kakasynyň mazaryny görmek üçin alyp gitdi. Yzyna gaýdyp barýarka, syrkawlap, Mekge bilen Madinanyň arasyndaky Abwa diýilýän ýerde öldi we şol ýerde jaýlandy. Muhammadaş Muhammet now indi ene-atasynyň ikisini-de ýitirdi.\n\nMaşgalanyň azat edilen hyzmatkäri Umm Aýman tarapyndan Mekgä getirilip, ony gaty gowy görýän we Ka\'bada özi bilen oturýan Kuraýşyň abraýly başlygy Abd al-Muttalibiň hossaryna ýerleşdirildi.\n\nSapak: Pygamberimiz, köp adamyň göterýän hasratyny - ýogalmak, göçmek, başgalara garaşlylyk dadyp gördi. Bu onuň taýýarlygynyň bir bölegi. Lossitgini bilýän ýürek, ýetim, dul we nätanyş adam üçin duýup bilýän ýürekdir we jemgyýeti soňra şol rehimdarlyga esaslanar. Bu sapak "Hasrat ýyly" -da dowam edýär.',
    location: "Kaka",
  },
  {
    title: "Abu Talybyň hossarlygy",
    body: "Ejesinden iki ýyl soň, atasy Abd al-Muttalib hem sekiz ýaşyndaka aradan çykdy. Ölüm düşeginde söýgüli agtygyny Pygamberiň kakasy daýysy ogly Ebu Talyba ynandyrdy. Abu Talib baý bolmasa-da, çagany öz öýüne alyp gitdi we oňa iň eziz çagalarynyň biri hökmünde garady.\n\nAbu Talib, Mekgedäki iň agyr yzarlamalardan başlap, kyrk ýyldan gowrak wagt bäri goragçysy bolup galar. Mälim bolşy ýaly, monah Bahira özünde pygamberlik alamatlaryny gören ýaş Muhammet Syria Siriýa söwda saparyna alyp gidipdir (jikme-jiklikleri dürli güýçler bilen berilse-de).\n\nSapak: Allah her tapgyrda wepaly, abraýly adamlary Pygamberiniň töweregine goýdy. Abu Talibiň onlarça ýyllyk goragy rehimdarlykdy - hakykaty we garyndaşlygy goldamak, hatda ynanmadyklar üçinem asylly stansiýadygyny we bizi goraýanlara hormat goýmalydygymyzy ýatladýar. Soňra ýitgi, hasrat ýylynda hemme zady üýtgederdi.",
    location: "Mekge",
  },
  {
    title: "Hadyýa durmuşa çykmak",
    body: 'Muhammadaş wagtynda Muhammet Makkada hiç bir baýlygyň satyn alyp bilmejek abraýyny gazandy: al-Sadyk, hakykatçy we al-Amin. Adamlar gymmat bahaly zatlaryny saklamak üçin oňa goýupdyrlar we hatda dürli hudaýlara çokunýanlara-da doly ynanýardylar.\n\nKuraýşyň asylly we üstünlikli söwdagäri Hadijah bint Huweýlid (Alla ondan razy bolsun!) Ony kerwenini Siriýa alyp gitmek üçin işe aldy. Dogruçyllygyna we häsiýetine haýran galyp, dosty Khawlah bint Hakimiň üsti bilen nikalaşmak teklibini iberdi. Ol ýigrimi bäş töweregi, kyrk töweregi; olaryň çuňňur söýgi we şäriklik nikasy boldy. Ol çagalaryny dogurdy we tä ölýänçä ýigrimi bäş ýyllap ýekeje aýaly bolup galdy.\n\nSapak: häsiýet soňraky ähli zadyň esasyny düzýär. Pygamber diýilmezinden has öň, Mekge ony eýýäm olaryň arasynda iň dogruçyl adam hökmünde tanaýardy - şonuň üçin ilkinji ylhamda Hadyjanyň özüne bolan ynamy şeýle aýgytlydy ("Ilkinji ylham" ser.). Möminleriň adaty gatnaşyklarda dogruçyllygy dawanyň bir görnüşidir.',
    location: "Mekge",
  },
  {
    title: "Hilf al-Fudul we Gara daş",
    body: "Pygamberlikden öňki durmuşyndan iki waka, soňra millet gurjak gymmatlyklaryny görkezýär. Ilki bilen, Hilf al-Fudul: Kuraýşyň birnäçe urugynyň Makkada, ýerli ýa-da daşary ýurtly islendik ezilen adam bilen hukuklary dikeldilýänçä durmaga kasam eden dabaraly şertnama. Pygamberimiz ﷺ gatnaşdy we soňra şeýle şertnama Yslamda-da jogap berjekdigini aýtdy, sebäbi adalaty goraýardy.\n\nIkinjiden, silden soň Käbäniň täzeden gurulmagy. Tire-taýpalar mukaddes Gara daşy (al-Hajar al-Aswad) gaýtadan dikeltmegiň hormatyna zarba uranda, indiki adamyň girjek kararyny kabul etmäge razy boldular - bu Muhammet was. Onuň çözgüdi pähim-paýhasy bilen meşhur bolupdyr: daşy matanyň üstünde goýupdyr we her taýpanyň baştutany bir burçy galdyrypdyr, soň bolsa öz eli bilen ýerleşdiripdir, şonuň üçin hemmeler hormat paýlaşardy we hiç kimem kemsidilmedi.\n\nSapak: adalat we gapma-garşylyklary çözmek, wahy tassyklamazdan ozal onuň instinkti boldy. Imanly, zulum edilenleri goraýan we bölünmek däl-de, birleşmegiň ýollaryny tapýan adamdyr - Hilf al-Fudul hijretden soň gurjak adalatly jemgyýetini görkezýär.",
    location: "Mekge",
  },
  {
    title: "Ilkinji ylham",
    body: 'Otuz ýaşynda Pygamberimiz Makkanyň daşyndaky Jabal an-Nur dagynda ýerleşýän Hira gowagynda ybadat etmek we pikirlenmek üçin gitdigiçe yza çekildi. Remezan aýynda kyrk ýaşyndaka, Jibril perişde peýda bolup, oňa: "Oka!" Okap bilmejekdigine jogap berdi; Perişde ony üç gezek berk gujaklady we Gurhanyň ilkinji sözleri bolan "Allak" süresiniň - "createdaradan Rebbiň adyndan oka ..." (Gurhan 96: 1-5) aýatlaryny açdy.\n\nOl titräp öýüne gaýdyp geldi, Hadyýa ony gurşap aldy we imanyny we häsiýetini açyp görkezýän sözler bilen ynandyrdy: Allatagala ony hiç haçan masgara etmez, sebäbi garyndaşlyk gatnaşyklaryny saklaýardy, başgalaryň ýüküni çekýärdi we mynasyplara kömek edýärdi. Ol ony doganoglany Waraqah ibn Nawfalyň ýanyna alyp bardy, öňki ýazgylarda öwrenilen garry adamy Musanyň ýanyna gelen we oňa wada berlen pygamberlikdigini aýdýan şol "Namus" (perişde) diýip tanady. Bu bölümiň hemmesi Sahih al-Buhari 3-de ýazylýar.\n\nSapak: wahý häkimiýete talap etmek bilen däl-de, bilim we pespällige esaslanan din "Oka" sözi bilen başlandy. Ilki bilen kimiň ynanandygyna üns beriň: aýal we dogruçyl maşgala. Hakykat eýýäm çyn ýürekden ýaşaýanlar tarapyndan tanalýar.',
    location: "Hira gowagy",
  },
  {
    title: "Şahsy wagyz ýyllary",
    body: 'Ilkinji aýatlardan soň biraz arakesmeden soň, Allah Pygambere people adamlary diňe Oňa ybadat etmäge çagyrmagy buýurdy. Takmynan ilkinji üç ýylda bu çagyryş asuda we şahsy boldy - köçelerde yglan edilmän, ýakyn maşgala we ynamdar dostlara ýaýrady.\n\nIlkinji ynanýanlar, "as-Sabikun al-Awwalun" (iň esasy) jemgyýetiň dürli künjeklerinden gelip çykypdyrlar: aýaly Hadyýa; ýaş doganoglany Ali ibn Abi Talib; azat edilen hyzmatkäri we ogullyga alan ogly Zaýd ibn Harita; wepaly dosty Abu Bakr as-Siddik (Alla olaryň hemmesinden razy bolsun). Ebu Bekir öz gezeginde yslamy başga-da köp adam getirdi. Olar Käbäniň golaýyndaky Al-Arqamyň öýünde duşuşyp, paýhasly doga etdiler.\n\nSapak: Yslam ilki tomaşa däl-de, ynam we gatnaşyk arkaly ösdi. Ilkinji ýürekleriň giňligine üns beriň - baý aýal, çaga, azat gul, täjir - jyns we dereje tapawudyny ýok etjek imanyň başlangyjy. Da\'wah yhlas we sabyr bilen öýe ýakyn başlaýar.',
    location: "Mekge",
  },
  {
    title: "Halk köpçüligi yslama çagyrýar",
    body: 'Allatagala "we iň ýakyn garyndaşlaryňyza duýduryş beriň" (Gurhan 26: 214), Pygamberimiz Ka\'banyň gapdalyndaky Safa dagyna çykyp, Kuraýş uruglaryna çagyrdy. Ilki bilen depäniň aňyrsynda gizlenen goşunyň bardygyny aýtsa, oňa ynanjakdyklaryny sorady; ýalan sözlemegini hiç haçan tanamaýandyklaryna jogap berdiler. Soň bolsa olara geljek jeza barada duýduryş berdi we olary diňe Allaha ybadat etmäge çagyrdy.\n\nBu açyk habar, Mekgäniň buýrugynyň düýbüni tutdy. Butlar diňe bir din bolman, eýsem eklenç we abraýdy - şäheriň ybadathananyň goragçysy statusy zyýaratçylary we söwdany özüne çekdi. Butlaryň güýçsüzdigini aýtmak Kuraýşyň ykdysadyýetine, ata-babalaryna we buýsanjyna birbada garşy çykmakdy. Bu ýerden Bilal ibn Rabah we asirasiriň maşgalasy ýaly imanlylaryň arasynda ejizlere we gullara agyr degmek, yzarlamalar hasam güýçlendi.\n\nSapak: aç-açan aýdylýan hakykat kök uran gyzyklanmalary çözmez. Pygamber alaýhyssalam, haýbat atmazdan ozal dogruçyl - paýhasly we dogruçyldygyna güwä geçdi. Tewhidiň üstünde durmak, Makkanlylaryň öwrenişleri ýaly dünýä rahatlygy üçin gymmat bolup biler. Bu kynçylyk gönüden-göni "Abyssiýa göçmegine" eltýär.',
    location: "Safa dagy",
  },
  {
    title: "Abyssiýa göç",
    body: "Zulumlar çydap bolmansoň, Pygamber alaýhyssalam öz ýoldaşlarynyň bir toparyna Abyssiýanyň (häzirki Efiopiýa) adalatly hristian şasy Negusdan (an-Najaşi) gaçybatalga sorady we öz ýurdunda hiç kime zulum edilmändigini aýtdy. Bir topar Gyzyl deňziň üstünden geçdi, soňra has uly ikinji göç - Yslamdaky ilkinji hijret.\n\nKuraýş bosgunlaryň yzyna berilmegini talap edip öz wekillerini iberende, Negus olary çagyrdy. Jafar ibn Abi Talib (Alla ondan razy bolsun!) Musulmanlar üçin nadanlykdan hakykata, rehim-şepagat we gowy gylyk-häsiýetlere nädip çykandyklaryny beýan etdi, soň bolsa Merýem süresinden Isa we ejesi hakda aýatlar okady. Hristian patyşasy aglady, ýere çyzyk çyzdy we imany bilen imanyň arasyndaky tapawudyň mundan has giň däldigini aýtdy we boýun egmedi.\n\nSapak: bu dini çydamlylygyň we Kitabyň yhlasly adamlary bilen köpri gurmagyň möhüm nyşanydyr. Şeýle hem, adalatly musulman däl häkimýetiň döwründe sütemden howpsuzlygy gözlemegiň düýbünden kanunydygyny öwredýär. Günüň ýeňen jedeliniň owadan häsiýetdigine we Allanyň okan sözüniň güýç däldigine üns beriň.",
    location: "Abyssiýa",
  },
  {
    title: "Banu Haşimi boýkot etmek",
    body: "Yslamyň ýaýramagynyň öňüni alyp bilmedi ýa-da Pygambere ýetip bilmedi, tire-taýpalary ony goraýarka, Kureýşiň ýolbaşçylary köpçülikleýin jezalandyryldy. Şertnama ýazyp, Ka'bada asdylar, Banu Haşimiň (we olaryň ýaranlary Banu al-Muttalibiň) tutuş urugyny boýkot etjekdiklerine söz berdiler: Muhammet tabyn bolýança olar bilen nikalaşma, söwda, jemgyýetçilik gatnaşyklary bolmaz.\n\nTakmynan üç ýyllap tire - Haşime ynanmaýanlar we ynanmaýanlar - Şyb Abi Talib dag jülgesinde saklandylar, açlyga çydadylar, çagalaryň nalyşlary eşidildi we adamlar ýaprak iýdiler. Birnäçe adalatly Kuraýşi erkek adam muny aç-açan ret edende we pergamentiň iýilendigi anyklanylandan soň, boýkot ýykyldy, Allanyň adynyň görkezilen sözlerinden başga.\n\nSapak: ýalan çakdanaşa ýetýär. Boýkotyň zalymlygy diňe yzarlaýanlaryň adalatsyzlygyny paş etdi we imanlylaryň kararyny berkitdi. Şeýle hem, wagşylygy bes etmek üçin hatardan çykan duşmançylykly jemgyýetiň içinde birnäçe adalatly adamyň abraýyny görkezýär - wy consciencedanyň iň ýiti oppozisiýada-da ýaşap biljekdigini ýatladýar.",
    location: "Şy'b Abi Talib",
  },
  {
    title: "Hasrat ýyly",
    body: "Baýkot gutarandan kän wagt geçmänkä, Pygamberimiz gysga wagtyň içinde iki sany uly ýitgi çekdi we bu ýyl Am al-Huzn, hasrat ýyly diýlip atlandyryldy. Ilki daýysy we ömürboýy goraýjy Abu Talib aradan çykdy - adamy onlarça ýyllap Kuraýşdan goraýan adam. Soňra ýigrimi bäş ýyl töweregi aýaly, ilkinji imanly we iň ýakyn goldawy bolan Hadyýa (Alla ondan razy bolsun!) We aradan çykdy.\n\nSosial goragy we emosional labyry ikisi bilen gidensoň, Kuraýş hyýanatçylyklarynda has berkleşdi. Hut şu döwürde halkynyň bu habary kabul etmegine umyt edip Ta'if şäherine syýahat etdi; tersine, ony kowup çykardylar we aýaklary ganýança çagalary daşlamak üçin goýdular. Şonda-da şäheri weýran etmegi teklip edenlerinde, olaryň nesillerinden bir gün Allaha ybadat etmegini dileg etdi.\n\nSapak: hatda pygamberlerem gaýgy we ret etmek bilen synagdan geçirilýär we jogap ajy bolmazdan sabyr etmekdir. Adamyň ýitmegi, ylahy terk etmegi aňlatmaýar; ýeňillik, indiki geljek gijeki syýahatda yzarlandy. Seret \"Al-Isra wal-Mi'raj.\"",
    location: "Mekge",
  },
  {
    title: "Al-Isra wal-Mi'raj",
    body: "Hasrat ýylyndan soň adatdan daşary hormat gijesi geldi. Ysraýylda Pygamber a bir gijede Mekgedäki mukaddes metjitden Iýerusalimdäki Al-Masjid al-Aqsa şäherine äkidildi - bu Gurhan al-Isra süresini açýar (Gurhan 17: 1). Ol ýerde öňki pygamberleri doga edip alyp bardy. Soňra Mirajda ýedi asmanyň üsti bilen direldi we Adam, Musa we Ybraýym ýaly pygamberler bilen duşuşdy we ýaradylanlardan has köp Rebbine ýakyn bir duralga geldi.\n\nŞol gijäniň esasy sowgady gündelik bäş namazdy. Sahih al-Buhari 3887-de ýazylyşy ýaly, ilki bilen elli hökmünde emr edildi; Musa pygamberiň maslahaty bilen, elli sylagy alyp barýarka iş ýüzünde bäşe çenli azalýança ýeňillik soramak üçin gaýta-gaýta gaýdyp geldi. Alymlar takyk senesi boýunça tapawutlanýarlar, köpüsi hijretden birnäçe ýyl öň ýerleşdirýärler.\n\nSapak: gynanýan Pygambere teselli bermek üçin berlen sowgat, biziň gijeki Allaha çykmagymyzdyr. Gündelik bäş doga bir perişde tarapyndan ýere iberilmän, imanly adamyň durmuşynda agramynyň alamaty hökmünde kabul etmek üçin asmana göterildi.",
    location: "Iýerusalim",
  },
  {
    title: "Aqabahyň ilkinji girewi",
    body: "Zyýaratçylar her ýyl Mekgä ýygnanyşýardylar we Pygamber alaýhyssalam zyýarat edýän taýpalara yslamy hödürleýärdi. Minanyň golaýyndaky Al-Aqabah diýilýän ýerde, Aws we Khazraj taýpalarynyň arasynda dawa-jenjel sebäpli dörän we ýewreý jemagatynyň üsti bilen monoteizm bilen tanyş bolan athatribden (Madinadan) kiçi bir topar habar diňledi, ynanýardy we öýüne alyp gitdi.\n\nIndiki möwsümde on ikisi gaýdyp gelip, Al-Aqabanyň birinji wadasyny berdi: diňe Allaha ybadat etmek, ogurlamazlyk, bikanun jynsy gatnaşyklar etmezlik, çagany öldürmezlik we Pygambere boýun bolmak. Soňra ýaş ýoldaş Mus'ab ibn Umaýry (Alla ondan razy bolsun!) Yslamyň ilkinji mugallymy we ilçisi hökmünde yzyna iberdi we iman bilen athatribiň maşgalalaryna çalt ýaýrady.\n\nSapak: Mekgede ýapyk ýaly görünýän gapy Madinada açyldy. Jemgyýetiň nädip gurlandygyna üns beriň - öwretmek arkaly. Gurhan bilen iberilen wepaly ýaş mugallym, tutuş şäheri Yslamyň bäşligi bolmak üçin taýýarlady. Bu gönüden-göni Ikinji girewi we hijri düzýär.",
    location: "Mina",
  },
  {
    title: "Aqabanyň ikinji girewi",
    body: 'Ilkinji wadadan bir ýyl soň, athatribdan has uly delegasiýa - ýetmiş üç erkek we iki aýal zyýarat wagtynda Al-Aqaba pygambere gizlin geldi. Bu gezek borçnama hasam dowam etdi: öz aýallaryny we çagalaryny gorajak bolşy ýaly, ony goramagy we Mekgäniň yzarlanan musulmanlaryny öz şäherlerine kabul etjekdiklerine söz berdiler.\n\nBu öwrülişik boldy. Täze döredilen jemgyýetde ilkinji gezek watany bardy we ony goramaga kasam eden bir topar adam bardy. Howpuna düşünip, Pygamber alaýhyssalam, Makkadaky ýoldaşlaryna Kuraýşy gorkuzmazlyk üçin athatribe kiçi toparlara göçüp başlamagy buýurdy.\n\nSapak: çyn ýürekden ygrarlylyk jogapkärçiligi öz üstüne alýar. Ansarlar (Medinäniň "Kömekçileri") diňe iman üçin hiç zat gazanmazdan ozal durmuşlaryny we öýlerini wada berdiler. Olaryň jomartlygy yslam doganlygynyň nusgasyna öwrüler - emigrantlary maşgala hökmünde garşy alýan “Hijradan Medinä” ýatlanylýar.',
    location: "Mina",
  },
  {
    title: "Medinä hijri",
    body: 'Kuraýş Pygambere janyna kast etmek üçin dildüwşük guranda, Allah oňa göçmäge rugsat berdi. Iň ýakyn dosty Ebu Bekir (Alla ondan razy bolsun!) Bilen ýola düşüp, Alyny adamlaryň goýumlaryny yzyna gaýtarmak üçin düşeginde goýdy. Iki adam Tawr gowagynda üç gije gizlenip, kowalap gelýänler şeýle bir ýakynlaşdy welin, Abu Bakr olardan gorkýardy we Pygamber alaýhyssalam oňa: «Iki hakda näme pikir edýärsiň, üçünjisi Allah?» Diýip ynandyrdy. Bu pursat Sahih al-Buhari 3653-de ýazylyp, Gurhanda ýaňlanýar: "... gowakda bolanlarynda ikisine ikinjisi, ýoldaşyna:" Gaýgy etme, hakykatdanam Allah biziň bilendir "(Gurhan 9:40).\n\nIlkinji metjidiň gurlan Kubasyna baryp ýetdiler, soňra athatriba girdiler - şondan soň al-Medine al-Munawwarah, "iantagty şäher". Pygamberimiz each her bir emigranty (Muhajir) Kömekçi (Ansari) bilen doganlyk baglanyşyklarynda jübütledi; sahylyk şeýle bir dolydy welin, Sa\'d ibn al-Rabi \'baýlygynyň ýarysyny Abdur-Rahman ibn Awf bilen paýlaşmagy teklip etdi, ol ýerine diňe bazaryň görkezilmegini isledi (Sahih al-Buhari 3780/3906).\n\nHijri şeýle bir möhümdi welin, Umar soňra Yslam senenamasynyň başlangyjy boldy - beöň 1-nji ýyl. Sapak: käwagt iman hemme zady Allah üçin terk etmegi, Onuň ak ýüreklidigine ynanmagy we gan däl-de, doganlygy täzeden gurmagy talap edýär.',
    location: "Madina",
  },
  {
    title: "Medinäniň konstitusiýasy",
    body: 'Tire-taýpa urşy zerarly weýran bolan şähere gelen Pygamberimiz, diňe bir musulmanlara ýolbaşçylyk etmedi - bir jemgyýet döretdi. Ibn Yshagyň seerasynda saklanylýan we Sahifah ýa-da Medinäniň konstitusiýasy diýlip atlandyrylýan ýazmaça şertnama baglaşyp, Muhajirun, Ansar we şäheriň ýewreý taýpalaryny birek-biregi goramak şertnamasyna baglady.\n\nSözleri öz döwri üçin ajaýypdy: taraplar şertnamanyň maksatlary üçin "bir jemagat (ymmat)" döretdiler, her topar öz dinini saklady, jedeller Pygambere ýüz tutulmalydy, agressiýa we adalatsyzlyk gadagan edildi we hemmesi şäheri daşarky hüjümlerden goramagy wada berdiler. Medinäni tükeniksiz dawa däl-de, ylalaşylan hukuklar we borçlar bilen şäher-döwlet etdi.\n\nSapak: Yslam diňe bir şahsy ybadat däl, eýsem jemgyýetiň adalatly tertibi. Pygamber plýuralistik bilelikde ýaşamagy, taýpa söwdasy barada ylalaşylan kanunyň hökmürowanlygyny we geljekdäki çaknyşyklarda synag ediljek ýörelgelere hormat goýdy. Tutuş şähere adalatlylygy giňeltmek bilen "Hijranyň Medinä" doganlygyny doldurýar.',
    location: "Madina",
  },
  {
    title: "Badr söweşi",
    body: 'Hijreden soň ikinji ýyl özüni goramak üçin söweşmäge rugsat berildi (Gurhan 22:39). Miladydan öňki 17-nji Remezan aýynda takmynan 313 adamdan ybarat musulman güýçleri, ýaragsyz, diňe sanlyja at bilen ýaragly, Madinanyň günorta-günbataryndaky Badr guýusynda takmynan müň güýçli Kuraýş goşuny bilen duşuşdy. Bu yslamyň ilkinji uly söweşi boldy.\n\nMusulmanlar kynçylyklara garşy aýgytly ýeňiş gazandylar we Kuraýşy yzarlaýanlaryň birnäçesi öldürildi. Gurhan ýeňşi diňe bir harby edermenlik däl-de, alamat hökmünde görkezýär: "Allatagala ejiz wagtyňyz Badrda ýeňiş gazandy, şükür etmek üçin Alladan gorkuň" (Gurhan 3: 123) we perişdeleriň kömegini suratlandyrýar (Gurhan 3: 124–125). Badr ýaş jemgyýeti Arabystanda hakyky güýç hökmünde döretdi.\n\nSapak: netijeler sanlara ýa-da enjamlara däl-de, Allaha degişlidir. Badr "ölçeg güni" (yawm al-furqan) hökmünde ýatda saklanýar, hakykat we ýalan tapawutlandy - günä Allaha çyn ýürekden bil baglamagyň subutnamasydyr. Indiki ýyl Uhuddaky terslik goşmaça sapak berer.',
    location: "Badr",
  },
  {
    title: "Uhud söweşi",
    body: 'Badrdan bir ýyl soň, Kuraýş has uly goşun bilen ar almak üçin gaýdyp geldi we iki tarap Madinanyň golaýyndaky Uhud dagynyň eteginde duşuşdy. Pygamberimiz, näme bolsa-da hiç wagt öz pozisiýasyny terk etmezligi berk tabşyryk bilen elli ýaýçy depä ýerleşdirdi. Söweşiň başynda musulmanlar ýeňiş gazandy; duşmanyň gaçýandygyny görüp, ýaýçylaryň köpüsi olja ýygnamak üçin postundan gitdiler. Halid ibn al-Walidiň (henizem musulman däl) ýolbaşçylygyndaky Kuraýş atlylary açyk kenara aýlandy we tolkun gaty agyr, agyr güne öwrüldi.\n\nKöp sahabalar şehit boldular, olaryň arasynda Pygamberiň söýgüli daýysy Hamza (Alla ondan razy bolsun!) "Allanyň arslany". Pygamberimiziň özi ýaralandy, dişleri döwüldi we ýüzi ganlydy. Ondan soň Gurhan bu kynçylyklara aç-açan ýüzlenip, synagyň we buýruga boýun bolmazlygyň we dünýäni islemegiň netijesidigini düşündirdi (Gurhan 3: 152, 3: 165-166).\n\nSapak: Uhud tertip-düzgüne we tabynlyga uly sapakdyr. Düzgün-nyzamly ýekeje hereket, kiçijik ýaly görünse-de, ýeňiş gazandy. Emma Allah olary terk etmedi - öwretdi, bagyşlady we ýygnady. Çyn ýürekden ýeňilen ýeňiş, ýeňişden has öwrediji bolup biler.',
    location: "Uhud dagy",
  },
  {
    title: "Çukur söweşi",
    body: 'Bäşinji ýylda Kuraýşyň, beýleki arap taýpalarynyň we duşman toparlaryň bileleşigi - "Konfederasiýa" (al-Ahzab), Arabystanda henizem görülýän iň uly güýç, belki on müň güýçli bolup, Medinäni bir gezek ýok etmek üçin ýygnandy. Açyk söweşde duşmak üçin gaty uly bir duşmana ýüz tutup, Pygamberimiz pars ýoldaşy Salman al-Farisiniň (Alla ondan razy bolsun!) Şähere açyk demirgazyk çemeleşmelerinden giň çukur gazmak baradaky maslahatyny kabul etdi - bu araplaryň hiç haçan görmedik taktikasy.\n\nÇukur gabawy saklady. Birnäçe hepde sowuk, açlyk we gorky dowam etdi we Gurhan imanlylaryň Ahzab süresindäki synagyny aç-açan suratlandyrýar: "... gözler gorkudan ýaňa ýürek bokurdagyna ýetende" (Gurhan 33:10). Ahyrynda güýçli ýel we içerki düşünişmezlik konfederasiýa goşunyny dargatdy we hiç hili söweşsiz yza çekildi. Gurhan, "görmedik ýeliňi we goşunyňy olara iberen" Allaha gutulyş hasaplaýar (Gurhan 33: 9).\n\nSapak: paýhasly maslahat (şura) we her kimden gowy pikirlere açyklyk - bu ýerde, daşary ýurtlularyň in engineeringenerligi - imanyň bir bölegidir. Ynsan tagallasy doly berlensoň, halas bolmak henizem Alladan gelýär. Bu döwülen gabaw Kuraýşyň hüjüm etmek ukybyny netijeli tamamlady.',
    location: "Madina",
  },
  {
    title: "Hudaýbiýa şertnamasy",
    body: 'Pygamberimiz altynjy ýylda 1400 töweregi ýoldaşy bilen parahatçylykly niýetini aýdyňlaşdyrmak üçin söweşmek däl-de, ymram döwletine girmek üçin ýola çykdy. Kuraýş mukaddes ýeriň gyrasynda, Hudaýbiýa diýilýän ýerde gadagan etdi. Dartgynly gepleşiklerden soň köp ýoldaşlara kemsidiji şertlerde on ýyllyk ýaraşyk baglaşyldy: Musulmanlar şol ýyl yza gaýdyp, indiki ýyl gelerler; Kuraýşdan musulmanlara gaçýan islendik adam yzyna gaýtarylar, ýöne tersine däl.\n\nŞeýle-de bolsa, Allah bu şertnamanyň "aç-açan ýeňiş" bolandygyny aýan etdi (Gurhan 48: 1, Fath süresi). Sahabalar soňra has uly ýeňiş görmändiklerini aýtdylar - sebäbi soňraky parahatçylykda adamlar erkin garyşdylar, habary asuda eşitdiler we söweş ýyllaryna garanyňda has köp Yslam dinine girdiler; Al-Bara ibn Azibiň bu barada beren hasabaty Sahih al-Buhari 4606-da ýazylýar. Bu ýaraşyk musulmanlary deň güýç hökmünde aç-açan ykrar etdi.\n\nSapak: şowsuzlyga meňzeýän zat iň uly açyş bolup biler. Pygamberimiz long uzak möhletli ýagşylyk üçin görünýän gysga möhletli ýitgini saýlady we hatda söwdasyna hormat goýdy. Sabyr etmek, saklamak we sözüňi saklamak gapma-garşylygyň edip bilmejek zadyna ýetip biler.',
    location: "Hudaybiýa",
  },
  {
    title: "Haýbara ekspedisiýa",
    body: "Hudaýbiýadan kän wagt geçmänkä, Pygamberimiz Madinanyň demirgazygyndaky berkitilen berkitmeleriň baý oazisi Haýbara tarap öwrüldi. Haýbar, Konfederasiýalaryň Madinany gabawyny gurnamaga kömek eden we musulman jemagatyna garşy dildüwşük guran taýpalaryň mekanyna öwrüldi. Kampaniýa bu howpy ýok etmegi maksat edinýärdi.\n\nGalalar agyr söweşlerden soň yzly-yzyna ýykyldy; aýgytly günde baýdak Ali ibn Abi Talyba (Alla ondan razy bolsun!) berildi. Ondan soň Pygamberimiz, ýaşaýjylara önümleriniň paýynyň deregine ýerlerinde galmaga we ekerançylyklaryny dowam etdirmäge rugsat berdi - bu hemmäni kowmak däl-de, Medinä azyk we durnuklylygy üpjün edýän ylalaşyk. Hut şu ýerde-de bir aýal oňa goýun bilen zäherlemäge synanyşdy, oňa duýduryş berildi.\n\nSapak: howpsuzlyk we şertnamalary ýerine ýetirmek bir-birine ýakynlaşdy. Bu hereket subut edilen duşman güýjüne garşydy, ýöne ýeňilenleriň eklenjini dowam etdirmäge mümkinçilik berýän çözgüt bilen tamamlandy. Yslamdaky güýç ýok etmek däl-de, howpsuzlygy we adalaty döretmek üçin niýetlenendir.",
    location: "Haýbar",
  },
  {
    title: "Mekgäni basyp almak",
    body: 'Kuraýşyň ýaranlary Musulmanlara ýaran bir taýpa hüjüm edip, Hudaýbiýanyň şertlerini bozanda, ýaraşyk ýatyryldy. Sekizinji ýylyň Remezan aýynda Pygamber alaýhyssalam iň uly güýç bolan on müň adam bilen Mekgä ýöriş etdi we ýigrimi ýyllap oňa garşy yzarlan, boýkot eden we söweşen şäher gan dökülmän diýen ýaly boýun egdi.\n\nAhyrynda özüni kowup çykaran adamlaryň üstünden ýeňiji bolup durup, Makkandan özlerinden näme garaşýandyklaryny sorady. Asylly doganyň rehim-şepagatyna umyt bagladylar we ol Yusufusubyň doganlaryna: "Bu gün size günäkär däl" diýip jogap berdi we "Git, sebäbi sen azat" diýdi. Käbä girdi we 360 ​​hakykatdan arassalady, "Hakykat geldi, ýalan ýitdi" (Gurhan 17:81), Ybraýymyň ybadathanasyny Allanyň arassa ybadatyna dikeltdi. Nasr süresi (110-njy Gurhan) adamlaryň "Allanyň dinine köp adam girýän" pursaty hakda aýdýar.\n\nSapak: bu pygamberlik rehimdarlygynyň we bagyşlamagyň ýokary derejesi. Ar almak üçin doly güýji bilen, ol günäsini geçdi. Mömin, güýçlileriň jezalandyryp bilýänlerinde bagyşlaýandyklaryny we maksat hiç haçan ar almak däl-de, ýol görkezmekdigini öwrenýär.',
    location: "Mekge",
  },
  {
    title: "Tabuga ekspedisiýa",
    body: 'Dokuzynjy ýylda Wizantiýa (Rim) demirgazyk serhedinde bolup biläýjek mobilizasiýa barada habarlar Medinä ýetdi. Tomusyň yssy yssysynda, hasyl ýetişip, syýahat uzak we kyn bolanda, Pygamberimiz led ýolbaşçylyk eden iň uly goşuny - belki otuz müň adamy demirgazykdan Tabuk şäherine gitmäge çagyrdy. Bu "kynçylyk sagady" boldy (Gurhan 9: 117) we yhlasy öňküsi ýaly synady.\n\nSöweş bolmady; çözgüt görkezmek ýeterlikdi we birnäçe demirgazyk baştutany Madina bilen şertnama baglaşdy. Campaignöne bu kampaniýa, ilkinji nobatda, adamlaryň ýüregi barada açan zatlary bilen ýatda saklanýar. Gurhan Tawba süresiniň köp bölegini özüne bagyşlaýar - hemme zady berenleri öwýär (Ebu Bekir ähli baýlygyny berdi), galmak üçin bahana oýlap tapan ikiýüzlüleri paş etdi we üç ak ýürekli imanlynyň, şol sanda Ka\'b ibn Mälikiň bahana ýokdugyny boýun aldy we 9 synagdan soň bagyşlandy.\n\nSapak: amatly bolanda boýun bolmak aňsat; hakykaty gymmat bolanda görkezýär. Tabuk ak ýüreklileri bahanaçylardan aýyrdy we Arabystanda guramaçylykly butparazlygyň garşylygynyň netijeli gutarandygyny görkezdi. Dogruçyllyk - hatda biriniň şowsuzlygyny boýun almagyň dogruçyllygy - Allaha gaýdyp barýan ýol.',
    location: "Tabuk",
  },
  {
    title: "Hoşlaşyk zyýaraty",
    body: 'Onunjy ýylda Pygamberimiz, ýüz müňden gowrak ýoldaşy bilen bilelikde ýeke-täk doly hajyny okady we olara däp-dessurlary öwretdi. Arafah düzlüginde durup, Yslamyň esaslandyran ähli zatlarynyň gysgaça mazmuny bilen Hoşlaşyk hutbasyny (Khutbat al-Wada \') berdi.\n\nOl her bir adamyň ömrüniň, emläginiň we abraýynyň mukaddesligini yglan etdi - "ganyňyz we emlägiňiz şu gün, şu aý, bu toprak ýaly mukaddesdir" (Sahih al-Buhari 1741). Gan dawa-jenjellerini we Jahilýanyň gyzyklanmasyny (riba) ýatyrdy, aýal-gyzlara Allanyň ynamy hökmünde gowy garamagy buýurdy, takwa bolmakdan başga hiç bir arapyň arap dällerden ýokary däldigini ýada saldy we Gurhana berk ýapyşmalydygyny aýtdy. Hut şu haj zyýaratynda, anna güni düşen Araf güni, Allatagala "Bu gün men siziň diniňizi kämilleşdirdim ..." (Gurhan 5: 3) - Umaryň ýatlaýan we takyk ýazylan aýaty (Sahih al-Buhari 45).\n\nSapak: Hoşlaşyk hutbasy Yslamyň adam mertebesi, adalat we deňlik düzgünnamasydyr, bu diniň doludygyny yglan etmek bilen möhürlenendir. Bu ýerden imanly adamyň wezipesi oňa goşmak däl-de, ýaşamakdyr.',
    location: "Arafah",
  },
  {
    title: "Onuň aradan çykmagy",
    body: 'Hoşlaşyk hajyndan birnäçe aý soň, Pygamberimiz a gyzzyrma bilen keselledi. Soňky günlerinde aýallaryndan Aýşanyň (Alla ondan razy bolsun!) Otagynda emdirilmegi üçin rugsat sorady we Ebu Bekri namazlara ýolbaşçylyk etdi. Iň soňky gününde namaz okaýanlaryň hataryna doga edip, ýylgyryp, jemagatyna begenip, soň ýykylmagyny görmek üçin perdäni yza çekdi. Sahih al-Buhari 4449/4451-de aýdyşy ýaly, kellesi Aýşanyň döşüniň we eňeginiň arasynda durýan 12-nji Rabi al-Awwal 11-nji duşenbe güni aradan çykdy.\n\nMadinadaky hasrat gaty köpdi, hatda Umar hem muny kabul etmekden ýüz öwürdi. Soňra Ebu Bekir ýerinden turdy, Pygamberiň ýüzüni ogşady we bütin jemagaty berkitýän we Sahih al-Buhari 1241/1242-de ýazylan sözler bilen halka ýüzlendi: "Kim Muhammet alaýhyssalam ybadat eden bolsa, Muhammet öldi; ýöne Allaha ybadat edýän bolsa, Allah hemişe ýaşaýar we ölmez." Ol "Muhammet pygamberdir, ondan öň habarçylar aradan çykdy ..." (Gurhan 3: 144).\n\nSapak: habar doly boldy we indi ymmatyňkydy. Pygamber alaýhyssalam öldi, ýöne getiren zatlary - Gurhan we Sünnet däl. Ebu Bekiriň beren jogaby, hasratyň dowamly jogabydyr: biziň baglanşygymyz hiç haçan ölmeýän Allaha we Pygambere söýmegiň ýoly his onuň ýol görkezmegidir.',
    location: "Madina",
  },
];
