// Bosnian translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_BS: DeepPartial<SeerahEvent>[] = [
  {
    title: "Arabija prije islama (džahilijjet)",
    body: 'Da biste razumjeli Poslanika, sallallahu alejhi ve sellem, prvo morate zamisliti svijet u koji je poslan. Arabija iz šestog vijeka bila je zemlja raštrkanih plemena bez centralne države, povezanih lozom, čašću i svetilištem Kabe u Mekki - svetištu koje su izgradili Ibrahim i Ismail za obožavanje jedinog Boga, ali je do sada okruženo sa oko tri stotine šezdeset idola.\n\nOvo doba se naziva džahilija, "doba neznanja" - ne zato što je Arapima nedostajala inteligencija (njihova poezija i pamćenje su bili izvanredni) već zato što im je nedostajalo vodstvo. Plemenske svađe su mogle trajati generacijama, jaki su plijenili slabe, a kćeri su ponekad bile zakopane žive iz stida ili straha od siromaštva – praksa koju bi Kur\'an kasnije direktno osudio (Kur\'an 81:8–9). Pored idolopoklonstva, nekoliko "hunafa" je još uvijek tražilo čisti Ibrahimov monoteizam, a male jevrejske i kršćanske zajednice živjele su širom poluotoka.\n\nPouka: otkrivenje se nije spustilo u vakuum već u pravo društvo sa dubokim ranama, a prvo što je zaliječilo bio je odnos između čovjeka i njegovog Stvoritelja. Imajte na umu ovu pozadinu kako se vremenska linija odvija – skoro svaka reforma Poslanika, sallallahu alejhi ve sellem, je direktan odgovor na nepravdu džahilijeta.',
    location: "Arabija",
  },
  {
    title: "Rođen u Mekki",
    body: 'Poslanik, sallallahu alejhi ve sellem, je rođen u Mekki u godini slona (Am al-Fil), nazvan je tako jer je te godine Abraha, abesinski guverner Jemena, krenuo sa vojskom sa slonovima da uništi Kabu i čudesno je vraćen nazad – događaja na koji Kur\'an podsjeća (Kur\'an 105). U ovoj opterećenoj godini rođeno je dijete plemenu Kurejš i njegovom najpoštovanijem klanu, Banu Hašimu.\n\nVeć je bio siroče po rođenju: njegov otac Abdulah je umro mjesecima ranije dok je trgovao u gostima. Njegova majka, Amina bint Wahb, dala mu je ime Muhammad - "najhvaljeni" - ime gotovo nepoznato među Arapima. U skladu s mekanskim običajima, poslan je da bude njegovan i odgajan na otvorenom pustinjskom zraku među Banu Sadima, pod brigom Halime as-Sa\'diyyah.\n\nPouka za vjernika: veličina u Allahovim očima nema nikakve veze sa svjetskom sigurnošću. Posljednji Poslanik je započeo život bez oca i uskoro će ostati bez majke, a ipak je sam Allah bio njegov staratelj - "Zar te nije našao siroče i dao ti utočište?" (Kur\'an 93:6). Vidi također "Umiranje njegove majke" i "Starateljstvo Abu Taliba" koji slijede.',
    location: "Mekka",
  },
  {
    title: "Smrt njegove majke",
    body: 'Kada mu je bilo oko šest godina, Amina je odvela svog sina da posjeti svoje rođake u Jatribu (kasnije Medini) i da vidi grob svog oca. Na povratku se razboljela i umrla na mjestu zvanom Abwa\', između Mekke i Medine, i tamo je pokopana. Mladi Muhammed, sallallahu alejhi ve sellem, je sada izgubio oba roditelja.\n\nU Mekku ga je vratila Umm Ayman, oslobođena sluškinja porodice, i dala na brigu njegovom djedu Abd al-Muttalibu, uvaženom poglavici Kurejšija, koji ga je duboko volio i koji ga je stavljao pored sebe u Kabu.\n\nPouka: Poslanik, sallallahu alejhi ve sellem, je okusio, rano i iznova, tugu koju nose mnoga ljudska bića — žalost, raseljavanje, ovisnost o drugima. Ovo je bio dio njegovih priprema. Srce koje je doživjelo gubitak je srce koje može osjećati prema siročetu, udovici i strancu, a njegova zajednica će kasnije biti izgrađena upravo na toj milosti. Ova nit se nastavlja u "Godini tuge".',
    location: "Abwa'",
  },
  {
    title: "Starateljstvo Abu Taliba",
    body: "Dvije godine nakon njegove majke, umro je i njegov djed Abd al-Muttalib, kada je dječak imao oko osam godina. Na samrti je povjerio svog voljenog unuka svom sinu Ebu Talibu, Poslanikovom stricu sa očeva. Iako Ebu Talib nije bio bogat, uzeo je dijete u svoje domaćinstvo i tretirao ga kao jedno od svoje najdraže djece.\n\nAbu Talib će ostati njegov zaštitnik više od četrdeset godina, kroz najteže godine progona u Mekki. Upravo je on odveo mladog Muhammeda sallallahu alejhi ve sellem na trgovačka putovanja u Siriju, gdje je — prema dobro poznatom izvještaju — monah Bahira primijetio znakove proroštva u njemu (izvještaj koji sera čuva, iako se njegovi detalji prenose s različitom snagom).\n\nPouka: Allah je postavio lojalne, časne ljude oko Svoga Poslanika, sallallahu alejhi ve sellem, na svakoj fazi. Decenije Abu Talibove zaštite bile su milost — podsjetnik da je podrška istini i srodstvu plemenita pozicija čak i za one koji još nisu vjerovali, i da trebamo poštovati one koji nas štite. Njegov gubitak kasnije, u godini tuge, promijenio bi sve.",
    location: "Mekka",
  },
  {
    title: "Vjenčanje sa Hatidžom",
    body: 'Kao mladić, Muhammed sallallahu alejhi ve sellem je stekao reputaciju širom Mekke koju nijedno bogatstvo nije moglo kupiti: Al-Sadiq, istinoljubiv, i al-Amin, pouzdani. Ljudi su mu polagali svoje dragocjenosti na čuvanje i apsolutno su mu vjerovali na riječ, čak i oni koji su obožavali različite bogove.\n\nHatidža bint Huvejlid (neka je Allah zadovoljan njom), plemeniti i uspješni trgovac Kurejšija, unajmila ga je da vodi njenu karavanu u Siriju. Impresionirana njegovom iskrenošću i karakterom, poslala je ponudu za brak preko svog prijatelja Khawlaha bint Hakima. On je imao oko dvadeset pet, a ona oko četrdeset; njihov brak je postao brak duboke ljubavi i partnerstva. Rodila mu je djecu i ostala njegova jedina žena nekih dvadeset i pet godina, sve do svoje smrti.\n\nPouka: karakter je temelj svega što je uslijedilo. Mnogo prije nego što je nazvan poslanikom, Meka ga je već poznavala kao najpoštenijeg čovjeka među njima — zbog čega je, pri prvom otkrivenju, Hatidžino trenutno povjerenje u njega bilo tako odlučujuće (vidi "Prvo otkrivenje"). Vjernikov integritet u uobičajenim postupcima je sam po sebi oblik da\'we.',
    location: "Mekka",
  },
  {
    title: "Hilf al-Fudul i Crni kamen",
    body: "Dva incidenta iz njegovog preproročkog života pokazuju vrednosti na kojima će kasnije graditi naciju. Prvo, Hilf al-Fudul: svečani pakt na koji se zaklelo nekoliko klanova Kurejšija da će stajati uz bilo koju potlačenu osobu u Mekki, domaću ili stranu, sve dok njihova prava ne budu vraćena. Poslanik, sallallahu alejhi ve sellem, je učestvovao i kasnije je rekao da će i dalje odgovoriti na takav pakt čak i u islamu – jer je branio pravdu.\n\nDrugo, obnova Kabe nakon poplave. Kada su se klanovi umalo sukobili zbog časti da podignu sveti Crni kamen (al-Hajar al-Aswad) nazad na svoje mjesto, pristali su da prihvate presudu sljedećeg čovjeka koji je ušao - a to je bio Muhammed ﷺ. Njegovo rješenje bilo je poznato po svojoj mudrosti: položio je kamen na tkaninu i dao poglavicu svakog klana da podigne ugao, a zatim ga svojim rukama postavi na mjesto, tako da su svi dijelili čast i niko nije bio omalovažen.\n\nPouka: pravda i rješavanje sukoba bili su njegov instinkt prije nego što ih je otkrivenje potvrdilo. Vjernik je onaj koji brani povrijeđene i pronalazi načine da se ujedini umjesto da podijeli - Hilf al-Fudul nagovještava pravednu zajednicu koju će uspostaviti nakon hidžre.",
    location: "Mekka",
  },
  {
    title: "Prvo otkrovenje",
    body: 'U svojim kasnim tridesetim, Poslanik, sallallahu alejhi ve sellem, se sve više povlačio da klanja i razmišlja u pećini Hira na planini Džebel an-Nur izvan Mekke. Tamo se oko četrdesete godine u mjesecu ramazanu pojavio melek Džibril i naredio mu: "Čitaj!" Odgovorio je da ne zna čitati; melek ga je čvrsto zagrlio tri puta i otkrio početne ajete sure al-\'Alaq - "Čitaj u ime Gospodara svoga koji je stvorio..." (Kur\'an 96:1-5), prve riječi Kur\'ana.\n\nVratio se kući potresen, a Hatidža ga je zamotala i uvjerila riječima koje otkrivaju njenu vjeru i njegov karakter: Allah ga nikada neće osramotiti, jer je držao rodbinske veze, nosio tuđe terete i pomagao zaslužnima. Odvela ga je svom rođaku Waraqah ibn Nawfalu, starijem čovjeku naučenom u ranijim spisima, koji je prepoznao posjetioca kao istog "Namusa" (anđela) koji je došao Musau i rekao mu da je to obećano poslanstvo. Cijela ova epizoda je zabilježena u Sahih al-Bukhari 3.\n\nPouka: otkrivenje nije započelo tvrdnjom o moći, već riječju "Čitaj" - religijom zasnovanom na znanju i poniznosti. I zapazi ko je prvi poverovao: žena i pošteno domaćinstvo. Istinu prepoznaju oni koji već žive iskreno.',
    location: "Pećina Hira",
  },
  {
    title: "Godine privatnog propovijedanja",
    body: 'Nakon prvih objava uslijedila je pauza (fatra), a zatim je Allah naredio Poslaniku, sallallahu alejhi ve sellem, da počne pozivati ​​ljude na ibadet samo Njemu. Otprilike prve tri godine ovaj poziv je bio tih i ličan - proširen na blisku porodicu i pouzdane prijatelje, a ne na ulicama.\n\nNajraniji vjernici, "as-Sabiqun al-Awwalun" (najvažniji), dolazili su iz svih dijelova društva: Hatidža, njegova žena; njegov mladi rođak Ali ibn Abi Talib; njegov oslobođeni sluga i usvojeni sin Zejd ibn Haritha; i njegov odani prijatelj Ebu Bekr as-Siddiq (neka je Allah zadovoljan sa svima njima). Ebu Bekr je zauzvrat doveo mnoge druge u Islam. Sastajali su se i diskretno molili, često u kući al-Arkama blizu Kabe.\n\nPouka: Islam je prvo rastao kroz povjerenje i odnos, a ne kroz spektakl. Zapazite širinu tih prvih srca - bogata žena, dijete, oslobođeni rob, trgovac - predokus vjere koji bi izbrisao razlike rase i ranga. Da\'wah počinje blizu kuće, sa iskrenošću i strpljenjem.',
    location: "Mekka",
  },
  {
    title: "Javni poziv islamu",
    body: 'Kada je Allah objavio "I upozori svoje najbliže rodbinu" (Kur\'an 26:214), Poslanik, sallallahu alejhi ve sellem, se popeo na brdo Safa pored Ka\'be i pozvao klanove Kurejšija. Prvo je pitao da li bi mu povjerovali da kaže da je iza brda skrivena vojska; odgovorili su da nikada nisu znali da laže. Zatim ih je upozorio na kaznu koja će doći i pozvao ih da obožavaju samo Allaha.\n\nOva otvorena poruka pogodila je srž Mekkine naredbe. Idoli nisu bili samo religija, već i sredstva za život i prestiž - status grada kao čuvara svetinje privlačio je hodočasnike i trgovinu. Reći da su idoli bili nemoćni značilo je istovremeno osporiti ekonomiju, porijeklo i ponos Kurejšija. Odavde se naglo pojačao progon, koji je najteže padao na slabe i porobljene među vjernicima, kao što su Bilal ibn Rabah i porodica Yasir.\n\nPouka: istina izrečena jasno će poremetiti ukorijenjene interese. Poslanik, sallallahu alejhi ve sellem, se prvo pozvao na njihovo vlastito svjedočenje da je bio pošten – razum i poštenje prije prijetnje – a zatim je ostao čvrst. Zalaganje za tevhid može koštati svjetovnu udobnost, kao što su mekanski vjernici naučili. Ova teškoća vodi direktno do "seobe u Abesiniju".',
    location: "Mount Safa",
  },
  {
    title: "Migracija u Abesiniju",
    body: "Kako je progon postajao nepodnošljiv, Poslanik, sallallahu alejhi ve sellem, je rekao grupi svojih drugova da potraže utočište kod Negusa (an-Najashi), pravednog kršćanskog kralja Abesinije (moderna Etiopija), rekavši da u njegovoj zemlji nikome nije učinjena nepravda. Prva grupa je prešla Crveno more, nakon čega je uslijedila veća druga migracija - prva hidžra u islamu.\n\nKada su Kurejšije poslali izaslanike tražeći da se izbjeglice vrate, Negus ih je pozvao. Džafer ibn Ebi Talib ra je govorio za muslimane, opisujući kako su iz neznanja došli u vjeru istine, milosti i dobrog karaktera, a zatim je učio ajete iz sure Merjem o Isusu i njegovoj majci. Kršćanski kralj je plakao, povukao crtu na tlu i rekao da razlika između njihove i njegove vjere nije šira od nje - i odbio ih je predati.\n\nPouka: ovo je orijentir vjerske tolerancije i izgradnje mostova sa iskrenim Ljudima Knjige. Također uči da je traženje sigurnosti od ugnjetavanja pod pravednom nemuslimanskom vlašću potpuno legitimno. Obratite pažnju i na to da je argument koji je pobijedio bio lijep karakter i izgovorena Allahova riječ — a ne sila.",
    location: "Abesinija",
  },
  {
    title: "Bojkot Banu Hašima",
    body: "U nemogućnosti da zaustave širenje islama ili da dođu do Poslanika, sallallahu alejhi ve sellem, dok ga je njegov klan štitio, vođe Kurejšija pribjegle su kolektivnoj kazni. Napisali su pakt i objesili ga u Ka'bu, obećavajući da će bojkotirati cijeli klan Banu Hašima (i njihovih saveznika Banu al-Muttaliba): bez braka s njima, bez trgovine, bez društvenog poslovanja, sve dok ne predaju Muhammeda, as.\n\nOtprilike tri godine klan — kako vjernici tako i nevjernici Hašima — bio je zatvoren u planinskoj dolini Shi'b Abi Talib, trpeći tako jaku glad da su se čuli plači djece i ljudi jeli lišće. Bojkot je konačno propao kada ga je nekoliko poštenih muškaraca iz Kurejšija javno odbacilo i otkriveno je da je pergament pojeden, osim riječi u kojima se pojavilo Allahovo ime.\n\nPouka: laž je prekomjerna. Okrutnost bojkota samo je razotkrila nepravdu progonitelja i očvrsnula odlučnost vjernika. To također pokazuje čast nekolicini pravednih pojedinaca unutar neprijateljskog društva koji su se razbili da bi okončali zločin - podsjetnik da savjest može preživjeti čak i u najžešćoj opoziciji.",
    location: "Shi'b Abi Talib",
  },
  {
    title: "Godina tuge",
    body: "Ubrzo nakon što je bojkot završio, Poslanik, sallallahu alejhi ve sellem, je pretrpio dva razarajuća gubitka u kratkom periodu, a godina je postala poznata kao Am al-Huzn, godina tuge. Prvo je umro njegov ujak i doživotni zaštitnik Abu Talib - čovjek čiji ga je položaj decenijama štitio od Kurejšija. Tada je umrla i Hatidža (neka je Allah zadovoljan njom), njegova žena od dvadeset i pet godina, njegova prva vjernica i najbliža podrška.\n\nPošto su njegova socijalna zaštita i njegovo emocionalno sidro nestali, Kurejšije su postali hrabriji u njihovom zlostavljanju. U tom periodu je otputovao u grad Ta'if nadajući se da će njegovi ljudi prihvatiti poruku; umjesto toga su ga istjerali i natjerali djecu da ga gađaju kamenjem dok mu noge ne prokrvare. Čak i tada, kada mu je ponuđeno uništenje grada, molio je za njihove potomke da jednog dana obožavaju Allaha - milost koja ga definira.\n\nPouka: čak su i proroci testirani tugom i odbacivanjem leđa uz leđa, a odgovor je strpljenje bez gorčine. Ljudski gubitak ne znači božansko napuštanje; olakšanje je uslijedilo izbliza, u noćnom putovanju koje dolazi. Vidi \"Al-Isra wal-Mi'raj.\"",
    location: "Mekka",
  },
  {
    title: "Al-Isra wal-Mi'radž",
    body: "Nakon Godine tuge došla je noć izuzetne časti. U Israu, Poslanik, sallallahu alejhi ve sellem, je prenesen u jednoj noći iz Svete džamije u Mekki u Al-Mesjid al-Aqsa u Jerusalimu - događaj kojim Kur'an otvara suru al-Isra (Kur'an 17:1). Tamo je vodio prethodne proroke u molitvi. Zatim je u Mi'radžu uzdignut kroz sedam nebesa, susrećući poslanike uključujući Adama, Musu i Ibrahima, i dostigao je mjesto bliže svome Gospodaru od bilo kojeg stvorenog bića.\n\nCentralni dar te noći bilo je pet dnevnih namaza. Kao što je zabilježeno u Sahihu al-Bukhari 3887, prvo im je naređeno kao pedeset; po savjetu Musaa, Poslanik, sallallahu alejhi ve sellem, se vraćao iznova i iznova da traži olakšanje sve dok se u praksi nisu smanjili na pet, dok su nosili nagradu od pedeset. Učenjaci se razlikuju oko tačnog datuma, a većina ga smješta u godine neposredno prije hidžre.\n\nPouka: dar koji je dat da utješimo ožalošćenog Poslanika, sallallahu alejhi ve sellem, bio je namaz - naš vlastiti noćni uspon ka Allahu. Pet dnevnih molitvi nije poslao anđeo na zemlju, već su odneti na nebo da bi primili, znak njihove težine u životu vjernika.",
    location: "Jerusalem",
  },
  {
    title: "Prvi zavjet al-Aqabe",
    body: "Svake godine hodočasnici su se okupljali u Mekki, a Poslanik, sallallahu alejhi ve sellem, bi prezentovao Islam posjetiocima plemena. Na mjestu zvanom al-Aqabah u blizini Mine, mala grupa ljudi iz Yathriba (Medina) - grada koji je dugo bio razderan sukobima između njegovih plemena Aws i Khazraj, i koji je bio upoznati s monoteizmom kroz svoju jevrejsku zajednicu - slušala je, vjerovala i prenosila poruku kući.\n\nSljedeće sezone njih dvanaest vratilo se i dalo prvi zavjet al-Aqabe: obožavati samo Allaha, ne krasti, ne činiti nezakonite seksualne odnose, ne ubijati dijete i pokoravati se Poslaniku sallallahu alejhi ve sellem u onome što je ispravno. Zatim je sa njima poslao mladog ashaba Mus'aba ibn Umejra ra sa njima kao prvog učitelja i ambasadora islama, i kroz njega se vjera brzo proširila kroz domaćinstva Jasriba.\n\nPouka: vrata koja su izgledala zatvorena u Mekki otvorila su se u Medini. Obratite pažnju na to kako je zajednica izgrađena — podučavanjem. Jedan odani mladi učitelj, poslan s Kur'anom, pripremio je cijeli grad da postane kolevka islama. Ovo direktno postavlja Drugi zavjet i Hidžru.",
    location: "Mina",
  },
  {
    title: "Drugi zavjet al-Aqabe",
    body: 'Godinu dana nakon prvog obećanja, mnogo veća delegacija iz Yathriba — sedamdeset tri muškarca i dvije žene — došla je tajno Poslaniku, sallallahu alejhi ve sellem, u Al-Aqabu tokom hodočašća. Ovog puta obaveza je otišla dalje: oni su se obavezali da će ga štititi baš kao što će štititi svoje žene i djecu, i da će primiti progonjene muslimane Mekke u svoj grad.\n\nOvo je bila prekretnica. Po prvi put novonastala zajednica imala je domovinu i mnoštvo ljudi zakletih da će je braniti. Shvativši opasnost, Poslanik, sallallahu alejhi ve sellem, je tiho uputio svoje drugove u Mekki da počnu emigrirati u Jasrib u malim grupama kako ne bi uznemirili Kurejšije.\n\nPouka: iskrena posvećenost nosi odgovornost. Ensarije ("Pomagači" iz Medine) su založili svoje živote i domove prije nego što su išta stekli, čisto radi vjere. Njihova velikodušnost će postati model islamskog bratstva - sjeća se u "Hidžri u Medinu" koja slijedi, gdje su emigrante dočekali kao porodicu.',
    location: "Mina",
  },
  {
    title: "Hidžra u Medinu",
    body: "Kada su Kurejšije skovali zavjeru da ubiju Poslanika, sallallahu alejhi ve sellem, Allah mu je dozvolio da emigrira. Krenuo je sa svojim najbližim prijateljem Ebu Bekrom ra, ostavivši Alija u njegovom krevetu da vrati depozite ljudima. Njih dvojica su se skrivali tri noći u pećini Thawr dok su se progonitelji toliko približili da se Ebu Bekr bojao za njih — i Poslanik, sallallahu alejhi ve sellem, ga je uvjerio: \"Šta misliš o dvojici, od kojih je treći Allah?\" Ovaj trenutak je zabilježen u Sahihu al-Bukhari 3653 i odjekivan u Kur'anu: \"...drugi od dvojice, kada su bili u pećini, kada je rekao svom drugu: 'Ne tuguj, Allah je zaista s nama'\" (Kur'an 9:40).\n\nStigli su do Qube, gdje je sagrađena prva džamija, a zatim ušli u Yathrib - nakon toga u al-Medina al-Munawwarah, \"Sjajni grad\". Poslanik, sallallahu alejhi ve sellem, je upario svakog emigranta (Muhajira) sa Pomagačem (Ansari) u bratskim vezama; velikodušnost je bila toliko potpuna da je Sa'd ibn al-Rabi' ponudio da polovicu svog bogatstva podijeli sa Abdur-Rahmanom ibn Awfom, koji je umjesto toga tražio samo da mu se pokaže tržište (Sahih al-Bukhari 3780/3906).\n\nHidžra je bila toliko ključna da ju je Omer kasnije postavio za početak islamskog kalendara – 1. godina po Hidžri. Pouka: ponekad vjera zahtijeva da sve ostavimo za Allahom, da vjerujemo da je On sa iskrenima i da se obnovimo na bratstvu, a ne na krvi.",
    location: "Medina",
  },
  {
    title: "Ustav Medine",
    body: 'Došavši u grad koji je bio uništen plemenskim ratom, Poslanik, sallallahu alejhi ve sellem, nije samo predvodio muslimane – on je osnovao zajednicu. Sastavio je pismeni sporazum, sačuvan u seri Ibn Ishaka i poznat kao sahifa ili ustav Medine, koji je povezivao Muhadžirune, Ensarije i jevrejska plemena grada u jedan sporazum o međusobnoj odbrani.\n\nNjegovi uvjeti bili su izvanredni za svoje vrijeme: strane su formirale "jednu zajednicu (ummet)" za potrebe sporazuma, svaka grupa je zadržala svoju vjeru, sporovi su trebali biti upućeni Poslaniku sallallahu alejhi ve sellem, agresija i nepravda su bili zabranjeni, i svi su se obavezali da će braniti grad od vanjskih napada. To je zapravo učinilo Medinu gradom-državom sa dogovorenim pravima i dužnostima, a ne beskrajnom krvnom osvetom.\n\nPouka: Islam nije samo privatno obožavanje, već pravedno uređenje društva. Poslanik, sallallahu alejhi ve sellem, je modelirao pluralistički suživot, vladavinu dogovorenog zakona nad plemenskom osvetom i poštovanje saveza — principe koji će biti testirani u godinama sukoba koji dolaze. Ona nadopunjuje bratstvo "Hidžra u Medinu" proširujući pravednost na cijeli grad.',
    location: "Medina",
  },
  {
    title: "Bitka kod Badra",
    body: "Do druge godine nakon Hidžre, data je dozvola za borbu u samoodbrani (Kur'an 22:39). Dana 17. Ramazana 2 po Hidžri, muslimanske snage od oko 313 ljudi - slabo naoružanih, sa samo šačicom konja - susrele su se s vojskom Kurejšija od otprilike hiljadu ljudi kod bunara Bedra, jugozapadno od Medine. Bila je to prva velika bitka islama.\n\nUprkos izgledima, muslimani su odlučno pobijedili, a nekoliko arhiprogonitelja Kurejšija je ubijeno. Kur'an predstavlja pobjedu kao znak, a ne samo vojni podvig: \"Allah ti je već dao pobjedu na Bedru dok si bio slab, zato se bojte Allaha da budete zahvalni\" (Kur'an 3:123) i opisuje pomoć meleka (Kur'an 3:124–125). Badr je uspostavio mladu zajednicu kao pravu moć u Arabiji.\n\nPouka: ishodi pripadaju Allahu, a ne brojevima ili opremi. Bedr se pamti kao \"dan kriterija\" (yawm al-furqan), dan kada su se razlikovale istina i laž - dokaz da je iskreno oslanjanje na Allaha uz iskren trud ono što se računa. Preokret na Uhudu sljedeće godine bi naučio komplementarnu lekciju.",
    location: "Badr",
  },
  {
    title: "Bitka na Uhudu",
    body: "Godinu dana nakon Bedra, Kurejšije su se vratile radi osvete sa daleko većom vojskom, a dvije strane su se susrele u podnožju planine Uhud blizu Medine. Poslanik, sallallahu alejhi ve sellem, postavio je pedeset strijelaca na brdo sa strogim naredbama da nikada ne napuštaju svoj položaj, šta god da se dogodilo. Na početku bitke muslimani su imali prednost; ali vidjevši da neprijatelj bježi, većina strijelaca je napustila svoje mjesto da pokupe plijen. Kurejšijska konjica pod Halidom ibn al-Validom (još nije musliman) zahvatila je otkriveni bok, a plima se pretvorila u skup, bolan dan.\n\nMnogi ashabi su ubijeni, među njima i Poslanikov voljeni stric Hamza (neka je Allah zadovoljan njime), \"Allahov lav.\" Sam Poslanik, sallallahu alejhi ve sellem, je ranjen, slomljen mu zub i krvavo lice. Nakon toga, Kur'an se iskreno osvrnuo na neuspjeh, objašnjavajući da je to bio test i posljedica nepoštivanja naredbi i žudnje za svijetom (Kur'an 3:152, 3:165–166).\n\nPouka: Uhud je velika lekcija o disciplini i poslušnosti. Jedan jedini čin nediscipline, koliko god se činio malim, poništio je skoro pobjedu. Ipak, Allah ih nije napustio – On ih je podučavao, opraštao i okupljao ih. Iskreno suočen s porazom može biti poučniji od pobjede.",
    location: "Mount Uhud",
  },
  {
    title: "Bitka u rovu",
    body: 'U petoj godini, savez Kurejšija, drugih arapskih plemena i neprijateljskih frakcija - "Konfederati" (al-Ahzab) - okupio je najveću snagu do sada viđenu u Arabiji, možda deset hiljada, da uništi Medinu jednom zauvijek. Suočen s neprijateljem koji je prevelik da bi se susreo u otvorenoj borbi, Poslanik, sallallahu alejhi ve sellem, je prihvatio savjet perzijskog pratioca Salmana al-Farisija ra da iskopa široki rov preko otvorenih sjevernih prilaza gradu – taktika s kojom se Arapi nikada nisu susreli.\n\nRov je zaustavio opsadu. Uslijedile su sedmice hladnoće, gladi i straha, a Kur\'an slikovito opisuje suđenje vjernicima u suri al-Ahzab: "...kada su se oči pomaknule od straha i srca stizale do grla" (Kur\'an 33:10). Konačno su žestoki vjetar i unutrašnji razdor raspršili vojsku konfederacije, i oni su se povukli bez započete bitke. Kur\'an pripisuje izbavljenje Allahu, koji je "na njih poslao vjetar i vojske koje niste vidjeli" (Kur\'an 33:9).\n\nPouka: mudre konsultacije (shura) i otvorenost za dobre ideje od bilo koga — ovdje, inženjering stranca — dio su vjere. A kada se ljudski trud uloži u potpunosti, izbavljenje još uvijek dolazi od Allaha. Ova prekinuta opsada je efektivno okončala sposobnost Kurejšija da preuzme ofanzivu.',
    location: "Medina",
  },
  {
    title: "Ugovor iz Hudaybiyyah",
    body: "Šeste godine Poslanik, sallallahu alejhi ve sellem, je krenuo sa oko 1.400 drugova da obavlja umru, a ne da se bori, ušavši u stanje ihrama kako bi jasno pokazao miroljubivu namjeru. Kurejšije su ih zabranile na mjestu zvanom Hudaybiyyah, na rubu svetilišta. Nakon napetih pregovora dogovoreno je desetogodišnje primirje pod uslovima koji su za mnoge drugove izgledali ponižavajuće: muslimani će se te godine vratiti i doći sljedeće; svako ko bježi od Kurejšija muslimanima bi bio vraćen, ali ne i obrnuto.\n\nIpak, Allah je na povratku otkrio da je upravo ovaj sporazum \"jasna pobjeda\" (Kur'an 48:1, sura al-Fath). Ashabi su kasnije rekli da nikada nisu vidjeli veću pobjedu — jer su se u miru koji je uslijedio, ljudi slobodno miješali, mirno čuli poruku i ušli u Islam u daleko većem broju nego u svim godinama borbe; Izvještaj Al-Bara' ibn Aziba o tome je zabilježen u Sahihu al-Bukhari 4606. Primirje je također implicitno priznalo muslimane kao jednaku silu.\n\nPouka: ono što izgleda kao nazadovanje može biti najveće otvaranje. Poslanik, sallallahu alejhi ve sellem, je odabrao očigledan kratkoročni gubitak za dugoročno dobro, i poštovao je tešku pogodbu čak i kada je to ubolo. Strpljenje, uzdržanost i držanje riječi mogu postići ono što konfrontacija ne može.",
    location: "Hudaybiyyah",
  },
  {
    title: "Ekspedicija na Khaybar",
    body: "Nedugo nakon Hudejbije, Poslanik, sallallahu alejhi ve sellem, se okrenuo Hajbaru, bogatoj oazi utvrđenih uporišta sjeverno od Medine. Khaybar je postao baza neprijateljstva - dom plemena koja su pomogla u organizaciji opsade Medine od strane Konfederacija i koja su nastavila kovati zavjeru protiv muslimanske zajednice. Kampanja je imala za cilj okončanje te prijetnje.\n\nTvrđave su padale jedna za drugom nakon teških borbi; zastavu odlučujućeg dana dobio je Ali ibn Ebi Talib (neka je Allah zadovoljan njime). Poslije je Poslanik, sallallahu alejhi ve sellem, dozvolio stanovnicima da ostanu i nastave da obrađuju zemlju u zamjenu za dio njenih proizvoda - aranžman koji je osigurao hranu i stabilnost za Medinu umjesto da protjera sve. I ovdje ga je jedna žena pokušala otrovati ovcom, na šta je bio upozoren.\n\nPouka: sigurnost i poštovanje sporazuma išli su ruku pod ruku. Akcija je bila protiv dokazano neprijateljske sile, ali je završila izvodljivim poravnanjem koje je poraženima omogućilo da zadrže sredstva za život. Snaga u islamu ima za cilj uspostavljanje sigurnosti i pravde, a ne uništavanje.",
    location: "Khaybar",
  },
  {
    title: "Osvajanje Mekke",
    body: 'Kada su Kurejšijevi saveznici prekršili uslove Hudejbije napadom na pleme koje je bilo saveznik muslimana, primirje je poništeno. U ramazanu osme godine Poslanik, sallallahu alejhi ve sellem, je marširao na Mekku sa vojskom od deset hiljada — najvećom snagom do sada — i grad koji ga je progonio, bojkotirao i ratovao protiv njega dvadeset godina se predao bez gotovo ikakvog krvoprolića.\n\nStojeći konačno kao pobjednik nad ljudima koji su ga protjerali, pitao je Mekance šta očekuju od njega. Nadali su se milosti plemenitog brata, a on je odgovorio Jusufovim riječima svojoj braći: "Danas nemate krivice" - i rekao: "Idite, jer ste slobodni." Ušao je u Kabu i očistio je od njenih 360 idola, recitirajući "Istina je došla, a laž je nestala" (Kur\'an 17:81), vraćajući Ibrahimovo svetište čistom obožavanju Allaha. Sura an-Nasr (Kur\'an 110) govori o ovom trenutku kada ljudi "u mnoštvu ulaze u Allahovu vjeru."\n\nPouka: ovo je vrhunac proročke milosti i praštanja. Sa apsolutnom moći da se osveti, pomilovao je. Vjernik uči da su jaki oni koji opraštaju kada mogu kazniti, te da cilj nikada nije bila osveta, već vodstvo.',
    location: "Mekka",
  },
  {
    title: "Ekspedicija na Tabuk",
    body: "Devete godine u Medinu su stigli izvještaji o mogućoj vizantijskoj (rimskoj) mobilizaciji na sjevernoj granici. U žestokoj vrućini velikog ljeta, kada je žetva bila zrela i put bio dug i težak, Poslanik, sallallahu alejhi ve sellem, je pozvao najveću vojsku koju je ikada vodio — možda trideset hiljada — da krene na sjever do Tabuka. Ovo je bio \"čas teškoća\" (Kur'an 9:117) i testirao je iskrenost kao ništa prije.\n\nDo bitke nije došlo; pokazivanje odlučnosti je bilo dovoljno, i nekoliko poglavica sa sjevera sklopilo je ugovore s Medinom. Ali kampanja se pamti prije svega po onome što je otkrila o srcima ljudi. Kur'an joj posvećuje veliki dio sure at-Tawbah — hvaleći one koji su dali sve (Ebu Bekr je navodno dao sve svoje bogatstvo), razotkrivajući licemjere koji su izmišljali izgovore da ostanu, i pričajući dirljivu priču o trojici iskrenih vjernika, uključujući Ka'b ibn Malika, koji su iskreno priznali i nisu imali opravdanje nakon što su bili zasluženi. 9:118).\n\nPouka: poslušnost je laka kada je udobna; njegova istina pokazuje kada je skupa. Tabuk je odvojio iskrene od onih koji izgovaraju izgovore i označio efektivni kraj otpora organizovanog idolopoklonstva u Arabiji. Iskrenost — čak i poštenje priznavanja neuspjeha — je put natrag do Allaha.",
    location: "Tabuk",
  },
  {
    title: "Oproštajno hodočašće",
    body: "Desete godine je Poslanik, sallallahu alejhi ve sellem, obavio svoj jedini potpuni hadž, kojem se pridružilo više od sto hiljada ashaba, učeći ih lično obredima. Stojeći na ravnici Arafah, održao je oproštajnu hutbu (Khutbat al-Wada'), sažetak svega što je Islam došao da uspostavi.\n\nOn je proglasio svetost života, imovine i časti svake osobe - \"vaša krv i vaša imovina su sveti kao ovaj dan, ovaj mjesec, ova zemlja\" (Sahih al-Buhari 1741). On je ukinuo krvnu osvetu i kamatu (riba) džahilijjeta, naredio dobar tretman žena kao Allahovo povjerenje, podsjetio ih da nijedan Arap nije superiorniji od nearapa osim u pobožnosti, i rekao im da se čvrsto drže Kur'ana. Tokom ovog hodočašća, na Dan Arefe koji je padao u petak, Allah je objavio: „Ovaj dan sam za vas usavršio vašu vjeru...“ (Kur'an 5:3) - ajet kojeg je Omer podsjetio i datirao (Sahih al-Buhari 45).\n\nPouka: Oproštajna hutba je islamska povelja ljudskog dostojanstva, pravde i jednakosti, zapečaćena najavom da je vjera sada potpuna. Zadatak vjernika odavde nije da tome dodaje, već da to živi.",
    location: "Arafah",
  },
  {
    title: "Njegov odlazak",
    body: 'Nekoliko mjeseci nakon oproštajnog hadža, Poslanik, sallallahu alejhi ve sellem, se razbolio od groznice. U svojim posljednjim danima tražio je od svojih žena dopuštenje da ga njeguju u sobi Aiše (neka je Allah zadovoljan njom), i odredio je Ebu Bekra da predvodi namaz. Posljednjeg jutra povukao je zavjesu da vidi redove vjernika kako se mole i nasmiješio se, radostan svojoj zajednici, a onda je pustio da padne. Preminuo je u ponedjeljak, 12. Rabi al-Awwal 11. po Hidžri, s glavom položenom između Aišenih grudi i brade — kako je ona sama ispričala u Sahihu al-Bukhari 4449/4451.\n\nTuga u Medini je bila ogromna, pa je čak i Omer isprva odbio da to prihvati. Tada je Ebu Bekr ustao, poljubio Poslanikovo lice i obratio se ljudima riječima koje su umirile čitavu zajednicu i koje su zabilježene u Sahih al-Buhari 1241/1242: "Ko god je obožavao Muhameda, onda je Muhammed umro; a ko obožava Allaha, tada je Allah vječni." On je recitirao "Muhammed je samo poslanik; poslanici su prošli prije njega..." (Kur\'an 3:144).\n\nPouka: poruka je bila potpuna i sada pripada ummetu. Poslanik, sallallahu alejhi ve sellem, je bio smrtan, ali ono što je donio - Kur\'an i njegov sunnet - nije. Ebu Bekrov odgovor je trajni odgovor na tugu: naša vezanost je za Allaha, koji nikada ne umire, a način da volimo Poslanika, sallallahu alejhi ve sellem, je da živimo njegovu uputu.',
    location: "Medina",
  },
];
