import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

// Malay translation overlay for the Seerah timeline. Mirrors the order of
// SEERAH_EVENTS in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, years and Hijri
// numbers stay in the English source.

export const SEERAH_EVENTS_MS: DeepPartial<SeerahEvent>[] = [
  {
    title: "Arab sebelum Islam (Zaman Jahiliyah)",
    body: 'Bagi memahami Nabi ﷺ, kita perlu membayangkan terterlebih dulu dunia tempat baginda diutus. Semenanjung Tanah Arab pada abad keenam adalah negeri suku-suku yang tersebar tanpa pentadbiran pusat, disatukan oleh garis keturunan, kehormatan, dan kesucian Kaabah di Mekah — rumah ibadat yang dibangun oleh Ibrahim dan Isma\'il untuk menyembah satu Tuhan, namun kini telah dikelilingi sekitar tiga ratus enam puluh berhala.\n\nMasa ini disebut Jahiliyah, "zaman kebodohan" — bukan kerana orang Arab kurang cerdas (syair dan daya ingat mereka luar biasa), melainkan kerana mereka tidak memiliki petunjuk. Permusuhan antarsuku boleh berlangsung turun-temurun, yang kuat menindas yang lemah, dan anak perempuan terkadang dikubur hidup-hidup kerana rasa malu atau takut miskin — sebuah praktik yang kelak dikecam secara tegas oleh Al-Quran (Al-Quran 81:8–9). Di tengah penyembahan berhala, beberapa "hunafa" masih mencari tauhid murni ajaran Ibrahim, dan komunitas Yahudi serta Nasrani yang kecil tersebar di seluruh jazirah.\n\nPengajarannya: wahyu tidak turun ke ruang hampa, melainkan ke tengah masyarakat nyata yang penuh luka, dan hal pertama yang diperbaikinya adalah hubungan antara manusia dan Penciptanya. Ingatlah latar belakang ini seiring kisah ini bergulir — hampir setiap perbaikan yang dibawa Nabi ﷺ adalah jawaban langsung atas ketidakadilan zaman Jahiliyah.',
    location: "Semenanjung Tanah Arab",
  },
  {
    title: "Kelahiran di Mekah",
    body: 'Nabi ﷺ lahir di Mekah pada Tahun Gajah (Am al-Fil), dinamai demikian kerana pada tahun itu Abrahah, gubernur Habasyah untuk Yaman, memimpin pasukan bergajah untuk menghancurkan Ka\\\'bah namun secara ajaib dipukul mundur — peristiwa yang diabadikan Al-Qur\\\'an dalam Surah al-Fil (Al-Qur\\\'an 105). Pada tahun yang penuh makna ini, lahirlah seorang anak dari suku Quraisy, dari kabilah yang paling terhormat, Bani Hasyim.\\n\\nBaginda telah menjadi yatim sejak lahir: ayahnya, Abdullah, meninggal dunia dunia beberapa bulan sebelumnya ketika sedang berdagang di negeri jauh. Ibunya, Aminah binti Wahb, menamainya Muhammad — "yang banyak dipuji" — sebuah nama yang hampir tidak dikenal di kalangan orang Arab. Sesuai kebiasaan Mekah, baginda dikirim untuk disusui dan dibesarkan di udara terbuka padang pasir bersama Bani Sa\\\'d, dalam asuhan Halimah as-Sa\\\'diyyah.\\n\\nPengajaran bagi seorang mukmin: kemuliaan di sisi Allah tidak ada kaitannya dengan jaminan duniawi. Rasul terakhir memulai hidupnya tanpa ayah dan tak lama kemudian juga tanpa ibu, namun Allah sendiri yang menjadi penjaganya — "Bukankah Dia mendapatimu sebagai yatim, lalu Dia melindungimu?" (Al-Qur\\\'an 93:6). Lihat juga "Meninggal dunia dunianya sang ibu" dan "Perwalian Abu Thalib" berikutnya.',
    location: "Mekah",
  },
  {
    title: "Meninggal dunia dunianya sang ibu",
    body: 'Ketika baginda berusia sekitar enam tahun, Aminah membawa putranya mengunjungi kerabat mereka di Yathrib (yang kelak menjadi Madinah) dan melihat makam ayahnya. Dalam perjalanan pulang, Aminah jatuh sakit dan meninggal dunia dunia di sebuah tempat bernama Abwa\', antara Mekah dan Madinah, dan dimakamkan di sana. Muhammad ﷺ yang masih kecil kini telah kehilangan kedua orang tuanya.\n\nBaginda dibawa kembali ke Mekah oleh Ummu Aiman, pelayan keluarga yang telah dimerdekakan, dan diasuh oleh kakeknya, Abdul Muthalib, pemimpin Quraisy yang disegani, yang sangat mencintainya dan biasa mendudukkannya di sisinya di dekat Kaabah.\n\nPengajarannya: Nabi ﷺ merasakan, sejak dini dan berulang kali, duka yang dipikul begitu banyak manusia — kehilangan orang tercinta, keterlantaran, ketergantungan pada orang lain. Ini adalah bahagian dari persiapan hidupnya. Hati yang pernah mengenal kehilangan adalah hati yang mampu merasakan penderitaan anak yatim, janda, dan orang asing, dan umatnya kelak dibangun di atas rahmat yang sama itu. Kisah ini berlanjut pada "Tahun Kesedihan".',
    location: "Abwa'",
  },
  {
    title: "Perwalian Abu Thalib",
    body: "Dua tahun selepas meninggal dunia dunianya sang ibu, kakeknya, Abdul Muthalib, juga meninggal dunia dunia, ketika baginda berusia sekitar delapan tahun. Menjelang meninggal dunia dunianya, sang kakek mempercayakan cucu tercintanya kepada putranya, Abu Thalib, paman Nabi ﷺ dari pihak ayah. Walaupun Abu Thalib bukan orang kaya, ia menerima anak itu ke dalam rumahnya dan memperlakukannya seperti anak yang paling ia sayangi.\n\nAbu Thalib tetap menjadi pelindungnya selama lebih dari empat puluh tahun, bahkan sepanjang tahun-tahun penganiayaan terberat di Mekah. Dialah yang membawa Muhammad ﷺ muda dalam perjalanan dagang ke Syam, di mana — menurut riwayat yang masyhur — pendeta Bahira melihat tanda-tanda kenabian padanya (sebuah riwayat yang dipertahankan dalam sirah, walaupun rincinya diriwayatkan dengan tingkat kekuatan yang berbeda-beda).\n\nPengajarannya: Allah menempatkan orang-orang yang setia dan terhormat di sekeliling Nabi-Nya ﷺ pada setiap tahapan. Perlindungan Abu Thalib selama puluhan tahun adalah sebuah rahmat — pengingat bahawa membela kebenaran dan menjaga tali kekerabatan adalah kedudukan mulia bahkan bagi mereka yang belum beriman, dan bahawa kita harus menghormati orang-orang yang melindungi kita. Kehilangannya kelak, pada Tahun Kesedihan, akan mengubah segalanya.",
    location: "Mekah",
  },
  {
    title: "Pernikahan dengan Khadijah",
    body: 'Sebagai pemuda, Muhammad ﷺ meraih reputasi di seluruh Mekah yang tidak boleh dibeli dengan harta apa pun: al-Sadiq, yang jujur, dan al-Amin, yang tepercaya. Orang-orang menitipkan barang berharga mereka kepadanya dan sepenuhnya memercayai perkataannya, bahkan mereka yang menyembah tuhan-tuhan lain.\n\nKhadijah binti Khuwailid (semoga Allah meridainya), seorang pedagang Quraisy yang terhormat dan sukses, mempekerjakannya untuk memimpin kafilah dagangnya ke Syam. Terkesan oleh kejujuran dan akhlaknya, ia mengirimkan lamaran pernikahan melalui sahabatnya, Khaulah binti Hakim. Saat itu baginda berusia sekitar dua puluh lima tahun dan Khadijah sekitar empat puluh tahun; pernikahan mereka menjadi pernikahan yang penuh cinta mendalam dan kemitraan sejati. Khadijah melahirkan anak-anak baginda dan tetap menjadi satu-satunya istri baginda selama kurang lebih dua puluh lima tahun, hingga meninggal dunia dunianya.\n\nPengajarannya: akhlak adalah fondasi dari segala yang mengikutinya. Jauh sebelum disebut nabi, Mekah telah mengenalnya sebagai orang paling jujur di antara mereka — itulah sebabnya, pada wahyu pertama, kepercayaan Khadijah yang seketika kepadanya begitu menentukan (lihat "Wahyu pertama"). Kejujuran seorang mukmin dalam urusan sehari-hari itu sendiri adalah bentuk dakwah.',
    location: "Mekah",
  },
  {
    title: "Hilful Fudhul dan Hajar Aswad",
    body: "Dua peristiwa dari kehidupannya sebelum kenabian menunjukkan nilai-nilai yang kelak akan baginda bangun menjadi sebuah bangsa. Pertama, Hilful Fudhul: sebuah perjanjian sakral yang disumpahkan oleh beberapa kabilah Quraisy untuk membela siapa pun yang tertindas di Mekah, baik penduduk asli maupun pendatang, hingga hak mereka dikembalikan. Nabi ﷺ turut serta dan kelak bersabda bahawa baginda akan tetap memenuhi perjanjian semacam itu bahkan dalam Islam — kerana perjanjian itu menegakkan keadilan.\n\nKedua, pembangunan kembali Kaabah selepas banjir. Ketika kabilah-kabilah hampir baku hantam memperebutkan kehormatan mengangkat Hajar Aswad ke tempatnya, mereka sepakat menerima keputusan orang pertama yang memasuki area itu — dan orang itu adalah Muhammad ﷺ. Penyelesaiannya terkenal kerana kebijaksanaannya: baginda meletakkan batu itu di atas selembar kain dan meminta pemimpin setiap kabilah mengangkat satu sudutnya, lalu dengan tangannya sendiri baginda menaruhnya ke tempatnya, sehingga semua ikut serta dalam kehormatan itu dan tak seorang pun merasa direndahkan.\n\nPengajarannya: keadilan dan penyelesaian konflik sudah menjadi naluri baginda bahkan sebelum wahyu menegaskannya. Seorang mukmin adalah orang yang membela yang teraniaya dan mencari cara untuk mempersatukan, bukan memecah belah — Hilful Fudhul adalah bayangan awal dari masyarakat adil yang kelak baginda dirikan selepas Hijrah.",
    location: "Mekah",
  },
  {
    title: "Wahyu pertama",
    body: 'Menjelang akhir usia tiga puluhan, Nabi ﷺ semakin sering mengasingkan diri untuk beribadat dan merenung di Gua Hira di Jabal an-Nur, luar kota Mekah. Di sanalah, pada usia sekitar empat puluh tahun, di bulan Ramadan, malaikat Jibril datang dan memerintahkan: "Bacalah!" Baginda menjawab bahawa baginda tidak boleh membaca; malaikat itu mendekapnya erat sebanyak tiga kali dan menurunkan ayat-ayat pembuka Surah al-\\\'Alaq — "Bacalah dengan nama Tuhanmu yang menciptakan…" (Al-Qur\\\'an 96:1–5), kata-kata pertama Al-Qur\\\'an.\\n\\nBaginda pulang dalam keadaan menggigil, dan Khadijah menyelimutinya serta menenangkannya dengan kata-kata yang menyingkap keimanannya dan akhlak baginda: Allah tidak akan pernah menghinakannya, kerana baginda menyambung tali silaturahmi, menanggung beban orang lain, dan menolong mereka yang berhak dibantu. Khadijah membawanya menemui sepupunya, Waraqah bin Naufal, seorang tua yang mendalami kitab-kitab terdulu, yang mengenali bahawa yang datang itu adalah "Namus" (malaikat) yang sama yang pernah datang kepada Musa, dan memberitahunya bahawa ini adalah kenabian yang telah dijanjikan. Seluruh kisah ini tercatat dalam Shahih al-Bukhari 3.\\n\\nPengajarannya: wahyu dimulai bukan dengan klaim kekuasaan, melainkan dengan kata "Bacalah" — sebuah agama yang dibangun di atas ilmu dan kerendahan hati. Dan perhatikan siapa yang pertama beriman: seorang istri dan sebuah rumah tangga yang jujur. Kebenaran dikenali oleh mereka yang sudah terlebih dulu hidup dengan tulus.',
    location: "Gua Hira",
  },
  {
    title: "Tahun-tahun dakwah secara rahasia",
    body: 'Selepas wahyu-wahyu pertama turun, ada masa jeda (fatrah), lalu Allah memerintahkan Nabi ﷺ untuk mulai mengajak manusia menyembah-Nya semata. Selama kurang lebih tiga tahun pertama, seruan ini bersifat tenang dan pribadi — disampaikan kepada keluarga dekat dan sahabat tepercaya, bukan diserukan di jalanan.\\n\\nOrang-orang yang beriman paling awal, "as-Sabiqun al-Awwalun" (para pendulu), berasal dari seluruh lapisan masyarakat: Khadijah, istrinya; sepupunya yang masih muda, Ali bin Abi Thalib; pelayannya yang telah dimerdekakan dan anak angkatnya, Zaid bin Haritsah; serta sahabatnya yang setia, Abu Bakar ash-Shiddiq (semoga Allah meridai mereka semua). Abu Bakar pada gilirannya membawa banyak orang lain memeluk Islam. Mereka berkumpul dan solat secara diam-diam, sering kali di rumah al-Arqam dekat Ka\\\'bah.\\n\\nPengajarannya: Islam tumbuh pertama kali melalui kepercayaan dan hubungan, bukan melalui pertunjukan. Perhatikan betapa luasnya kalangan hati-hati pertama itu — seorang perempuan kaya, seorang anak kecil, seorang budak yang telah dimerdekakan, seorang pedagang — sebuah gambaran awal dari sebuah keyakinan yang kelak akan menghapus perbedaan ras dan status. Dakwah dimulai dari lingkungan terdekat, dengan ketulusan dan kesabaran.',
    location: "Mekah",
  },
  {
    title: "Seruan Islam secara terang-terangan",
    body: 'Ketika Allah menurunkan ayat "Dan berilah peringatan kepada kerabat-kerabatmu yang terdekat" (Al-Qur\\\'an 26:214), Nabi ﷺ mendaki Bukit Shafa di dekat Ka\\\'bah dan menyerukan kepada kabilah-kabilah Quraisy. Baginda terlebih dulu bertanya apakah mereka akan mempercayainya bila baginda mengatakan ada pasukan bersembunyi di balik bukit; mereka menjawab bahawa mereka tidak pernah mendapatinya berdusta. Kemudian baginda memperingatkan mereka akan azab yang akan datang dan menyeru mereka untuk menyembah Allah semata.\\n\\nPesan terbuka ini mengguncang inti tatanan Mekah. Berhala-berhala itu bukan sekadar agama, tetapi juga mata pencaharian dan kehormatan — status kota sebagai penjaga rumah suci itu menarik jamaah haji dan perdagangan. Mengatakan bahawa berhala-berhala itu tidak berdaya sama sahaja dengan menantang ekonomi, garis keturunan, dan kebanggaan Quraisy sekaligus. Sejak saat itu penganiayaan meningkat tajam, menimpa paling keras kaum lemah dan budak di kalangan orang-orang beriman, seperti Bilal bin Rabah dan keluarga Yasir.\\n\\nPengajarannya: kebenaran yang disampaikan secara terang-terangan akan mengusik kepentingan yang telah mengakar. Nabi ﷺ pertama-tama meminta mereka bersaksi sendiri bahawa baginda jujur — akal sehat dan integritas sebelum ancaman — lalu tetap teguh. Berpegang pada tauhid boleh berharga mahal secara duniawi, seperti yang dipelajari kaum mukmin Mekah. Kesulitan ini langsung membawa kita pada "Hijrah ke Habasyah".',
    location: "Bukit Shafa",
  },
  {
    title: "Hijrah ke Habasyah",
    body: "Ketika penganiayaan menjadi tak tertahankan, Nabi ﷺ memerintahkan sekelompok sahabatnya untuk mencari perlindungan kepada Najasyi, raja Nasrani yang adil di Habasyah (kini Ethiopia), dengan mengatakan bahawa di negerinya tidak ada seorang pun yang dizalimi. Rombongan pertama menyeberangi Laut Merah, diikuti oleh migrasi kedua yang lebih besar — hijrah pertama dalam Islam.\n\nKetika Quraisy mengirim utusan menuntut supaya para pengungsi itu dikembalikan, Najasyi memanggil mereka menghadap. Ja'far bin Abi Thalib (semoga Allah meridainya) berbicara mewakili kaum muslimin, menjelaskan bagaimana mereka keluar dari kebodohan menuju sebuah keyakinan yang penuh kebenaran, rahmat, dan akhlak mulia, lalu membaca ayat-ayat dari Surah Maryam tentang Isa dan ibunya. Raja Nasrani itu menangis, menggoreskan garis di tanah, dan berkata bahawa perbedaan antara keyakinannya dan keyakinan mereka tidak lebih lebar dari garis itu — dan ia menolak menyerahkan mereka.\n\nPengajarannya: ini adalah tonggak toleransi beragama dan membangun jembatan dengan Ahli Kitab yang tulus. Ini juga mengajarkan bahawa mencari keselamatan dari penindasan di bawah kekuasaan non-muslim yang adil sepenuhnya dibolehkan. Perhatikan juga bahawa argumen yang memenangkan keadaan itu adalah akhlak yang indah dan firman Allah yang dibacakan — bukan kekuatan senjata.",
    location: "Habasyah",
  },
  {
    title: "Pemboikotan Bani Hasyim",
    body: "Kerana gagal menghentikan penyebaran Islam atau menjangkau Nabi ﷺ selagi kabilahnya melindunginya, para pemimpin Quraisy melakukan hukuman kolektif. Mereka menulis sebuah perjanjian dan menggantungkannya di Kaabah, bersumpah akan memboikot seluruh kabilah Bani Hasyim (dan sekutu mereka Bani al-Muthalib): tidak ada pernikahan dengan mereka, tidak ada perdagangan, tidak ada pergaulan sosial, sampai mereka menyerahkan Muhammad ﷺ.\n\nSelama kurang lebih tiga tahun, kabilah itu — baik yang beriman maupun yang belum, sesama Bani Hasyim — terkurung di lembah pegunungan Syi'b Abi Thalib, menahan kelaparan yang begitu parah hingga tangisan anak-anak terdengar dan orang-orang memakan dedaunan. Boikot itu akhirnya runtuh ketika beberapa orang Quraisy yang berhati adil secara terbuka menolaknya dan lembaran perjanjian itu ditemukan telah rusak dimakan rayap, kecuali kata-kata yang memuat nama Allah.\n\nPengajarannya: kebatilan selalu melampaui batas. Kekejaman boikot itu justru menyingkap ketidakadilan para penindas dan mengukuhkan tekad kaum mukmin. Ini juga menunjukkan kemuliaan segelintir orang yang adil di tengah masyarakat yang bermusuhan, yang berani keluar dari barisan untuk mengakhiri sebuah kezaliman — pengingat bahawa hati nurani boleh bertahan bahkan di tengah perlawanan yang paling sengit.",
    location: "Syi'b Abi Thalib",
  },
  {
    title: "Tahun Kesedihan",
    body: 'Tak lama selepas boikot berakhir, Nabi ﷺ mengalami dua kehilangan yang menghancurkan dalam waktu singkat, dan tahun itu dikenal sebagai Am al-Huzn, Tahun Kesedihan. Pertama, pamannya sekaligus pelindungnya seumur hidup, Abu Thalib, meninggal dunia dunia — orang yang kedudukannya telah melindunginya dari Quraisy selama puluhan tahun. Kemudian Khadijah (semoga Allah meridainya), istrinya selama kurang lebih dua puluh lima tahun, orang pertama yang beriman kepadanya dan penopang terdekatnya, juga meninggal dunia dunia.\n\nDengan hilangnya perlindungan sosial dan sandaran batinnya sekaligus, Quraisy menjadi semakin berani dalam penganiayaan mereka. Pada masa inilah baginda pergi ke kota Thaif dengan harapan penduduknya mau menerima pesan itu; namun mereka justru mengusirnya dan menyuruh anak-anak melemparinya dengan batu hingga kakinya berdarah. Bahkan saat itu, ketika ditawari kehancuran kota tersebut, baginda justru berdoa supaya keturunan mereka kelak menyembah Allah — sebuah kasih sayang yang menjadi ciri khas baginda.\n\nPengajarannya: bahkan para nabi diuji dengan kesedihan dan penolakan secara beruntun, dan jawabannya adalah kesabaran tanpa kepahitan. Kehilangan yang bersifat manusiawi bukan berarti ditinggalkan oleh Allah; kelegaan datang segera selepasnya, dalam perjalanan malam yang akan menyusul. Lihat "Isra dan Mikraj".',
    location: "Mekah",
  },
  {
    title: "Isra dan Mikraj",
    body: "Selepas Tahun Kesedihan, datanglah sebuah malam kehormatan yang luar biasa. Dalam Isra, Nabi ﷺ diperjalankan dalam satu malam dari Masjidil Haram di Mekah menuju Masjidil Aqsa di Yerusalem — peristiwa yang menjadi pembuka Surah al-Isra dalam Al-Quran (Al-Quran 17:1). Di sana baginda mengimami para nabi terdulu dalam solat. Kemudian, dalam Mikraj, baginda diangkat melewati tujuh lapis langit, bertemu para nabi termasuk Adam, Musa, dan Ibrahim, dan mencapai kedudukan yang lebih dekat dengan Tuhannya daripada makhluk mana pun.\n\nHadiah utama malam itu adalah solat lima waktu. Seperti tercatat dalam Shahih al-Bukhari 3887, solat itu mula-mula diwajibkan sebanyak lima puluh kali; atas saran Musa, Nabi ﷺ berulang kali kembali memohon keringanan hingga jumlahnya dikurangi menjadi lima dalam pelaksanaannya namun tetap membawa pahala lima puluh. Para ulama berbeda penboleh mengenai tanggal pastinya, kebanyakan menempatkannya pada tahun-tahun tepat sebelum Hijrah.\n\nPengajarannya: hadiah yang diberikan untuk menghibur seorang Nabi ﷺ yang sedang berduka adalah solat — perjalanan naik kita sendiri menuju Allah setiap malamnya. Solat lima waktu tidak diturunkan oleh malaikat ke bumi, melainkan diangkat naik ke langit untuk diterima, sebuah tanda betapa besarnya bobotnya dalam kehidupan seorang mukmin.",
    location: "Yerusalem",
  },
  {
    title: "Baiat Aqabah Pertama",
    body: "Setiap tahun para jamaah haji berkumpul di Mekah, dan Nabi ﷺ akan menyampaikan Islam kepada kabilah-kabilah yang berkunjung. Di sebuah tempat bernama al-Aqabah dekat Mina, sekelompok kecil orang dari Yathrib (Madinah) — sebuah kota yang telah lama terpecah oleh permusuhan antara kabilah Aus dan Khazraj, dan telah mengenal tauhid melalui komunitas Yahudinya — mendengarkan, beriman, dan membawa pulang pesan itu.\n\nPada musim berikutnya, dua belas orang dari mereka kembali dan mengucapkan Baiat Aqabah Pertama: untuk menyembah Allah semata, tidak mencuri, tidak berzina, tidak membunuh anak, dan menaati Nabi ﷺ dalam kebaikan. Baginda kemudian mengutus sahabat muda Mush'ab bin Umair (semoga Allah meridainya) untuk kembali bersama mereka sebagai guru dan duta pertama Islam, dan melaluinya, iman menyebar dengan cepat ke rumah-rumah di Yathrib.\n\nPengajarannya: pintu yang tampak tertutup di Mekah terbuka di Madinah. Perhatikan bagaimana komunitas itu dibangun — melalui pendidikan. Seorang guru muda yang berdedikasi, diutus bersama Al-Quran, mempersiapkan seluruh kota untuk menjadi tempat lahirnya Islam. Ini secara langsung membuka jalan bagi Baiat Kedua dan Hijrah.",
    location: "Mina",
  },
  {
    title: "Baiat Aqabah Kedua",
    body: 'Setahun selepas baiat pertama, sebuah delegasi yang jauh lebih besar dari Yathrib — tujuh puluh tiga pria dan dua wanita — datang secara diam-diam menemui Nabi ﷺ di al-Aqabah selama musim haji. Kali ini komitmen mereka melangkah lebih jauh: mereka berjanji akan melindungi baginda persis seperti mereka melindungi istri dan anak-anak mereka sendiri, dan akan menerima kaum muslimin Mekah yang teraniaya ke kota mereka.\n\nIni adalah titik balik yang menentukan. Untuk pertama kalinya, komunitas yang masih muda ini memiliki tanah air dan sekelompok orang yang bersumpah untuk membelanya. Menyadari bahaya yang ada, Nabi ﷺ secara diam-diam mengarahkan para sahabatnya di Mekah untuk mulai berhijrah ke Yathrib dalam kelompok-kelompok kecil supaya tidak menimbulkan kewaspadaan Quraisy.\n\nPengajarannya: komitmen yang tulus membawa tanggung jawab. Kaum Anshar ("Para Penolong" dari Madinah) mempertaruhkan nyawa dan rumah mereka sebelum mereka memperoleh apa pun, semata-mata demi keyakinan mereka. Kemurahan hati mereka kelak menjadi teladan persaudaraan dalam Islam — dikenang dalam "Hijrah ke Madinah" berikutnya, tempat mereka menyambut para muhajirin seolah-olah keluarga sendiri.',
    location: "Mina",
  },
  {
    title: "Hijrah ke Madinah",
    body: 'Ketika Quraisy berkomplot untuk membunuh Nabi ﷺ, Allah mengizinkan baginda untuk berhijrah. Baginda berangkat bersama sahabat terdekatnya, Abu Bakar (semoga Allah meridainya), dengan meninggal duniakan Ali di tempat tidurnya untuk mengembalikan barang-barang titipan orang-orang. Keduanya bersembunyi selama tiga malam di Gua Tsur ketika para pengejar sudah begitu dekat hingga Abu Bakar mengkhawatirkan keselamatan mereka — dan Nabi ﷺ menenangkannya, "Bagaimana pendapatmu tentang dua orang yang ketiganya adalah Allah?" Momen ini tercatat dalam Shahih al-Bukhari 3653 dan bergema dalam Al-Quran: "…yang kedua dari dua orang ketika keduanya berada di dalam gua, ketika dia berkata kepada sahabatnya, \'Jangan bersedih, sesungguhnya Allah bersama kita\'" (Al-Quran 9:40).\n\nMereka tiba di Quba, tempat masjid pertama dibangun, lalu memasuki Yathrib — yang sejak itu disebut al-Madinah al-Munawwarah, "Kota yang Bercahaya". Nabi ﷺ mempersaudarakan setiap muhajir dengan seorang anshar dalam ikatan persaudaraan; kemurahan hati mereka begitu sempurna hingga Sa\'d bin Rabi\' menawarkan untuk membagi separuh hartanya dengan Abdurrahman bin Auf, yang justru hanya meminta ditunjukkan ke pasar (Shahih al-Bukhari 3780/3906).\n\nHijrah begitu penting hingga Umar kelak menjadikannya awal penanggalan Islam — tahun 1 Hijriah. Pengajarannya: terkadang keimanan menuntut kita meninggal duniakan segalanya demi Allah, dengan keyakinan bahawa Dia bersama orang-orang yang tulus, dan membangun kembali di atas persaudaraan, bukan hubungan darah.',
    location: "Madinah",
  },
  {
    title: "Piagam Madinah",
    body: 'Tiba di sebuah kota yang telah hancur oleh perang antarsuku, Nabi ﷺ tidak sekadar memimpin kaum muslimin — baginda mendirikan sebuah komunitas. Baginda menyusun sebuah perjanjian tertulis, yang terpelihara dalam sirah Ibnu Ishaq dan dikenal sebagai Shahifah atau Piagam Madinah, yang mengikat kaum Muhajirin, Anshar, dan kabilah-kabilah Yahudi di kota itu dalam satu perjanjian pertahanan bersama.\n\nKetentuan-ketentuannya luar biasa untuk zamannya: semua pihak membentuk "satu umat" untuk tujuan perjanjian tersebut, setiap kelompok mempertahankan agamanya masing-masing, perselisihan harus diserahkan kepada Nabi ﷺ, permusuhan dan ketidakadilan dilarang, dan semua pihak berjanji membela kota itu dari serangan luar. Perjanjian ini secara efektif menjadikan Madinah sebuah negara-kota dengan hak dan kewajiban yang disepakati bersama, bukan permusuhan darah yang tiada akhir.\n\nPengajarannya: Islam bukan hanya ibadat pribadi, tetapi juga penataan masyarakat yang adil. Nabi ﷺ mencontohkan hidup berdampingan secara majemuk, supremasi hukum yang disepakati bersama di atas dendam antarsuku, dan menepati perjanjian — prinsip-prinsip yang akan diuji pada tahun-tahun konflik yang akan datang. Ini melengkapi persaudaraan dalam "Hijrah ke Madinah" dengan memperluas keadilan ke seluruh kota.',
    location: "Madinah",
  },
  {
    title: "Perang Badar",
    body: 'Pada tahun kedua selepas Hijrah, izin untuk berperang membela diri telah diturunkan (Al-Quran 22:39). Pada 17 Ramadan tahun 2 Hijriah, sebuah pasukan muslim berjumlah sekitar 313 orang — dengan persenjataan yang minim dan hanya beberapa ekor kuda — bertemu dengan pasukan Quraisy yang berjumlah sekitar seribu orang di sumur-sumur Badar, barat daya Madinah. Ini adalah pertempuran besar pertama dalam Islam.\n\nDi luar dugaan, kaum muslimin menang telak, dan beberapa tokoh utama penindas dari Quraisy tewas. Al-Quran menggambarkan kemenangan ini bukan sekadar sebagai capaian militer, melainkan sebagai sebuah tanda: "Dan sungguh, Allah telah menolongmu di Badar, padahal kamu dalam keadaan lemah. Maka bertakwalah kepada Allah supaya kamu bersyukur" (Al-Quran 3:123), dan menyebutkan bantuan para malaikat (Al-Quran 3:124–125). Badar menegakkan komunitas yang masih muda itu sebagai kekuatan nyata di jazirah Arab.\n\nPengajarannya: hasil akhir berada di tangan Allah, bukan pada jumlah pasukan atau perlengkapan. Badar dikenang sebagai "hari pembeda" (yaum al-furqan), hari ketika kebenaran dan kebatilan dipisahkan dengan jelas — bukti bahawa tawakal yang tulus kepada Allah disertai usaha yang sungguh-sungguh itulah yang sesungguhnya menentukan. Kekalahan di Uhud setahun kemudian akan mengajarkan pengajaran yang saling melengkapi.',
    location: "Badar",
  },
  {
    title: "Perang Uhud",
    body: 'Setahun selepas Badar, Quraisy kembali untuk membalas dendam dengan pasukan yang jauh lebih besar, dan kedua pihak bertemu di kaki Gunung Uhud dekat Madinah. Nabi ﷺ menempatkan lima puluh pemanah di sebuah bukit dengan perintah tegas supaya tidak pernah meninggal duniakan posisi mereka, apa pun yang terjadi. Di awal pertempuran, kaum muslimin memegang keunggulan; namun melihat musuh melarikan diri, sebahagian besar pemanah meninggal duniakan posnya untuk mengumpulkan harta rampasan. Pasukan berkuda Quraisy di bawah pimpinan Khalid bin Walid (yang saat itu belum memeluk Islam) berputar melalui sisi yang terbuka itu, dan keadaan berbalik menjadi hari yang berat dan menyakitkan.\n\nBanyak sahabat gugur sebagai syuhada, di antaranya paman tercinta Nabi ﷺ, Hamzah (semoga Allah meridainya), "Singa Allah". Nabi ﷺ sendiri terluka, giginya patah dan wajahnya berdarah. Selepas itu, Al-Quran membahas kemunduran ini secara terus terang, menjelaskan bahawa itu adalah sebuah ujian dan akibat dari ketidaktaatan terhadap perintah serta ketamakan terhadap dunia (Al-Quran 3:152, 3:165–166).\n\nPengajarannya: Uhud adalah pengajaran besar tentang disiplin dan ketaatan. Satu tindakan kelalaian disiplin, sekecil apa pun tampaknya, boleh membalikkan kemenangan yang hampir diraih. Namun Allah tidak meninggal duniakan mereka — Dia mengajarkan, mengampuni, dan menyatukan kembali mereka. Kekalahan yang dihadapi dengan jujur boleh lebih banyak mengajarkan daripada kemenangan.',
    location: "Gunung Uhud",
  },
  {
    title: "Perang Khandaq",
    body: 'Pada tahun kelima, sebuah aliansi Quraisy, suku-suku Arab lainnya, dan kelompok-kelompok yang bermusuhan — "Al-Ahzab" (kaum sekutu) — menghimpun pasukan terbesar yang pernah dilihat di jazirah Arab, mungkin sepuluh ribu orang, untuk menghancurkan Madinah selamanya. Menghadapi musuh yang terlalu besar untuk dilawan dalam pertempuran terbuka, Nabi ﷺ menerima saran sahabat Persia, Salman al-Farisi (semoga Allah meridainya), untuk menggali parit lebar di sepanjang jalur utara kota yang terbuka — sebuah taktik yang belum pernah dijumpai orang Arab sebelumnya.\\n\\nParit itu menghentikan pengepungan. Berminggu-minggu dingin, kelaparan, dan ketakutan menyusul, dan Al-Qur\\\'an menggambarkan dengan begitu hidup ujian kaum mukmin dalam Surah al-Ahzab: "…ketika pandangan mata terbelalak kerana takut dan hati naik menyesak sampai ke tenggorokan" (Al-Qur\\\'an 33:10). Akhirnya angin kencang dan perpecahan internal mencerai-beraikan pasukan sekutu itu, dan mereka mundur tanpa terjadi pertempuran besar. Al-Qur\\\'an menyandarkan keselamatan itu kepada Allah, yang "mengirimkan kepada mereka angin dan bala tentara yang tidak boleh kamu lihat" (Al-Qur\\\'an 33:9).\\n\\nPengajarannya: musyawarah yang bijak (syura) dan keterbukaan terhadap gagasan baik dari siapa pun — di sini, dari keahlian teknik seorang asing — adalah bahagian dari keimanan. Dan ketika usaha manusia telah dicurahkan sepenuhnya, pertolongan tetap datang dari Allah. Pengepungan yang gagal ini secara efektif mengakhiri kemampuan Quraisy untuk melancarkan serangan.',
    location: "Madinah",
  },
  {
    title: "Perjanjian Hudaibiyah",
    body: 'Pada tahun keenam, Nabi ﷺ berangkat bersama sekitar 1.400 sahabat untuk melaksanakan umrah, bukan untuk berperang, dengan mengenakan ihram supaya niat damai itu jelas terlihat. Quraisy menghadang mereka di sebuah tempat bernama Hudaibiyah, di tepi tanah suci. Selepas perundingan yang tegang, disepakati gencatan senjata selama sepuluh tahun dengan syarat-syarat yang, bagi banyak sahabat, tampak merendahkan: kaum muslimin akan kembali pulang tahun itu dan datang lagi tahun berikutnya; siapa pun yang lari dari Quraisy menuju kaum muslimin akan dikembalikan, tetapi tidak berlaku sebaliknya.\n\nNamun Allah menurunkan wahyu dalam perjalanan pulang bahawa perjanjian inilah yang merupakan "kemenangan yang nyata" (Al-Quran 48:1, Surah al-Fath). Para sahabat kelak berkata bahawa mereka tidak pernah melihat kemenangan yang lebih besar — kerana dalam kedamaian yang menyusul, orang-orang bercampur bebas, mendengarkan pesan itu dengan tenang, dan memeluk Islam dalam jumlah yang jauh lebih besar dibanding sepanjang tahun-tahun peperangan; riwayat al-Bara\' bin Azib tentang hal ini tercatat dalam Shahih al-Bukhari 4606. Gencatan senjata itu juga secara tersirat mengakui kaum muslimin sebagai kekuatan yang setara.\n\nPengajarannya: apa yang tampak seperti kemunduran boleh menjadi peluang terbesar. Nabi ﷺ memilih kerugian jangka pendek yang tampak nyata demi kebaikan jangka panjang, dan menepati kesepakatan yang berat itu bahkan ketika terasa menyakitkan. Kesabaran, pengendalian diri, dan menepati janji boleh mencapai apa yang tidak boleh dicapai oleh konfrontasi.',
    location: "Hudaibiyah",
  },
  {
    title: "Surat-surat kepada pemerintah",
    body: "Selepas gencatan senjata Hudaibiyah memberi umat Islam kelegaan daripada peperangan, Nabi ﷺ mengalihkan perhatian ke luar Semenanjung Arab. Sekitar tahun 6-7 H, baginda menghantar sahabat yang dipercayai sebagai utusan, masing-masing membawa surat yang dimeteraikan dengan cincin baginda, menjemput pemerintah besar zaman itu memeluk Islam: Heraklius, Maharaja Byzantine; Khosrow II, Maharaja Parsi; al-Muqawqis, gabenor Byzantine di Mesir; Raja Najasyi Habsyah yang telah melindungi para muhajirin; serta pemerintah Bahrain dan Oman.\n\nSurat kepada Heraklius terpelihara hampir kata demi kata dalam hadis: 'Aku menjemputmu kepada Islam. Terimalah Islam, nescaya kamu akan selamat... Terimalah Islam, nescaya Allah akan memberimu pahala berganda' (Sahih al-Bukhari 7). Riwayat ini juga merekodkan perbualan panjang apabila Heraklius menyoal peniaga Mekah, Abu Sufyan — yang ketika itu masih kafir — tentang keturunan dan akhlak Nabi ﷺ, lalu menyimpulkan daripada jawapan jujur itu bahawa sifat-sifat tersebut sepadan dengan seorang nabi yang benar, walaupun baginda sendiri tidak menuruti keyakinan itu. Khosrow pula dikenang dalam sirah kerana mengoyak surat itu dengan marah, sementara Najasyi menyambut utusan baginda dengan penuh kehormatan.\n\nPengajaran: misi Rasul terakhir tidak pernah terhad kepada Semenanjung Arab — sebaik sahaja Madinah selamat, dakwah tersebar ke seluruh dunia yang dikenali ketika itu, sepertimana Al-Quran menggambarkan baginda diutuskan 'untuk seluruh manusia' (Al-Quran 34:28). Sebahagian pemerintah mendengar dengan jujur, sebahagian membalas dengan hormat, dan sebahagian lagi dengan sombong — dan setiap tindak balas itu menjadi petanda bagaimana kerajaan mereka akan berdepan dengan Islam kemudiannya.",
    location: "Madinah",
  },
  {
    title: "Ekspedisi ke Khaibar",
    body: "Tidak lama selepas Hudaibiyah, Nabi ﷺ mengarahkan perhatian ke Khaibar, sebuah oasis kaya dengan benteng-benteng pertahanan di utara Madinah. Khaibar telah menjadi basis permusuhan — tempat tinggal kabilah-kabilah yang membantu mengorganisasi pengepungan Madinah oleh kaum sekutu dan terus berkomplot melawan komunitas muslim. Ekspedisi ini bertujuan mengakhiri ancaman tersebut.\n\nBenteng-benteng itu jatuh satu demi satu selepas pertempuran sengit; panji kemenangan pada hari yang menentukan diberikan kepada Ali bin Abi Thalib (semoga Allah meridainya). Selepas itu, Nabi ﷺ mengizinkan penduduknya tetap tinggal dan melanjutkan bercocok tanam di tanah itu dengan imbalan sebahagian hasil panennya — sebuah kesepakatan yang menjamin pangan dan kestabilan bagi Madinah, alih-alih mengusir semua orang. Di sinilah pula seorang wanita mencoba meracuninya lewat daging kambing, namun baginda diberi tahu sebelumnya.\n\nPengajarannya: keamanan dan menepati perjanjian berjalan beriringan. Tindakan ini ditujukan terhadap sebuah kekuatan yang terbukti bermusuhan, namun berakhir dengan penyelesaian yang boleh diterima, yang membiarkan pihak yang kalah tetap mempertahankan mata pencaharian mereka. Kekuatan dalam Islam dimaksudkan untuk menegakkan keamanan dan keadilan, bukan untuk memusnahkan.",
    location: "Khaibar",
  },
  {
    title: "Umrah gantian (Umrat al-Qada)",
    body: "Perjanjian Hudaibiyah telah menghalang umat Islam daripada Umrah pada tahun 6 H, dengan jaminan bahawa mereka boleh kembali pada tahun berikutnya. Pada bulan Zulkaedah tahun 7 H, tepat seperti yang dipersetujui, Nabi ﷺ memimpin kira-kira dua ribu sahabat kembali ke Mekah untuk menunaikan ibadah yang sebelum ini dihalang — dikenali sebagai Umrat al-Qada, Umrah 'gantian' (disebut juga Umrat al-Qisas dalam sesetengah sumber).\n\nMenepati bahagian perjanjian mereka, Quraisy mengosongkan kota selama tiga hari agar umat Islam dapat menunaikan ibadah dengan aman, sambil memerhati dari bukit-bukit sekeliling bagaimana masyarakat yang pernah mereka halau itu kini bertawaf mengelilingi Kaabah dengan penuh keselamatan. Semasa lawatan inilah bapa saudara Nabi ﷺ, al-Abbas, menguruskan perkahwinan baginda dengan Maimunah binti al-Harith, dan beberapa penduduk Mekah yang menyaksikan kesungguhan dan disiplin para jemaah turut tersentuh hati.\n\nPengajaran: menepati janji itu sendiri adalah satu bentuk dakwah. Ketika dua puluh tahun dakwah dan peperangan tidak berjaya melembutkan hati, satu Umrah yang aman dan bermartabat — hasil langsung daripada 'kemenangan yang nyata' di Hudaibiyah (Al-Quran 48:1) — melembutkan hati yang tidak dapat disentuh oleh kekuatan. Lawatan tenang ini turut membuka jalan kepada penyerahan Mekah yang hampir tanpa pertumpahan darah setahun kemudian.",
    location: "Mekah",
  },
  {
    title: "Pembebasan Mekah",
    body: 'Ketika sekutu-sekutu Quraisy melanggar syarat Perjanjian Hudaibiyah dengan menyerang sebuah kabilah yang bersekutu dengan kaum muslimin, gencatan senjata pun batal. Pada bulan Ramadan tahun kedelapan, Nabi ﷺ berangkat menuju Mekah dengan pasukan sepuluh ribu orang — yang terbesar yang pernah ada — dan kota yang telah menganiaya, memboikot, dan memeranginya selama dua puluh tahun itu menyerah hampir tanpa pertumpahan darah.\\n\\nBerdiri akhirnya sebagai pemenang di hadapan orang-orang yang telah mengusirnya, baginda bertanya kepada penduduk Mekah apa yang mereka harapkan darinya. Mereka berharap akan belas kasih seorang saudara yang mulia, dan baginda menjawab dengan kata-kata yang pernah diucapkan Yusuf kepada saudara-saudaranya: "Tidak ada cercaan atasmu hari ini" — dan menyatakan, "Pergilah, kamu bebas." Baginda memasuki Ka\\\'bah dan membersihkannya dari 360 berhala, sambil membaca "Yang benar telah datang dan yang batil telah lenyap" (Al-Qur\\\'an 17:81), mengembalikan rumah suci Ibrahim itu kepada penyembahan murni kepada Allah. Surah an-Nashr (Al-Qur\\\'an 110) berbicara tentang momen ini, ketika orang-orang "masuk ke dalam agama Allah secara berbondong-bondong".\\n\\nPengajarannya: ini adalah puncak dari kasih sayang dan pengampunan kenabian. Dengan kekuasaan penuh untuk membalas dendam, baginda justru mengampuni. Seorang mukmin belajar bahawa orang yang kuat adalah mereka yang mengampuni ketika mampu menghukum, dan bahawa tujuannya tidak pernah berupa balas dendam, melainkan hidayah.',
    location: "Mekah",
  },
  {
    title: "Perang Hunain",
    body: "Hanya beberapa minggu selepas pembebasan Mekah secara aman, suku-suku bergabung Hawazin dan Thaqif — yang cemas melihat kekuatan umat Islam yang tiba-tiba meningkat dan berazam bertempur habis-habisan — mengumpulkan pasukan besar, membawa keluarga, ternakan, dan harta mereka, lalu berdepan dengan pasukan Nabi ﷺ yang jauh lebih besar di lembah Hunain yang sempit, antara Mekah dan Taif.\n\nHawazin telah menyembunyikan pemanah di lorong-lorong bukit, dan apabila mereka melepaskan tembakan mengejut ketika subuh, barisan hadapan tentera Islam berpecah dan bersepah; buat seketika ia seolah-olah tentera terbesar yang pernah dikumpulkan umat Islam akan tewas hanya kerana kejutan itu. Al-Quran menggambarkan pembalikan ini dengan tepat: '...dan (ingatlah) hari peperangan Hunain, ketika kamu berasa megah dengan bilangan kamu yang ramai, maka bilangan yang ramai itu tidak mendatangkan faedah kepada kamu sedikit pun, dan bumi yang luas itu turut terasa sempit bagi kamu, kemudian kamu berpaling melarikan diri' (Al-Quran 9:25). Nabi ﷺ sendiri tetap tenang dan menyuruh bapa saudaranya, al-Abbas, memanggil nama-nama kaum Ansar dan suku Madinah; seruan itu membuat para sahabat kembali, menyusun semula saf, dan pertempuran bertukar menjadi kemenangan yang menentukan, yang oleh Al-Quran dikaitkan dengan ketenangan dan bantuan ghaib yang diturunkan Allah (Al-Quran 9:26).\n\nPengajaran: bilangan dan kelengkapan tidak menentukan hasil sesuatu peperangan — Badar telah mengajarkan itu dengan pasukan kecil, dan Hunain mengajarkan sebaliknya, bahawa pasukan besar sekalipun boleh tergugat tanpa bantuan Allah dan disiplin di medan perang. Selepas itu, harta rampasan yang banyak diagihkan dengan penuh kemurahan, termasuk kepada penduduk Mekah yang baru memeluk Islam, demi memenangi hati bukan menimbun harta.",
    location: "Hunain",
  },
  {
    title: "Ekspedisi ke Tabuk",
    body: 'Pada tahun kesembilan, kabar sampai ke Madinah tentang kemungkinan mobilisasi pasukan Bizantium (Romawi) di perbatasan utara. Di tengah teriknya musim panas, ketika hasil panen sedang matang dan perjalanan jauh serta berat, Nabi ﷺ menyerukan pasukan terbesar yang pernah baginda pimpin — mungkin tiga puluh ribu orang — untuk berbaris ke utara menuju Tabuk. Ini adalah "saat kesulitan" (Al-Quran 9:117), dan ia menguji ketulusan seperti belum pernah terjadi sebelumnya.\n\nTidak terjadi pertempuran; unjuk keteguhan itu sudah cukup, dan beberapa pemimpin di utara membuat perjanjian dengan Madinah. Namun ekspedisi ini dikenang terutamanya kerana apa yang diungkapkannya tentang isi hati manusia. Al-Quran mencurahkan sebahagian besar Surah at-Taubah untuk peristiwa ini — memuji mereka yang memberikan segalanya (Abu Bakar konon menyerahkan seluruh hartanya), menyingkap kaum munafik yang mengarang-ngarang alasan untuk tidak ikut serta, dan menceritakan kisah yang menyentuh tentang tiga mukmin yang jujur, termasuk Ka\'b bin Malik, yang dengan jujur mengakui bahawa mereka tidak punya alasan dan akhirnya diampuni selepas ujian yang berat (Al-Quran 9:118).\n\nPengajarannya: ketaatan itu mudah ketika nyaman; kebenarannya teruji ketika harus mengorbankan sesuatu. Tabuk memisahkan yang tulus dari yang mencari-cari alasan dan menandai berakhirnya secara efektif perlawanan penyembahan berhala yang terorganisasi di jazirah Arab. Kejujuran — bahkan kejujuran mengakui kesalahan diri sendiri — adalah jalan kembali kepada Allah.',
    location: "Tabuk",
  },
  {
    title: "Tahun Perutusan (Am al-Wufud)",
    body: "Pada tahun kesembilan selepas Hijrah, susulan penyerahan Mekah dan tunjuk kekuatan di Tabuk, suku-suku Arab menyedari bahawa menentang susunan baharu itu sudah tidak lagi realistik. Perutusan demi perutusan — dari Bani Tamim, Bani Amir, suku-suku Yaman, dan ramai lagi — tiba di Madinah untuk mengisytiharkan keislaman dan kesetiaan mereka kepada Nabi ﷺ, sehingga tahun itu dikenali dalam sirah sebagai Am al-Wufud, Tahun Perutusan.\n\nNabi ﷺ menyambut setiap rombongan dengan keramahan dan pengajaran yang sabar, menghantar sahabat bersama mereka untuk mengajar kaum mereka Al-Quran dan solat, bukan menghantar pemerintah untuk mentadbir dengan kekuatan. Al-Quran menyentuh secara langsung detik ini dalam Surah an-Nasr: 'Apabila telah datang pertolongan Allah dan kemenangan, dan engkau melihat manusia masuk ke dalam agama Allah dengan berpuak-puak, maka bertasbihlah dengan memuji Tuhanmu dan mintalah ampun kepada-Nya' (Al-Quran 110:1-3) — sebuah surah yang difahami oleh para sahabat, sepertimana dijelaskan oleh Ibn Abbas kepada Umar, sebagai tanda bahawa hayat Nabi ﷺ semakin hampir ke penghujungnya (Sahih al-Bukhari 4430).\n\nPengajaran: selepas berdekad-dekad mesej itu ditolak oleh ramai dan diterima oleh segelintir, janji Allah tiba serentak — satu pengajaran tentang kesabaran, dan tentang cara memaknai kejayaan dengan tepat. Tindak balas Surah an-Nasr terhadap kemenangan bukanlah perayaan, sebaliknya pujian dan istighfar, satu teladan bagaimana seorang mukmin harus menyambut sebarang kejayaan dalam hidupnya. Ini membuka jalan kepada Haji Wada' yang menyusul kemudian.",
    location: "Madinah",
  },
  {
    title: "Haji Wada'",
    body: 'Pada tahun kesepuluh, Nabi ﷺ melaksanakan satu-satunya haji lengkap dalam hidupnya, didampingi lebih dari seratus ribu sahabat, mengajarkan tata cara ibadat haji itu secara langsung kepada mereka. Berdiri di padang Arafah, baginda menyampaikan Khutbah Wada\', sebuah ringkasan dari segala hal yang datang untuk ditegakkan oleh Islam.\n\nBaginda menyatakan kesucian jiwa, harta, dan kehormatan setiap orang — "darah dan hartamu sesuci hari ini, bulan ini, dan negeri ini" (Shahih al-Bukhari 1741). Baginda menghapuskan dendam darah dan riba peninggalan Jahiliyah, mewajibkan perlakuan baik terhadap para perempuan sebagai amanah dari Allah, mengingatkan bahawa tidak ada keunggulan orang Arab atas non-Arab kecuali dalam ketakwaan, dan memerintahkan mereka untuk berpegang teguh pada Al-Quran. Pada haji inilah, di hari Arafah yang jatuh pada hari Jumat, Allah menurunkan ayat "Pada hari ini telah Aku sempurnakan untukmu agamamu…" (Al-Quran 5:3) — sebuah ayat yang diingat dan ditentukan waktunya secara tepat oleh Umar (Shahih al-Bukhari 45).\n\nPengajarannya: Khutbah Wada\' adalah piagam Islam tentang martabat manusia, keadilan, dan kesetaraan, disegel dengan pengumuman bahawa agama ini kini telah sempurna. Tugas seorang mukmin sejak saat itu bukanlah menambahkannya, melainkan menjalankannya.',
    location: "Arafah",
  },
  {
    title: "Meninggal dunia dunianya Nabi ﷺ",
    body: 'Beberapa bulan selepas Haji Wada\', Nabi ﷺ jatuh sakit demam. Pada hari-hari terakhirnya, baginda meminta izin kepada para istrinya untuk dirawat di kamar Aisyah (semoga Allah meridainya), dan baginda menunjuk Abu Bakar untuk mengimami solat. Pada pagi terakhirnya, baginda menyingkap tirai untuk melihat barisan kaum mukmin yang sedang solat dan tersenyum, gembira melihat umatnya, lalu membiarkan tirai itu tertutup kembali. Baginda meninggal dunia dunia pada hari Senin, 12 Rabiul Awal tahun 11 Hijriah, dengan kepalanya bersandar di antara dada dan dagu Aisyah — seperti ia sendiri riwayatkan dalam Shahih al-Bukhari 4449/4451.\n\nKesedihan di Madinah tak terlukiskan, dan bahkan Umar pada mulanya menolak menerima kenyataan itu. Kemudian Abu Bakar bangkit berdiri, mencium wajah Nabi ﷺ, dan berbicara kepada orang-orang dengan kata-kata yang menenangkan seluruh komunitas dan tercatat dalam Shahih al-Bukhari 1241/1242: "Siapa yang dulu menyembah Muhammad, maka sesungguhnya Muhammad telah meninggal dunia dunia; tetapi siapa yang menyembah Allah, maka sesungguhnya Allah Maha Hidup dan tidak akan pernah mati." Ia lalu membaca ayat "Muhammad hanyalah seorang rasul; sungguh telah berlalu sebelumnya beberapa rasul…" (Al-Quran 3:144).\n\nPengajarannya: pesan itu telah sempurna dan kini menjadi milik umat. Nabi ﷺ adalah manusia biasa yang fana, namun apa yang baginda bawa — Al-Quran dan Sunnahnya — tidak akan pernah fana. Jawaban Abu Bakar adalah obat abadi bagi kesedihan: keterikatan kita adalah kepada Allah, yang tidak pernah mati, dan jalan untuk mencintai Nabi ﷺ adalah dengan menjalankan petunjuknya.',
    location: "Madinah",
  },
];
