// Albanian translation overlay for the Seerah timeline. Mirrors the order of
// its English source in ../seerah.ts (index-aligned); untranslated entries fall back
// to English. Only human-readable text is translated — ids, routes, surah/ayah
// numbers, collections, citations and grades stay in the English source.
import type { SeerahEvent } from "../../types/seerah";
import type { DeepPartial } from "./localize";

export const SEERAH_EVENTS_SQ: DeepPartial<SeerahEvent>[] = [
  {
    title: "Arabia para Islamit (Xhahilijet)",
    body: 'Për të kuptuar Profetin ﷺ, së pari duhet të përfytyroni botën në të cilën ai u dërgua. Arabia e shekullit të gjashtë ishte një vend fisesh të shpërndara pa shtet qendror, të lidhur së bashku me prejardhjen, nderin dhe shenjtëroren e Qabes në Mekë - një faltore e ndërtuar nga Ibrahimi dhe Ismaili për adhurimin e Zotit të vetëm, por tashmë e rrethuar nga rreth treqind e gjashtëdhjetë idhuj.\n\nKjo epokë quhet Xhahilijet, "epoka e injorancës" - jo sepse arabëve u mungonte inteligjenca (poezia dhe kujtesa e tyre ishin të jashtëzakonshme), por sepse u mungonte udhëzimi. Grindjet fisnore mund të zgjasin me breza, të fortët prenë të dobëtit dhe vajzat nganjëherë varroseshin të gjalla nga turpi ose frika e varfërisë – një praktikë që Kurani më vonë do ta dënonte drejtpërdrejt (Kur\'ani 81:8–9). Krahas idhujtarisë, disa "hunafa" ende kërkonin monoteizmin e pastër të Ibrahimit, dhe komunitete të vogla çifute dhe të krishtera jetonin në të gjithë gadishullin.\n\nMësimi: Shpallja nuk zbriti në vakum, por në një shoqëri reale me plagë të thella dhe gjëja e parë që shëroi ishte marrëdhënia midis qenies njerëzore dhe Krijuesit të tij. Mbajeni në mend këtë sfond kur shpaloset afati kohor - pothuajse çdo reformë e Profetit ﷺ është një përgjigje e drejtpërdrejtë ndaj një padrejtësie të xhahilijetit.',
    location: "Arabia",
  },
  {
    title: "Lindja në Mekke",
    body: 'Profeti ﷺ lindi në Mekë në Vitin e Elefantit (Am al-Fil), i quajtur kështu sepse atë vit Abraha, guvernatori abisinian i Jemenit, marshoi me një ushtri me elefantët për të shkatërruar Qaben dhe u kthye mrekullisht mbrapa - një ngjarje që Kurani e kujton në suren el-Fil (Kur\'an 110). Në këtë vit të ngarkuar lindi një fëmijë nga fisi Kurejsh dhe nga fisi i tij më i nderuar, Benu Hashim.\n\nAi ishte tashmë jetim në lindje: babai i tij Abdullah kishte vdekur muaj më parë ndërsa ishte larguar nga tregtia. Nëna e tij, Aminah bint Vehb, e quajti Muhamed - "i shumëlavdëruari" - një emër pothuajse i panjohur në mesin e arabëve. Në përputhje me zakonet mekase, ai u dërgua për t\'u ushqyer dhe rritur në ajrin e shkretëtirës në mesin e Benu Sa\'d, nën kujdesin e Halimeh es-Sa\'dijeh.\n\nMësimi për një besimtar: madhështia në sytë e Allahut nuk ka të bëjë fare me sigurinë e kësaj bote. I Dërguari i fundit filloi jetën pa baba dhe së shpejti do të mbetej pa nënë, megjithatë Vetë Allahu ishte kujdestari i tij - "A nuk të gjeti jetim dhe të strehoi?" (Kur\'an 93:6). Shih gjithashtu "Vdekja e nënës së tij" dhe "Ruajtja e Ebu Talibit" që vijojnë.',
    location: "Meka",
  },
  {
    title: "Vdekja e nënës së tij",
    body: 'Kur ishte rreth gjashtë vjeç, Aminah e mori djalin e saj për të vizituar të afërmit e tij në Jethrib (më vonë në Medine) dhe për të parë varrin e babait të tij. Në udhëtimin e kthimit ajo u sëmur dhe vdiq në vendin e quajtur Abwa\', midis Mekës dhe Medinës, dhe u varros atje. I riu Muhamedi ﷺ tani kishte humbur të dy prindërit.\n\nAi u kthye në Mekë nga Umm Ajman, shërbëtori i liruar i familjes, dhe u vendos nën kujdesin e gjyshit të tij Abd al-Muttalib, prijësit të respektuar të Kurejshëve, i cili e donte shumë dhe e ulte pranë vetes në Qabe.\n\nMësimi: Profeti a.s e shijoi herët dhe në mënyrë të përsëritur pikëllimin që bartin kaq shumë qenie njerëzore - humbjen, zhvendosjen, varësinë nga të tjerët. Kjo ishte pjesë e përgatitjes së tij. Një zemër që ka njohur humbje është një zemër që mund të ndjejë për jetimin, të venë dhe të huajin, dhe komuniteti i tij më vonë do të ndërtohet pikërisht mbi atë mëshirë. Kjo fillesë vazhdon në "Viti i pikëllimit".',
    location: "Abwa'",
  },
  {
    title: "Kujdestaria e Ebu Talibit",
    body: "Dy vjet pas nënës së tij, i vdiq edhe gjyshi Abd al-Muttalib, kur djali ishte rreth tetë vjeç. Në shtratin e vdekjes, ai ia besoi nipin e tij të dashur djalit të tij Ebu Talibit, xhaxhait të Profetit a.s. Megjithëse Ebu Talibi nuk ishte i pasur, ai e mori fëmijën në shtëpinë e tij dhe e trajtoi atë si një nga fëmijët e tij më të dashur.\n\nEbu Talibi do të mbetej mbrojtësi i tij për më shumë se dyzet vjet, pikërisht gjatë viteve më të vështira të persekutimit në Mekë. Ishte ai që e çoi të riun Muhamed ﷺ në udhëtime tregtare për në Siri, ku - sipas tregimit të mirënjohur - murgu Bahira vuri re tek ai shenja të profetësisë (një raport që ruan seerah, megjithëse detajet e tij transmetohen me fuqi të ndryshme).\n\nMësimi: Allahu vendosi rreth Profetit të Tij njerëz besnikë dhe të nderuar në çdo fazë. Dekadat e mbrojtjes së Ebu Talibit ishin një mëshirë - një kujtesë se mbështetja e së vërtetës dhe farefisnisë është një pozitë fisnike edhe për ata që nuk kanë besuar ende, dhe se ne duhet të nderojmë ata që na strehojnë. Humbja e tij më vonë, në vitin e pikëllimit, do të ndryshonte gjithçka.",
    location: "Meka",
  },
  {
    title: "Martesa me Hatixhen",
    body: 'Kur ishte i ri, Muhamedi salAllahu alejhi ue selem fitoi një reputacion në të gjithë Mekën që asnjë pasuri nuk mund ta blinte: el-Sadiku, i sinqerti dhe el-Amini, i besueshëm. Njerëzit i depozitonin gjërat e tyre me vlerë për t\'u ruajtur dhe i besuan absolutisht fjalës së tij, madje edhe ata që adhuronin perëndi të ndryshme.\n\nHatixhe bint Khuvejlid (Allahu qoftë i kënaqur me të), një tregtar fisnik dhe i suksesshëm i Kurejshëve, e punësoi atë për të udhëhequr karvanin e saj në Siri. E impresionuar nga ndershmëria dhe karakteri i tij, ajo i dërgoi një propozim për martesë përmes mikut të saj Khawlah bint Hakim. Ai ishte rreth njëzet e pesë vjeç dhe ajo rreth dyzet; e tyre u bë një martesë e dashurisë dhe partneritetit të thellë. Ajo i lindi fëmijët e tij dhe mbeti gruaja e tij e vetme për rreth njëzet e pesë vjet, deri në vdekjen e saj.\n\nMësimi: karakteri është themeli i gjithçkaje që pasoi. Shumë kohë përpara se të quhej profet, Meka e njihte tashmë atë si njeriun më të ndershëm mes tyre – prandaj, në zbulimin e parë, besimi i menjëhershëm i Hatixhes tek ai ishte kaq vendimtar (shih "Zbulesa e parë"). Integriteti i një besimtari në marrëdhëniet e zakonshme është në vetvete një formë e davetit.',
    location: "Meka",
  },
  {
    title: "Hilf al-Fudul dhe Guri i Zi",
    body: "Dy incidente nga jeta e tij paraprofetike tregojnë vlerat mbi të cilat ai do të ndërtonte më vonë një komb. Së pari, Hilf el-Fudul: një pakt solemn i betuar nga disa klane të Kurejshëve për të qëndruar me çdo person të shtypur në Mekë, vendas apo të huaj, derisa të rikthehen të drejtat e tyre. Profeti ﷺ mori pjesë dhe më vonë tha se do t'i përgjigjej akoma një pakti të tillë edhe në Islami - sepse ai mbronte drejtësinë.\n\nSë dyti, rindërtimi i Qabes pas një përmbytjeje. Kur klanet gati u përplasën për nderin e ngritjes së Gurit të Zi të shenjtë (al-Hajar al-Aswad) në vend, ata ranë dakord të pranonin gjykimin e njeriut të ardhshëm që do të hynte - dhe ai ishte Muhamedi ﷺ. Zgjidhja e tij ishte e famshme për urtësinë e saj: ai e vendosi gurin në një leckë dhe kërkoi nga një kryetar i çdo klani të ngrinte një cep, pastaj ta vendoste në vend me duart e veta, në mënyrë që të gjithë të ndanin nderin dhe askush të mos nënvlerësohej.\n\nMësimi: drejtësia dhe zgjidhja e konflikteve ishin instinkti i tij përpara se shpallja t'i konfirmonte ato. Besimtar është ai që mbron të padrejtët dhe gjen mënyra për t'u bashkuar në vend që të përçajë - Hilf el-Fudul parashikon bashkësinë e drejtë që ai do të themelonte pas hixhretit.",
    location: "Meka",
  },
  {
    title: "Shpallja e parë",
    body: 'Në fund të të tridhjetave, Profeti (ﷺ) tërhiqej gjithnjë e më shumë për të adhuruar dhe reflektuar në shpellën Hira në malin Xhebel en-Nur jashtë Mekës. Aty, rreth moshës dyzetvjeçare gjatë muajit të Ramazanit, u shfaq meleku Xhibril dhe e urdhëroi: "Lexo!" Ai u përgjigj se nuk dinte të lexonte; engjëlli e përqafoi fort tri herë dhe i shpalli vargjet hyrëse të sures Al-\'Alak - "Lexo në emër të Zotit tënd që krijoi..." (Kur\'an 96:1–5), fjalët e para të Kur\'anit.\n\nAi u kthye në shtëpi duke u dridhur, dhe Hatixheja e mbështolli dhe e qetësoi me fjalë që zbulojnë besimin e saj dhe karakterin e tij: Allahu nuk do ta turpëronte kurrë, sepse ai mbante lidhjet farefisnore, mbante barrët e të tjerëve dhe i ndihmonte të merituarit. Ajo e çoi te kushëriri i saj Ueraka ibn Naufal, një burrë i moshuar i mësuar në shkrimet e mëparshme, i cili e njohu vizitorin si i njëjti "Namus" (engjëll) që kishte ardhur te Musai dhe i tha atij se kjo ishte profetësia e premtuar. I gjithë ky episod është regjistruar në Sahih el-Buhari 3.\n\nMësimi: zbulesa filloi jo me pretendimin për pushtet, por me fjalën "Lexo" - një fe e themeluar mbi dijen dhe përulësinë. Dhe vini re se kush besoi i pari: një grua dhe një familje e ndershme. E vërteta njihet nga ata që tashmë jetojnë sinqerisht.',
    location: "Shpella e Hirës",
  },
  {
    title: "Vite predikimi privat",
    body: 'Pas shpalljeve të para, pasoi një pauzë (fatrah), pastaj Allahu e urdhëroi Profetin ﷺ që të fillonte t\'i thërriste njerëzit në adhurimin vetëm ndaj Tij. Përafërsisht për tre vitet e para, kjo thirrje ishte e qetë dhe personale - e shtrirë në familjen e ngushtë dhe miqtë e besuar në vend që të shpallej në rrugë.\n\nBesimtarët më të hershëm, "es-Sabiqun al-Awwalun" (i pari), vinin nga çdo pjesë e shoqërisë: Hatixheja gruaja e tij; kushëriri i tij i ri Ali ibn Ebi Talib; shërbëtori i tij i liruar dhe djali i adoptuar Zejd ibn Harithah; dhe mikun e tij besnik Ebu Bekr es-Siddik (Allahu qoftë i kënaqur me të gjithë). Ebu Bekri nga ana e tij solli shumë të tjerë në Islami. Ata takoheshin dhe faleshin me maturi, shpesh në shtëpinë e el-Arkamit afër Qabes.\n\nMësimi: Islami u rrit së pari përmes besimit dhe marrëdhënies, jo spektaklit. Vini re gjerësinë e atyre zemrave të para - një grua e pasur, një fëmijë, një skllav i liruar, një tregtar - një shije paraprake e një besimi që do të fshinte dallimet e racës dhe gradës. Daveti fillon afër shtëpisë, me sinqeritet dhe durim.',
    location: "Meka",
  },
  {
    title: "Thirrja publike në Islami",
    body: 'Kur Allahu shpalli "Dhe paralajmëro farefisin tënd më të afërt" (Kur\'an 26:214), Profeti ﷺ u ngjit në malin Safa pranë Qabes dhe thirri fiset e Kurejshëve. Ai fillimisht e pyeti nëse do ta besonin nëse ai thoshte se një ushtri ishte fshehur prapa kodrës; ata u përgjigjën se nuk e kishin njohur kurrë për të gënjyer. Pastaj i paralajmëroi për një dënim që do të vinte dhe i thirri në adhurim vetëm ndaj Allahut.\n\nKy mesazh i hapur goditi në zemër të urdhrit të Mekës. Idhujt nuk ishin vetëm feja, por edhe jetesa dhe prestigji - statusi i qytetit si kujdestar i faltores tërhoqi pelegrinët dhe tregtinë. Të thuash se idhujt ishin të pafuqishëm do të ishte të sfidoje ekonominë, prejardhjen dhe krenarinë e Kurejshëve menjëherë. Prej këtu përndjekja u intensifikua ashpër, duke rënë më së shumti mbi të dobëtit dhe të robëruarit në mesin e besimtarëve, si Bilal ibn Rabah dhe familja e Jasirit.\n\nMësimi: e vërteta e thënë qartë do të prishë interesat e rrënjosura. Profeti ﷺ iu drejtua fillimisht dëshmisë së tyre se ai ishte i ndershëm - arsyeja dhe integriteti para kërcënimit - dhe më pas u mbajt i patundur. Qëndrimi për teuhid mund të kushtojë rehati të kësaj bote, siç mësuan besimtarët mekas. Kjo vështirësi çon drejtpërsëdrejti në "Migrimin në Abisini".',
    location: "Mali Safa",
  },
  {
    title: "Migrimi në Abisini",
    body: "Ndërsa persekutimi u bë i padurueshëm, Profeti (a.s.) i tha një grupi shokësh të tij që të kërkonin strehim tek Negus (an-Najashi), mbreti i drejtë i krishterë i Abisinisë (Etiopia moderne), duke thënë se në vendin e tij askush nuk i është bërë padrejtësi. Një grup i parë kaloi Detin e Kuq, i ndjekur nga një migrim i dytë më i madh - hixhreti i parë në Islami.\n\nKur Kurejshët dërguan të dërguar që kërkonin kthimin e refugjatëve, Negus i thirri ata. Xhafer ibn Ebi Talibi (Allahu qoftë i kënaqur me të) foli për muslimanët, duke përshkruar se si ata kishin ardhur nga injoranca në besimin e së vërtetës, mëshirës dhe karakterit të mirë, dhe më pas recitoi vargje nga sureja Merjem për Jezusin dhe nënën e tij. Mbreti i krishterë qau, tërhoqi një vijë në tokë dhe tha se ndryshimi midis besimit të tyre dhe besimit të tij nuk ishte më i gjerë se ai - dhe ai refuzoi t'i dorëzonte ata.\n\nMësimi: kjo është një pikë referimi e tolerancës fetare dhe e ndërtimit të urave me ithtarët e sinqertë të Librit. Ai gjithashtu mëson se kërkimi i sigurisë nga shtypja nën një autoritet të drejtë jomusliman është plotësisht legjitime. Vini re gjithashtu se argumenti që fitoi ditën ishte karakteri i bukur dhe fjala e lexuar e Allahut - jo forca.",
    location: "Abisini",
  },
  {
    title: "Bojkoti i Benu Hashimit",
    body: "Në pamundësi për të ndalur përhapjen e Islamit ose për të arritur Profetin sal-lAllahu alejhi ue sel-lem, ndërkohë që klani i tij e mbronte atë, udhëheqësit e Kurejshëve iu drejtuan ndëshkimit kolektiv. Ata shkruan një pakt dhe e varën në Qabe, duke u zotuar se do të bojkotojnë të gjithë fisin e Benu Hashim (dhe aleatët e tyre Benu al-Muttalib): pa martesë me ta, pa tregti, pa marrëdhënie shoqërore, derisa ata të dorëzojnë Muhamedin a.s.\n\nPër afërsisht tre vjet, klani - besimtarë dhe jobesimtarë të Hashimit - ishte i kufizuar në luginën malore të Shi'b Ebi Talib, duke duruar urinë aq të fortë sa u dëgjuan klithmat e fëmijëve dhe njerëzit hanin gjethe. Bojkoti përfundimisht u rrëzua kur disa burra kurejshi me mendje të drejtë e hodhën poshtë atë publikisht dhe u zbulua se pergamena ishte ngrënë, përveç fjalëve në të cilat u shfaq emri i Allahut.\n\nMësimi: shtrirja e gënjeshtrës. Mizoria e bojkotit vetëm sa ekspozoi padrejtësinë e persekutorëve dhe ngurtësoi vendosmërinë e besimtarëve. Ai gjithashtu tregon nderin e disa individëve të drejtë brenda një shoqërie armiqësore që thyen radhët për t'i dhënë fund një mizorie - një kujtesë se ndërgjegjja mund të mbijetojë edhe në kundërshtimin më të ashpër.",
    location: "Shi'b Ebi Talib",
  },
  {
    title: "Viti i pikëllimit",
    body: "Menjëherë pas përfundimit të bojkotit, Profeti ﷺ pësoi dy humbje shkatërruese brenda një periudhe të shkurtër dhe viti u bë i njohur si Am el-Huzn, Viti i hidhërimit. Së pari vdiq xhaxhai i tij dhe mbrojtësi i përjetshëm Abu Talibi - njeriu qëndrimi i të cilit e kishte mbrojtur atë nga Kurejshët për dekada. Pastaj ndërroi jetë edhe Hatixheja (Allahu qoftë i kënaqur me të), gruaja e tij prej rreth njëzet e pesë vjetësh, besimtarja e parë dhe mbështetja e tij më e afërt.\n\nMe mbrojtjen e tij sociale dhe spirancën emocionale të zhdukur, kurejshët u bënë më të guximshëm në abuzimin e tyre. Pikërisht në këtë periudhë ai udhëtoi për në qytetin e Taifit duke shpresuar se njerëzit e tij mund ta pranonin mesazhin; në vend të kësaj e dëbuan dhe i vunë fëmijët që ta godasin me gurë derisa t'i gjakosen nga këmbët. Edhe atëherë, kur iu ofrua shkatërrimi i qytetit, ai u lut që pasardhësit e tyre të adhuronin një ditë Allahun - një mëshirë që e përcakton atë.\n\nMësimi: edhe pejgamberët sprovohen me pikëllim dhe refuzim, dhe përgjigja është durimi pa hidhërim. Humbja njerëzore nuk do të thotë braktisje hyjnore; lehtësimi ndoqi nga afër, në udhëtimin e natës që vjen më pas. Shih \"El-Isra uel-Mi'raj\".",
    location: "Meka",
  },
  {
    title: "El-Isra uel-Mi'raj",
    body: "Pas Vitit të Trishtimit erdhi një natë nderi e jashtëzakonshme. Në Isra, Profeti ﷺ u transportua brenda një nate të vetme nga Xhamia e Shenjtë në Mekë në el-Masjid al-Aksa në Jerusalem - një ngjarje me të cilën Kurani hap suren el-Isra (Kur'an 17:1). Atje ai udhëhoqi profetët e mëparshëm në lutje. Pastaj, në Mi'raxh, ai u ngrit në shtatë qiej, duke takuar profetët duke përfshirë Ademin, Musain dhe Ibrahimin, dhe arriti në një pozicion më afër Zotit të tij se çdo qenie e krijuar.\n\nDhurata qendrore e asaj nate ishin pesë namazet ditore. Siç është shënuar në Sahih el-Buhari 3887, ata fillimisht u urdhëruan si pesëdhjetë; me këshillën e Musait, Profeti (a.s.) kthehej vazhdimisht për të kërkuar lehtësim derisa ata u reduktuan në pesë në praktikë, ndërsa mbanin shpërblimin prej pesëdhjetë. Dijetarët ndryshojnë për datën e saktë, shumica e vendosin atë në vitet pak para hixhretit.\n\nMësimi: dhurata e dhënë për të ngushëlluar një Profet të pikëlluar ishte namazi – ngjitja jonë e natës tek Allahu. Pesë namazet ditore nuk u zbritën nga një engjëll në tokë, por u ngritën në qiej për t'i marrë, një shenjë e peshës së tyre në jetën e një besimtari.",
    location: "Jeruzalemin",
  },
  {
    title: "Betimi i parë i el-Akabes",
    body: "Çdo vit pelegrinët mblidheshin në Mekë dhe Profeti ﷺ ua prezantonte Islamin fiseve vizitore. Në një vend të quajtur al-Akabah afër Minës, një grup i vogël burrash nga Jethrib (Medina) - një qytet i grisur prej kohësh nga grindjet midis fiseve të tij Aws dhe Khazraj, dhe i njohur me monoteizmin përmes komunitetit të tij hebre - dëgjuan, besuan dhe e çuan mesazhin në shtëpi.\n\nSezoni pasues, dymbëdhjetë prej tyre u kthyen dhe dhanë zotimin e parë të el-Akabes: të adhurojnë vetëm Allahun, të mos vjedhin, të mos kryejnë marrëdhënie seksuale të paligjshme, të mos vrasin asnjë fëmijë dhe t'i binden Profetit ﷺ në atë që është e drejtë. Më pas ai e ktheu me ta shokun e ri Mus'ab ibn Umejr (Allahu qoftë i kënaqur me të) si mësuesi dhe ambasadori i parë i Islamit, dhe nëpërmjet tij besimi u përhap me shpejtësi nëpër familjet e Jethribit.\n\nMësimi: dera që dukej e mbyllur në Mekë u hap në Medine. Vini re se si u ndërtua komuniteti - duke mësuar. Një mësues i ri i përkushtuar, i dërguar me Kur'an, përgatiti një qytet të tërë për t'u bërë djepi i Islamit. Kjo vendos drejtpërdrejt Betimin e Dytë dhe Hixhretin.",
    location: "Mina",
  },
  {
    title: "Betimi i dytë i el-Akabes",
    body: 'Një vit pas zotimit të parë, një delegacion shumë më i madh nga Jethribi - shtatëdhjetë e tre burra dhe dy gra - erdhi fshehurazi te Profeti a.s në el-Akabe gjatë haxhit. Këtë herë angazhimi shkoi më tej: ata u zotuan se do ta mbronin atë pikërisht ashtu siç do t\'i mbronin gratë dhe fëmijët e tyre dhe do t\'i prisnin muslimanët e persekutuar të Mekës në qytetin e tyre.\n\nKjo ishte një pikë kthese. Për herë të parë komuniteti i ri kishte një atdhe dhe një trup njerëzish të betuar për ta mbrojtur atë. Duke e kuptuar rrezikun, Profeti a.s i udhëzoi në heshtje shokët e tij në Mekë që të fillonin emigrimin në Jethrib në grupe të vogla për të mos alarmuar kurejshët.\n\nMësimi: angazhimi i sinqertë mbart përgjegjësi. Ensarët ("Ndihmuesit" e Medinës) i dhanë peng jetën dhe shtëpitë e tyre para se të kishin fituar ndonjë gjë, thjesht për hir të besimit. Bujaria e tyre do të bëhej modeli i vëllazërisë islame – kujtohet në "Hixhra në Medine" që vijon, ku ata i pritën mërgimtarët si familje.',
    location: "Mina",
  },
  {
    title: "Hixhreti deri në Medine",
    body: 'Kur Kurejshët komplotuan për të vrarë Profetin ﷺ, Allahu e lejoi atë të emigronte. U nis me shokun e tij më të ngushtë Ebu Bekrin (Allahu qoftë i kënaqur me të), duke e lënë Aliun në shtratin e tij për t\'ua kthyer depozitat njerëzve. Të dy u fshehën për tre netë në shpellën e Thevrit, ndërsa ndjekësit u afruan aq shumë sa Ebu Bekri u frikësua për ta - dhe Profeti (a.s.) e qetësoi: "Çfarë mendon për dy, prej të cilëve i treti është Allahu?" Ky moment është regjistruar në Sahih el-Buhari 3653 dhe ka jehonë në Kuran: "...i dyti nga dy, kur ishin në shpellë, kur ai i tha shokut të tij: "Mos u pikëlloni, me të vërtetë Allahu është me ne" (Kur\'an 9:40).\n\nAta arritën në Quba, ku u ndërtua xhamia e parë, më pas hynë në Jethrib - më pas në Medine el-Munavwarah, "Qyteti Shkëlqyes". Pejgamberi salAllahu alejhi ue selem e bashkoi çdo mërgimtar (Muhaxhir) me një Ndihmës (Ensari) në lidhje vëllazërimi; bujaria ishte aq e plotë sa Sa\'d ibn el-Rabi\'u ofroi të ndante gjysmën e pasurisë së tij me Abdur-Rahman ibn Awf, i cili në vend të kësaj kërkoi që t\'i tregonte vetëm tregu (Sahih el-Bukhari 3780/3906).\n\nHixhreti ishte aq i rëndësishëm sa që Omeri më vonë e bëri atë fillimin e kalendarit Islami - viti 1 hixhri. Mësimi: ndonjëherë besimi kërkon lënien e çdo gjëje për Allahun, besimin se Ai është me të sinqertët dhe rindërtimin mbi vëllazërinë dhe jo gjakun.',
    location: "Medine",
  },
  {
    title: "Kushtetuta e Medines",
    body: 'Me të mbërritur në një qytet që ishte shkatërruar nga lufta fisnore, Profeti a.s nuk i udhëhoqi thjesht muslimanët - ai themeloi një komunitet. Ai hartoi një marrëveshje të shkruar, e ruajtur në serahun e Ibn Is\'hakut dhe e njohur si Sahifa ose Kushtetuta e Medinës, duke i lidhur së bashku fiset muhaxhirune, ensarët dhe çifutët e qytetit në një kompakt të vetëm të mbrojtjes reciproke.\n\nKushtet e tij ishin të jashtëzakonshme për kohën e tyre: palët formuan "një komunitet (ummet)" për qëllimet e traktatit, secili grup mbajti fenë e tij, mosmarrëveshjet duhej t\'i referoheshin Profetit ﷺ, agresioni dhe padrejtësia ishin të ndaluara dhe të gjitha u zotuan se do ta mbronin qytetin nga sulmet e jashtme. Ajo në fakt e bëri Medinën një qytet-shtet me të drejta dhe detyra të dakorduara dhe jo gjakmarrje të pafundme.\n\nMësimi: Islami nuk është vetëm adhurim privat, por urdhërimi i drejtë i një shoqërie. Profeti ﷺ modeloi bashkëjetesën pluraliste, sundimin e ligjit të rënë dakord mbi hakmarrjen fisnore dhe respektimin e besëlidhjeve – parime që do të testoheshin në vitet e konfliktit në vijim. Ai plotëson vëllazërinë e "Hixhrës në Medine" duke shtrirë drejtësinë në të gjithë qytetin.',
    location: "Medine",
  },
  {
    title: "Beteja e Bedrit",
    body: "Në vitin e dytë pas Hixhrës, leja për të luftuar në vetëmbrojtje ishte dhënë (Kur'an 22:39). Më 17 Ramazan 2 Hixhri, një forcë muslimane prej rreth 313 burrash – të armatosur dobët, me vetëm një grusht kuajsh – u ndesh me një ushtri kurejshësh rreth një mijë të fortë në puset e Bedrit, në jugperëndim të Medinës. Ishte beteja e parë e madhe e Islamit.\n\nPërkundër mundësive, muslimanët fituan me vendosmëri dhe disa nga kryepersekutorët e Kurejshëve u vranë. Kur'ani e përshkruan fitoren si një shenjë, jo thjesht një vepër ushtarake: \"Allahu tashmë ju kishte dhënë fitoren në Bedr ndërsa ishit të dobët, prandaj kini frikë Allahun që të jeni mirënjohës\" (Kur'an 3:123) dhe përshkruan ndihmën e engjëjve (Kur'an 3:124–125). Badr themeloi komunitetin e të rinjve si një fuqi të vërtetë në Arabi.\n\nMësimi: rezultatet i përkasin Allahut, jo numrave apo pajisjeve. Bedri mbahet mend si \"dita e kriterit\" (yawm al-furkan), dita kur u dallua e vërteta dhe e pavërteta - një dëshmi se mbështetja e sinqertë në Allahun me përpjekje të sinqerta është ajo që ka rëndësi. Përmbysja në Uhud vitin e ardhshëm do të jepte mësimin plotësues.",
    location: "Bedr",
  },
  {
    title: "Beteja e Uhudit",
    body: "Një vit pas Bedrit, kurejshët u kthyen për hakmarrje me një ushtri shumë më të madhe dhe të dy palët u takuan në rrëzë të malit Uhud afër Medinës. Profeti ﷺ vendosi pesëdhjetë harkëtarë në një kodër me urdhër të rreptë që të mos largoheshin kurrë nga pozicioni i tyre, çfarëdo që të ndodhte. Në fillim të betejës, muslimanët kishin përparësinë; por duke parë armikun të ikë, shumica e harkëtarëve u larguan nga posti i tyre për të mbledhur plaçkën. Kalorësia e Kurejshëve nën drejtimin e Khalid ibn al-Validit (ende jo musliman) përfshiu krahun e zbuluar dhe batica u kthye në një ditë të kushtueshme dhe të dhimbshme.\n\nShumë sahabë ranë shehid, ndër ta edhe xhaxhai i dashur i Profetit, Hamza (Allahu qoftë i kënaqur prej tij), “Luani i Allahut”. Vetë Pejgamberi ﷺ u plagos, dhëmbi i tij u thye dhe fytyra e gjakosur. Më pas, Kur'ani e trajtoi haptazi pengesën, duke shpjeguar se ishte një provë dhe pasojë e mosbindjes ndaj urdhrit dhe lakmisë ndaj botës (Kur'an 3:152, 3:165–166).\n\nMësimi: Uhudi është mësimi i madh në disiplinë dhe bindje. Një akt i vetëm mosdisipline, sado i vogël të dukej, zhbë një fitore gati. Megjithatë Allahu nuk i braktisi ata - Ai i mësoi, i fali dhe i tuboi ata. Humbja, e përballur me ndershmëri, mund të jetë më mësimdhënëse se fitorja.",
    location: "mali Uhud",
  },
  {
    title: "Beteja e Hendekut",
    body: 'Në vitin e pestë, një aleancë e kurejshëve, fiseve të tjera arabe dhe fraksioneve armiqësore - "Konfederatat" (al-Ahzab) - mblodhën forcën më të madhe të parë në Arabi, ndoshta dhjetë mijë të fortë, për të shkatërruar Medinën një herë e përgjithmonë. Duke u përballur me një armik shumë të madh për t\'u përballur në betejë të hapur, Profeti a.s pranoi këshillën e shokut persian Salman al-Farisi (Allahu qoftë i kënaqur me të) për të gërmuar një llogore të gjerë nëpër afrimet e ekspozuara veriore të qytetit - një taktikë që arabët nuk e kishin hasur kurrë.\n\nHendeku e ndali rrethimin. Pasuan javë të ftohta, urie dhe frike, dhe Kur\'ani përshkruan gjallërisht sprovën e besimtarëve në suren el-Ahzab: "...kur sytë u zhvendosën nga frika dhe zemrat arritën në fyt" (Kur\'an 33:10). Më në fund një erë e fortë dhe mosmarrëveshje e brendshme shpërndanë ushtrinë konfederative dhe ata u tërhoqën pa një betejë të ashpër. Kur\'ani ia atribuon shpëtimin Allahut, i cili "dërgoi mbi ta një erë dhe ushtri që nuk i shihnit" (Kur\'an 33:9).\n\nMësimi: konsultimi i mençur (shura) dhe hapja ndaj ideve të mira nga kushdo - këtu, inxhinieria e një të huaji - janë pjesë e besimit. Dhe kur përpjekja njerëzore është dhënë plotësisht, çlirimi ende vjen nga Allahu. Ky rrethim i thyer i dha fund aftësisë së Kurejshit për të ndërmarrë ofensivën.',
    location: "Medine",
  },
  {
    title: "Marrëveshja e Hudejbijes",
    body: "Në vitin e gjashtë, Profeti (sal-lAllahu alejhi ue sel-lem) u nis me rreth 1400 shokë për të kryer umren, jo për të luftuar, duke hyrë në gjendjen e ihramit për të bërë të qartë qëllimin paqësor. Kurejshët i ndaluan në një vend të quajtur Hudejbije, në buzë të shenjtërores. Pas negociatave të tensionuara u ra dakord për një armëpushim dhjetëvjeçar me kushte që për shumë shokë dukeshin poshtërues: muslimanët do të ktheheshin prapa atë vit dhe do të vinin vitin tjetër; kushdo që ikte nga Kurejshët te muslimanët do të kthehej, por jo e kundërta.\n\nMegjithatë, Allahu shpalli në kthim se pikërisht ky traktat ishte \"një fitore e qartë\" (Kur'an 48:1, Surja el-Fath). Sahabët më vonë thanë se nuk panë kurrë një fitore më të madhe - sepse në paqen që pasoi, njerëzit u përzien lirshëm, e dëgjuan mesazhin me qetësi dhe hynë në Islami në një numër shumë më të madh se në të gjitha vitet e luftimit; Raporti i El-Bara' ibn Azibit për këtë qëllim është regjistruar në Sahih el-Buhari 4606. Armëpushimi gjithashtu në mënyrë implicite i njohu muslimanët si një fuqi të barabartë.\n\nMësimi: ajo që duket si një pengesë mund të jetë hapja më e madhe. Profeti ﷺ zgjodhi humbjen e dukshme afatshkurtër për të mirën afatgjate dhe nderoi një pazar të vështirë edhe kur ajo thumbonte. Durimi, përmbajtja dhe mbajtja e fjalës mund të arrijnë atë që përballja nuk mundet.",
    location: "Hudejbije",
  },
  {
    title: "Letra drejtuar sundimtarëve",
    body: "Pasi armëpushimi i Hudejbijes u dha muslimanëve një pushim nga lufta, Profeti ﷺ e drejtoi vëmendjen e tij përtej Arabisë. Rreth vitit 6-7 hixhri, ai dërgoi shokë të besuar si të dërguar, secili duke mbartur një letër të vulosur me vulën e tij, duke ftuar sundimtarët e mëdhenj të kohës të pranonin Islamin: Heraklin, Perandorin Bizantin; Kosroun II, Perandorin Persian; al-Mukaukisin, guvernatorin bizantin të Egjiptit; Negusin e Abisinisë, i cili tashmë kishte strehuar emigrantët myslimanë; dhe sundimtarët e Bahreinit dhe Omanit.\n\nLetra drejtuar Heraklit ka mbijetuar pothuajse fjalë për fjalë në literaturën e hadithit: 'Të ftoj në Islam. Prano Islamin dhe do të jesh i sigurt... Prano Islamin dhe Allahu do të të dyfishojë shpërblimin' (Sahih el-Buhari 7). Ai raport ruan gjithashtu bisedën e gjatë në të cilën Herakli e pyeti tregtarin mekas Ebu Sufjan - i cili ishte ende jobesimtar - për prejardhjen dhe karakterin e Profetit ﷺ, dhe nga përgjigjet e sinqerta arriti në përfundimin se tiparet e përshkruara përputheshin me një profet të vërtetë, edhe pse nuk veproi sipas kësaj bindjeje. Kosrou, në anën tjetër, mbahet mend në sire si ai që e grisi letrën me zemërim, ndërsa Negusi e priti të dërguarin me nder.\n\nMësimi: misioni i të Dërguarit të fundit nuk u kufizua kurrë në Arabi - sapo Medina u sigurua, thirrja shkoi në gjithë botën e njohur, pikërisht ashtu si Kurani e përshkruan të dërguar 'për gjithë njerëzimin' (Kuran 34:28). Disa sundimtarë dëgjuan me sinqeritet, disa u përgjigjën me mirësjellje, e disa me arrogancë - dhe çdo përgjigje paralajmëroi se si mbretëritë e tyre do të përballeshin më vonë me Islamin.",
    location: "Medine",
  },
  {
    title: "Ekspedita në Khajbar",
    body: "Jo shumë kohë pas Hudejbijes, Profeti ﷺ iu drejtua Hajberit, një oaz i pasur me fortesa të fortifikuara në veri të Medinës. Hajbari ishte bërë një bazë armiqësie - shtëpia e fiseve që kishin ndihmuar në organizimin e rrethimit të Medinës nga konfederatat dhe vazhdonin të komplotonin kundër komunitetit mysliman. Fushata kishte për qëllim t'i jepte fund këtij kërcënimi.\n\nKështjellat ranë njëra pas tjetrës pas luftimeve të vështira; flamuri në ditën vendimtare iu dha Ali ibn Ebi Talibit (Allahu qoftë i kënaqur me të). Më pas, Profeti ﷺ i lejoi banorët të qëndronin dhe të vazhdonin të punonin tokën në këmbim të një pjese të prodhimit të saj - një marrëveshje që siguroi ushqim dhe stabilitet për Medinën në vend që të dëbonte të gjithë. Edhe këtu një grua tentoi ta helmonte me një dele, për të cilën ai u paralajmërua.\n\nMësimi: siguria dhe mbajtja e traktateve shkuan dorë për dore. Aksioni ishte kundër një fuqie të dëshmuar armiqësore, megjithatë ai përfundoi në një zgjidhje të zbatueshme që i lejonte të mundurit të mbanin mjetet e jetesës. Forca në Islami ka për qëllim vendosjen e sigurisë dhe drejtësisë, jo për të asgjësuar.",
    location: "Hajbar",
  },
  {
    title: "Umra e Kompensimit (Umrat al-Qada)",
    body: "Marrëveshja e Hudejbijes i ktheu muslimanët nga umra në vitin e gjashtë hixhri, me premtimin se mund të ktheheshin vitin pasues. Në muajin Dhul-Kaide të vitit të shtatë hixhri, pikërisht si u ra dakord, Profeti ﷺ udhëhoqi rreth dy mijë shokë përsëri në Mekë për të kryer haxhillëkun që u ishte mohuar - i mbajtur në kujtesë si Umrat al-Qada, umra e 'kompensimit' (e quajtur gjithashtu Umrat al-Kisas në disa burime).\n\nDuke nderuar pjesën e tyre të armëpushimit, Kurejshët e lëshuan qytetin për tri ditë që muslimanët të kryenin ritet në paqe, duke vështruar nga kodrat përreth ndërsa komuniteti që dikur kishin dëbuar tani sillej rreth Qabes në siguri të plotë. Ishte pikërisht gjatë kësaj vizite që xhaxhai i Profetit ﷺ, Abasi, organizoi martesën e tij me Meimunen bint el-Harith, dhe disa mekas që dëshmuan devotshmërinë dhe disiplinën e pelegrinëve u prekën dukshëm nga ç'ka panë.\n\nMësimi: mbajtja e një premtimi është vetë një formë thirrjeje. Aty ku njëzet vjet predikimi nuk kishin arritur të zbusnin zemrat, një umra e qetë dhe e dinjitetshme - fryti i drejtpërdrejtë i 'fitores së qartë' të Hudejbijes (Kuran 48:1) - zbuti zemra që forca kurrë nuk mundi. Kjo vizitë e qetë ndihmoi të hapej rruga për dorëzimin pothuajse pa gjakderdhje të Mekës vitin pasues.",
    location: "Meka",
  },
  {
    title: "Pushtimi i Mekës",
    body: 'Kur aleatët e Kurejshit thyen kushtet e Hudejbijes duke sulmuar një fis aleat të muslimanëve, armëpushimi u anulua. Në Ramazanin e vitit të tetë, Profeti ﷺ marshoi në Mekë me një ushtri prej dhjetë mijë - forca më e madhe deri më tani - dhe qyteti që e kishte persekutuar, bojkotuar dhe luftuar kundër tij për njëzet vjet, u dorëzua pothuajse pa gjakderdhje.\n\nDuke qëndruar më në fund si fitimtar mbi njerëzit që e kishin dëbuar, ai i pyeti mekasit se çfarë prisnin prej tij. Ata shpresonin në mëshirën e një vëllai fisnik, dhe ai iu përgjigj vëllezërve të tij me fjalët e Jusufit: "Nuk ju fajësoni sot" - dhe tha: "Shkoni, se jeni të lirë". Ai hyri në Qabe dhe e pastroi atë nga 360 idhujt e saj, duke recituar "E vërteta erdhi dhe gënjeshtra u zhduk" (Kur\'an 17:81), duke e rikthyer faltoren e Ibrahimit në adhurimin e pastër të Allahut. Surja En-Nasr (Kur\'an 110) flet për këtë moment kur njerëzit "hyjnë në fenë e Allahut me shumicë".\n\nMësimi: kjo është maja e mëshirës dhe faljes profetike. Me fuqi absolute për t\'u hakmarrë, ai fali. Besimtari mëson se të fortët janë ata që falin kur kanë mundësi të ndëshkojnë dhe se qëllimi nuk ka qenë kurrë hakmarrja por udhëzimi.',
    location: "Meka",
  },
  {
    title: "Beteja e Hunejnit",
    body: 'Vetëm disa javë pas pushtimit të qetë të Mekës, fiset e bashkuara të Hevazinit dhe Thakifit - të shqetësuara nga rritja e papritur e fuqisë myslimane dhe të vendosura të luftonin deri në fund - mblodhën një ushtri të madhe, duke sjellë me vete familjet, bagëtinë dhe pasurinë e tyre, dhe u ndeshën me ushtrinë shumë më të madhe të Profetit ﷺ në luginën e ngushtë të Hunejnit, midis Mekës dhe Taifit.\n\nHevazinët kishin fshehur harkëtarë në gryka, dhe kur lëshuan papritur një breshëri shigjetash në agim, avangarda myslimane u thye dhe u shpërnda; për një moment dukej sikur ushtria më e madhe që myslimanët kishin mbledhur ndonjëherë do të mundej thjesht nga sorprizë. Kurani e përshkruan pikërisht këtë kthesë: "...dhe në ditën e Hunejnit, kur numri juaj i madh nuk ju vlejti fare, dhe toka, sado e gjerë, ju u bë e ngushtë, e ju kthyet shpinën duke ikur" (Kuran 9:25). Profeti ﷺ vetë qëndroi i patundur dhe urdhëroi xhaxhain e tij Abasin t\'i thërriste Ensarët dhe fiset e Medinës me emër; ky thirrje i solli shokët e tij mbrapsht, u riorganizuan, dhe beteja u kthye në një fitore vendimtare myslimane, të cilën Kurani ia atribuon qetësisë dhe ndihmës së padukshme që Allahu zbriti (Kuran 9:26).\n\nMësimi: numri dhe pajisjet nuk vendosin rezultatin e një beteje - Bedri e kishte mësuar tashmë këtë mësim me një ushtri të vogël, dhe Hunejni tregoi anën e kundërt, se edhe një ushtri e madhe mund të lëkundet pa ndihmën e Allahut dhe disiplinën në fushën e betejës. Më pas, pasuria e konsiderueshme e kapur u shpërnda me bujari, duke përfshirë edhe të konvertuarit e rinj mekas, për të fituar zemrat dhe jo për të grumbulluar pasuri.',
    location: "Hunejn",
  },
  {
    title: "Ekspedita në Tebuk",
    body: "Në vitin e nëntë, në Medine mbërritën raportet për një mobilizim të mundshëm bizantin (romak) në kufirin verior. Në vapën e egër të verës së lartë, kur të korrat ishin pjekur dhe udhëtimi ishte i gjatë dhe i vështirë, Profeti ﷺ thirri ushtrinë më të madhe që ai udhëhoqi ndonjëherë - ndoshta tridhjetë mijë - për të marshuar në veri për në Tebuk. Kjo ishte \"ora e vështirësisë\" (Kur'an 9:117) dhe e sprovoi sinqeritetin si asgjë më parë.\n\nNuk u zhvillua asnjë betejë; shfaqja e vendosmërisë ishte e mjaftueshme dhe disa prijës veriorë bënë traktate me Medinën. Por fushata mbahet mend mbi të gjitha për atë që zbuloi për zemrat e njerëzve. Kur'ani i kushton asaj një pjesë të madhe të sures et-Tewbe - duke i lavdëruar ata që dhanë gjithçka (thotë se Ebu Bekri dha të gjithë pasurinë e tij), duke i ekspozuar hipokritët që shpikën justifikime për të qëndruar dhe duke treguar historinë prekëse të tre besimtarëve të sinqertë, duke përfshirë Ka'b ibn Malikun, i cili sinqerisht pranoi se nuk kishin asnjë justifikim dhe ishin fajtorë 19:19.\n\nMësimi: bindja është e lehtë kur është e rehatshme; e vërteta e saj tregon kur kushton. Tebuku ndau të sinqertët nga arsyetuesit dhe shënoi fundin efektiv të rezistencës së organizuar të idhujtarisë në Arabi. Ndershmëria – madje edhe ndershmëria e pranimit të dështimit – është rruga e kthimit te Allahu.",
    location: "Tebuku",
  },
  {
    title: "Viti i Delegacioneve (Am al-Wufud)",
    body: "Në vitin e nëntë hixhri, pas dorëzimit të Mekës dhe demonstrimit të fuqisë në Tebuk, fiset e Arabisë e kuptuan se rezistenca ndaj rendit të ri nuk ishte më realiste. Delegacion pas delegacioni - nga Beni Temimi, Beni Amiri, fiset e Jemenit dhe shumë të tjerë - erdhën në Medine për të shpallur pranimin e tyre të Islamit dhe besnikërinë ndaj Profetit ﷺ, kaq shumë sa viti mbahet mend në sire si Am al-Wufud, Viti i Delegacioneve.\n\nProfeti ﷺ i priti çdo grup me mikpritje dhe mësimdhënie të durueshme, duke i dërguar shokët e tij bashkë me ta për t'u mësuar popullit të tyre Kuranin dhe namazin, në vend të guvernatorëve që do t'i qeverisnin me forcë. Kurani i drejtohet direkt këtij momenti në suren En-Nasr: \"Kur të vijë ndihma e Allahut dhe fitorja, dhe i sheh njerëzit duke hyrë në fenë e Allahut turma-turma, atëherë lartësoje Atë me lavdërim dhe kërko falje prej Tij\" (Kuran 110:1-3) - një sure që shokët, siç ia shpjegoi Ibn Abasi Omerit, e kuptuan si shenjë se jeta e Profetit ﷺ po afrohej drejt fundit (Sahih el-Buhari 4430).\n\nMësimi: pas dekadave në të cilat mesazhi ishte refuzuar nga shumica dhe pranuar nga pak, premtimi i Allahut mbërriti gjithnjë menjëherë - një mësim në durim dhe në leximin e duhur të suksesit. Përgjigja e sures En-Nasr ndaj fitores nuk është festë, por lavdërim dhe pendim, një model për mënyrën se si besimtari duhet të presë çdo sukses në jetë. Kjo vendos tonin për Haxhillëkun e Lamtumirës që vjen më pas.",
    location: "Medine",
  },
  {
    title: "Pelegrinazhi i Lamtumirës",
    body: 'Në vitin e dhjetë Profeti ﷺ kreu haxhin e tij të vetëm të plotë, të cilit iu bashkuan mbi njëqind mijë shokë, duke u mësuar atyre ritet personalisht. Duke qëndruar në fushën e Arafahut, ai mbajti Hutbetin e Lamtumirës (Khutbat al-Uada\'), një përmbledhje e gjithçkaje që Islami kishte arritur të vendoste.\n\nAi shpalli shenjtërinë e jetës, pronës dhe nderit të çdo personi - "gjaku juaj dhe prona juaj janë po aq të shenjta sa kjo ditë, ky muaj, kjo tokë" (Sahih al-Bukhari 1741). Ai shfuqizoi gjakmarrjen dhe interesin (riba) e xhahilijetit, urdhëroi sjelljen e mirë të grave si amanet nga Allahu, u kujtoi atyre se asnjë arab nuk është më i lartë se joarabi përveçse në devotshmëri dhe u tha atyre që të kapeshin fort pas Kuranit. Pikërisht gjatë këtij pelegrinazhi, në Ditën e Arafatit, e cila binte të premten, Allahu shpalli "Këtë ditë përsosa për ju fenë tuaj..." (Kur\'an 5:3) - një varg që Omeri kujtoi dhe daton saktësisht (Sahih el-Bukhari 45).\n\nMësimi: Predikimi i Lamtumirës është Karta e Islamit për dinjitetin njerëzor, drejtësinë dhe barazinë, e vulosur me njoftimin se feja tashmë ishte e plotë. Detyra e besimtarit nga këtu nuk është ta shtojë atë, por ta jetojë atë.',
    location: "Arafah",
  },
  {
    title: "Kalimi i tij",
    body: 'Disa muaj pas Haxhit Lamtumirës, ​​Profeti a.s. u sëmur nga ethet. Në ditët e tij të fundit ai kërkoi lejen e grave të tij që të ushqeheshin në dhomën e Aishes (Allahu qoftë i kënaqur me të) dhe caktoi Ebu Bekrin për të udhëhequr namazin. Në mëngjesin e tij të fundit ai tërhoqi perden për të parë radhët e besimtarëve duke u lutur dhe buzëqeshur, të gëzuar me komunitetin e tij, pastaj e la të bjerë. Ai ndërroi jetë të hënën, më 12 Rabiul-Evel të vitit 11 hixhri, me kokën e mbështetur midis gjoksit dhe mjekrës së Aishes – siç ka transmetuar ajo vetë në Sahih el-Buhari 4449/4451.\n\nHidhërimi në Medine ishte i jashtëzakonshëm, madje edhe Omeri në fillim refuzoi ta pranonte atë. Pastaj Ebu Bekri u ngrit, e puthi fytyrën e Profetit dhe iu drejtua njerëzve me fjalë që siguruan të gjithë bashkësinë dhe janë të shënuara në Sahih el-Buhari 1241/1242: "Kush e adhuronte Muhammedin, atëherë Muhamedi ka vdekur; por kush e adhuron Allahun, atëherë Allahu nuk është i Gjithëdijshëm". Ai lexoi "Muhamedi është vetëm një i dërguar; para tij kanë vdekur të dërguar..." (Kur\'an 3:144).\n\nMësimi: mesazhi ishte i plotë dhe tani i përkiste umetit. Profeti ﷺ ishte i vdekshëm, por ajo që ai solli - Kur\'ani dhe Suneti i tij - nuk është. Përgjigja e Ebu Bekrit është përgjigja e qëndrueshme ndaj pikëllimit: lidhja jonë është me Allahun, i cili nuk vdes kurrë, dhe mënyra për ta dashur Profetin ﷺ është të jetojmë udhëzimin e tij.',
    location: "Medine",
  },
];
