// Manifest writer + deterministic file IO helpers.
//
// The manifest records, for each dataset, its version, the sha256 + byte size
// of every emitted file, and licensing/attribution. It is primarily a build
// artifact and it powers the in-app Credits screen.

import { createHash } from "node:crypto";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
export const APP_ROOT = join(HERE, "..", "..");
export const REPO_ROOT = join(APP_ROOT, "..", "..");
export const ASSETS_DATA_DIR = join(APP_ROOT, "assets", "data");
export const SHARED_CONTENT_DIR = join(REPO_ROOT, "packages", "shared", "src", "content");

/** Write UTF-8 (no BOM), `\n` newlines, trailing newline. */
export async function writeFileStable(absPath, contents) {
  await mkdir(dirname(absPath), { recursive: true });
  const normalized = contents.endsWith("\n") ? contents : `${contents}\n`;
  await writeFile(absPath, normalized, { encoding: "utf8" });
}

/** Write a value as pretty JSON (stable — no timestamps/random). */
export async function writeJSON(absPath, value) {
  await writeFileStable(absPath, JSON.stringify(value, null, 2));
}

/** Write a compact JSON map (one object, minified) — for per-surah data files. */
export async function writeCompactJSON(absPath, value) {
  await writeFileStable(absPath, JSON.stringify(value));
}

async function fileHash(absPath) {
  const buf = await readFile(absPath);
  const sha256 = createHash("sha256").update(buf).digest("hex");
  const { size } = await stat(absPath);
  return { sha256, bytes: size };
}

/**
 * Build a manifest dataset entry.
 * @param {{ id, kind, version, absFiles: string[], license, attribution, sourceUrl, note? }} input
 */
export async function datasetEntry({
  id,
  kind,
  version,
  absFiles,
  license,
  attribution,
  sourceUrl,
  note,
}) {
  const files = [];
  for (const abs of absFiles.sort()) {
    const { sha256, bytes } = await fileHash(abs);
    files.push({ path: relative(APP_ROOT, abs).split("\\").join("/"), sha256, bytes });
  }
  const entry = { id, kind, version, files, license, attribution, sourceUrl };
  if (note) entry.note = note;
  return entry;
}

/** Write the top-level manifest.json aggregating all dataset entries. */
export async function writeManifest(datasets) {
  const manifest = {
    generatedAtNote:
      "Generated by scripts/build-data. Re-run `pnpm --filter app build:data` to refresh.",
    datasets: datasets.sort((a, b) => a.id.localeCompare(b.id)),
  };
  await writeJSON(join(ASSETS_DATA_DIR, "manifest.json"), manifest);
}
