import type { BattlesTimelineEvent } from "../types/battles";

/** Bump when timeline milestones change. */
export const BATTLES_TIMELINE_VERSION = 2;

/** Chronological milestones from revelation through the Farewell Pilgrimage. */
export const BATTLES_TIMELINE: BattlesTimelineEvent[] = [
  {
    id: "revelation",
    year: 610,
    title: "First revelation",
    body: "The Prophet ﷺ receives the first verses of Surah al-'Alaq in the Cave of Hira. For years the call is peaceful — no permission to fight.",
    location: "Makkah",
  },
  {
    id: "persecution",
    year: 613,
    title: "Public call and persecution",
    body: "Open preaching brings torture, boycott, and martyrdom. Muslims endure without armed retaliation — patience and migration are the responses taught.",
    location: "Makkah",
  },
  {
    id: "hijra",
    year: 622,
    ah: 1,
    title: "Hijra to Madinah",
    body: "The Muslim community establishes a polity in Yathrib (Madinah). Treaties with Jewish tribes and the Constitution of Madinah set rules for coexistence.",
    location: "Madinah",
  },
  {
    id: "badr",
    year: 624,
    ah: 2,
    title: "Battle of Badr",
    body: "On 17 Ramadan, about 313 Muslims defeat a much larger Quraysh army — the first major battle and a decisive moral victory.",
    location: "Badr",
    topicId: "badr",
  },
  {
    id: "uhud",
    year: 625,
    ah: 3,
    title: "Battle of Uhud",
    body: "Muslims initially gain ground, but archers leaving their post leads to a painful setback. The Qur'an addresses the lessons of that day.",
    location: "Mount Uhud",
    topicId: "uhud",
  },
  {
    id: "trench",
    year: 627,
    ah: 5,
    title: "Battle of the Trench",
    body: "A confederate army besieges Madinah. Digging a trench — Salman's suggestion — breaks the siege without a pitched battle.",
    location: "Madinah",
    topicId: "trench",
  },
  {
    id: "banu-qurayzah",
    year: 627,
    ah: 5,
    title: "Banu Qurayzah",
    body: "Having broken the covenant of Madinah during the siege, Banu Qurayzah surrender and ask to be judged by an arbiter of their own choosing, Sa'd ibn Mu'adh.",
    location: "Madinah",
    topicId: "banu-qurayzah",
  },
  {
    id: "hudaybiyyah",
    year: 628,
    ah: 6,
    title: "Treaty of Hudaybiyyah",
    body: "A ten-year truce that seemed a concession became, in the Qur'an's words, a manifest victory — the Pledge of Ridwan was given under the tree, conversions spread, and the path to Makkah opened.",
    location: "Hudaybiyyah",
    topicId: "hudaybiyyah",
  },
  {
    id: "mutah",
    year: 629,
    ah: 8,
    title: "Battle of Mu'tah",
    body: "An expedition to the Roman frontier; the three appointed commanders are martyred in succession before Khalid ibn al-Walid withdraws the army safely.",
    location: "Mu'tah",
    topicId: "mutah",
  },
  {
    id: "khaybar",
    year: 629,
    ah: 7,
    title: "Expedition of Khaybar",
    body: "Jewish fortresses north of Madinah that had harboured hostility are subdued. Ali ibn Abi Talib is given the banner after Abu Bakr and Umar are tried.",
    location: "Khaybar",
    topicId: "khaybar",
  },
  {
    id: "makkah",
    year: 630,
    ah: 8,
    title: "Conquest of Makkah",
    body: "Quraysh break the treaty; the Prophet ﷺ marches with ten thousand companions and enters Makkah almost without bloodshed — general amnesty declared.",
    location: "Makkah",
    topicId: "conquest-makkah",
  },
  {
    id: "hunayn",
    year: 630,
    ah: 8,
    title: "Battle of Hunayn",
    body: "Hawazin and Thaqif ambush the Muslims after Makkah. Initial panic gives way to victory when the Prophet ﷺ calls the believers to rally around him.",
    location: "Hunayn",
    topicId: "hunayn",
  },
  {
    id: "tabuk",
    year: 631,
    ah: 9,
    title: "Expedition of Tabuk",
    body: "A difficult summer march toward the Roman border. No battle occurs, but hypocrisy is exposed and Surah at-Tawbah addresses those who stayed behind.",
    location: "Tabuk",
    topicId: "tabuk",
  },
  {
    id: "farewell",
    year: 632,
    ah: 10,
    title: "Farewell Pilgrimage",
    body: "The Prophet ﷺ performs Hajj and delivers the Farewell Sermon. He passes away in Madinah shortly after — the era of prophetic battles closes.",
    location: "Makkah",
  },
];
