import type { DuaCategoryId, DuaItem } from "../types/index";

export const DUA_CONTENT_VERSION = 4;

export const DUA_CATEGORY_LABELS: Record<DuaCategoryId, string> = {
  sunnah: "Sunnah Duas",
  quranic: "Quranic Duas",
  daily: "Daily Duas",
};

/**
 * Curated supplications. Generated by
 * apps/app/scripts/build-data/build-adhkar.mjs — do not edit by hand.
 */
export const DUA_ITEMS: DuaItem[] = [
  {
    id: "quranic-hasanah",
    categoryId: "quranic",
    title: "Good in this world and the next",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration:
      "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhaban-nar",
    translation:
      "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
    reference: "Quran 2:201",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/235hm.mp3",
  },
  {
    id: "quranic-ilma",
    categoryId: "quranic",
    title: "Increase me in knowledge",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transliteration: "Rabbi zidni 'ilma",
    translation: "My Lord, increase me in knowledge.",
    reference: "Quran 20:114",
  },
  {
    id: "quranic-sabr",
    categoryId: "quranic",
    title: "Patience and steadfastness",
    arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا",
    transliteration: "Rabbana afrigh 'alayna sabran wa thabbit aqdamana",
    translation: "Our Lord, pour upon us patience and make firm our footing.",
    reference: "Quran 2:250",
  },
  {
    id: "quranic-light",
    categoryId: "quranic",
    title: "Light and forgiveness",
    arabic: "رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Rabbana atmim lana nurana waghfir lana innaka 'ala kulli shay'in qadir",
    translation:
      "Our Lord, perfect for us our light and forgive us; indeed You are over all things competent.",
    reference: "Quran 66:8",
  },
  {
    id: "quranic-tawakkul",
    categoryId: "quranic",
    title: "Reliance upon Allah",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    transliteration: "Hasbunallahu wa ni'mal-wakil",
    translation: "Allah is sufficient for us, and He is the best disposer of affairs.",
    reference: "Quran 3:173",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/128hm.mp3",
  },
  {
    id: "quranic-dhun-nun",
    categoryId: "quranic",
    title: "The supplication of Yunus",
    arabic: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimin",
    translation: "There is no god but You; glory be to You. Indeed, I have been of the wrongdoers.",
    virtues: "No Muslim supplicates with it for anything but Allah answers him.",
    reference: "Quran 21:87 · Tirmidhi",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/124hm.mp3",
  },
  {
    id: "sunnah-huda-tuqa",
    categoryId: "sunnah",
    title: "Guidance and contentment",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    transliteration: "Allahumma inni as'aluka al-huda wat-tuqa wal-'afafa wal-ghina",
    translation: "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.",
    reference: "Muslim",
  },
  {
    id: "sunnah-hamm-hazan",
    categoryId: "sunnah",
    title: "Relief from anxiety and grief",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan",
    translation: "O Allah, I seek refuge in You from anxiety and grief.",
    reference: "Bukhari",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/121hm.mp3",
  },
  {
    id: "sunnah-afiyah",
    categoryId: "sunnah",
    title: "Well-being in body and faith",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    transliteration: "Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah",
    translation: "O Allah, I ask You for well-being in this world and the Hereafter.",
    reference: "Ibn Majah",
  },
  {
    id: "sunnah-dhikr-shukr",
    categoryId: "sunnah",
    title: "Help to remember and thank Allah",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation:
      "O Allah, help me to remember You, to thank You, and to worship You in the best manner.",
    virtues: "The Prophet ﷺ advised Mu'adh never to leave this after every prayer.",
    reference: "Abu Dawud & An-Nasa'i",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/59hm.mp3",
  },
  {
    id: "sunnah-thabbit-qalbi",
    categoryId: "sunnah",
    title: "Make my heart firm upon Your religion",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
    transliteration: "Ya muqallibal-qulub thabbit qalbi 'ala dinik",
    translation: "O Turner of the hearts, make my heart firm upon Your religion.",
    reference: "Tirmidhi",
  },
  {
    id: "daily-before-eating",
    categoryId: "daily",
    title: "Before eating",
    arabic: "بِسْمِ اللَّهِ",
    transliteration: "Bismillah",
    translation: "In the name of Allah.",
    reference: "Abu Dawud",
  },
  {
    id: "daily-after-eating",
    categoryId: "daily",
    title: "After eating",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration:
      "Alhamdu lillahilladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation:
      "All praise is for Allah who fed me this and provided it for me without any might or power on my part.",
    virtues: "Whoever says it after eating has his past sins forgiven.",
    reference: "Abu Dawud & Tirmidhi",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/180hm.mp3",
  },
  {
    id: "daily-leaving-home",
    categoryId: "daily",
    title: "Leaving the home",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    translation:
      "In the name of Allah, I place my trust in Allah; there is no might nor power except with Allah.",
    reference: "Abu Dawud & Tirmidhi",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/16hm.mp3",
  },
  {
    id: "daily-entering-home",
    categoryId: "daily",
    title: "Entering the home",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَىٰ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'ala Rabbina tawakkalna",
    translation:
      "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.",
    reference: "Abu Dawud",
  },
  {
    id: "daily-travel",
    categoryId: "daily",
    title: "Travel",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    transliteration: "Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin",
    translation:
      "Glory to Him who has subjected this to us, and we could not have done it by ourselves.",
    reference: "Quran 43:13 · Muslim",
  },
  {
    id: "daily-entering-masjid",
    categoryId: "daily",
    title: "Entering the masjid",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahummaftah li abwaba rahmatik",
    translation: "O Allah, open for me the gates of Your mercy.",
    reference: "Muslim",
  },
  {
    id: "daily-distress",
    categoryId: "daily",
    title: "In times of distress",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "La ilaha illallahul-'Azimul-Halim, la ilaha illallahu Rabbul-'Arshil-'Azim",
    translation:
      "There is no god but Allah, the Magnificent, the Forbearing; there is no god but Allah, Lord of the Magnificent Throne.",
    virtues: "The Prophet ﷺ would say it in times of distress.",
    reference: "Bukhari & Muslim",
  },
  {
    id: "daily-supplication-before-sleeping",
    categoryId: "daily",
    title: "Supplication Before Sleeping",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوْتُ وَأَحْيَا",
    transliteration: "bismika allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    virtues:
      "The Prophet, sallallahu 'alayhi wa sallam, always started and ended his day with dhikr.",
    reference: "HR. al-Bukhari",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/105hm.mp3",
  },
  {
    id: "daily-supplication-upon-waking-up",
    categoryId: "daily",
    title: "Supplication Upon Waking Up",
    arabic: "الحَمْدُ للهِ الَّذِي أَحْيَانَا بعْدَ مَا أماتَنَا وإِلَيْهِ النُّشُورُ",
    transliteration: "alhamdulillahilladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation:
      "All praise is for Allah who gives us life after He has caused us to die, and to Him is the resurrection.",
    virtues:
      "By reciting the supplication above, a servant begins his day by praising the name of Allah, the Giver of Life and the Bringer of Death.",
    reference: "HR. Bukhari: 6327",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/1hm.mp3",
  },
  {
    id: "daily-supplication-entering-the-bathroom",
    categoryId: "daily",
    title: "Supplication Entering the Bathroom",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
    transliteration: "allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
    translation: "O Allah, I seek refuge in You from the evil and the wicked.",
    virtues:
      "This supplication acts as a barrier between a servant's private parts and the jinn when entering the bathroom.",
    reference: "HR. al-Bukhari and Muslim",
  },
  {
    id: "daily-supplication-leaving-the-bathroom",
    categoryId: "daily",
    title: "Supplication Leaving the Bathroom",
    arabic: "غُفْرَانَكَ",
    transliteration: "ghufranak",
    translation: "I ask for Your forgiveness (O Allah).",
    virtues:
      "The bathroom is one of the homes of the jinn and devils, so it is recommended to ask for forgiveness for any mistakes, intentional or unintentional, made while in the bathroom.",
    reference: "HR. at-Tirmidzi",
  },
  {
    id: "daily-supplication-if-forgetting-bismillah-at-the-begi",
    categoryId: "daily",
    title: "Supplication If Forgetting Bismillah at the Beginning of a Meal",
    arabic: "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ",
    transliteration: "bismillahi awwalahu wa akhirahu",
    translation: "In the name of Allah, at its beginning and its end.",
    virtues:
      "Islam pays great attention to etiquette. If someone forgets to recite the supplication before eating at the beginning, it is still recommended to recite it in the middle, even if there is only a spoonful of rice left.",
    reference: "HR. Abu Dawud",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/9hm.mp3",
  },
  {
    id: "daily-supplication-after-eating",
    categoryId: "daily",
    title: "Supplication After Eating",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِى أَطْعَمَنِى هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّى وَلاَ قُوَّةٍ",
    transliteration:
      "alhamdulillahilladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation:
      "All praise is to Allah who has fed me this and provided for me without any power or strength from me.",
    virtues:
      "The Messenger of Allah, sallallahu 'alayhi wa sallam, said that if someone recites this supplication, then his past sins will be forgiven.",
    reference: "Shahih at-Tirmidzi",
  },
  {
    id: "daily-supplication-leaving-the-mosque",
    categoryId: "daily",
    title: "Supplication Leaving the Mosque",
    arabic: "اَللَّهُمَّ إِنِّيْ أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "allahumma inni as'aluka min fadlik",
    translation: "O Allah, I ask You for Your bounty.",
    virtues:
      "Allah's earth is vast, and there are many ways to seek provision. A servant should ask for Allah's bounty to be facilitated in obtaining the provision that Allah has distributed to all His servants.",
    reference: "HR. Muslim No. 713",
  },
  {
    id: "daily-supplication-after-performing-ablution",
    categoryId: "daily",
    title: "Supplication After Performing Ablution",
    arabic:
      "أشْهَدُ أنْ لا إله إِلاَّ اللَّهُ وَحْدَهُ لا شَرِيك لَهُ ، وأشْهَدُ أنَّ مُحَمَّداً عَبْدُهُ وَرَسُولُهُ ، اللَّهُمَّ اجْعَلْنِي مِنَ التَوَّابِينَ ، واجْعَلْني مِنَ المُتَطَهِّرِينَ ، سُبْحانَكَ اللَّهُمَّ وبِحَمْدِكَ ، أشْهَدُ أنْ لا إلهَ إِلاَّ أنْتَ ، أسْتَغْفِرُكَ وأتُوبُ إِلَيْكَ",
    transliteration:
      "ashhadu alla ilaha illa allah wahdahu la sharika lahu, wa ashhadu anna muhammadan 'abduhu wa rasuluh. allahummaj'alni minat-tawwabina waj'alni minal-mutatahhirin. subhanakallahumma wa bihamdika ashhadu alla ilaha illa anta astaghfiruka wa atubu ilayk",
    translation:
      "I bear witness that there is no deity except Allah alone, with no partner, and I bear witness that Muhammad is His servant and Messenger. O Allah, make me among those who repent and make me among those who purify themselves. Glory be to You, O Allah, and with Your praise, I bear witness that there is no deity except You. I seek Your forgiveness and repent to You.",
    virtues:
      "Whoever recites this supplication, eight gates of Paradise will be opened for him, and he may enter from whichever gate he wishes.",
    reference: "HR. Muslim, at-Tirmidzi and an-Nasa'i",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/13hm.mp3",
  },
  {
    id: "daily-supplication-for-breaking-the-fast",
    categoryId: "daily",
    title: "Supplication for Breaking the Fast",
    arabic: "ذَهَبَ الظَّمَأُ وابْتَلَّتِ الْعُرُوقُ وثَبَتَ اْلأَجْرُ إِنْ شَاءَاللهُ",
    transliteration: "dhahabadh-dhama'u wabtallatil-'uruqu wa thabatal-ajru insha allah",
    translation:
      "The thirst has gone, the veins are moistened, and the reward is confirmed, Insha Allah.",
    virtues:
      "It is highly recommended for those who are fasting to increase their supplications before and after breaking the fast, because the supplication of a fasting person is one of the three supplications that are not rejected.",
    reference:
      "HR. Abu Daud, As-Sunan Al-Kubra Lil Baihaqi, Vol. 4, p. 239, al-Hakim in Mustadrak 'alas Shahihain No. 1484",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/176hm.mp3",
  },
  {
    id: "daily-supplication-entering-the-house-1",
    categoryId: "daily",
    title: "Supplication Entering the House #1",
    arabic: "اَلسَّلَامُ عَلَيْكُمْ",
    transliteration: "assalamu 'alaykum",
    translation: "Peace be upon you.",
    virtues:
      "The greeting is a supplication of hope, a hope that you will be safe from all kinds of sorrow and suffering, and be enveloped in mercy and blessings.",
    reference: "HR. at-Tirmidzi",
  },
  {
    id: "daily-supplication-entering-the-house-2",
    categoryId: "daily",
    title: "Supplication Entering the House #2",
    arabic: "اَلسَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَا تُهُ",
    transliteration: "assalamu 'alaykum wa rahmatullahi wa barakatuh",
    translation: "Peace, mercy, and blessings of Allah be upon you.",
    virtues:
      "The greeting is a supplication of hope, a hope that you will be safe from all kinds of sorrow and suffering, and be enveloped in mercy and blessings.",
    reference: "HR. at-Tirmidzi",
  },
  {
    id: "daily-supplication-leaving-the-house",
    categoryId: "daily",
    title: "Supplication Leaving the House",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "bismillah, tawakkaltu 'alallah, la hawla wa la quwwata illa billah",
    translation:
      "In the name of Allah, I place my trust in Allah. There is no might nor power except with Allah.",
    virtues:
      'Whoever recites this supplication, it will be said to him: "You will be guided, sufficed, and protected." Satan will then depart from him. Another satan will say: "How can you harm someone who has been guided, sufficed, and protected?!"',
    reference: "HR. Abu Dawud and at-Tirmidzi",
  },
  {
    id: "daily-supplication-for-protection-from-causing-or-expe",
    categoryId: "daily",
    title: "Supplication for Protection from Causing or Experiencing Harm Outside the House",
    arabic: "اللَّهُمَّ إِنِّى أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ أَوْ أَزِلَّ أَوْ أُزَلَّ أَوْ أَظْلِمَ أَوْ أُظْلَمَ أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَىَّ",
    transliteration:
      "allahumma inni a'udhu bika an adilla aw udalla, aw azilla aw uzalla, aw adhlima aw udhlama, aw ajhala aw yujhala 'alayya",
    translation:
      "O Allah, I seek refuge in You lest I should stray or be led astray, slip or be tripped, wrong or be wronged, or act foolishly or have foolishness done to me.",
    virtues:
      "When a person leaves the house, they will encounter all kinds of things, both good and bad, especially harm caused by themselves. Therefore, it is commanded to seek refuge from oneself and from others.",
    reference: "HR. Abu Dawud, at-Tirmidzi, Ibn Majah and an-Nasa'i",
  },
  {
    id: "daily-travel-supplication",
    categoryId: "daily",
    title: "Travel Supplication",
    arabic:
      "الله أَكْبَرُ،الله أَكْبَرُ،الله أَكْبَرُ،سُبْحَانَ الَّذِى سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ اللَّهُمَّ إِنَّا نَسْأَلُكَ فِى سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ اللَّهُمَّ أَنْتَ الصَّاحِبُ فِى السَّفَرِ وَالْخَلِيفَةُ فِى الأَهْلِ اللَّهُمَّ إِنِّى أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمَنْظَرِ وَسُوءِ الْمُنْقَلَبِ فِى الْمَالِ وَالأَهْلِ",
    transliteration:
      "allahu akbar, allahu akbar, allahu akbar. subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila rabbina lamunqalibun. allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa wa minal-'amali ma tarda. allahumma hawwin 'alayna safarana hadha watwi 'anna bu'dah. allahumma antas-sahibu fis-safar. wal-khalifatu fil-ahl. allahumma inni a'udhu bika min wa'tha'is-safar wa ka'abatil-mandhari wa su'il-munqalabi fil-mali wal-ahl",
    translation:
      "Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. Glory be to Him who has provided this for us, though we could never have had it by our own efforts. Surely to our Lord we are returning. O Allah, we ask You for righteousness and piety in this journey of ours, and for deeds that please You. O Allah, lighten for us the hardship of this journey and quickly bring us to our destination. O Allah, You are our Companion on the journey and the Guardian of our families. O Allah, I seek refuge in You from the hardship of travel, from a bad return, and from seeing something unpleasant concerning our wealth, family, or children.",
    virtues:
      "This supplication has two parts. The first is praise of Allah and the submission of the servant. The second is a request to Allah for ease in travel and in the affairs of what the servant has left at home.",
    reference: "HR. Muslim",
  },
  {
    id: "daily-supplication-of-a-resident-for-someone-who-is-tr",
    categoryId: "daily",
    title: "Supplication of a Resident for Someone Who is Traveling",
    arabic: "أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ وَخَوَاتِيمَ عَمَلِكَ",
    transliteration: "astawdi'ullaha dinaka, wa amanataka, wa khawatima 'amalik",
    translation: "I entrust your religion, your trust, and the end of your deeds to Allah.",
    virtues:
      "Three priorities of a servant that must be maintained everywhere: religion, trust, and deeds, because a person will be resurrected according to their deeds.",
    reference: "HR. Abu Dawud: 2601",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/212hm.mp3",
  },
  {
    id: "daily-supplication-for-piety-from-a-resident-to-someon",
    categoryId: "daily",
    title: "Supplication for Piety from a Resident to Someone Who is Traveling",
    arabic: "زَوَّدَكَ اللَّهُ التَّقْوَى وَغَفَرَ ذَنْبَكَ  وَيَسَّرَ لَكَ الْخَيْرَ حَيْثُمَا كُنْتَ",
    transliteration:
      "zawwadakallahut-taqwa, wa ghafara dhanbaka, wa yassara lakal-khayra haythuma kunta",
    translation:
      "May Allah provide you with piety, forgive your sins, and ease goodness for you wherever you are.",
    virtues:
      "Piety is the best provision that a servant must prepare for the Hereafter, because there is no salvation except through piety.",
    reference: "HR. at-Tirmidzi",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/213hm.mp3",
  },
  {
    id: "daily-supplication-when-wearing-new-clothes",
    categoryId: "daily",
    title: "Supplication When Wearing New Clothes",
    arabic: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ",
    transliteration:
      "allahumma lakal-hamdu anta kasawtanihi. as'aluka min khayrihi wa khayri ma suni'a lah, wa a'udhu bika min sharrihi wa sharri ma suni'a lah",
    translation:
      "O Allah, to You is all praise. You have clothed me with this. I ask You for its goodness and the goodness for which it was made, and I seek refuge in You from its evil and the evil for which it was made.",
    virtues:
      "By reciting this supplication, one asks that the clothes they have bought may provide goodness and also be a protection against various evils.",
    reference: "HR. Ahmad, Abu Dawud, at-Tirmidzi and Al-Hakim",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/6hm.mp3",
  },
  {
    id: "daily-supplication-when-wearing-clothes",
    categoryId: "daily",
    title: "Supplication When Wearing Clothes",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِى كَسَانِى هَذَا الثَّوْبَ وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّى وَلاَ قُوَّةٍ",
    transliteration:
      "alhamdulillahilladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation:
      "Praise be to Allah who has clothed me with this garment and provided it for me without any power or strength from me.",
    virtues:
      "The virtue of reciting this supplication is that past sins will be forgiven, Insha Allah.",
    reference: "HR. all compilers of Sunan books, except Nasa'i",
  },
  {
    id: "daily-supplication-when-mounting-a-vehicle",
    categoryId: "daily",
    title: "Supplication When Mounting a Vehicle",
    arabic:
      "بِسْمِ اللَّهِ، بِسْمِ اللَّهِ، بِسْمِ اللَّهِ، الحَمْدُ للِه، سُبْحَانَ الَّذِى سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ، سُبْحَانَكَ إِنِّى قَدْ ظَلَمْتُ نَفْسِى فَاغْفِرْ لِى فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
    transliteration:
      "bismillah, bismillah, bismillah, alhamdulillah, subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin. wa inna ila rabbina lamunqalibun. subhanaka inni qad dhalamtu nafsi, faghfir li fa innahu la yaghfirudh-dhunuba illa anta",
    translation:
      "In the name of Allah, in the name of Allah, in the name of Allah. All praise is to Allah. Glory be to Him who has subjected this to us, and we could not have done so by ourselves. And indeed, to our Lord we will return. Glory be to You, indeed I have wronged myself, so forgive me, for none can forgive sins except You.",
    virtues:
      "By reciting the supplication for mounting a vehicle, our journey will always be under the protection of Allah. In addition, we will also receive rewards, help, and a calmer heart.",
    reference: "HR. Abu Dawud and at-Tirmidzi",
  },
  {
    id: "daily-supplication-when-it-rains",
    categoryId: "daily",
    title: "Supplication When it Rains",
    arabic: "اللَّهُمَّ صَيِّبًا نَافِعًا",
    transliteration: "allahumma sayyiban nafi'a",
    translation: "O Allah, make it a beneficial rain.",
    virtues:
      "It is encouraged to pray when it rains so that goodness and blessings increase, as well as its benefits.",
    reference: "HR. al-Bukhari No. 1032",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/172hm.mp3",
  },
  {
    id: "daily-supplication-during-heavy-rain",
    categoryId: "daily",
    title: "Supplication During Heavy Rain",
    arabic: "اللَّهُمَّ حَوَالَيْنَا وَلاَ عَلَيْنَا ، اللَّهُمَّ عَلَى الآكَامِ وَالظِّرَابِ وَبُطُونِ الأَوْدِيَةِ وَمَنَابِتِ الشَّجَرِ",
    transliteration:
      "allahumma hawalayna wa la 'alayna. allahumma 'alal-akami wadh-dhirabi, wa butunil-awdiyati, wa manabitish-shajar",
    translation:
      "O Allah, (let the rain fall) around us, not on us. O Allah, (let it fall) on the hills, mountains, small mountains, valleys, and places where trees grow.",
    virtues:
      "The supplication above is recited when the rain gets heavier or there is a concern that the rain will cause harm.",
    reference: "HR. al-Bukhari No. 1014",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/174hm.mp3",
  },
  {
    id: "daily-supplication-after-it-rains",
    categoryId: "daily",
    title: "Supplication After it Rains",
    arabic: "مُطِرْنا بفَضْلِ اللهِ ورَحْمَتِهِ",
    transliteration: "mutirna bi fadlillahi wa rahmatih",
    translation: "We have been given rain by the bounty and mercy of Allah.",
    virtues:
      "By reciting this supplication, one believes that rain falls by the will of Allah (Allah's virtue), not by the stars, so they do not become disbelievers in Allah.",
    reference: "HR. al-Bukhari No. 846 and Muslim No. 71",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/173hm.mp3",
  },
  {
    id: "daily-supplication-during-strong-wind",
    categoryId: "daily",
    title: "Supplication During Strong Wind",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا، وَأَعُوْذُ بِكَ مِنْ شَرِّهَا",
    transliteration: "allahumma inni as'aluka khayraha wa a'udhu bika min sharriha",
    translation:
      "O Allah, I ask You for the good of this wind, and I seek refuge in You from its evil.",
    virtues:
      "Among the signs of Allah's power is a strong wind that can bring blessings and punishment, namely good and bad. Therefore, a servant should continue to ask for good and seek refuge from all harm.",
    reference: "HR. Abu Dawud and Ibn Majah",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/166hm.mp3",
  },
  {
    id: "daily-the-best-supplication-for-seeking-forgiveness-sa",
    categoryId: "daily",
    title: "The Best Supplication for Seeking Forgiveness (Sayyid al-Istighfar)",
    arabic:
      "اَللَّهُمَّ أَنْتَ رَبِّيْ ، لَا إِلٰـهَ إِلاَّ أَنْتَ خَلَقْتَنِيْ وَأَنَا عَبْدُكَ ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوْذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوْءُ لَكَ بِنِعْمتِكَ عَلَيَّ ، وَأَبُوْءُ بِذَنْبِيْ فَاغْفِرْ لِيْ ، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
    transliteration:
      "allahumma anta rabbi la ilaha illa anta khalaqtani wa ana 'abduka wa ana 'ala 'ahdika wa wa'dika mastata'tu a'udhu bika min sharri ma sana'tu abu'u laka bini'matika 'alayya wa abu'u bidhanbi faghfir li fa innahu la yaghfirudh-dhunuba illa anta",
    translation:
      "O Allah, You are my Lord. There is no deity worthy of worship except You. You created me, and I am Your servant. I abide to Your covenant and promise as best I can. I seek refuge in You from the evil of what I have done. I acknowledge Your blessings upon me, and I acknowledge my sin. So forgive me, for none can forgive sins except You.",
    virtues:
      "Whoever recites it with certainty in the evening, and then he dies, he will enter Paradise, and likewise if (recited) in the morning.",
    reference: "HR. al-Bukhari No. 6306, 6323, Ahmad IV/122-125, an-Nasa'i VIII/279-280",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/79hm.mp3",
  },
  {
    id: "daily-supplication-for-ease-in-all-matters",
    categoryId: "daily",
    title: "Supplication for Ease in All Matters",
    arabic: "اللَّهُمَّ لاَ سَهْلَ إِلاَّ مَا جَعَلْتَهُ سَهْلاً وَأَنْتَ تَجْعَلُ الحَزْنَ إِذَا شِئْتَ سَهْلاً",
    transliteration:
      "allahumma la sahla illa ma ja'altahu sahla, wa anta taj'alul-hazna idha shi'ta sahla",
    translation:
      "O Allah, there is no ease except in that which You make easy, and You make the difficult easy if You wish.",
    virtues: "Ease comes only from Allah. Even something difficult can become easy Insha Allah.",
    reference: "HR. Ibn Hibban",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/139hm.mp3",
  },
  {
    id: "daily-supplication-when-afflicted-by-calamity",
    categoryId: "daily",
    title: "Supplication When Afflicted by Calamity",
    arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ اللَّهُمَّ أْجُرْنِى فِى مُصِيبَتِى وَأَخْلِفْ لِى خَيْرًا مِنْهَا",
    transliteration:
      "inna lillahi wa inna ilayhi raji'un. allahumma'jurni fi musibati wa akhlif li khayran minha",
    translation:
      "Indeed we belong to Allah, and indeed to Him we will return. O Allah, reward me for my affliction and replace it with something better.",
    virtues:
      "A servant should recite the supplication above when afflicted by calamity with certainty and hope. Insha Allah, with this, they will receive a better replacement.",
    reference: "HR. Muslim",
  },
  {
    id: "daily-supplication-when-in-debt",
    categoryId: "daily",
    title: "Supplication When in Debt",
    arabic: "اللَّهُمَّ اكْفِنِى بِحَلاَلِكَ عَنْ حَرَامِكَ وَأَغْنِنِى بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    transliteration: "allahummakfini bi halalika 'an haramik, wa aghnini bi fadlika 'amman siwak",
    translation:
      "O Allah, suffice me with what is lawful and keep me away from what is unlawful, and enrich me with Your bounty so I do not depend on anyone besides You.",
    virtues: "Lawful provision, even if it is little, is better than abundant unlawful wealth.",
    reference: "HR. at-Tirmidzi No. 2563",
  },
  {
    id: "daily-supplication-for-protection-from-laziness-sadnes",
    categoryId: "daily",
    title: "Supplication for Protection from Laziness, Sadness, and Debt",
    arabic:
      "اَللّٰهُمَّ إِنِّى أَعُوْذُبِكَ مِنَ الْهَمِّ وَالْحَزْنِ وَأَعُوْذُبِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَأَعُوْذُبِكَ مِنَ الْجُبْنِ وَالْبُخْلِ وَأَعُوْذُبِكَ مِنْ غَلَبَتِ الدَّيْنِ وَقَهْرِ الرجال",
    transliteration:
      "allahumma inni a'udhu bika minal-hammi wal-hazan. wa a'udhu bika minal-'ajzi wal-kasal. wa a'udhu bika minal-jubni wal-bukhl. wa a'udhu bika min ghalabatid-dayni wa qahrir-rijal",
    translation:
      "O Allah, I seek refuge in You from anxiety and grief, and I seek refuge in You from incapacity and laziness, and I seek refuge in You from cowardice and miserliness, and I seek refuge in You from being overpowered by debt and from being overcome by men.",
    virtues:
      "Abu Umamah then narrated: After I practiced this supplication, Allah truly removed my anxiety and gave me the ability to repay my debt.",
    reference: "HR. Abu Dawud No. 1555",
  },
  {
    id: "daily-supplication-after-sneezing",
    categoryId: "daily",
    title: "Supplication After Sneezing",
    arabic: "الحَمْدُ للهِ",
    transliteration: "alhamdulillah",
    translation: "All praise is to Allah.",
    virtues:
      "Indeed, Allah loves sneezing because it moves a person to worship. It is encouraged to respond to the praise of Allah by someone who praises Allah, and vice versa.",
    reference: "HR. al-Bukhari",
  },
  {
    id: "daily-supplication-upon-hearing-someone-sneeze",
    categoryId: "daily",
    title: "Supplication Upon Hearing Someone Sneeze",
    arabic: "يَرْحَمُكَ اللهُ",
    transliteration: "yarhamukallah",
    translation: "May Allah have mercy on you.",
    virtues:
      "Indeed, Allah loves sneezing because it moves a person to worship. It is encouraged to respond to the praise of Allah by someone who praises Allah, and vice versa.",
    reference: "HR. al-Bukhari",
  },
  {
    id: "daily-response-to-someone-who-says-yarhamukallah-after",
    categoryId: "daily",
    title: "Response to Someone Who Says 'Yarhamukallah' After You Sneeze",
    arabic: "يَهْدِيكُمُ اللهُ وَيُصْلِحُ بَالَكُمْ",
    transliteration: "yahdikumullah wa yuslihu balakum",
    translation: "May Allah guide you and improve your condition.",
    virtues:
      "Indeed, Allah loves sneezing because it moves a person to worship. It is encouraged to respond to the praise of Allah by someone who praises Allah, and vice versa.",
    reference: "HR. al-Bukhari",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/189hm.mp3",
  },
  {
    id: "daily-supplication-for-good-character",
    categoryId: "daily",
    title: "Supplication for Good Character",
    arabic: "اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
    transliteration: "allahumma kama hassanta khalqi fahassin khuluqi",
    translation:
      "O Allah, just as You have made my external form good, make my character good as well.",
    virtues:
      "A charming appearance is not enough provision for a Muslim, but it must be accompanied by noble character. Therefore, a Muslim should constantly ask for their character to be improved and beautified.",
    reference: "HR. Ahmad, authenticated by al-Albani in al-Irwa', 1/115",
  },
  {
    id: "daily-prayer-for-protection-from-satan",
    categoryId: "daily",
    title: "Prayer for Protection from Satan",
    arabic: "رَبِّ أَعُوْذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِيْنِ وَأَعُوْذُ بِكَ رَبِّ أَنْ يَحْضُرُوْنِ",
    transliteration: "rabbi a'udhu bika min hamazatish-shayatin wa a'udhu bika rabbi ay-yahdurun",
    translation:
      "My Lord, I seek refuge in You from the whispers of Satan, and I seek refuge in You, my Lord, from their presence around me.",
    reference: "QS. Al-Mu'minun: 97-98",
  },
  {
    id: "daily-prayer-after-the-adhan",
    categoryId: "daily",
    title: "Prayer After the Adhan",
    arabic:
      "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ، وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ، وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    transliteration:
      "allahumma rabba hadhihid-da'watit-tammah, was-salatil-qa'imah, ati muhammadanil-wasilata wal-fadilah, wab'ath-hu maqaman mahmudanilladhi wa'adtah",
    translation:
      "O Allah, Lord of this perfect call and the established prayer, grant Muhammad the wasilah (a high status in Paradise) and the excellence (above all creation), and raise him to the praiseworthy station that You have promised him.",
    reference: "Narrated by Abu Dawud (529), at-Tirmidhi (211), an-Nasa'i (2:26), Ibn Majah (722)",
  },
  {
    id: "daily-prayer-for-forgiveness-for-parents",
    categoryId: "daily",
    title: "Prayer for Forgiveness for Parents",
    arabic: "رَبَّنَا ٱغْفِرْ لِى وَلِوَٰلِدَىَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ ٱلْحِسَابُ",
    transliteration: "rabbanaghfir li wa liwalidayya wa lil-mu'minina yawma yaqumul-hisab",
    translation:
      "Our Lord, forgive me and my parents and all the believers on the Day the account is established.",
    reference: "QS. Ibrahim: 41",
  },
  {
    id: "sunnah-dua-to-make-heart-firm-upon-deen-1",
    categoryId: "sunnah",
    title: "Dua To Make Heart Firm Upon Deen #1",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِى عَلَى دِينِكَ",
    transliteration: "ya muqallibal-qulubi thabbit qalbi 'ala dinik",
    translation: "O Changer of the hearts, make my heart firm upon Your religion.",
    reference: "HR. at-Tirmidzi, No. 3522 and Ahmad, 6: 315",
  },
  {
    id: "sunnah-dua-to-make-heart-firm-upon-deen-2",
    categoryId: "sunnah",
    title: "Dua To Make Heart Firm Upon Deen #2",
    arabic: "اللَّهُمَّ مُصَرِّفَ الْقُلُوبِ صَرِّفْ قُلُوبَنَا عَلَى طَاعَتِكَ",
    transliteration: "allahumma musarrifal-qulubi sarrif qulubana 'ala ta'atik",
    translation: "O Allah! Controller of the hearts, direct our hearts to Your obedience.",
    reference: "HR. Muslim No. 2654",
  },
  {
    id: "sunnah-dua-to-make-heart-firm-upon-deen-3",
    categoryId: "sunnah",
    title: "Dua To Make Heart Firm Upon Deen #3",
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا",
    transliteration: "rabbana la tuzigh qulubana ba'da idh hadaytana",
    translation: "O our Lord, do not make our hearts incline to error after You have guided us.",
    reference: "QS. Ali Imran: 8",
  },
  {
    id: "sunnah-dua-to-seek-refuge-against-the-loss-of-pleasure",
    categoryId: "sunnah",
    title: "Dua To Seek Refuge Against The Loss Of Pleasure",
    arabic: "اللَّهُمَّ إِنِّى أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ وَتَحَوُّلِ عَافِيَتِكَ وَفُجَاءَةِ نِقْمَتِكَ وَجَمِيعِ سَخَطِكَ",
    transliteration:
      "allahumma inni a'udhu bika min zawali ni'matik, wa tahawwuli 'afiyatik, wa fuja'ati niqmatik, wa jami'i sakhatik",
    translation:
      "O Allah, I seek refuge in You from the loss of the pleasures that You have bestowed, from changes in the health that You have bestowed, from Your sudden torment, and from all Your wrath.",
    reference: "HR. Muslim No. 2739",
  },
  {
    id: "sunnah-dua-to-resist-affliction",
    categoryId: "sunnah",
    title: "Dua To Resist Affliction",
    arabic: "اللَّهُمَّ إِنِّي أَعُوْذُ بِكَ مِنْ جَهْدِ البَلاَءِ ، وَدَرَكِ الشَّقَاءِ ، وَسُوءِ القَضَاءِ ، وَشَمَاتَةِ الأَعْدَاء",
    transliteration:
      "allahumma inni a'udhu bika min jahdil-bala', wa darakish-shaqa', wa su'il-qada', wa shamatatil-a'da'",
    translation:
      "O Allah, I seek refuge in You from severe calamity, being overtaken by misery, evil destiny, and the triumphant mockery of enemies.",
    reference: "HR. al-Bukhari: 6616, Muslim: 2707",
  },
  {
    id: "sunnah-dua-when-getting-good-news",
    categoryId: "sunnah",
    title: "Dua When Getting Good News",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِى بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
    transliteration: "alhamdu lillahi alladhi bini'matihi tattimmu assalihat",
    translation: "Praise be to Allah, by whose grace goodness is perfected.",
    reference: "HR. Ibn Majah in the Sunan, No. 3803 and al-Hakim in al-Mustadrak (1/499)",
  },
];

export function duasByCategory(categoryId: DuaCategoryId): DuaItem[] {
  return DUA_ITEMS.filter((item) => item.categoryId === categoryId);
}

export function getDuaById(id: string): DuaItem | undefined {
  return DUA_ITEMS.find((item) => item.id === id);
}
