import type { DuaCategoryId, DuaItem } from "../types/index";

export const DUA_CONTENT_VERSION = 2;

export const DUA_CATEGORY_LABELS: Record<DuaCategoryId, string> = {
  sunnah: "Sunnah Duas",
  quranic: "Quranic Duas",
  daily: "Daily Duas",
};

/**
 * Curated supplications. Generated by
 * apps/app/scripts/build-data/build-adhkar.mjs — do not edit by hand.
 */
export const DUA_ITEMS: DuaItem[] = [
  {
    id: "quranic-hasanah",
    categoryId: "quranic",
    title: "Good in this world and the next",
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    transliteration:
      "Rabbana atina fid-dunya hasanah, wa fil-akhirati hasanah, wa qina 'adhaban-nar",
    translation:
      "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
    reference: "Quran 2:201",
  },
  {
    id: "quranic-ilma",
    categoryId: "quranic",
    title: "Increase me in knowledge",
    arabic: "رَبِّ زِدْنِي عِلْمًا",
    transliteration: "Rabbi zidni 'ilma",
    translation: "My Lord, increase me in knowledge.",
    reference: "Quran 20:114",
  },
  {
    id: "quranic-sabr",
    categoryId: "quranic",
    title: "Patience and steadfastness",
    arabic: "رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا",
    transliteration: "Rabbana afrigh 'alayna sabran wa thabbit aqdamana",
    translation: "Our Lord, pour upon us patience and make firm our footing.",
    reference: "Quran 2:250",
  },
  {
    id: "quranic-light",
    categoryId: "quranic",
    title: "Light and forgiveness",
    arabic: "رَبَّنَا أَتْمِمْ لَنَا نُورَنَا وَاغْفِرْ لَنَا إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Rabbana atmim lana nurana waghfir lana innaka 'ala kulli shay'in qadir",
    translation:
      "Our Lord, perfect for us our light and forgive us; indeed You are over all things competent.",
    reference: "Quran 66:8",
  },
  {
    id: "quranic-tawakkul",
    categoryId: "quranic",
    title: "Reliance upon Allah",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    transliteration: "Hasbunallahu wa ni'mal-wakil",
    translation: "Allah is sufficient for us, and He is the best disposer of affairs.",
    reference: "Quran 3:173",
  },
  {
    id: "quranic-dhun-nun",
    categoryId: "quranic",
    title: "The supplication of Yunus",
    arabic: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimin",
    translation: "There is no god but You; glory be to You. Indeed, I have been of the wrongdoers.",
    virtues: "No Muslim supplicates with it for anything but Allah answers him.",
    reference: "Quran 21:87 · Tirmidhi",
  },
  {
    id: "sunnah-huda-tuqa",
    categoryId: "sunnah",
    title: "Guidance and contentment",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    transliteration: "Allahumma inni as'aluka al-huda wat-tuqa wal-'afafa wal-ghina",
    translation: "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency.",
    reference: "Muslim",
  },
  {
    id: "sunnah-hamm-hazan",
    categoryId: "sunnah",
    title: "Relief from anxiety and grief",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan",
    translation: "O Allah, I seek refuge in You from anxiety and grief.",
    reference: "Bukhari",
  },
  {
    id: "sunnah-afiyah",
    categoryId: "sunnah",
    title: "Well-being in body and faith",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    transliteration: "Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah",
    translation: "O Allah, I ask You for well-being in this world and the Hereafter.",
    reference: "Ibn Majah",
  },
  {
    id: "sunnah-dhikr-shukr",
    categoryId: "sunnah",
    title: "Help to remember and thank Allah",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation:
      "O Allah, help me to remember You, to thank You, and to worship You in the best manner.",
    virtues: "The Prophet ﷺ advised Mu'adh never to leave this after every prayer.",
    reference: "Abu Dawud & An-Nasa'i",
  },
  {
    id: "sunnah-thabbit-qalbi",
    categoryId: "sunnah",
    title: "Make my heart firm upon Your religion",
    arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَىٰ دِينِكَ",
    transliteration: "Ya muqallibal-qulub thabbit qalbi 'ala dinik",
    translation: "O Turner of the hearts, make my heart firm upon Your religion.",
    reference: "Tirmidhi",
  },
  {
    id: "daily-before-eating",
    categoryId: "daily",
    title: "Before eating",
    arabic: "بِسْمِ اللَّهِ",
    transliteration: "Bismillah",
    translation: "In the name of Allah.",
    reference: "Abu Dawud",
  },
  {
    id: "daily-after-eating",
    categoryId: "daily",
    title: "After eating",
    arabic: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration:
      "Alhamdu lillahilladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation:
      "All praise is for Allah who fed me this and provided it for me without any might or power on my part.",
    virtues: "Whoever says it after eating has his past sins forgiven.",
    reference: "Abu Dawud & Tirmidhi",
  },
  {
    id: "daily-leaving-home",
    categoryId: "daily",
    title: "Leaving the home",
    arabic: "بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    translation:
      "In the name of Allah, I place my trust in Allah; there is no might nor power except with Allah.",
    reference: "Abu Dawud & Tirmidhi",
  },
  {
    id: "daily-entering-home",
    categoryId: "daily",
    title: "Entering the home",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَىٰ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'ala Rabbina tawakkalna",
    translation:
      "In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we place our trust.",
    reference: "Abu Dawud",
  },
  {
    id: "daily-travel",
    categoryId: "daily",
    title: "Travel",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ",
    transliteration: "Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin",
    translation:
      "Glory to Him who has subjected this to us, and we could not have done it by ourselves.",
    reference: "Quran 43:13 · Muslim",
  },
  {
    id: "daily-entering-masjid",
    categoryId: "daily",
    title: "Entering the masjid",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahummaftah li abwaba rahmatik",
    translation: "O Allah, open for me the gates of Your mercy.",
    reference: "Muslim",
  },
  {
    id: "daily-distress",
    categoryId: "daily",
    title: "In times of distress",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "La ilaha illallahul-'Azimul-Halim, la ilaha illallahu Rabbul-'Arshil-'Azim",
    translation:
      "There is no god but Allah, the Magnificent, the Forbearing; there is no god but Allah, Lord of the Magnificent Throne.",
    virtues: "The Prophet ﷺ would say it in times of distress.",
    reference: "Bukhari & Muslim",
  },
];

export function duasByCategory(categoryId: DuaCategoryId): DuaItem[] {
  return DUA_ITEMS.filter((item) => item.categoryId === categoryId);
}

export function getDuaById(id: string): DuaItem | undefined {
  return DUA_ITEMS.find((item) => item.id === id);
}
