import type { DurudItem } from "../types/index";

export const DUROOD_CONTENT_VERSION = 6;

/**
 * Duroods and salawat upon the Prophet ﷺ. Generated by
 * apps/app/scripts/build-data/build-adhkar.mjs — do not edit by hand.
 */
export const DUROOD_ITEMS: DurudItem[] = [
  {
    id: "durood-ibrahim",
    title: "Durood Ibrahim",
    arabic:
      "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ اللَّهُمَّ بَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
    transliteration:
      "Allahumma salli 'ala Muhammadin wa 'ala aali Muhammad, kama sallayta 'ala Ibrahim wa 'ala aali Ibrahim, innaka Hamidun Majid. Allahumma barik 'ala Muhammadin wa 'ala aali Muhammad, kama barakta 'ala Ibrahim wa 'ala aali Ibrahim, innaka Hamidun Majid",
    translation:
      "O Allah, send blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim; indeed You are Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim; indeed You are Praiseworthy, Glorious.",
    translations: {
      bn: "হে আল্লাহ! আপনি (আপনার নিকটস্থ উচ্চসভায়) মুহাম্মাদকে সম্মানের সাথে স্মরণ করুন এবং তাঁর পরিবার-পরিজনকে, যেমন আপনি সম্মানের সাথে স্মরণ করেছেন ইবরাহীমকে ও তাঁর পরিবার-পরিজনদেরকে। নিশ্চয় আপনি অত্যন্ত প্রশংসিত ও মহামহিমান্বিত। হে আল্লাহ! আপনি মুহাম্মাদ ও তাঁর পরিবার পরিজনের উপর বরকত নাযিল করুন যেমন আপনি বরকত নাযিল করেছিলেন ইবরাহীম ও তাঁর পরিবার-পরিজনের উপর। নিশ্চয় আপনি অত্যন্ত প্রশংসিত ও মহামহিমান্বিত",
    },
    virtues:
      "Recited in every prayer; the most complete form of sending blessings on the Prophet ﷺ.",
    reference: "Bukhari & Muslim",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/53hm.mp3",
  },
  {
    id: "durood-short",
    title: "Short Salawat",
    arabic: "اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَىٰ نَبِيِّنَا مُحَمَّدٍ",
    transliteration: "Allahumma salli wa sallim 'ala Nabiyyina Muhammad",
    translation: "O Allah, send blessings and peace upon our Prophet Muhammad.",
    translations: { bn: "হে আল্লাহ! আপনি সালাত ও সালাম পেশ করুন আমাদের নবী মুহাম্মাদের উপর।" },
    virtues: "Whoever sends blessings once, Allah sends ten upon him.",
    reference: "Muslim",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/98hm.mp3",
  },
  {
    id: "durood-salli-ala",
    title: "Salli 'ala Muhammad",
    arabic: "صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ",
    transliteration: "Sallallahu 'alayhi wa sallam",
    translation: "May Allah send blessings and peace upon him.",
    virtues: "Said upon hearing the name of the Prophet ﷺ.",
    reference: "Tirmidhi",
  },
  {
    id: "durood-afdal",
    title: "Blessings and peace",
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ عَبْدِكَ وَرَسُولِكَ وَصَلِّ عَلَى الْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ",
    transliteration:
      "Allahumma salli 'ala Muhammadin 'abdika wa rasulika, wa salli 'alal-mu'minina wal-mu'minat",
    translation:
      "O Allah, send blessings upon Muhammad, Your servant and messenger, and upon the believing men and women.",
    reference: "Bukhari",
  },
  {
    id: "durood-hisn-219",
    title: "Salawat upon the Prophet ﷺ (1)",
    arabic: "قَالَ ﷺ: «مَنْ صَلَّ عَلَيَّ صَلاةً صَلَّ اللهُ عَلَيْهِ بِهَا عَشَراً»",
    translation:
      "The Prophet (salla Allaahu ʻalayhi wa salaam) said: 'Whoever sends a prayer upon me, Allah sends ten upon him.'",
    reference: "Muslim [408](1/288).",
  },
  {
    id: "durood-hisn-220",
    title: "Salawat upon the Prophet ﷺ (2)",
    arabic: "قَالَ ﷺ: «لا تَجْعَلُوا قَبْرِيْ عِيْداً وَ صَلُّوا عَلَيَّ فَإِنَّ صَلاتَكُمْ تَبْلُغُنِي حَيْثُ كُنْتُمْ»",
    translation:
      "The Prophet (salla Allaahu ʻalayhi wa salaam) said: 'Do not take my grave as a place of habitual ceremony. Send prayers upon me, for verily your prayers reach me wherever you are.'",
    reference:
      "Abû Dâwud [2042](2/218) and Aĥmad (2/367). Al-Albânî authenticated it in Ŝaĥîĥ Abû Dâwud (2/383).",
  },
  {
    id: "durood-hisn-221",
    title: "Salawat upon the Prophet ﷺ (3)",
    arabic: "قَالَ ﷺ: «البَخِيْلُ مَنْ ذُكِرْتُ عِنْدَهُ فَلَمْ يُصَلِّ عَلَيَّ»",
    translation:
      "The Prophet (salla Allaahu ʻalayhi wa salaam) said : 'A miser is one whom when I am mentioned to him, fails to send prayers upon me.'",
    reference:
      "At-Tirmidhî [3546](5/551). Also see Ŝaĥîĥ Al-Jâmi' [2787](3/25) and Ŝaĥîĥ At-Tirmidhî (3/177).",
  },
  {
    id: "durood-hisn-222",
    title: "Salawat upon the Prophet ﷺ (4)",
    arabic: "قَالَ ﷺ: «إنَّ لِلَّهِ مَلائِكَةً سَيَّا حِيْنَ فِي الأرْضِ، يُبَلِّغُونِي مِنْ أُمَّتِي السَّلامَ»",
    translation:
      "The Prophet (salla Allaahu ʻalayhi wa salaam) said: 'Allah exalted He is has got angels scouring the earth to spread the salutations of my community.'",
    reference:
      "An-Nisâ'i (3/43) and Al-Hâkim (2/421). Al-Albânî authenticated it in Ŝaĥîĥ An-Nisâ'i (1/274).",
  },
  {
    id: "durood-hisn-223",
    title: "Salawat upon the Prophet ﷺ (5)",
    arabic: "قَالَ ﷺ: «مَا مِنْ أحَدٍ يُسَلِّمُ عَلَيَّ، إلَّا رَدَّ اللهُ عَلَيَّ رُوْحي، حَتَّى أرُدَّ عَلَيْهِ السَّلامَ»",
    translation:
      "The Prophet (salla Allaahu ʻalayhi wa salaam) said: 'Every time somebody greets me, Allah gives me back my soul for me to answer this greeting.'",
    reference: "Abû Dâwud (2041). Al-Albânî declared it Ĥasan in Ŝaĥîĥ Abû Dâwud (1/283).",
  },
];

export function getDurudById(id: string): DurudItem | undefined {
  return DUROOD_ITEMS.find((item) => item.id === id);
}
