import type { LastDayTimelineEvent } from "../types/last-day";

/** Chronological journey from life through eternity — centerpiece of the module. */
export const LAST_DAY_TIMELINE: LastDayTimelineEvent[] = [
  {
    id: "life",
    order: 1,
    title: "Life in this world",
    body: "A brief appointed time to believe, worship, and prepare. This world is not the final home — it is the field of deeds.",
  },
  {
    id: "death",
    order: 2,
    title: "Death",
    body: "Every soul will taste death. The believer meets it with hope in Allah's mercy; heedlessness makes it sudden and bitter.",
    topicId: "death",
  },
  {
    id: "grave",
    order: 3,
    title: "The grave",
    body: "After burial, the soul enters barzakh. The grave is the first stage of the Hereafter for every person.",
    topicId: "barzakh",
  },
  {
    id: "barzakh",
    order: 4,
    title: "Barzakh",
    body: "Life between death and resurrection — questioning, bliss, or punishment according to authentic reports.",
    topicId: "barzakh",
  },
  {
    id: "minor-signs",
    order: 5,
    title: "Minor signs",
    body: "Gradual social and moral changes the Prophet ﷺ described. Many scholars note several have appeared; exact timing belongs to Allah alone.",
    topicId: "minor-signs",
    signType: "minor",
  },
  {
    id: "major-signs",
    order: 6,
    title: "Major signs",
    body: "Dramatic events near the end — including al-Mahdi, the Dajjal, and the return of 'Isa (peace be upon him) in authentic hadith. Sequence details differ among scholars.",
    topicId: "major-signs",
    signType: "major",
  },
  {
    id: "trumpet",
    order: 7,
    title: "The Trumpet",
    body: "Israfil will blow the trumpet. Creation dies at the first blast and is resurrected at the second.",
    topicId: "trumpet",
  },
  {
    id: "resurrection",
    order: 8,
    title: "Resurrection",
    body: "Bodies restored from dust; all of creation stands before Allah.",
    topicId: "resurrection",
  },
  {
    id: "gathering",
    order: 9,
    title: "The Gathering (Mahshar)",
    body: "All people assembled barefoot, naked, and uncircumcised — as Allah wills — awaiting judgment.",
    topicId: "gathering",
  },
  {
    id: "record",
    order: 10,
    title: "The Record of Deeds",
    body: "Books given in the right hand, left hand, or behind the back. Nothing omitted from what was recorded.",
    topicId: "record-of-deeds",
  },
  {
    id: "scale",
    order: 11,
    title: "The Scale (Mizan)",
    body: "Deeds weighed with perfect justice. Heavy scales bring joy; light scales bring loss.",
    topicId: "scale",
  },
  {
    id: "questioning",
    order: 12,
    title: "Accountability (Hisab)",
    body: "Easy reckoning for some; detailed questioning for others. Rights owed to people are not overlooked.",
    topicId: "accountability",
  },
  {
    id: "intercession",
    order: 13,
    title: "Intercession (Shafa'ah)",
    body: "By Allah's permission only — the greatest belongs to Prophet Muhammad ﷺ.",
    topicId: "intercession",
  },
  {
    id: "hawd",
    order: 14,
    title: "The Pond (Hawd)",
    body: "A vast basin from which the Prophet's ﷺ ummah drinks on the Day of Resurrection.",
    topicId: "hawd",
  },
  {
    id: "sirat",
    order: 15,
    title: "The Bridge (Sirat)",
    body: "Every person crosses over Hell — speed varies by faith and deeds in authentic narrations.",
    topicId: "sirat",
  },
  {
    id: "paradise-hell",
    order: 16,
    title: "Paradise or Hell",
    body: "Eternal abode — Jannah by Allah's mercy and righteous deeds; Jahannam as a true warning and just consequence.",
    topicId: "paradise",
  },
  {
    id: "eternity",
    order: 17,
    title: "Eternity",
    body: "No death after the Hereafter. The people of Paradise remain forever in bliss; the people of Hell remain as Allah has willed.",
  },
];
