import type { LearnDuaOccasion } from "../types/learn-dua";

/** Browse-by-occasion index linking to Learn Dua topics or bundled duas. */
export const LEARN_DUA_OCCASIONS: LearnDuaOccasion[] = [
  {
    id: "morning",
    title: "Morning adhkar",
    summary: "Start the day with remembrance",
    topicId: "morning-evening",
    category: "daily",
  },
  {
    id: "evening",
    title: "Evening adhkar",
    summary: "Protection before night",
    topicId: "morning-evening",
    category: "daily",
  },
  {
    id: "wake",
    title: "After waking",
    summary: "First words upon waking",
    topicId: "wake-sleep",
    category: "daily",
  },
  {
    id: "sleep",
    title: "Before sleep",
    summary: "Duas and adhkar for the night",
    topicId: "wake-sleep",
    category: "daily",
  },
  {
    id: "enter-home",
    title: "Entering home",
    summary: "Bismillah and greeting",
    topicId: "home-mosque",
    category: "daily",
  },
  {
    id: "leave-home",
    title: "Leaving home",
    summary: "Tawakkul when going out",
    topicId: "home-mosque",
    category: "daily",
  },
  {
    id: "mosque",
    title: "Mosque",
    summary: "Entering and leaving the masjid",
    topicId: "home-mosque",
    category: "daily",
  },
  {
    id: "eating",
    title: "Before & after food",
    summary: "Gratitude at meals",
    topicId: "eating",
    category: "daily",
  },
  {
    id: "wudu-dua",
    title: "Wudu",
    summary: "Before and after ablution",
    topicId: "wudu-prayer",
    category: "daily",
  },
  {
    id: "salah-dua",
    title: "Prayer",
    summary: "Before, during, and after salah",
    topicId: "wudu-prayer",
    category: "daily",
  },
  {
    id: "anxiety",
    title: "Anxiety & worry",
    summary: "Calm the heart with du'a",
    topicId: "anxiety-sadness",
    category: "situational",
  },
  {
    id: "illness",
    title: "Illness",
    summary: "Healing and patience",
    topicId: "illness-fear",
    category: "situational",
  },
  {
    id: "forgiveness",
    title: "Forgiveness",
    summary: "Istighfar and repentance",
    topicId: "forgiveness-guidance",
    category: "situational",
  },
  {
    id: "travel",
    title: "Travel",
    summary: "Setting out and returning",
    topicId: "travel-rain",
    category: "situational",
  },
  {
    id: "rizq",
    title: "Provision",
    summary: "Asking Allah for halal rizq",
    topicId: "rizq-family",
    category: "situational",
  },
  {
    id: "quranic",
    title: "Qur'anic duas",
    summary: "Supplications from the Book of Allah",
    topicId: "quranic-duas",
    category: "quranic",
  },
];
