import type { NameOfAllah } from "../types/index";

export const NAMES_CONTENT_VERSION = 3;

/**
 * The 99 names of Allah (Asma-ul-Husna), following the standard Tirmidhi
 * enumeration. Arabic is preserved verbatim; transliterations and meanings
 * follow widely published renderings.
 *
 * Generated by apps/app/scripts/build-data/build-names.mjs — do not edit by hand.
 */
export const NAMES_OF_ALLAH: NameOfAllah[] = [
  {
    id: "ar-rahman",
    arabic: "الرَّحْمَٰن",
    transliteration: "Ar-Rahman",
    translation: "The Most Gracious",
    meaning: "The One whose mercy embraces all creation.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/01_ar_rahman.mp3",
  },
  {
    id: "ar-rahim",
    arabic: "الرَّحِيم",
    transliteration: "Ar-Rahim",
    translation: "The Most Merciful",
    meaning: "The One who is especially merciful to the believers.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/02_ar_rahim.mp3",
  },
  {
    id: "al-malik",
    arabic: "الْمَلِك",
    transliteration: "Al-Malik",
    translation: "The King",
    meaning: "The Sovereign owner of all dominion.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/03_al_malik.mp3",
  },
  {
    id: "al-quddus",
    arabic: "الْقُدُّوس",
    transliteration: "Al-Quddus",
    translation: "The Most Holy",
    meaning: "The One pure and free from every imperfection.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/04_al_quddus.mp3",
  },
  {
    id: "as-salam",
    arabic: "السَّلَام",
    transliteration: "As-Salam",
    translation: "The Source of Peace",
    meaning: "The One free of all flaws, the giver of peace.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/05_as_salam.mp3",
  },
  {
    id: "al-mumin",
    arabic: "الْمُؤْمِن",
    transliteration: "Al-Mu'min",
    translation: "The Guardian of Faith",
    meaning: "The One who grants security and confirms His signs.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/06_al_mumin.mp3",
  },
  {
    id: "al-muhaymin",
    arabic: "الْمُهَيْمِن",
    transliteration: "Al-Muhaymin",
    translation: "The Protector",
    meaning: "The Guardian who watches over and preserves all things.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/07_al_muhaymin.mp3",
  },
  {
    id: "al-aziz",
    arabic: "الْعَزِيز",
    transliteration: "Al-Aziz",
    translation: "The Almighty",
    meaning: "The Mighty, invincible and ever-dominant.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/08_al_aziz.mp3",
  },
  {
    id: "al-jabbar",
    arabic: "الْجَبَّار",
    transliteration: "Al-Jabbar",
    translation: "The Compeller",
    meaning: "The One who mends and whose will always prevails.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/09_al_jabbar.mp3",
  },
  {
    id: "al-mutakabbir",
    arabic: "الْمُتَكَبِّر",
    transliteration: "Al-Mutakabbir",
    translation: "The Supreme",
    meaning: "The One who is justly proud of His greatness.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/10_al_mutakabbir.mp3",
  },
  {
    id: "al-khaliq",
    arabic: "الْخَالِق",
    transliteration: "Al-Khaliq",
    translation: "The Creator",
    meaning: "The One who brings all things into existence from nothing.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/11_al_khaliq.mp3",
  },
  {
    id: "al-bari",
    arabic: "الْبَارِئ",
    transliteration: "Al-Bari'",
    translation: "The Maker",
    meaning: "The Originator who fashions creation free of fault.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/12_al_bari.mp3",
  },
  {
    id: "al-musawwir",
    arabic: "الْمُصَوِّر",
    transliteration: "Al-Musawwir",
    translation: "The Fashioner",
    meaning: "The One who gives everything its distinct form.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/13_al_musawwir.mp3",
  },
  {
    id: "al-ghaffar",
    arabic: "الْغَفَّار",
    transliteration: "Al-Ghaffar",
    translation: "The Ever-Forgiving",
    meaning: "The One who forgives again and again.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/14_al_ghaffar.mp3",
  },
  {
    id: "al-qahhar",
    arabic: "الْقَهَّار",
    transliteration: "Al-Qahhar",
    translation: "The Subduer",
    meaning: "The Dominant One who prevails over all.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/15_al_qahhar.mp3",
  },
  {
    id: "al-wahhab",
    arabic: "الْوَهَّاب",
    transliteration: "Al-Wahhab",
    translation: "The Bestower",
    meaning: "The One who gives freely without expecting return.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/16_al_wahhab.mp3",
  },
  {
    id: "ar-razzaq",
    arabic: "الرَّزَّاق",
    transliteration: "Ar-Razzaq",
    translation: "The Provider",
    meaning: "The Sustainer who provides for all creation.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/17_ar_razzaq.mp3",
  },
  {
    id: "al-fattah",
    arabic: "الْفَتَّاح",
    transliteration: "Al-Fattah",
    translation: "The Opener",
    meaning: "The One who opens what is closed and grants victory.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/18_al_fattah.mp3",
  },
  {
    id: "al-alim",
    arabic: "الْعَلِيم",
    transliteration: "Al-'Alim",
    translation: "The All-Knowing",
    meaning: "The One whose knowledge encompasses everything.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/19_al_alim.mp3",
  },
  {
    id: "al-qabid",
    arabic: "الْقَابِض",
    transliteration: "Al-Qabid",
    translation: "The Withholder",
    meaning: "The One who withholds provision by His wisdom.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/20_al_qabid.mp3",
  },
  {
    id: "al-basit",
    arabic: "الْبَاسِط",
    transliteration: "Al-Basit",
    translation: "The Extender",
    meaning: "The One who extends provision and mercy generously.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/21_al_basit.mp3",
  },
  {
    id: "al-khafid",
    arabic: "الْخَافِض",
    transliteration: "Al-Khafid",
    translation: "The Abaser",
    meaning: "The One who lowers the arrogant and disbelieving.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/22_al_khafid.mp3",
  },
  {
    id: "ar-rafi",
    arabic: "الرَّافِع",
    transliteration: "Ar-Rafi'",
    translation: "The Exalter",
    meaning: "The One who raises the humble and faithful.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/23_ar_rafi.mp3",
  },
  {
    id: "al-muizz",
    arabic: "الْمُعِزّ",
    transliteration: "Al-Mu'izz",
    translation: "The Bestower of Honour",
    meaning: "The One who honours and strengthens whom He wills.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio24_24_al_muizz.mp3",
  },
  {
    id: "al-mudhill",
    arabic: "الْمُذِلّ",
    transliteration: "Al-Mudhill",
    translation: "The Humiliator",
    meaning: "The One who abases whom He wills by His justice.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio25_25_al_mudhill.mp3",
  },
  {
    id: "as-sami",
    arabic: "السَّمِيع",
    transliteration: "As-Sami'",
    translation: "The All-Hearing",
    meaning: "The One who hears all, secret and manifest.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio26_26_as_sami.mp3",
  },
  {
    id: "al-basir",
    arabic: "الْبَصِير",
    transliteration: "Al-Basir",
    translation: "The All-Seeing",
    meaning: "The One who sees all things without limit.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio27_27_al_basir.mp3",
  },
  {
    id: "al-hakam",
    arabic: "الْحَكَم",
    transliteration: "Al-Hakam",
    translation: "The Judge",
    meaning: "The Arbitrator whose judgement none can overturn.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio28_28_al_hakam.mp3",
  },
  {
    id: "al-adl",
    arabic: "الْعَدْل",
    transliteration: "Al-'Adl",
    translation: "The Utterly Just",
    meaning: "The One who is perfectly just in all He does.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio29_29_al_adl.mp3",
  },
  {
    id: "al-latif",
    arabic: "اللَّطِيف",
    transliteration: "Al-Latif",
    translation: "The Subtle",
    meaning: "The Gentle One, kind and aware of the finest matters.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio30_30_al_latif.mp3",
  },
  {
    id: "al-khabir",
    arabic: "الْخَبِير",
    transliteration: "Al-Khabir",
    translation: "The All-Aware",
    meaning: "The One acquainted with the reality of everything.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio31_31_al_khabir.mp3",
  },
  {
    id: "al-halim",
    arabic: "الْحَلِيم",
    transliteration: "Al-Halim",
    translation: "The Forbearing",
    meaning: "The One who is patient and does not hasten to punish.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio32_32_al_halim.mp3",
  },
  {
    id: "al-azim",
    arabic: "الْعَظِيم",
    transliteration: "Al-'Azim",
    translation: "The Magnificent",
    meaning: "The One of absolute greatness and majesty.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio33_33_al_azim.mp3",
  },
  {
    id: "al-ghafur",
    arabic: "الْغَفُور",
    transliteration: "Al-Ghafur",
    translation: "The Forgiving",
    meaning: "The One who forgives abundantly.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio34_34_al_ghafur.mp3",
  },
  {
    id: "ash-shakur",
    arabic: "الشَّكُور",
    transliteration: "Ash-Shakur",
    translation: "The Appreciative",
    meaning: "The One who rewards small good deeds greatly.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio35_35_ash_shakur.mp3",
  },
  {
    id: "al-aliyy",
    arabic: "الْعَلِيّ",
    transliteration: "Al-'Aliyy",
    translation: "The Most High",
    meaning: "The One exalted above all creation.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio36_36_al_ali.mp3",
  },
  {
    id: "al-kabir",
    arabic: "الْكَبِير",
    transliteration: "Al-Kabir",
    translation: "The Most Great",
    meaning: "The One greater than everything in majesty.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio37_37_al_kabir.mp3",
  },
  {
    id: "al-hafiz",
    arabic: "الْحَفِيظ",
    transliteration: "Al-Hafiz",
    translation: "The Preserver",
    meaning: "The One who protects and preserves all things.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio38_38_al_hafiz.mp3",
  },
  {
    id: "al-muqit",
    arabic: "الْمُقِيت",
    transliteration: "Al-Muqit",
    translation: "The Sustainer",
    meaning: "The One who nourishes and maintains all creatures.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio39_39_al_muqit.mp3",
  },
  {
    id: "al-hasib",
    arabic: "الْحَسِيب",
    transliteration: "Al-Hasib",
    translation: "The Reckoner",
    meaning: "The One who is sufficient and takes account of all.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio40_40_al_hasib.mp3",
  },
  {
    id: "al-jalil",
    arabic: "الْجَلِيل",
    transliteration: "Al-Jalil",
    translation: "The Majestic",
    meaning: "The One of true majesty and greatness.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio41_41_al_jalil.mp3",
  },
  {
    id: "al-karim",
    arabic: "الْكَرِيم",
    transliteration: "Al-Karim",
    translation: "The Most Generous",
    meaning: "The One of endless generosity and nobility.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio42_42_al_karim.mp3",
  },
  {
    id: "ar-raqib",
    arabic: "الرَّقِيب",
    transliteration: "Ar-Raqib",
    translation: "The Watchful",
    meaning: "The One who watches over and observes all.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio43_43_ar_raqib.mp3",
  },
  {
    id: "al-mujib",
    arabic: "الْمُجِيب",
    transliteration: "Al-Mujib",
    translation: "The Responsive",
    meaning: "The One who answers the call of those who ask.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio44_44_al_mujib.mp3",
  },
  {
    id: "al-wasi",
    arabic: "الْوَاسِع",
    transliteration: "Al-Wasi'",
    translation: "The All-Encompassing",
    meaning: "The Vast One whose knowledge and mercy have no bounds.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio45_45_al_wasi.mp3",
  },
  {
    id: "al-hakim",
    arabic: "الْحَكِيم",
    transliteration: "Al-Hakim",
    translation: "The All-Wise",
    meaning: "The One perfect in wisdom in all He decrees.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio46_46_al_hakim.mp3",
  },
  {
    id: "al-wadud",
    arabic: "الْوَدُود",
    transliteration: "Al-Wadud",
    translation: "The Loving",
    meaning: "The One loving to His servants and beloved to the righteous.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio47_47_al_wadud.mp3",
  },
  {
    id: "al-majid",
    arabic: "الْمَجِيد",
    transliteration: "Al-Majid",
    translation: "The Most Glorious",
    meaning: "The One of perfect glory and honour.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio48_48_al_majid.mp3",
  },
  {
    id: "al-baith",
    arabic: "الْبَاعِث",
    transliteration: "Al-Ba'ith",
    translation: "The Resurrector",
    meaning: "The One who raises the dead to life on Judgement Day.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio49_49_al_bayes.mp3",
  },
  {
    id: "ash-shahid",
    arabic: "الشَّهِيد",
    transliteration: "Ash-Shahid",
    translation: "The Witness",
    meaning: "The One who witnesses all that happens.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio50_50_ash_shahid.mp3",
  },
  {
    id: "al-haqq",
    arabic: "الْحَقّ",
    transliteration: "Al-Haqq",
    translation: "The Truth",
    meaning: "The One whose being and reality are absolute truth.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio51_51_al_haqq.mp3",
  },
  {
    id: "al-wakil",
    arabic: "الْوَكِيل",
    transliteration: "Al-Wakil",
    translation: "The Trustee",
    meaning: "The One entrusted with the affairs of all creation.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio52_52_al_wakil.mp3",
  },
  {
    id: "al-qawiyy",
    arabic: "الْقَوِيّ",
    transliteration: "Al-Qawiyy",
    translation: "The Most Strong",
    meaning: "The One of complete and perfect strength.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio53_53_al_qawi.mp3",
  },
  {
    id: "al-matin",
    arabic: "الْمَتِين",
    transliteration: "Al-Matin",
    translation: "The Firm",
    meaning: "The Steadfast One whose strength never wavers.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio54_54_al_matin.mp3",
  },
  {
    id: "al-waliyy",
    arabic: "الْوَلِيّ",
    transliteration: "Al-Waliyy",
    translation: "The Protecting Friend",
    meaning: "The Ally and guardian of the believers.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio55_55_al_wali.mp3",
  },
  {
    id: "al-hamid",
    arabic: "الْحَمِيد",
    transliteration: "Al-Hamid",
    translation: "The Praiseworthy",
    meaning: "The One deserving of all praise.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio56_56_al_hamid.mp3",
  },
  {
    id: "al-muhsi",
    arabic: "الْمُحْصِي",
    transliteration: "Al-Muhsi",
    translation: "The Enumerator",
    meaning: "The One who records and counts all things.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio57_57_al_muhsi.mp3",
  },
  {
    id: "al-mubdi",
    arabic: "الْمُبْدِئ",
    transliteration: "Al-Mubdi'",
    translation: "The Originator",
    meaning: "The One who begins creation without precedent.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio58_58_al_mubdi.mp3",
  },
  {
    id: "al-muid",
    arabic: "الْمُعِيد",
    transliteration: "Al-Mu'id",
    translation: "The Restorer",
    meaning: "The One who brings creation back after its end.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio59_59_al_muid.mp3",
  },
  {
    id: "al-muhyi",
    arabic: "الْمُحْيِي",
    transliteration: "Al-Muhyi",
    translation: "The Giver of Life",
    meaning: "The One who grants life to all living things.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio60_60_al_muhyi.mp3",
  },
  {
    id: "al-mumit",
    arabic: "الْمُمِيت",
    transliteration: "Al-Mumit",
    translation: "The Bringer of Death",
    meaning: "The One who ordains death for the living.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio61_61_al_mumit.mp3",
  },
  {
    id: "al-hayy",
    arabic: "الْحَيّ",
    transliteration: "Al-Hayy",
    translation: "The Ever-Living",
    meaning: "The One who lives eternally without end.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio62_62_al_hayy.mp3",
  },
  {
    id: "al-qayyum",
    arabic: "الْقَيُّوم",
    transliteration: "Al-Qayyum",
    translation: "The Self-Subsisting",
    meaning: "The One who sustains all while needing none.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio63_63_al_qayyum.mp3",
  },
  {
    id: "al-wajid",
    arabic: "الْوَاجِد",
    transliteration: "Al-Wajid",
    translation: "The Perceiver",
    meaning: "The One who lacks nothing and finds whatever He wills.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio64_64_al_wajid.mp3",
  },
  {
    id: "al-maajid",
    arabic: "الْمَاجِد",
    transliteration: "Al-Majid",
    translation: "The Noble",
    meaning: "The Illustrious One, abundant in glory and generosity.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio65_65_al_majid.mp3",
  },
  {
    id: "al-wahid",
    arabic: "الْوَاحِد",
    transliteration: "Al-Wahid",
    translation: "The One",
    meaning: "The One without partner or equal.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio66_66_al_wahid.mp3",
  },
  {
    id: "al-ahad",
    arabic: "الْأَحَد",
    transliteration: "Al-Ahad",
    translation: "The Indivisible",
    meaning: "The Unique One, single in His essence.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio67_67_al_ahad.mp3",
  },
  {
    id: "as-samad",
    arabic: "الصَّمَد",
    transliteration: "As-Samad",
    translation: "The Eternal",
    meaning: "The Self-Sufficient One whom all creation needs.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio68_68_as_samad.mp3",
  },
  {
    id: "al-qadir",
    arabic: "الْقَادِر",
    transliteration: "Al-Qadir",
    translation: "The Able",
    meaning: "The One with full power over all things.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio69_69_al_qadir.mp3",
  },
  {
    id: "al-muqtadir",
    arabic: "الْمُقْتَدِر",
    transliteration: "Al-Muqtadir",
    translation: "The Powerful",
    meaning: "The One who prevails and determines all.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio70_70_al_muqtadir.mp3",
  },
  {
    id: "al-muqaddim",
    arabic: "الْمُقَدِّم",
    transliteration: "Al-Muqaddim",
    translation: "The Expediter",
    meaning: "The One who brings forward whom He wills.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio71_71_al_muqaddim.mp3",
  },
  {
    id: "al-muakhkhir",
    arabic: "الْمُؤَخِّر",
    transliteration: "Al-Mu'akhkhir",
    translation: "The Delayer",
    meaning: "The One who postpones whom He wills by His wisdom.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio72_72_al_muakhkhir.mp3",
  },
  {
    id: "al-awwal",
    arabic: "الْأَوَّل",
    transliteration: "Al-Awwal",
    translation: "The First",
    meaning: "The One before all things, without beginning.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio73_73_al_awwal.mp3",
  },
  {
    id: "al-akhir",
    arabic: "الْآخِر",
    transliteration: "Al-Akhir",
    translation: "The Last",
    meaning: "The One after all things, without end.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio74_74_al_akhir.mp3",
  },
  {
    id: "az-zahir",
    arabic: "الظَّاهِر",
    transliteration: "Az-Zahir",
    translation: "The Manifest",
    meaning: "The One evident above all through His signs.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio75_75_az_zahir.mp3",
  },
  {
    id: "al-batin",
    arabic: "الْبَاطِن",
    transliteration: "Al-Batin",
    translation: "The Hidden",
    meaning: "The One nearer than all yet beyond perception.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio76_76_al_batin.mp3",
  },
  {
    id: "al-wali",
    arabic: "الْوَالِي",
    transliteration: "Al-Wali",
    translation: "The Governor",
    meaning: "The One who owns and manages all affairs.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio77_77_al_wali.mp3",
  },
  {
    id: "al-mutaali",
    arabic: "الْمُتَعَالِي",
    transliteration: "Al-Muta'ali",
    translation: "The Most Exalted",
    meaning: "The One far above every limitation.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio78_78_al_mutaali.mp3",
  },
  {
    id: "al-barr",
    arabic: "الْبَرّ",
    transliteration: "Al-Barr",
    translation: "The Source of Goodness",
    meaning: "The Kind One, ever gentle and beneficent.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio79_79_al_barr.mp3",
  },
  {
    id: "at-tawwab",
    arabic: "التَّوَّاب",
    transliteration: "At-Tawwab",
    translation: "The Ever-Relenting",
    meaning: "The One who accepts repentance again and again.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio80_80_at_tawwab.mp3",
  },
  {
    id: "al-muntaqim",
    arabic: "الْمُنْتَقِم",
    transliteration: "Al-Muntaqim",
    translation: "The Avenger",
    meaning: "The One who justly requites the persistent wrongdoer.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio81_81_al_muntaqim.mp3",
  },
  {
    id: "al-afuww",
    arabic: "الْعَفُوّ",
    transliteration: "Al-'Afuww",
    translation: "The Pardoner",
    meaning: "The One who effaces sins and pardons freely.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio82_82_al_afuw.mp3",
  },
  {
    id: "ar-rauf",
    arabic: "الرَّءُوف",
    transliteration: "Ar-Ra'uf",
    translation: "The Most Kind",
    meaning: "The One full of compassion and tenderness.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio83_83_ar_rauf.mp3",
  },
  {
    id: "malik-ul-mulk",
    arabic: "مَالِكُ الْمُلْك",
    transliteration: "Malik-ul-Mulk",
    translation: "Owner of All Sovereignty",
    meaning: "The Owner of all dominion who bestows it as He wills.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio84_84_malik_ul_mulk.mp3",
  },
  {
    id: "dhul-jalali-wal-ikram",
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَام",
    transliteration: "Dhul-Jalali wal-Ikram",
    translation: "Lord of Majesty and Bounty",
    meaning: "The Possessor of majesty, honour, and generosity.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio85_85_dhul_jalaal_wal_ikraam.mp3",
  },
  {
    id: "al-muqsit",
    arabic: "الْمُقْسِط",
    transliteration: "Al-Muqsit",
    translation: "The Equitable",
    meaning: "The One who acts with perfect fairness.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio86_86_al_muqsit.mp3",
  },
  {
    id: "al-jami",
    arabic: "الْجَامِع",
    transliteration: "Al-Jami'",
    translation: "The Gatherer",
    meaning: "The One who assembles all creation on Judgement Day.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio87_87_al_jame.mp3",
  },
  {
    id: "al-ghaniyy",
    arabic: "الْغَنِيّ",
    transliteration: "Al-Ghaniyy",
    translation: "The Self-Sufficient",
    meaning: "The Rich One in need of nothing.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio88_88_al_ghani.mp3",
  },
  {
    id: "al-mughni",
    arabic: "الْمُغْنِي",
    transliteration: "Al-Mughni",
    translation: "The Enricher",
    meaning: "The One who enriches and satisfies His servants.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio89_89_al_mughni.mp3",
  },
  {
    id: "al-mani",
    arabic: "الْمَانِع",
    transliteration: "Al-Mani'",
    translation: "The Preventer",
    meaning: "The One who withholds by His wisdom to protect.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio90_90_al_mani.mp3",
  },
  {
    id: "ad-darr",
    arabic: "الضَّارّ",
    transliteration: "Ad-Darr",
    translation: "The Distresser",
    meaning: "The One who can allow harm by His decree.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio91_91_ad_darr.mp3",
  },
  {
    id: "an-nafi",
    arabic: "النَّافِع",
    transliteration: "An-Nafi'",
    translation: "The Benefactor",
    meaning: "The One who is the source of all benefit.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio92_92_an_nafi.mp3",
  },
  {
    id: "an-nur",
    arabic: "النُّور",
    transliteration: "An-Nur",
    translation: "The Light",
    meaning: "The One who illuminates the heavens and the earth.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio93_93_an_nur.mp3",
  },
  {
    id: "al-hadi",
    arabic: "الْهَادِي",
    transliteration: "Al-Hadi",
    translation: "The Guide",
    meaning: "The One who guides His servants to the truth.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio94_94_al_hadi.mp3",
  },
  {
    id: "al-badi",
    arabic: "الْبَدِيع",
    transliteration: "Al-Badi'",
    translation: "The Incomparable Originator",
    meaning: "The One who creates in unprecedented ways.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio95_95_al_badi.mp3",
  },
  {
    id: "al-baqi",
    arabic: "الْبَاقِي",
    transliteration: "Al-Baqi",
    translation: "The Everlasting",
    meaning: "The One who remains after all else perishes.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio96_96_al_baqi.mp3",
  },
  {
    id: "al-warith",
    arabic: "الْوَارِث",
    transliteration: "Al-Warith",
    translation: "The Inheritor",
    meaning: "The One to whom all returns after creation ends.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio97_97_al_warith.mp3",
  },
  {
    id: "ar-rashid",
    arabic: "الرَّشِيد",
    transliteration: "Ar-Rashid",
    translation: "The Guide to the Right Path",
    meaning: "The One who directs all to their right course.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio98_98_ar_rashid.mp3",
  },
  {
    id: "as-sabur",
    arabic: "الصَّبُور",
    transliteration: "As-Sabur",
    translation: "The Patient",
    meaning: "The One who is patient and never acts in haste.",
    audioUri:
      "https://cdn.jsdelivr.net/gh/ProgrammerHasan/99-names-of-allah-audios@03c526366d460c3acb163c89fadb0201fd057b96/audio99_99_as_sabur.mp3",
  },
];
