import type { QuranGuideTimelineEvent } from "../types/quran-guide";

/** How the Qur'an was revealed — from Cave of Hira through preservation. */
export const QURAN_GUIDE_TIMELINE: QuranGuideTimelineEvent[] = [
  {
    id: "pre-revelation",
    year: 610,
    title: "Life before revelation",
    body: "Muhammad ﷺ withdrew to Cave Hira for contemplation. The society around him was steeped in idolatry, yet he was known as al-Amin — the trustworthy.",
    location: "Makkah",
  },
  {
    id: "cave-hira",
    year: 610,
    title: "Cave of Hira",
    body: "In Ramadan, Jibreel appeared with the first words: 'Read!' The Prophet ﷺ replied he could not read; the angel embraced him and recited the opening of Surah al-Alaq.",
    location: "Jabal an-Nur, Makkah",
    topicId: "revelation",
  },
  {
    id: "first-revelation",
    year: 610,
    title: "First revelation — Surah al-Alaq",
    body: "The command to read marks the beginning of prophethood. Early revelations in Makkah focused on tawheed, the Hereafter, and moral reform.",
    topicId: "revelation",
  },
  {
    id: "early-makkah",
    year: 610,
    ah: 0,
    title: "Early Makkan period",
    body: "Secret preaching, persecution of early Muslims, boycott of Banu Hashim, and migration to Abyssinia. Surahs of this era often speak in powerful, concise verses.",
    location: "Makkah",
    topicId: "revelation",
  },
  {
    id: "hijra",
    year: 622,
    ah: 1,
    title: "Hijra to Madinah",
    body: "The Muslim community established a polity in Madinah. Revelation now addressed law, family, economy, and relations with People of the Book.",
    location: "Madinah",
    topicId: "revelation",
  },
  {
    id: "madinan-period",
    year: 622,
    ah: 1,
    title: "Madinan period",
    body: "Longer surahs with legislation: salah, zakat, fasting, marriage, and treaties. Battles and hypocrisy are addressed with clarity.",
    location: "Madinah",
    topicId: "revelation",
  },
  {
    id: "final-sermon",
    year: 632,
    ah: 10,
    title: "Farewell Pilgrimage",
    body: "During the Prophet's ﷺ only Hajj, key verses of Surah al-Ma'idah were completed. He reminded the ummah of rights, equality, and holding fast to the Book.",
    location: "Arafat / Mina",
    topicId: "revelation",
  },
  {
    id: "compilation",
    year: 633,
    ah: 11,
    title: "Compilation under Abu Bakr",
    body: "After many huffaz were martyred at Yamama, Abu Bakr ordered Zayd ibn Thabit to gather the Qur'an on sheets (suhuf) from what had been written in the Prophet's ﷺ presence.",
    topicId: "revelation",
  },
  {
    id: "uthmanic-mushaf",
    year: 650,
    ah: 30,
    title: "Standardised mushaf — Uthman",
    body: "Uthman sent copies in the dialect of Quraysh to major cities and ordered other personal copies to be destroyed to prevent dispute over recitation.",
    topicId: "revelation",
  },
  {
    id: "preservation",
    year: 632,
    title: "Preservation until today",
    body: "Memorisation (hifz), written records, and unbroken chains of recitation (qira'at) preserve the Qur'an. Allah promised: 'We have sent down the Reminder and We will preserve it.'",
    topicId: "revelation",
  },
];
