import type { QuranGuideLetter } from "../types/quran-guide";

/** Arabic alphabet — 28 letters with names and examples. */
export const QURAN_GUIDE_LETTERS: QuranGuideLetter[] = [
  {
    id: "alif",
    letter: "ا",
    name: "Alif",
    transliteration: "a",
    pronunciation: "Long /a/ as in 'father' (when carrying hamza or madd)",
    examples: ["اَللَّه", "اِبْدَأ"],
  },
  {
    id: "ba",
    letter: "ب",
    name: "Ba",
    transliteration: "b",
    pronunciation: "Like English 'b'",
    examples: ["بِسْم", "رَبِّ"],
  },
  {
    id: "ta",
    letter: "ت",
    name: "Ta",
    transliteration: "t",
    pronunciation: "Like English 't'",
    examples: ["تَبَارَك", "رَحِيم"],
  },
  {
    id: "tha",
    letter: "ث",
    name: "Tha",
    transliteration: "th",
    pronunciation: "Like 'th' in 'think'",
    examples: ["ثُمَّ", "مِيثَاق"],
  },
  {
    id: "jim",
    letter: "ج",
    name: "Jim",
    transliteration: "j",
    pronunciation: "Like 'j' in 'jam'",
    examples: ["جَنَّة", "رَجُل"],
  },
  {
    id: "ha",
    letter: "ح",
    name: "Ha",
    transliteration: "ḥ",
    pronunciation: "Sharp breathy h from the throat — not English 'h'",
    examples: ["الْحَمْد", "رَحْمَن"],
  },
  {
    id: "kha",
    letter: "خ",
    name: "Kha",
    transliteration: "kh",
    pronunciation: "Like Scottish 'loch' — friction in the throat",
    examples: ["خَيْر", "سَمِيع"],
  },
  {
    id: "dal",
    letter: "د",
    name: "Dal",
    transliteration: "d",
    pronunciation: "Like English 'd'",
    examples: ["دِين", "عَبْد"],
  },
  {
    id: "dhal",
    letter: "ذ",
    name: "Dhal",
    transliteration: "dh",
    pronunciation: "Like 'th' in 'this'",
    examples: ["ذَٰلِك", "أُولَٰئِكَ"],
  },
  {
    id: "ra",
    letter: "ر",
    name: "Ra",
    transliteration: "r",
    pronunciation: "Rolled/trilled 'r'",
    examples: ["رَبِّ", "قُرْآن"],
  },
  {
    id: "zay",
    letter: "ز",
    name: "Zay",
    transliteration: "z",
    pronunciation: "Like English 'z'",
    examples: ["زَكَاة", "عَزِيز"],
  },
  {
    id: "sin",
    letter: "س",
    name: "Sin",
    transliteration: "s",
    pronunciation: "Like English 's'",
    examples: ["سَلَام", "نَفْس"],
  },
  {
    id: "shin",
    letter: "ش",
    name: "Shin",
    transliteration: "sh",
    pronunciation: "Like 'sh' in 'ship'",
    examples: ["شَهْر", "مُشْرِك"],
  },
  {
    id: "sad",
    letter: "ص",
    name: "Sad",
    transliteration: "ṣ",
    pronunciation: "Emphatic 's' — tongue raised, fuller sound",
    examples: ["صِرَاط", "صَبْر"],
  },
  {
    id: "dad",
    letter: "ض",
    name: "Dad",
    transliteration: "ḍ",
    pronunciation: "Emphatic 'd' — unique to Arabic",
    examples: ["ضَالِّين", "أَرْض"],
  },
  {
    id: "ta-emph",
    letter: "ط",
    name: "Ta (emphatic)",
    transliteration: "ṭ",
    pronunciation: "Emphatic 't' — deeper in the mouth",
    examples: ["طَيِّبَات", "مُطَهَّر"],
  },
  {
    id: "za-emph",
    letter: "ظ",
    name: "Za (emphatic)",
    transliteration: "ẓ",
    pronunciation: "Emphatic version of 'dh' sound",
    examples: ["ظَالِم", "حَفِيظ"],
  },
  {
    id: "ayn",
    letter: "ع",
    name: "Ayn",
    transliteration: "'",
    pronunciation: "Constriction in the throat — no English equivalent",
    examples: ["عَلِيم", "سَمِيع"],
  },
  {
    id: "ghayn",
    letter: "غ",
    name: "Ghayn",
    transliteration: "gh",
    pronunciation: "Like French 'r' or gargling 'gh'",
    examples: ["غَفُور", "بَغْي"],
  },
  {
    id: "fa",
    letter: "ف",
    name: "Fa",
    transliteration: "f",
    pronunciation: "Like English 'f'",
    examples: ["فَاتِحَة", "كَافِر"],
  },
  {
    id: "qaf",
    letter: "ق",
    name: "Qaf",
    transliteration: "q",
    pronunciation: "Deep 'k' from the back of the tongue — not English 'k'",
    examples: ["قُرْآن", "وَقَّى"],
  },
  {
    id: "kaf",
    letter: "ك",
    name: "Kaf",
    transliteration: "k",
    pronunciation: "Like English 'k' (forward in mouth)",
    examples: ["كِتَاب", "مُلْك"],
  },
  {
    id: "lam",
    letter: "ل",
    name: "Lam",
    transliteration: "l",
    pronunciation: "Like English 'l'",
    examples: ["لَا", "عَبْدُ"],
  },
  {
    id: "mim",
    letter: "م",
    name: "Mim",
    transliteration: "m",
    pronunciation: "Like English 'm'",
    examples: ["مُحَمَّد", "رَحِيم"],
  },
  {
    id: "nun",
    letter: "ن",
    name: "Nun",
    transliteration: "n",
    pronunciation: "Like English 'n'",
    examples: ["نُور", "إِنْسَان"],
  },
  {
    id: "ha-end",
    letter: "ه",
    name: "Ha (light)",
    transliteration: "h",
    pronunciation: "Soft 'h' at end of words",
    examples: ["إِلَٰه", "فَتْح"],
  },
  {
    id: "waw",
    letter: "و",
    name: "Waw",
    transliteration: "w / u",
    pronunciation: "Like 'w' or long 'oo'",
    examples: ["وَ", "نُور"],
  },
  {
    id: "ya",
    letter: "ي",
    name: "Ya",
    transliteration: "y / i",
    pronunciation: "Like 'y' or long 'ee'",
    examples: ["يَوْم", "رَحِيم"],
  },
];
