import type { ZikrItem } from "../types/index";

/** Bump when the bundled zikr content changes so clients can re-seed. */
export const ZIKR_CONTENT_VERSION = 5;

/**
 * Curated adhkar for every part of the day. Generated by
 * apps/app/scripts/build-data/build-adhkar.mjs — do not edit by hand.
 */
export const ZIKR_ITEMS: ZikrItem[] = [
  {
    id: "anytime-subhanallah-bihamdihi",
    categoryId: "anytime",
    title: "SubhanAllahi wa bihamdihi",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhan-Allahi wa bihamdihi",
    translation: "Glory is to Allah and praise is to Him.",
    virtues:
      "Whoever says it 100 times a day has his sins wiped away, though they be like the foam of the sea.",
    reference: "Bukhari & Muslim",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/91hm.mp3",
  },
  {
    id: "anytime-tahlil",
    categoryId: "anytime",
    title: "La ilaha illallah, wahdahu la sharika lah",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration:
      "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation:
      "There is no god but Allah, alone, without partner. His is the dominion and His is the praise, and He is over all things capable.",
    virtues: "Whoever says it 100 times has a reward equal to freeing ten slaves.",
    reference: "Bukhari & Muslim",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/237hm.mp3",
  },
  {
    id: "anytime-istighfar",
    categoryId: "anytime",
    title: "Astaghfirullah",
    arabic: "أَسْتَغْفِرُ اللَّهَ",
    transliteration: "Astaghfirullah",
    translation: "I seek the forgiveness of Allah.",
    virtues: "The Prophet ﷺ would seek forgiveness more than seventy times a day.",
    reference: "Bukhari",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/96hm.mp3",
  },
  {
    id: "anytime-hawqala",
    categoryId: "anytime",
    title: "La hawla wa la quwwata illa billah",
    arabic: "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    transliteration: "La hawla wa la quwwata illa billah",
    translation: "There is no might nor power except with Allah.",
    virtues: "A treasure from the treasures of Paradise.",
    reference: "Bukhari & Muslim",
    targetCount: 33,
  },
  {
    id: "anytime-tasbih-set",
    categoryId: "anytime",
    title: "The four most beloved words",
    arabic: "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَٰهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ",
    transliteration: "Subhan-Allah, wal-hamdu lillah, wa la ilaha illallah, wallahu akbar",
    translation:
      "Glory is to Allah, all praise is for Allah, there is no god but Allah, and Allah is the Greatest.",
    virtues: "The most beloved words to Allah.",
    reference: "Muslim",
    targetCount: 25,
  },
  {
    id: "anytime-kalimatan",
    categoryId: "anytime",
    title: "Two light words, heavy on the scale",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    transliteration: "Subhan-Allahi wa bihamdih, subhan-Allahil-'Azim",
    translation: "Glory and praise is to Allah, glory is to Allah the Magnificent.",
    virtues: "Two phrases light on the tongue, heavy on the scale, beloved to the Most Merciful.",
    reference: "Bukhari & Muslim",
    targetCount: 10,
  },
  {
    id: "after_prayer-tasbih",
    categoryId: "after_prayer",
    title: "SubhanAllah (x33)",
    arabic: "سُبْحَانَ اللَّهِ",
    transliteration: "Subhan-Allah",
    translation: "Glory is to Allah.",
    reference: "Muslim",
    targetCount: 33,
  },
  {
    id: "after_prayer-tahmid",
    categoryId: "after_prayer",
    title: "Alhamdulillah (x33)",
    arabic: "الْحَمْدُ لِلَّهِ",
    transliteration: "Alhamdulillah",
    translation: "All praise is for Allah.",
    reference: "Muslim",
    targetCount: 33,
  },
  {
    id: "after_prayer-takbir",
    categoryId: "after_prayer",
    title: "Allahu Akbar (x34)",
    arabic: "اللَّهُ أَكْبَرُ",
    transliteration: "Allahu Akbar",
    translation: "Allah is the Greatest.",
    virtues:
      "Completing the tasbih after each prayer wipes away sins though they be like the foam of the sea.",
    reference: "Muslim",
    targetCount: 34,
  },
  {
    id: "after_prayer-tahlil-hundred",
    categoryId: "after_prayer",
    title: "La ilaha illallah (completing the hundred)",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration:
      "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir",
    translation:
      "There is no god but Allah, alone, without partner. His is the dominion and His is the praise, and He is over all things capable.",
    virtues:
      "Whoever, after every prayer, glorifies Allah 33 times, praises Him 33 times, and magnifies Him 33 times — that is 99 — then completes the hundred with this, his sins are forgiven though they be like the foam of the sea.",
    reference: "Muslim 597",
    targetCount: 1,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/237hm.mp3",
  },
  {
    id: "after_prayer-tahlil-ten",
    categoryId: "after_prayer",
    title: "La ilaha illallah (x10 after Fajr & Maghrib)",
    arabic: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، يُحْيِي وَيُمِيتُ، وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration:
      "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, yuhyi wa yumit, wa huwa 'ala kulli shay'in qadir",
    translation:
      "There is no god but Allah, alone, without partner. His is the dominion and His is the praise. He gives life and causes death, and He is over all things capable.",
    virtues:
      "Whoever says it ten times after Maghrib and after Fajr: Allah records for him ten good deeds, erases ten sins, raises him ten degrees, and it is a protection for him that day from every disliked thing and a guard from Shaytan.",
    reference: "Tirmidhi 3474",
    targetCount: 10,
    prayers: ["fajr", "maghrib"],
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/72hm.mp3",
  },
  {
    id: "after_prayer-ajirni-min-an-nar",
    categoryId: "after_prayer",
    title: "Allahumma ajirni min an-nar (x7 after Fajr & Maghrib)",
    arabic: "اللَّهُمَّ أَجِرْنِي مِنَ النَّارِ",
    transliteration: "Allahumma ajirni minan-nar",
    translation: "O Allah, save me from the Fire.",
    virtues:
      "Whoever says it seven times after the Maghrib prayer before speaking, then dies that night, is protected from the Fire; and whoever says it after Fajr before speaking, then dies that day, is protected from the Fire.",
    reference: "Abu Dawud 5079",
    targetCount: 7,
    prayers: ["fajr", "maghrib"],
  },
  {
    id: "after_prayer-muadh-dhikr-shukr",
    categoryId: "after_prayer",
    title: "Help me to remember and thank You",
    arabic: "اللَّهُمَّ أَعِنِّي عَلَىٰ ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
    translation:
      "O Allah, help me to remember You, to thank You, and to worship You in the best manner.",
    virtues:
      "The Prophet ﷺ took Mu'adh by the hand and said, 'By Allah, I love you,' then advised him never to leave saying this after every prayer.",
    reference: "Abu Dawud 1522 & An-Nasa'i",
    targetCount: 1,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/59hm.mp3",
  },
  {
    id: "after_prayer-nur",
    categoryId: "after_prayer",
    title: "Supplication for Light (after Fajr)",
    arabic:
      "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا، وَفِي لِسَانِي نُورًا، وَفِي سَمْعِي نُورًا، وَفِي بَصَرِي نُورًا، وَمِنْ فَوْقِي نُورًا، وَمِنْ تَحْتِي نُورًا، وَعَنْ يَمِينِي نُورًا، وَعَنْ شِمَالِي نُورًا، وَمِنْ أَمَامِي نُورًا، وَمِنْ خَلْفِي نُورًا، وَاجْعَلْ فِي نَفْسِي نُورًا، وَأَعْظِمْ لِي نُورًا",
    transliteration:
      "Allahumma-j'al fi qalbi nuran, wa fi lisani nuran, wa fi sam'i nuran, wa fi basari nuran, wa min fawqi nuran, wa min tahti nuran, wa 'an yamini nuran, wa 'an shimali nuran, wa min amami nuran, wa min khalfi nuran, waj'al fi nafsi nuran, wa a'zim li nuran",
    translation:
      "O Allah, place light in my heart, light in my tongue, light in my hearing, light in my sight, light above me, light below me, light on my right, light on my left, light before me, light behind me; place light in my soul, and make light abundant for me.",
    virtues:
      "A supplication of the Prophet ﷺ, reported among the adhkar said after the Fajr prayer.",
    reference: "Muslim 763",
    targetCount: 1,
    prayers: ["fajr"],
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/19hm.mp3",
  },
  {
    id: "after_prayer-kaffarat-al-majlis",
    categoryId: "after_prayer",
    title: "Expiation of the sitting",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
    transliteration:
      "Subhanaka-llahumma wa bihamdik, ashhadu an la ilaha illa anta, astaghfiruka wa atubu ilayk",
    translation:
      "Glory is to You, O Allah, and praise; I bear witness that there is no god but You; I seek Your forgiveness and repent to You.",
    virtues:
      "'A'ishah reported that the Prophet ﷺ would say this at the end of a sitting. Whoever says it, what occurred in that gathering is forgiven for him.",
    reference: "Tirmidhi 3433 & An-Nasa'i",
    targetCount: 1,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/15hm.mp3",
  },
  {
    id: "after_prayer-malik-quddus",
    categoryId: "after_prayer",
    title: "Subhanal Malikil Quddus (x3 after Witr)",
    arabic: "سُبْحَانَ الْمَلِكِ الْقُدُّوسِ",
    transliteration: "Subhanal-Malikil-Quddus",
    translation: "Glory be to the King, the Most Holy.",
    virtues:
      "After the salam of the Witr prayer the Prophet ﷺ would say it three times, raising and prolonging his voice on the third, adding: 'Rabbil-mala'ikati war-ruh' (Lord of the angels and the Spirit). Witr is prayed after the Isha prayer.",
    reference: "An-Nasa'i 1699",
    targetCount: 3,
    prayers: ["witr"],
  },
  {
    id: "morning-tasbih-hundred",
    categoryId: "morning",
    title: "SubhanAllahi wa bihamdihi (x100)",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhan-Allahi wa bihamdihi",
    translation: "Glory is to Allah and praise is to Him.",
    virtues:
      "None will come on the Day of Judgement with better than this, except one who did the same or more.",
    reference: "Muslim",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/91hm.mp3",
  },
  {
    id: "morning-protection",
    categoryId: "morning",
    title: "Bismillahilladhi la yadurru (x3)",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration:
      "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama', wa huwas-Sami'ul-'Alim",
    translation:
      "In the name of Allah, with whose name nothing on earth or in the heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
    virtues: "Whoever says it three times, nothing will harm him.",
    reference: "Abu Dawud & Tirmidhi",
    targetCount: 3,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/86hm.mp3",
  },
  {
    id: "morning-radeetu",
    categoryId: "morning",
    title: "Contentment with Allah, Islam, and the Prophet ﷺ",
    arabic: "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
    transliteration: "Radeetu billahi Rabban, wa bil-Islami dinan, wa bi-Muhammadin ﷺ nabiyya",
    translation:
      "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.",
    virtues:
      "Whoever says it three times, it is a right upon Allah to please him on Judgement Day.",
    reference: "Abu Dawud & Tirmidhi",
    targetCount: 3,
  },
  {
    id: "evening-tasbih-hundred",
    categoryId: "evening",
    title: "SubhanAllahi wa bihamdihi (x100)",
    arabic: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    transliteration: "Subhan-Allahi wa bihamdihi",
    translation: "Glory is to Allah and praise is to Him.",
    reference: "Muslim",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/91hm.mp3",
  },
  {
    id: "evening-protection",
    categoryId: "evening",
    title: "Bismillahilladhi la yadurru (x3)",
    arabic: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration:
      "Bismillahilladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama', wa huwas-Sami'ul-'Alim",
    translation:
      "In the name of Allah, with whose name nothing on earth or in the heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
    reference: "Abu Dawud & Tirmidhi",
    targetCount: 3,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/86hm.mp3",
  },
  {
    id: "evening-refuge",
    categoryId: "evening",
    title: "A'udhu bikalimatillahit-tammat (x3)",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
    translation:
      "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    virtues: "Whoever says it three times in the evening, no venom will harm him that night.",
    reference: "Muslim",
    targetCount: 3,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/216hm.mp3",
  },
  {
    id: "evening-amsayna",
    categoryId: "evening",
    title: "We have reached the evening",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
    transliteration: "Amsayna wa amsal-mulku lillah, wal-hamdu lillah",
    translation:
      "We have reached the evening and at this time the whole dominion belongs to Allah, and all praise is for Allah.",
    reference: "Muslim",
    targetCount: 1,
  },
  {
    id: "after_azan-salawat",
    categoryId: "after_azan",
    title: "Salawat upon the Prophet ﷺ",
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
    translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad.",
    virtues:
      "Whoever sends blessings upon the Prophet ﷺ once, Allah sends blessings upon him tenfold.",
    reference: "Muslim",
    targetCount: 10,
  },
  {
    id: "after_azan-wasila",
    categoryId: "after_azan",
    title: "Dua after the Adhan",
    arabic:
      "اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ، وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ، وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    transliteration:
      "Allahumma Rabba hadhihid-da'watit-tammah, was-salatil-qa'imah, ati Muhammadanil-wasilata wal-fadilah, wab'ath-hu maqaman mahmudanil-ladhi wa'adtah",
    translation:
      "O Allah, Lord of this perfect call and established prayer, grant Muhammad the intercession (wasilah) and eminence, and raise him to the praiseworthy station that You have promised him.",
    virtues: "Whoever says it after the adhan, intercession is made permissible for him.",
    reference: "Bukhari",
    targetCount: 1,
  },
  {
    id: "after_azan-repeat",
    categoryId: "after_azan",
    title: "Repeat after the Muadhin",
    arabic: "وَأَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ",
    transliteration: "Wa ashhadu an la ilaha illallah wa anna Muhammadan rasulullah",
    translation:
      "And I bear witness that there is no god but Allah and that Muhammad is the Messenger of Allah.",
    reference: "Muslim",
    targetCount: 1,
  },
  {
    id: "before_prayer-intention",
    categoryId: "before_prayer",
    title: "Settle the heart before salah",
    arabic: "إِنَّ الصَّلَاةَ كَانَتْ عَلَى الْمُؤْمِنِينَ كِتَابًا مَوْقُوتًا",
    transliteration: "Innas-salata kanat 'alal-mu'minina kitaban mawquta",
    translation: "Indeed, prayer has been decreed upon the believers a decree of specified times.",
    reference: "Quran 4:103",
    targetCount: 1,
  },
  {
    id: "before_prayer-taawwudh",
    categoryId: "before_prayer",
    title: "Seek refuge from Shaytan",
    arabic: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    transliteration: "A'udhu billahi minash-shaytanir-rajim",
    translation: "I seek refuge in Allah from the accursed Shaytan.",
    reference: "Quran 16:98",
    targetCount: 1,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/193hm.mp3",
  },
  {
    id: "before_prayer-salawat",
    categoryId: "before_prayer",
    title: "Salawat before standing",
    arabic: "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ",
    transliteration: "Allahumma salli 'ala Muhammad",
    translation: "O Allah, send blessings upon Muhammad.",
    reference: "Muslim",
    targetCount: 3,
  },
  {
    id: "before_sleep-name",
    categoryId: "before_sleep",
    title: "Bismika Allahumma amutu wa ahya",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name, O Allah, I die and I live.",
    reference: "Bukhari",
    targetCount: 1,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/105hm.mp3",
  },
  {
    id: "before_sleep-tasbih-fatimah",
    categoryId: "before_sleep",
    title: "Tasbih of Fatimah",
    arabic: "سُبْحَانَ اللَّهِ (٣٣) الْحَمْدُ لِلَّهِ (٣٣) اللَّهُ أَكْبَرُ (٣٤)",
    transliteration: "Subhan-Allah (33), Alhamdulillah (33), Allahu Akbar (34)",
    translation: "Glory is to Allah, all praise is for Allah, Allah is the Greatest.",
    virtues: "Better for you than a servant, as the Prophet ﷺ taught Fatimah and 'Ali.",
    reference: "Bukhari & Muslim",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/240hm.mp3",
  },
  {
    id: "before_sleep-ikhlas",
    categoryId: "before_sleep",
    title: "The Three Quls",
    arabic:
      "قُلۡ هُوَ ٱللَّهُ أَحَدٌ ٱللَّهُ ٱلصَّمَدُ لَمۡ يَلِدۡ وَلَمۡ يُولَدۡ وَلَمۡ يَكُن لَّهُۥ كُفُوًا أَحَدُۢ\nقُلۡ أَعُوذُ بِرَبِّ ٱلۡفَلَقِ مِن شَرِّ مَا خَلَقَ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ وَمِن شَرِّ ٱلنَّفَّـٰثَٰتِ فِي ٱلۡعُقَدِ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ\nقُلۡ أَعُوذُ بِرَبِّ ٱلنَّاسِ مَلِكِ ٱلنَّاسِ إِلَٰهِ ٱلنَّاسِ مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ",
    transliteration:
      "Qul huwa Allahu ahadun Allahu alssamadu Lam yalid walam yooladu Walam yakun lahu kufuwan ahadun\nQul aAAoothu birabbi alfalaqi Min sharri ma khalaqa Wamin sharri ghasiqin itha waqaba Wamin sharri alnnaffathati fee alAAuqadi Wamin sharri hasidin itha hasada\nQul aAAoothu birabbi alnnasi Maliki alnnasi Ilahi alnnasi Min sharri alwaswasi alkhannasi Allathee yuwaswisu fee sudoori alnnasi Mina aljinnati wa alnnasm",
    translation:
      "Say: He is Allah, the One Allah, the eternally Besought of all He begetteth not nor was begotten And there is none comparable unto Him\nSay: I seek refuge in the Lord of the Daybreak From the evil of that which He created From the evil of the darkness when it is intense And from the evil of malignant witchcraft And from the evil of the envier when he envieth\nSay: I seek refuge in the Lord of mankind The King of mankind The god of mankind From the evil of the sneaking whisperer Who whispereth in the hearts of mankind Of the jinn and of mankind",
    virtues: "Recite before sleep, blow into the palms, and wipe over the body three times.",
    reference: "Quran 112-114 · Bukhari",
    targetCount: 3,
  },
  {
    id: "after_prayer-allah-the-giver-of-peace",
    categoryId: "after_prayer",
    title: "Allah, The Giver of Peace",
    arabic: "اَللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَاْلإِكْرَامِ",
    transliteration: "allahumma antas-salam wa minkas-salam tabarakta ya dhal-jalali wal-ikram",
    translation:
      "O Allah, You are Peace, and from You is peace. Blessed are You, O Possessor of majesty and honor.",
    virtues:
      "When the Messenger of Allah, sallallahu 'alayhi wa sallam, finished his prayer, he would seek forgiveness three times and recite the dhikr above. Al-Auza'i stated that the recitation of istighfar is 'Astaghfirullah, Astaghfirullah.'",
    reference: "HR. Muslim No. 591",
  },
  {
    id: "after_prayer-allah-the-preventer-and-the-giver-of-all-things",
    categoryId: "after_prayer",
    title: "Allah, The Preventer and The Giver of All Things",
    arabic:
      "لاَ إِلَـهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيْكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيْرُ، اَللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ",
    transliteration:
      "la ilaha illa allah wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir. allahumma la mani'a lima a'tayta wa la mu'tiya lima mana'ta wa la yanfa'u dhal-jaddi minkal-jaddu",
    translation:
      "There is no deity worthy of worship except Allah alone, He has no partner. To Him belongs dominion and praise, and He is over all things competent. O Allah, there is no preventer of what You give, and no giver of what You withhold, and wealth and honor do not benefit their possessor (except faith and righteous deeds that save from punishment). Only from You is wealth and honor.",
    virtues: "Read 1x",
    reference: "HR. Bukhari No. 844 and Muslim No. 593",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/237hm.mp3",
  },
  {
    id: "after_prayer-allah-the-possessor-of-all-and-the-only-one-wort",
    categoryId: "after_prayer",
    title: "Allah, The Possessor of All and The Only One Worthy of Worship",
    arabic:
      "لاَ إِلَـهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيْكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيْرُ. لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللهِ، لاَ إِلَـهَ إِلاَّ اللهُ، وَلاَ نَعْبُدُ إِلاَّ إِيَّاهُ، لَهُ النِّعْمَةُ وَلَهُ الْفَضْلُ وَلَهُ الثَّنَاءُ الْحَسَنُ، لاَ إِلَـهَ إِلاَّ اللهُ مُخْلِصِيْنَ لَهُ الدِّيْنَ وَلَوْ كَرِهَ الْكَافِرُوْنَ",
    transliteration:
      "la ilaha illa allah wahdahu la sharika lah. lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadir. la hawla wa la quwwata illa billah. la ilaha illa allah wa la na'budu illa iyyah. lahun-ni'mah wa lahul-fadl wa lahuth-thana'ul-hasan. la ilaha illa allah mukhlisina lahud-dina wa law karihal-kafirun",
    translation:
      "There is no deity worthy of worship except Allah alone, He has no partner. To Him belongs dominion and praise, and He is over all things competent. There is no power and no strength except by Allah. There is no deity worthy of worship except Allah, and we do not worship except Him. To Him belongs all favor, grace, and good praise. There is no deity worthy of worship except Allah, making our religion sincerely for Him, even if the disbelievers dislike it.",
    virtues:
      "'Abdullah bin Zubair said, \"The Prophet, sallallahu 'alayhi wa sallam, used to recite the tahlil (laa ilaha illallah) at the end of the prayer.\"",
    reference: "HR. Muslim No. 594",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/68hm.mp3",
  },
  {
    id: "after_prayer-ayat-al-kursi",
    categoryId: "after_prayer",
    title: "Ayat al-Kursi",
    arabic:
      "ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ",
    transliteration:
      "allahu la ilaha illa huwa, al-hayyul-qayyum. la ta'khudhuhu sinatun wa la nawm. lahu ma fis-samawati wa ma fil-ard. man dhal-ladhi yashfa'u 'indahu illa bi-idhnihi. ya'lamu ma bayna aydihim wa ma khalfahum. wa la yuhituna bishay'in min 'ilmihi illa bima sha'. wa si'a kursiyyuhu as-samawati wal-ard. wa la ya'udu-hu hifdhuhuma. wa huwa al-'aliyyul-'azim",
    translation:
      "Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
    virtues:
      "Whoever recites Ayat al-Kursi after finishing the prayer, nothing will prevent him from entering Paradise except death.",
    reference:
      "HR. an-Nasai in Al-Kubro 9: 44. This hadith is declared sahih by Ibn Hibban, as mentioned by Ibn Hajar in Bulugh al-Maram",
  },
  {
    id: "after_prayer-al-ikhlas",
    categoryId: "after_prayer",
    title: "Al-Ikhlas",
    arabic: "قُلْ هُوَ ٱللَّهُ أَحَدٌ (1) ٱللَّهُ ٱلصَّمَدُ (2) لَمْ يَلِدْ وَلَمْ يُولَدْ (3) وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ (4)",
    transliteration:
      "qul huwa allahu ahad (1) allahu samad (2) lam yalid wa lam yulad (3) wa lam yakun lahu kufuwan ahad (4)",
    translation:
      'Say, "He is Allah , [who is] One, (1) Allah , the Eternal Refuge. (2) He neither begets nor is born, (3) Nor is there to Him any equivalent." (4)',
    virtues:
      "The Messenger of Allah, sallallahu 'alayhi wa sallam, said: Recite Qul huwallahu ahad, and Al-Mu'awwidhatayn (Al-Falaq and An-Nas) in the evening and morning three times, and it will suffice you (protect you) from everything.",
    reference:
      "HR. Abu Dawud No. 1523 and an-Nasa'i No. 1337. Al-Hafiz Abu Tahir said that the chain of this hadith is hasan",
    targetCount: 3,
  },
  {
    id: "after_prayer-al-falaq",
    categoryId: "after_prayer",
    title: "Al-Falaq",
    arabic:
      "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ (1) مِن شَرِّ مَا خَلَقَ (2) وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ (3) وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ (4) وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ (5)",
    transliteration:
      "qul a'udhu birabbil-falaq (1) min sharri ma khalaq (2) wa min sharri ghasiqin idha waqab (3) wa min sharri naffathati fil-'uqad (4) wa min sharri hasidin idha hasad (5)",
    translation:
      'Say, "I seek refuge in the Lord of daybreak (1) From the evil of that which He created (2) And from the evil of darkness when it settles (3) And from the evil of the blowers in knots (4) And from the evil of an envier when he envies." (5)',
    virtues:
      "The Messenger of Allah, sallallahu 'alayhi wa sallam, said: Recite Qul huwallahu ahad, and Al-Mu'awwidhatayn (Al-Falaq and An-Nas) in the evening and morning three times, and it will suffice you (protect you) from everything.",
    reference:
      "HR. Abu Dawud No. 1523 and an-Nasa'i No. 1337. Al-Hafiz Abu Tahir said that the chain of this hadith is hasan",
    targetCount: 3,
  },
  {
    id: "after_prayer-an-nas",
    categoryId: "after_prayer",
    title: "An-Nas",
    arabic:
      "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ (1) مَلِكِ ٱلنَّاسِ (2) إِلَٰهِ ٱلنَّاسِ (3) مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ (4) ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ (5) مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ (6)",
    transliteration:
      "qul a'udhu birabbin-nas (1) malikin-nas (2) ilahin-nas (3) min sharri al-waswasi al-khannas (4) alladhi yuwaswisu fi sudurin-nas (5) mina al-jinnati wan-nas (6)",
    translation:
      'Say, "I seek refuge in the Lord of mankind, (1) The King of mankind. (2) The God of mankind, (3) From the evil of the whisperer who withdraws, (4) Who whispers in the breasts of mankind, (5) Of the jinn and mankind." (6)',
    virtues:
      "The Messenger of Allah, sallallahu 'alayhi wa sallam, said: Recite Qul huwallahu ahad, and Al-Mu'awwidhatayn (Al-Falaq and An-Nas) in the evening and morning three times, and it will suffice you (protect you) from everything.",
    reference:
      "HR. Abu Dawud No. 1523 and an-Nasa'i No. 1337. Al-Hafiz Abu Tahir said that the chain of this hadith is hasan",
    targetCount: 3,
  },
  {
    id: "after_prayer-supplication-for-beneficial-knowledge-good-provi",
    categoryId: "after_prayer",
    title: "Supplication for Beneficial Knowledge, Good Provision, and Accepted Deeds",
    arabic: "اللَّهُمَّ إِنِّى أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلاً مُتَقَبَّلاً",
    transliteration:
      "allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan",
    translation: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.",
    virtues:
      "Beneficial knowledge is a provision that makes life easier, obtaining good provision is a person's goal in working, and accepted deeds are the hope of every person who performs good deeds. Therefore, a servant should always ask for these 3 things every morning before starting their various activities.",
    reference:
      "HR. Ibn Majah No. 925 and Ahmad 6: 305, 322. Al-Hafiz Abu Tahir said that this hadith is sahih",
    prayers: ["fajr"],
  },
  {
    id: "morning-upon-entering-the-morning-by-asking-for-protecti",
    categoryId: "morning",
    title: "Upon Entering The Morning by Asking for Protection from Allah",
    arabic:
      "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَـهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيْكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيْرُ. رَبِّ أَسْأَلُكَ خَيْرَ مَا فِيْ هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوْذُ بِكَ مِنْ شَرِّ مَا فِيْ هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوْذُ بِكَ مِنَ الْكَسَلِ وَسُوْءِ الْكِبَرِ، رَبِّ أَعُوْذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ",
    transliteration:
      "asbahna wa asbahal-mulku lillahi, wal-hamdu lillahi, la ilaha illa allah wahdahu la sharika lahu, lahu al-mulku wa lahu al-hamdu wa huwa 'ala kulli shay'in qadir. rabbi as'aluka khayra ma fi hadha al-yawm wa khayra ma ba'dahu, wa a'udhu bika min sharri ma fi hadha al-yawm wa sharri ma ba'dahu. rabbi a'udhu bika mina al-kasali wa su'il-kibar. rabbi a'udhu bika min 'adhabin fin-nar wa 'adhabin fil-qabr",
    translation:
      "We have entered the morning and the dominion belongs to Allah, and all praise is for Allah. There is no deity worthy of worship except Allah alone, He has no partner. To Him belongs the dominion and to Him is praise, and He is over all things competent. My Lord, I ask You for the good of this day and the good of what follows it, and I seek refuge in You from the evil of this day and the evil of what follows it. My Lord, I seek refuge in You from laziness and the evil of old age. My Lord, I seek refuge in You from the punishment of the Fire and the punishment of the grave.",
    virtues: "Recite 1x",
    reference:
      "HR. Muslim No. 2723 (75), Abu Dawud No. 5071, and at-Tirmidzi 3390, sahih from Abdullah Ibn Mas'ud",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/77hm.mp3",
  },
  {
    id: "morning-upon-entering-the-morning-with-the-grace-of-alla",
    categoryId: "morning",
    title: "Upon Entering The Morning with The Grace of Allah",
    arabic: "اَللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوْتُ وَإِلَيْكَ النُّشُوْرُ",
    transliteration:
      "allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namutu wa ilaykan-nushur",
    translation:
      "O Allah, with Your grace and help we enter the morning, and with Your grace and help we enter the evening. By Your grace and will we live and by Your grace and will we die. And to You is the resurrection (for all creatures).",
    virtues: "Recite 1x",
    reference:
      "HR. al-Bukhari in al-Adab al-Mufrad No. 1199, this wording is the wording of al-Bukhari, at-Tirmidzi No. 3391, Abu Dawud No. 5068, Ahmad 11/354, Ibn Majah No. 3868",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/78hm.mp3",
  },
  {
    id: "morning-sayyid-al-istighfar",
    categoryId: "morning",
    title: "Sayyid al-Istighfar",
    arabic:
      "اَللَّهُمَّ أَنْتَ رَبِّيْ ، لَا إِلٰـهَ إِلاَّ أَنْتَ خَلَقْتَنِيْ وَأَنَا عَبْدُكَ ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ ، أَعُوْذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ ، أَبُوْءُ لَكَ بِنِعْمتِكَ عَلَيَّ ، وَأَبُوْءُ بِذَنْبِيْ فَاغْفِرْ لِيْ ، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
    transliteration:
      "allahumma anta rabbi, la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu. a'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u bidhanbi faghfir li, fa innahu la yaghfirudh-dhunuba illa anta",
    translation:
      "O Allah, You are my Lord. There is no deity worthy of worship except You. You created me and I am Your servant. I will be true to my covenant and promise to You as much as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, therefore, forgive me. Indeed, there is no one who can forgive sins except You.",
    virtues: "Recite 1x",
    reference: "HR. al-Bukhari No. 6306, 6323, Ahmad IV/122-125, an-Nasa'i VIII/279-280",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/79hm.mp3",
  },
  {
    id: "morning-dua-for-protection-and-good-health",
    categoryId: "morning",
    title: "Dua for Protection and Good Health",
    arabic:
      "اَللَّهُمَّ عَافِنِيْ فِيْ بَدَنِيْ ، اَللَّهُمَّ عَافِنِيْ فِيْ سَمْعِيْ ، اَللَّهُمَّ عَافِنِيْ فِيْ بَصَرِيْ ، لَا إِلَـهَ إِلَّا أَنْتَ ، اَللَّهُمَّ إِنِّيْ أَعُوْذُ بِكَ مِنَ الْكُفْرِوَالْفَقْرِ ، وَأَعُوْذُ بِكَ مِنْ عَذَابِ الْقَبْرِ ، لَا إِلَـهَ إِلَّا أَنْتَ",
    transliteration:
      "allahumma 'afini fi badani, allahumma 'afini fi sam'i, allahumma 'afini fi basari, la ilaha illa anta. allahumma inni a'udhu bika minal-kufri wal-faqr, wa a'udhu bika min 'adhabil-qabr, la ilaha illa anta",
    translation:
      "O Allah, protect my body (from illness and from what I do not want). O Allah, protect my hearing (from illness and disobedience or from what I do not want). O Allah, protect my sight, there is no deity worthy of worship except You. O Allah, indeed I seek refuge in You from disbelief and poverty. I seek refuge in You from the punishment of the grave, there is no deity worthy of worship except You.",
    virtues: "Recite 1x",
    reference:
      "HR. al-Bukhari in Sahih al-Adab al-Mufrad No. 701, Abu Dawud No. 5090, Ahmad V/42, hasan",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/82hm.mp3",
  },
  {
    id: "morning-dua-for-salvation-in-the-world-and-hereafter",
    categoryId: "morning",
    title: "Dua for Salvation in The World and Hereafter",
    arabic:
      "اَللَّهُمَّ إِنِّيْ أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَاْلآخِرَةِ، اَللَّهُمَّ إِنِّيْ أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِيْنِيْ وَدُنْيَايَ وَأَهْلِيْ وَمَالِيْ اللَّهُمَّ اسْتُرْ عَوْرَاتِى وَآمِنْ رَوْعَاتِى. اَللَّهُمَّ احْفَظْنِيْ مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِيْ، وَعَنْ يَمِيْنِيْ وَعَنْ شِمَالِيْ، وَمِنْ فَوْقِيْ، وَأَعُوْذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِيْ",
    transliteration:
      "allahumma inni as'alukal-'afwa wal-'afiyah fid-dunya wal-akhirah. allahumma inni as'alukal-'afwa wal-'afiyah fi dini wa dunyaya wa ahli wa mali. allahummastur 'awrati wa amin raw'ati. allahummahfadhni min bayni yadayya, wa min khalfi, wa 'an yamini wa 'an shimali, wa min fawqi. wa a'udhu bi 'adhamatika an ughtala min tahti",
    translation:
      "O Allah, indeed I ask You for well-being and safety in this world and the Hereafter. O Allah, indeed I ask You for well-being and safety in my religion, my world, my family and my wealth. O Allah, cover my flaws (faults and things that are not appropriate for others to see) and calm me from fear. O Allah, protect me from the front, behind, right, left and above me. I seek refuge in Your greatness, so that I am not snatched from below me (by snakes or swallowed by the earth, etc., which would cause me to fall).",
    virtues: "Recite 1x",
    reference:
      "HR. al-Bukhari in al-Adab al-Mufrad No. 1200, Abu Dawud No. 5074, an-Nasa'i VII/282, Ibn Majah No. 3871, al-Hakim 1/517-518, and others from Ibn Umar radhiyallahu 'anhuma",
  },
  {
    id: "morning-dua-for-protection-from-shaytan-whispers",
    categoryId: "morning",
    title: "Dua for Protection from Shaytan Whispers",
    arabic:
      "اَللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ فَاطِرَ السَّمَاوَاتِ وَاْلأَرْضِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيْكَهُ، أَشْهَدُ أَنْ لاَ إِلَـهَ إِلاَّ أَنْتَ، أَعُوْذُ بِكَ مِنْ شَرِّ نَفْسِيْ، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ، وَأَنْ أَقْتَرِفَ عَلَى نَفْسِيْ سُوْءًا أَوْ أَجُرَّهُ إِلَى مُسْلِمٍ",
    transliteration:
      "allahumma 'alimal-ghaybi wash-shahadati, fatiras-samawati wal-ard, rabbakulli shayin wa malikahu. ashhadu alla ilaha illa anta, a'udhu bika min sharri nafsi, wa min sharri ash-shaytani wa shirkih. wa an aqtarifa 'ala nafsi su'an aw ajurrahu ila muslim",
    translation:
      "O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, Lord of all things and their Sovereign. I bear witness that there is no deity worthy of worship except You. I seek refuge in You from the evil of myself, Satan and his soldiers (temptations to commit shirk against Allah), and I (seek refuge in You) from committing evil against myself or dragging it to a Muslim.",
    virtues: "Recite 1x",
    reference:
      "HR. al-Bukhari in al-Adab al-Mufrad No. 1202, at-Tirmidzi No. 3392 and Abu Dawud No. 5067",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/85hm.mp3",
  },
  {
    id: "morning-asking-for-protection-from-all-harms",
    categoryId: "morning",
    title: "Asking for Protection from All Harms",
    arabic: "بِسْمِ اللَّهِ الَّذِى لاَ يَضُرُّ مَعَ اسْمِهِ شَىْءٌ فِى الأَرْضِ وَلاَ فِى السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration:
      "bismillahi alladhi la yadurru ma'asmihi shay'un fi'l-ard wa la fi's-sama'i, wa huwa as-sami'u al-'aleem",
    translation:
      "In the name of Allah with Whose name nothing can harm on earth or in heaven, and He is the All-Hearing, All-Knowing.",
    virtues: "Recite 3x",
    reference:
      "HR. at-Tirmidzi No. 3388, Abu Dawud No. 5088, Ibn Majah No. 3869, al-Hakim 1/514, and Ahmad No. 446 and 474",
    targetCount: 3,
  },
  {
    id: "morning-asking-allah-for-guidance",
    categoryId: "morning",
    title: "Asking Allah for Guidance",
    arabic: "يَا حَيُّ يَا قَيُّوْمُ بِرَحْمَتِكَ أَسْتَغِيْثُ، وَأَصْلِحْ لِيْ شَأْنِيْ كُلَّهُ وَلاَ تَكِلْنِيْ إِلَى نَفْسِيْ طَرْفَةَ عَيْنٍ أَبَدًا",
    transliteration:
      "ya hayyu ya qayyum, bi rahmatika astaghith. wa aslih li sha'ni kullahu wa la takilni ila nafsi tarfata 'aynin abada",
    translation:
      "O Ever-Living, O Self-Sustaining, by Your mercy I seek help, rectify all my affairs and do not leave me to myself even for the blink of an eye.",
    virtues: "Recite 1x",
    reference:
      "HR. an-Nasa'i in 'Amalul Yaum wal Lailah No. 575, and al-Hakim 1/545, Sahih at-Targhib wat Tarhib 1/417 No. 661, As-Sahihah No. 227, hasan",
  },
  {
    id: "morning-entering-the-morning-upon-the-natural-religion-o",
    categoryId: "morning",
    title: "Entering The Morning Upon The Natural Religion of Islam",
    arabic:
      "أَصْبَحْنَا عَلَى فِطْرَةِ اْلإِسْلاَمِ وَعَلَى كَلِمَةِ اْلإِخْلاَصِ، وَعَلَى دِيْنِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِيْنَا إِبْرَاهِيْمَ، حَنِيْفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِيْنَ",
    transliteration:
      "asbahna 'ala fitratil-islam wa 'ala kalimatil-ikhlas, wa 'ala dini nabiyyina muhammadin sallallahu 'alayhi wa sallam, wa 'ala millati abina ibrahima hanifan musliman wa ma kana minal-mushrikin",
    translation:
      "In the morning we are upon the fitrah of Islam, the word of sincerity (the testimony of faith), the religion of our Prophet Muhammad, sallallahu 'alayhi wa sallam, and the religion of our father Abraham, who stood upon the straight path, a Muslim, and was not among the polytheists.",
    virtues: "Recite 1x",
    reference:
      "HR. Ahmad III/406, 407, ad-Darimi II/292 and Ibnus Sunni in Amalul Yaum wal Lailah No. 34, Mishkat al-Masabih No. 2415, Sahih al-Jami' as-Saghir No. 4674, sahih",
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/90hm.mp3",
  },
  {
    id: "morning-read-tasbih",
    categoryId: "morning",
    title: "Read Tasbih",
    arabic: "سُبْحَانَ اللهِ وَبِحَمْدِهِ عَدَدَ خَلْقَهِ وَرِضَى نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ",
    transliteration:
      "subhanallahi wa bihamdihi 'adada khalqihi wa rida nafsihi wa zinata 'arshihi wa midada kalimatihi",
    translation:
      "Glory to Allah, I praise Him as many as the number of His creatures, Glory to Allah according to His pleasure, as pure as the weight of His Throne, and as pure as the ink (which writes) His words.",
    virtues: "Recite 3x",
    reference:
      "HR. Muslim No. 2726. Sharh Muslim XVII/44. From Juwairiyah binti al-Harits radhiyallahu 'anhuma",
    targetCount: 3,
  },
  {
    id: "morning-istighfar-100x-a-day",
    categoryId: "morning",
    title: "Istighfar 100x a Day",
    arabic: "أَسْتَغْفِرُ الله وَأَتُوْبُ إِلَيْهِ",
    transliteration: "astaghfirullah wa atubu ilayh",
    translation: "I seek forgiveness from Allah and repent to Him.",
    virtues: "Recite 100x a day",
    reference: "HR. al-Bukhari/Fat-hul Baari XI/101 and Muslim No. 2702",
    targetCount: 100,
    audioUri:
      "https://cdn.jsdelivr.net/gh/sheikhhanif/Hisnul_Muslim_Database@07533fa1494d02c4b24aecb3ad7267e09219c956/audio/96hm.mp3",
  },
  {
    id: "evening-entering-the-evening-in-the-kingdom-of-allah-and",
    categoryId: "evening",
    title: "Entering the Evening in the Kingdom of Allah and Seeking His Protection",
    arabic:
      "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ للهِ، وَالْحَمْدُ للهِ، لَا إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُبِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُبِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُبِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ",
    transliteration:
      "amsayna wa amsal-mulku lillahi wal-hamdu lillahi, la ilaha illa allah wahdahu la sharika lahu, lahu al-mulku wa lahu al-hamdu wa huwa 'ala kulli shay'in qadir. rabbi as'aluka khayra ma fi hadhihil-laylah wa khayra ma ba'daha, wa a'udhu bika min sharri ma fi hadhihil-laylah wa sharri ma ba'daha. rabbi a'udhu bika mina al-kasali wa su'il-kibar. rabbi a'udhu bika min 'adhabin fin-nar wa 'adhabin fil-qabr",
    translation:
      "We have entered the evening and the dominion belongs to Allah, and all praise is for Allah. There is no deity worthy of worship except Allah alone, He has no partner. To Him belongs the dominion and to Him is praise, and He is over all things competent. My Lord, I ask You for the good of this night and the good of what follows it, and I seek refuge in You from the evil of this night and the evil of what follows it. My Lord, I seek refuge in You from laziness and the evil of old age. My Lord, I seek refuge in You from the punishment of the Fire and the punishment of the grave.",
    virtues:
      'Seeking protection from evil is prioritized, the principle that shows the importance of this is: "Preventing harm is more important and prioritized than bringing about good."',
    reference:
      "HR. Muslim No. 2723 (75), Abu Dawud No. 5071, and at-Tirmidzi 3390, sahih from Abdullah Ibn Mas'ud",
  },
  {
    id: "evening-entering-the-evening-by-seeking-allah-s-mercy",
    categoryId: "evening",
    title: "Entering the Evening by Seeking Allah's Mercy",
    arabic: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا،وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيْرُ",
    transliteration:
      "allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namutu wa ilayka al-masir",
    translation:
      "O Allah, by Your grace and help we have entered the evening, and by Your grace and help we enter the morning. By Your grace and help we live and by Your will we die. And to You is the final return (of all creatures).",
    virtues:
      "Everything we do from morning to evening, from the beginning of our lives until we die, is all under Allah's control and to Him we return.",
    reference:
      "HR. al-Bukhari in al-Adab al-Mufrad No. 1199, this wording is the wording of al-Bukhari at-Tirmidzi No. 3391, Abu Dawud No. 5068, Ahmad 11/354, Ibn Majah No. 3868",
  },
  {
    id: "evening-entering-the-evening-on-the-natural-disposition-",
    categoryId: "evening",
    title: "Entering the Evening on the Natural Disposition of Islam",
    arabic:
      "أَمْسَيْنَا عَلَى فِطْرَةِ اْلإِسْلاَمِ وَعَلَى كَلِمَةِ اْلإِخْلاَصِ، وَعَلَى دِيْنِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِيْنَا إِبْرَاهِيْمَ، حَنِيْفًا مُسْلِمًا وَمَا كَانَ مِنَ الْمُشْرِكِيْنَ",
    transliteration:
      "amsayna 'ala fitratil-islam wa 'ala kalimatil-ikhlas, wa 'ala dini nabiyyina muhammadin sallallahu 'alayhi wa sallam, wa 'ala millati abina ibrahima hanifan musliman wa ma kana minal-mushrikin",
    translation:
      "In the evening we are upon the fitrah of Islam, the word of sincerity (the testimony of faith), the religion of our Prophet Muhammad, sallallahu 'alayhi wa sallam, and the religion of our father Abraham, who stood upon the straight path, a Muslim, and was not among the polytheists.",
    virtues:
      "'Fitratil Islam' means upon the Sunnah, 'kalimatil ikhlas' means the testimony of faith, and 'hanifan' means a heart inclined towards the straight path and goodness.",
    reference:
      "HR. Ahmad III/406, 407, ad-Darimi II/292 and Ibnus Sunni in Amalul Yaum wal Lailah No. 34, Mishkat al-Masabih No. 2415, Sahih al-Jami' as-Saghir No. 4674, sahih",
  },
];

export function getZikrById(id: string): ZikrItem | undefined {
  return ZIKR_ITEMS.find((item) => item.id === id);
}
