/** @type {import('@bacons/apple-targets/app.plugin').ConfigFunction} */
module.exports = (config) => ({
  type: "watch",
  name: "MunibTrackerWatch",
  bundleIdentifier: ".munibtrackerwatch",
  displayName: "Munib Tracker",
  deploymentTarget: "10.0",
  // Light canvas (not phone icon.png #152921) — watchOS circular mask on a black
  // home screen; App Review Guideline 4 rejects near-black full-bleed Watch icons.
  // Generated by `pnpm --filter app generate:brand-assets` from icon-512-watch-apple.png.
  icon: "../../assets/images/icon-watch-1024.png",
  frameworks: ["SwiftUI", "WatchConnectivity", "WidgetKit"],
  entitlements: {
    "com.apple.security.application-groups": [
      config.ios?.entitlements?.["com.apple.security.application-groups"]?.[0] ??
        "group.app.munibtracker.widgets",
    ],
  },
});
